import 'package:playkosmos_v3/models/country_model.dart';

const List<CountryModel> kCountriesList = [
  CountryModel(
    name: 'Afghanistan',
    iso3: 'AFG',
    iso2: 'AF',
    phoneCode: '93',
    translations: {
      "en": "Afghanistan",
      "fr": "Afghanistan",
      "si": "ඇෆ්ගනිස්ථානය",
      "ta": "ஆப்கானிஸ்தான்",
      "fi": "Afganistan",
      "hi": "अफ़ग़ानिस्तान",
      "zh": "阿富汗"
    },
    flag: '🇦🇫',
    flagU: 'U+1F1E6 U+1F1EB',
  ),
  CountryModel(
    name: 'Åland Islands',
    iso3: 'ALA',
    iso2: 'AX',
    phoneCode: '358',
    translations: {
      "en": "Åland Islands",
      "fr": "Åland",
      "si": "Åland දූපත්",
      "ta": "ஓலந்து தீவுகள்",
      "fi": "Ahvenanmaan maakunta",
      "hi": "ऑलैण्ड द्वीपसमूह",
      "zh": "奥兰群岛"
    },
    flag: '🇦🇽',
    flagU: 'U+1F1E6 U+1F1FD',
  ),
  CountryModel(
    name: 'Albania',
    iso3: 'ALB',
    iso2: 'AL',
    phoneCode: '355',
    translations: {
      "en": "Albania",
      "fr": "Albanie",
      "si": "ඇල්බේනියාව",
      "ta": "அல்பேனியா",
      "hi": "अल्बानिया",
      "zh": "阿尔巴尼亚"
    },
    flag: '🇦🇱',
    flagU: 'U+1F1E6 U+1F1F1',
  ),
  CountryModel(
    name: 'Algeria',
    iso3: 'DZA',
    iso2: 'DZ',
    phoneCode: '213',
    translations: {
      "en": "Algeria",
      "fr": "Algérie",
      "si": "ඇල්ජීරියාව",
      "ta": "அல்சீரியா",
      "hi": "अल्जीरिया",
      "zh": "阿尔及利亚"
    },
    flag: '🇩🇿',
    flagU: 'U+1F1E9 U+1F1FF',
  ),
  CountryModel(
    name: 'American Samoa',
    iso3: 'ASM',
    iso2: 'AS',
    phoneCode: '1',
    translations: {
      "en": "American Samoa",
      "fr": "Samoa américaines",
      "si": "ඇමරිකානු සැමෝවා",
      "ta": "அமெரிக்க சமோவா",
      "fi": "Amerikan Samoa",
      "hi": "अमेरिकी समोआ",
      "zh": "美属萨摩亚"
    },
    flag: '🇦🇸',
    flagU: 'U+1F1E6 U+1F1F8',
  ),
  CountryModel(
    name: 'Andorra',
    iso3: 'AND',
    iso2: 'AD',
    phoneCode: '376',
    translations: {
      "en": "Andorra",
      "fr": "Andorre",
      "si": "ඇන්ඩෝරා",
      "ta": "அந்தோரா",
      "hi": "अंडोरा",
      "zh": "安道尔"
    },
    flag: '🇦🇩',
    flagU: 'U+1F1E6 U+1F1E9',
  ),
  CountryModel(
    name: 'Angola',
    iso3: 'AGO',
    iso2: 'AO',
    phoneCode: '244',
    translations: {
      "en": "Angola",
      "fr": "Angola",
      "si": "ඇන්ගෝලාව",
      "ta": "அங்கோலா",
      "hi": "अंगोला",
      "zh": "安哥拉"
    },
    flag: '🇦🇴',
    flagU: 'U+1F1E6 U+1F1F4',
  ),
  CountryModel(
    name: 'Anguilla',
    iso3: 'AIA',
    iso2: 'AI',
    phoneCode: '1',
    translations: {
      "en": "Anguilla",
      "fr": "Anguilla",
      "si": "ඇන්ගුයිලා",
      "ta": "அங்கியுலா",
      "hi": "अंगुइला",
      "zh": "安圭拉"
    },
    flag: '🇦🇮',
    flagU: 'U+1F1E6 U+1F1EE',
  ),
  CountryModel(
    name: 'Antigua & Barbuda',
    iso3: 'ATG',
    iso2: 'AG',
    phoneCode: '1',
    translations: {
      "en": "Antigua & Barbuda",
      "fr": "Antigua-et-Barbuda",
      "si": "ඇන්ටිගුවා සහ බාබුඩා",
      "ta": "அன்டிகுவாவும் பர்பியுடாவும்",
      "fi": "Antigua ja Barbuda",
      "hi": "अण्टीगुआ और बारबूडा",
      "zh": "安提瓜和巴布达"
    },
    flag: '🇦🇬',
    flagU: 'U+1F1E6 U+1F1EC',
  ),
  CountryModel(
    name: 'Argentina',
    iso3: 'ARG',
    iso2: 'AR',
    phoneCode: '54',
    translations: {
      "en": "Argentina",
      "fr": "Argentine",
      "si": "ආජන්ටිනාව",
      "ta": "அர்கெந்தீனா",
      "fi": "Argentiina",
      "hi": "अर्जेण्टीना",
      "zh": "阿根廷"
    },
    flag: '🇦🇷',
    flagU: 'U+1F1E6 U+1F1F7',
  ),
  CountryModel(
    name: 'Armenia',
    iso3: 'ARM',
    iso2: 'AM',
    phoneCode: '374',
    translations: {
      "en": "Armenia",
      "fr": "Arménie",
      "si": "ආර්මේනියාව",
      "ta": "ஆர்மீனியா",
      "hi": "आर्मीनिया",
      "zh": "亚美尼亚"
    },
    flag: '🇦🇲',
    flagU: 'U+1F1E6 U+1F1F2',
  ),
  CountryModel(
    name: 'Aruba',
    iso3: 'ABW',
    iso2: 'AW',
    phoneCode: '297',
    translations: {
      "en": "Aruba",
      "fr": "Aruba",
      "si": "අරුබා",
      "ta": "அரூபா",
      "hi": "अरूबा",
      "zh": "阿鲁巴"
    },
    flag: '🇦🇼',
    flagU: 'U+1F1E6 U+1F1FC',
  ),
  CountryModel(
    name: 'Ascension Island',
    iso3: 'ASC',
    iso2: 'AC',
    phoneCode: '247',
    translations: {
      "en": "Ascension Island",
      "fr": "Île de l'Ascension",
      "si": "ඇසෙන්ෂන් දූපත",
      "ta": "அசென்சன் தீவு",
      "hi": "असेंशियन द्वीप",
      "zh": "阿森松岛"
    },
    flag: '🇦🇨',
    flagU: 'U+1F1E6 U+1F1E8',
  ),
  CountryModel(
    name: 'Australia',
    iso3: 'AUS',
    iso2: 'AU',
    phoneCode: '61',
    translations: {
      "en": "Australia",
      "fr": "Australie",
      "si": "ඕස්ට්‍රේලියාව",
      "ta": "ஆத்திரேலியா",
      "hi": "ऑस्ट्रेलिया",
      "zh": "澳大利亚"
    },
    flag: '🇦🇺',
    flagU: 'U+1F1E6 U+1F1FA',
  ),
  CountryModel(
    name: 'Austria',
    iso3: 'AUT',
    iso2: 'AT',
    phoneCode: '43',
    translations: {
      "en": "Austria",
      "fr": "Autriche",
      "si": "ඔස්ට්‍රියාව",
      "ta": "ஆஸ்திரியா",
      "fi": "Itävalta",
      "hi": "ऑस्ट्रिया",
      "zh": "奥地利"
    },
    flag: '🇦🇹',
    flagU: 'U+1F1E6 U+1F1F9',
  ),
  CountryModel(
    name: 'Azerbaijan',
    iso3: 'AZE',
    iso2: 'AZ',
    phoneCode: '994',
    translations: {
      "en": "Azerbaijan",
      "fr": "Azerbaïdjan",
      "si": "අසර්බයිජාන්",
      "ta": "அசர்பைஜான்",
      "fi": "Azerbaidžan",
      "hi": "अज़रबैजान",
      "zh": "阿塞拜疆"
    },
    flag: '🇦🇿',
    flagU: 'U+1F1E6 U+1F1FF',
  ),
  CountryModel(
    name: 'Bahamas',
    iso3: 'BHS',
    iso2: 'BS',
    phoneCode: '1',
    translations: {
      "en": "Bahamas",
      "fr": "Bahamas",
      "si": "බහමාස්",
      "ta": "பஹாமாஸ்",
      "fi": "Bahama",
      "hi": "बहामास",
      "zh": "巴哈马"
    },
    flag: '🇧🇸',
    flagU: 'U+1F1E7 U+1F1F8',
  ),
  CountryModel(
    name: 'Bahrain',
    iso3: 'BHR',
    iso2: 'BH',
    phoneCode: '973',
    translations: {
      "en": "Bahrain",
      "fr": "Bahreïn",
      "si": "බහරේන්",
      "ta": "பஹ்ரைன்",
      "hi": "बहरीन",
      "zh": "巴林"
    },
    flag: '🇧🇭',
    flagU: 'U+1F1E7 U+1F1ED',
  ),
  CountryModel(
    name: 'Bangladesh',
    iso3: 'BGD',
    iso2: 'BD',
    phoneCode: '880',
    translations: {
      "en": "Bangladesh",
      "fr": "Bangladesh",
      "si": "බංග්ලාදේශය",
      "ta": "வங்காளதேசம்",
      "hi": "बांग्लादेश",
      "zh": "孟加拉"
    },
    flag: '🇧🇩',
    flagU: 'U+1F1E7 U+1F1E9',
  ),
  CountryModel(
    name: 'Barbados',
    iso3: 'BRB',
    iso2: 'BB',
    phoneCode: '1',
    translations: {
      "en": "Barbados",
      "fr": "Barbade",
      "si": "බාබඩෝස්",
      "ta": "பார்படோசு",
      "hi": "बारबाडोस",
      "zh": "巴巴多斯"
    },
    flag: '🇧🇧',
    flagU: 'U+1F1E7 U+1F1E7',
  ),
  CountryModel(
    name: 'Belarus',
    iso3: 'BLR',
    iso2: 'BY',
    phoneCode: '375',
    translations: {
      "en": "Belarus",
      "fr": "Biélorussie",
      "si": "බෙලාරස්",
      "ta": "பெலருஸ்",
      "fi": "Valko-Venäjä",
      "hi": "बेलारूस",
      "zh": "白俄罗斯"
    },
    flag: '🇧🇾',
    flagU: 'U+1F1E7 U+1F1FE',
  ),
  CountryModel(
    name: 'Belgium',
    iso3: 'BEL',
    iso2: 'BE',
    phoneCode: '32',
    translations: {
      "en": "Belgium",
      "fr": "Belgique",
      "si": "බෙල්ජියම",
      "ta": "பெல்ஜியம்",
      "fi": "Belgia",
      "hi": "बेल्जियम",
      "zh": "比利时"
    },
    flag: '🇧🇪',
    flagU: 'U+1F1E7 U+1F1EA',
  ),
  CountryModel(
    name: 'Belize',
    iso3: 'BLZ',
    iso2: 'BZ',
    phoneCode: '501',
    translations: {
      "en": "Belize",
      "fr": "Belize",
      "si": "බෙලීස්",
      "ta": "பெலீசு",
      "hi": "बेलीज़",
      "zh": "伯利兹"
    },
    flag: '🇧🇿',
    flagU: 'U+1F1E7 U+1F1FF',
  ),
  CountryModel(
    name: 'Benin',
    iso3: 'BEN',
    iso2: 'BJ',
    phoneCode: '229',
    translations: {
      "en": "Benin",
      "fr": "Bénin",
      "si": "බෙනින්",
      "ta": "பெனின்",
      "hi": "बेनिन",
      "zh": "贝宁"
    },
    flag: '🇧🇯',
    flagU: 'U+1F1E7 U+1F1EF',
  ),
  CountryModel(
    name: 'Bermuda',
    iso3: 'BMU',
    iso2: 'BM',
    phoneCode: '1',
    translations: {
      "en": "Bermuda",
      "fr": "Bermudes",
      "si": "බර්මියුඩා",
      "ta": "பெர்முடா",
      "hi": "बरमूडा",
      "zh": "百慕大"
    },
    flag: '🇧🇲',
    flagU: 'U+1F1E7 U+1F1F2',
  ),
  CountryModel(
    name: 'Bhutan',
    iso3: 'BTN',
    iso2: 'BT',
    phoneCode: '975',
    translations: {
      "en": "Bhutan",
      "fr": "Bhoutan",
      "si": "භූතානය",
      "ta": "பூட்டான்",
      "hi": "भूटान",
      "zh": "不丹"
    },
    flag: '🇧🇹',
    flagU: 'U+1F1E7 U+1F1F9',
  ),
  CountryModel(
    name: 'Bolivia',
    iso3: 'BOL',
    iso2: 'BO',
    phoneCode: '591',
    translations: {
      "en": "Bolivia",
      "fr": "Bolivie",
      "si": "බොලිවියාව",
      "ta": "பொலிவியா",
      "hi": "बोलिविया",
      "zh": "玻利维亚"
    },
    flag: '🇧🇴',
    flagU: 'U+1F1E7 U+1F1F4',
  ),
  CountryModel(
    name: 'Bosnia and Herzegovina',
    iso3: 'BIH',
    iso2: 'BA',
    phoneCode: '387',
    translations: {
      "en": "Bosnia and Herzegovina",
      "fr": "Bosnie-Herzégovine",
      "si": "බොස්නියා සහ හර්සගෝවිනා",
      "ta": "போஸ்னியா மற்றும் ஹெர்சகோவினா",
      "fi": "Bosnia ja Hertsegovina",
      "hi": "बॉस्निया और हर्ज़ेगोविना",
      "zh": "波斯尼亚和黑塞哥维那"
    },
    flag: '🇧🇦',
    flagU: 'U+1F1E7 U+1F1E6',
  ),
  CountryModel(
    name: 'Botswana',
    iso3: 'BWA',
    iso2: 'BW',
    phoneCode: '267',
    translations: {
      "en": "Botswana",
      "fr": "Botswana",
      "si": "බොට්ස්වානා",
      "ta": "போட்சுவானா",
      "hi": "बोत्सवाना",
      "zh": "博茨瓦纳"
    },
    flag: '🇧🇼',
    flagU: 'U+1F1E7 U+1F1FC',
  ),
  CountryModel(
    name: 'Brazil',
    iso3: 'BRA',
    iso2: 'BR',
    phoneCode: '55',
    translations: {
      "en": "Brazil",
      "fr": "Brésil",
      "si": "බ්‍රසීලය",
      "ta": "பிரேசில்",
      "fi": "Brasilia",
      "hi": "ब्राज़ील",
      "zh": "巴西"
    },
    flag: '🇧🇷',
    flagU: 'U+1F1E7 U+1F1F7',
  ),
  CountryModel(
    name: 'British Indian Ocean Territory',
    iso3: 'IOT',
    iso2: 'IO',
    phoneCode: '246',
    translations: {
      "en": "British Indian Ocean Territory",
      "fr": "Territoire britannique de l'océan Indien",
      "si": "බ්‍රිතාන්‍ය ඉන්දියානු සාගර කලාපය",
      "ta": "பிரித்தானிய இந்தியப் பெருங்கடல் மண்டலம்",
      "fi": "Brittiläinen Intian valtameren alue",
      "hi": "ब्रिटिश हिंद महासागर क्षेत्र",
      "zh": "英属印度洋领地"
    },
    flag: '🇮🇴',
    flagU: 'U+1F1EE U+1F1F4',
  ),
  CountryModel(
    name: 'British Virgin Islands',
    iso3: 'VGB',
    iso2: 'VG',
    phoneCode: '1',
    translations: {
      "en": "British Virgin Islands",
      "fr": "Îles Vierges britanniques",
      "si": "බ්‍රිතාන්‍ය වර්ජින් දූපත්",
      "ta": "பிரித்தானிய கன்னித் தீவுகள்",
      "fi": "Brittiläiset Neitsytsaaret",
      "hi": "ब्रिटिश वर्जिन द्वीपसमूह",
      "zh": "英属维尔京群岛"
    },
    flag: '🇻🇬',
    flagU: 'U+1F1FB U+1F1EC',
  ),
  CountryModel(
    name: 'Brunei',
    iso3: 'BRN',
    iso2: 'BN',
    phoneCode: '673',
    translations: {
      "en": "Brunei",
      "fr": "Brunei",
      "si": "බෲනායි",
      "ta": "புரூணை",
      "hi": "ब्रुनेई",
      "zh": "文莱"
    },
    flag: '🇧🇳',
    flagU: 'U+1F1E7 U+1F1F3',
  ),
  CountryModel(
    name: 'Bulgaria',
    iso3: 'BGR',
    iso2: 'BG',
    phoneCode: '359',
    translations: {
      "en": "Bulgaria",
      "fr": "Bulgarie",
      "si": "බල්ගේරියාව",
      "ta": "பல்காரியா",
      "hi": "बुल्गारिया",
      "zh": "保加利亚"
    },
    flag: '🇧🇬',
    flagU: 'U+1F1E7 U+1F1EC',
  ),
  CountryModel(
    name: 'Burkina Faso',
    iso3: 'BFA',
    iso2: 'BF',
    phoneCode: '226',
    translations: {
      "en": "Burkina Faso",
      "fr": "Burkina Faso",
      "si": "බුර්කිනා ෆාසෝ",
      "ta": "புர்க்கினா பாசோ",
      "hi": "बुर्किना फासो",
      "zh": "布基纳法索"
    },
    flag: '🇧🇫',
    flagU: 'U+1F1E7 U+1F1EB',
  ),
  CountryModel(
    name: 'Burundi',
    iso3: 'BDI',
    iso2: 'BI',
    phoneCode: '257',
    translations: {
      "en": "Burundi",
      "fr": "Burundi",
      "si": "බුරුන්ඩි",
      "ta": "புருண்டி",
      "hi": "बुरुण्डी",
      "zh": "布隆迪"
    },
    flag: '🇧🇮',
    flagU: 'U+1F1E7 U+1F1EE',
  ),
  CountryModel(
    name: 'Cambodia',
    iso3: 'KHM',
    iso2: 'KH',
    phoneCode: '855',
    translations: {
      "en": "Cambodia",
      "fr": "Cambodge",
      "si": "කාම්බෝජය",
      "ta": "கம்போடியா",
      "fi": "Kambodža",
      "hi": "कम्बोडिया",
      "zh": "柬埔寨"
    },
    flag: '🇰🇭',
    flagU: 'U+1F1F0 U+1F1ED',
  ),
  CountryModel(
    name: 'Cameroon',
    iso3: 'CMR',
    iso2: 'CM',
    phoneCode: '237',
    translations: {
      "en": "Cameroon",
      "fr": "Cameroun",
      "si": "කැමරූන්",
      "ta": "கமரூன்",
      "fi": "Kamerun",
      "hi": "कैमरून",
      "zh": "喀麦隆"
    },
    flag: '🇨🇲',
    flagU: 'U+1F1E8 U+1F1F2',
  ),
  CountryModel(
    name: 'Canada',
    iso3: 'CAN',
    iso2: 'CA',
    phoneCode: '1',
    translations: {
      "en": "Canada",
      "fr": "Canada",
      "si": "කැනඩාව",
      "ta": "கனடா",
      "fi": "Kanada",
      "hi": "कनाडा",
      "zh": "加拿大"
    },
    flag: '🇨🇦',
    flagU: 'U+1F1E8 U+1F1E6',
  ),
  CountryModel(
    name: 'Cape Verde',
    iso3: 'CPV',
    iso2: 'CV',
    phoneCode: '238',
    translations: {
      "en": "Cape Verde",
      "fr": "Cap-Vert",
      "si": "කේප් වර්ඩ්",
      "ta": "கேப் வர்டி",
      "fi": "Kap Verde",
      "hi": "केप वर्दे",
      "zh": "佛得角"
    },
    flag: '🇨🇻',
    flagU: 'U+1F1E8 U+1F1FB',
  ),
  CountryModel(
    name: 'Caribbean Netherlands',
    iso3: 'BES',
    iso2: 'BQ',
    phoneCode: '599',
    translations: {
      "en": "Caribbean Netherlands",
      "fr": "Pays-Bas caribéens",
      "si": "කැරිබියානු නෙදර්ලන්තය",
      "ta": "கரீபியன் நெதர்லாந்து",
      "fi": "Alankomaiden Karibia",
      "hi": "कैरेबियन नीदरलैंड",
      "zh": "加勒比荷兰"
    },
    flag: '🇧🇶',
    flagU: 'U+1F1E7 U+1F1F6',
  ),
  CountryModel(
    name: 'Cayman Islands',
    iso3: 'CYM',
    iso2: 'KY',
    phoneCode: '1',
    translations: {
      "en": "Cayman Islands",
      "fr": "Îles Caïmans",
      "si": "කේමන් දූපත්",
      "ta": "கேமன் தீவுகள்",
      "fi": "Caymansaaret",
      "hi": "केमन द्वीपसमूह",
      "zh": "开曼群岛"
    },
    flag: '🇰🇾',
    flagU: 'U+1F1F0 U+1F1FE',
  ),
  CountryModel(
    name: 'Central African Republic',
    iso3: 'CAF',
    iso2: 'CF',
    phoneCode: '236',
    translations: {
      "en": "Central African Republic",
      "fr": "République centrafricaine",
      "si": "මධ්‍යම අප්‍රිකානු ජනරජය",
      "ta": "மத்திய ஆப்பிரிக்கக் குடியரசு",
      "fi": "Keski-Afrikan tasavalta",
      "hi": "मध्य अफ़्रीकी गणराज्य",
      "zh": "中非共和國"
    },
    flag: '🇨🇫',
    flagU: 'U+1F1E8 U+1F1EB',
  ),
  CountryModel(
    name: 'Chad',
    iso3: 'TCD',
    iso2: 'TD',
    phoneCode: '235',
    translations: {
      "en": "Chad",
      "fr": "Tchad",
      "si": "චෑඩ්",
      "ta": "சாட்",
      "fi": "Tšad",
      "hi": "चाड",
      "zh": "乍得"
    },
    flag: '🇹🇩',
    flagU: 'U+1F1F9 U+1F1E9',
  ),
  CountryModel(
    name: 'Chile',
    iso3: 'CHL',
    iso2: 'CL',
    phoneCode: '56',
    translations: {
      "en": "Chile",
      "fr": "Chili",
      "si": "චිලි ජනරජය",
      "ta": "சிலி",
      "hi": "चिली",
      "zh": "智利"
    },
    flag: '🇨🇱',
    flagU: 'U+1F1E8 U+1F1F1',
  ),
  CountryModel(
    name: 'China',
    iso3: 'CHN',
    iso2: 'CN',
    phoneCode: '86',
    translations: {
      "en": "China",
      "fr": "Chine",
      "si": "චීනය",
      "ta": "சீனா",
      "fi": "Kiina",
      "hi": "चीन",
      "zh": "中国"
    },
    flag: '🇨🇳',
    flagU: 'U+1F1E8 U+1F1F3',
  ),
  CountryModel(
    name: 'Christmas Island',
    iso3: 'CXR',
    iso2: 'CX',
    phoneCode: '61',
    translations: {
      "en": "Christmas Island",
      "fr": "Île Christmas",
      "si": "ක්‍රිස්මස් දූපත",
      "ta": "கிறிஸ்துமசு தீவு",
      "fi": "Joulusaari",
      "hi": "क्रिसमस द्वीप",
      "zh": "圣诞岛"
    },
    flag: '🇨🇽',
    flagU: 'U+1F1E8 U+1F1FD',
  ),
  CountryModel(
    name: 'Cocos (Keeling) Islands',
    iso3: 'CCK',
    iso2: 'CC',
    phoneCode: '61',
    translations: {
      "en": "Cocos (Keeling) Islands",
      "fr": "Îles Cocos",
      "si": "කොකෝස් (කීලිං) දූපත්",
      "ta": "கொக்கோசு (கீலிங்) தீவுகள்",
      "fi": "Kookossaaret",
      "hi": "कोकोस (कीलिंग) द्वीपसमूह",
      "zh": "科科斯（基林）群岛"
    },
    flag: '🇨🇨',
    flagU: 'U+1F1E8 U+1F1E8',
  ),
  CountryModel(
    name: 'Colombia',
    iso3: 'COL',
    iso2: 'CO',
    phoneCode: '57',
    translations: {
      "en": "Colombia",
      "fr": "Colombie",
      "si": "කොලොම්බියාව",
      "ta": "கொலம்பியா",
      "fi": "Kolumbia",
      "hi": "कोलम्बिया",
      "zh": "哥伦比亚"
    },
    flag: '🇨🇴',
    flagU: 'U+1F1E8 U+1F1F4',
  ),
  CountryModel(
    name: 'Comoros',
    iso3: 'COM',
    iso2: 'KM',
    phoneCode: '269',
    translations: {
      "en": "Comoros",
      "fr": "Comores",
      "si": "කොමරොස්",
      "ta": "கொமொரோசு",
      "fi": "Komorit",
      "hi": "कोमोरोस",
      "zh": "科摩罗"
    },
    flag: '🇰🇲',
    flagU: 'U+1F1F0 U+1F1F2',
  ),
  CountryModel(
    name: 'Cook Islands',
    iso3: 'COK',
    iso2: 'CK',
    phoneCode: '682',
    translations: {
      "en": "Cook Islands",
      "fr": "Îles Cook",
      "si": "කුක් දිවයින්",
      "ta": "குக் தீவுகள்",
      "fi": "Cookinsaaret",
      "hi": "कुक द्वीपसमूह",
      "zh": "库克群岛"
    },
    flag: '🇨🇰',
    flagU: 'U+1F1E8 U+1F1F0',
  ),
  CountryModel(
    name: 'Costa Rica',
    iso3: 'CRI',
    iso2: 'CR',
    phoneCode: '506',
    translations: {
      "en": "Costa Rica",
      "fr": "Costa Rica",
      "si": "කෝස්ට රිකා",
      "ta": "கோஸ்ட்டா ரிக்கா",
      "hi": "कोस्टा रिका",
      "zh": "哥斯达黎加"
    },
    flag: '🇨🇷',
    flagU: 'U+1F1E8 U+1F1F7',
  ),
  CountryModel(
    name: 'Cote d\'Ivoire (Ivory Coast)',
    iso3: 'CIV',
    iso2: 'CI',
    phoneCode: '225',
    translations: {
      "en": "Ivory Coast",
      "fr": "Côte d'Ivoire",
      "si": "අයිවරි කෝස්ට්",
      "ta": "ஐவரி கோஸ்ட்",
      "fi": "Norsunluurannikko",
      "hi": "कोत दिव्वार",
      "zh": "科特迪瓦"
    },
    flag: '🇨🇮',
    flagU: 'U+1F1E8 U+1F1EE',
  ),
  CountryModel(
    name: 'Croatia',
    iso3: 'HRV',
    iso2: 'HR',
    phoneCode: '385',
    translations: {
      "en": "Croatia",
      "fr": "Croatie",
      "si": "ක්‍රොඒෂියා",
      "ta": "குரோவாசியா",
      "fi": "Kroatia",
      "hi": "क्रोएशिया",
      "zh": "克罗地亚"
    },
    flag: '🇭🇷',
    flagU: 'U+1F1ED U+1F1F7',
  ),
  CountryModel(
    name: 'Cuba',
    iso3: 'CUB',
    iso2: 'CU',
    phoneCode: '53',
    translations: {
      "en": "Cuba",
      "fr": "Cuba",
      "si": "කියුබාව",
      "ta": "கியூபா",
      "fi": "Kuuba",
      "hi": "क्यूबा",
      "zh": "古巴"
    },
    flag: '🇨🇺',
    flagU: 'U+1F1E8 U+1F1FA',
  ),
  CountryModel(
    name: 'Curaçao',
    iso3: 'CUW',
    iso2: 'CW',
    phoneCode: '599',
    translations: {
      "en": "Curaçao",
      "fr": "Curaçao",
      "si": "කුරකාවෝ",
      "ta": "குராசோ",
      "hi": "कुराकाओ",
      "zh": "库拉索"
    },
    flag: '🇨🇼',
    flagU: 'U+1F1E8 U+1F1FC',
  ),
  CountryModel(
    name: 'Cyprus',
    iso3: 'CYP',
    iso2: 'CY',
    phoneCode: '357',
    translations: {
      "en": "Cyprus",
      "fr": "Chypre",
      "si": "සයිප්‍රසය",
      "ta": "சைப்பிரசு",
      "fi": "Kyproksen tasavalta",
      "hi": "साइप्रस",
      "zh": "塞浦路斯"
    },
    flag: '🇨🇾',
    flagU: 'U+1F1E8 U+1F1FE',
  ),
  CountryModel(
    name: 'Czech Republic',
    iso3: 'CZE',
    iso2: 'CZ',
    phoneCode: '420',
    translations: {
      "en": "Czech Republic",
      "fr": "République tchèque",
      "si": "චෙක් ජනරජය",
      "ta": "செக் குடியரசு",
      "fi": "Tšekki",
      "hi": "चेक गणराज्य",
      "zh": "捷克"
    },
    flag: '🇨🇿',
    flagU: 'U+1F1E8 U+1F1FF',
  ),
  CountryModel(
    name: 'Democratic Republic of the Congo',
    iso3: 'COD',
    iso2: 'CD',
    phoneCode: '243',
    translations: {
      "en": "Democratic Republic of the Congo",
      "fr": "République démocratique du Congo",
      "si": "කොන්ගෝ ප්‍රජාතන්ත්‍රවාදී ජනරජය",
      "ta": "காங்கோ மக்களாட்சிக் குடியரசு",
      "fi": "Kongon demokraattinen tasavalta",
      "hi": "कांगो लोकतान्त्रिक गणराज्य",
      "zh": "刚果民主共和国"
    },
    flag: '🇨🇩',
    flagU: 'U+1F1E8 U+1F1E9',
  ),
  CountryModel(
    name: 'Denmark',
    iso3: 'DNK',
    iso2: 'DK',
    phoneCode: '45',
    translations: {
      "en": "Denmark",
      "fr": "Danemark",
      "si": "ඩෙන්මාර්කය",
      "ta": "டென்மார்க்",
      "fi": "Tanska",
      "hi": "डेनमार्क",
      "zh": "丹麦"
    },
    flag: '🇩🇰',
    flagU: 'U+1F1E9 U+1F1F0',
  ),
  CountryModel(
    name: 'Djibouti',
    iso3: 'DJI',
    iso2: 'DJ',
    phoneCode: '253',
    translations: {
      "en": "Djibouti",
      "fr": "Djibouti",
      "si": "ජිබුටි",
      "ta": "ஜிபூட்டி",
      "hi": "जिबूती",
      "zh": "吉布提"
    },
    flag: '🇩🇯',
    flagU: 'U+1F1E9 U+1F1EF',
  ),
  CountryModel(
    name: 'Dominica',
    iso3: 'DMA',
    iso2: 'DM',
    phoneCode: '1',
    translations: {
      "en": "Dominica",
      "fr": "Dominique",
      "si": "ඩොමිනිකා",
      "ta": "டொமினிக்கா",
      "hi": "डोमिनिका",
      "zh": "多米尼克"
    },
    flag: '🇩🇲',
    flagU: 'U+1F1E9 U+1F1F2',
  ),
  CountryModel(
    name: 'Dominican Republic',
    iso3: 'DOM',
    iso2: 'DO',
    phoneCode: '1',
    translations: {
      "en": "Dominican Republic",
      "fr": "République dominicaine",
      "si": "ඩොමිනිකානු ජනරජය",
      "ta": "டொமினிக்கன் குடியரசு",
      "fi": "Dominikaaninen tasavalta",
      "hi": "डोमिनिकन गणराज्य",
      "zh": "多明尼加共和国"
    },
    flag: '🇩🇴',
    flagU: 'U+1F1E9 U+1F1F4',
  ),
  CountryModel(
    name: 'Ecuador',
    iso3: 'ECU',
    iso2: 'EC',
    phoneCode: '593',
    translations: {
      "en": "Ecuador",
      "fr": "Équateur",
      "si": "ඉක්වදෝරය",
      "ta": "எக்குவடோர்",
      "hi": "इक्वाडोर",
      "zh": "厄瓜多尔"
    },
    flag: '🇪🇨',
    flagU: 'U+1F1EA U+1F1E8',
  ),
  CountryModel(
    name: 'Egypt',
    iso3: 'EGY',
    iso2: 'EG',
    phoneCode: '20',
    translations: {
      "en": "Egypt",
      "fr": "Égypte",
      "si": "ඊජිප්තුව",
      "ta": "எகிப்து",
      "fi": "Egypti",
      "hi": "मिस्र",
      "zh": "埃及"
    },
    flag: '🇪🇬',
    flagU: 'U+1F1EA U+1F1EC',
  ),
  CountryModel(
    name: 'El Salvador',
    iso3: 'SLV',
    iso2: 'SV',
    phoneCode: '503',
    translations: {
      "en": "El Salvador",
      "fr": "Salvador",
      "si": "එල් සැල්වදෝරය",
      "ta": "எல் சால்வடோர்",
      "hi": "अल साल्वाडोर",
      "zh": "萨尔瓦多"
    },
    flag: '🇸🇻',
    flagU: 'U+1F1F8 U+1F1FB',
  ),
  CountryModel(
    name: 'Equatorial Guinea',
    iso3: 'GNQ',
    iso2: 'GQ',
    phoneCode: '240',
    translations: {
      "en": "Equatorial Guinea",
      "fr": "Guinée-Équatoriale",
      "si": "සමක ගිනියාව",
      "ta": "எக்குவடோரியல் கினி",
      "fi": "Päiväntasaajan Guinea",
      "hi": "भूमध्यरेखीय गिनी",
      "zh": "赤道几内亚"
    },
    flag: '🇬🇶',
    flagU: 'U+1F1EC U+1F1F6',
  ),
  CountryModel(
    name: 'Eritrea',
    iso3: 'ERI',
    iso2: 'ER',
    phoneCode: '291',
    translations: {
      "en": "Eritrea",
      "fr": "Érythrée",
      "si": "එරිත්‍රියාව",
      "ta": "எரித்திரியா",
      "hi": "इरिट्रिया",
      "zh": "厄立特里亚"
    },
    flag: '🇪🇷',
    flagU: 'U+1F1EA U+1F1F7',
  ),
  CountryModel(
    name: 'Estonia',
    iso3: 'EST',
    iso2: 'EE',
    phoneCode: '372',
    translations: {
      "en": "Estonia",
      "fr": "Estonie",
      "si": "එස්ටෝනියාව",
      "ta": "எஸ்டோனியா",
      "fi": "Viro",
      "hi": "एस्टोनिया",
      "zh": "爱沙尼亚"
    },
    flag: '🇪🇪',
    flagU: 'U+1F1EA U+1F1EA',
  ),
  CountryModel(
    name: 'Eswatini',
    iso3: 'SWZ',
    iso2: 'SZ',
    phoneCode: '268',
    translations: {
      "en": "Eswatini",
      "fr": "Eswatini",
      "si": "ඊස්වාටිනි",
      "ta": "எசுவாத்தினி",
      "hi": "इस्वातिनी",
      "zh": "史瓦帝尼"
    },
    flag: '🇸🇿',
    flagU: 'U+1F1F8 U+1F1FF',
  ),
  CountryModel(
    name: 'Ethiopia',
    iso3: 'ETH',
    iso2: 'ET',
    phoneCode: '251',
    translations: {
      "en": "Ethiopia",
      "fr": "Éthiopie",
      "si": "ඉතියෝපියාව",
      "ta": "எத்தியோப்பியா",
      "fi": "Etiopia",
      "hi": "इथोपिया",
      "zh": "埃塞俄比亚"
    },
    flag: '🇪🇹',
    flagU: 'U+1F1EA U+1F1F9',
  ),
  CountryModel(
    name: 'Falkland Islands',
    iso3: 'FLK',
    iso2: 'FK',
    phoneCode: '500',
    translations: {
      "en": "Falkland Islands",
      "fr": "Îles Malouines",
      "si": "ෆෝක්ලන්ඩ් දූපත්",
      "ta": "போக்லாந்து தீவுகள்",
      "fi": "Falklandinsaaret",
      "hi": "फ़ॉकलैंड द्वीपसमूह",
      "zh": "福克兰群岛"
    },
    flag: '🇫🇰',
    flagU: 'U+1F1EB U+1F1F0',
  ),
  CountryModel(
    name: 'Faroe Islands',
    iso3: 'FRO',
    iso2: 'FO',
    phoneCode: '298',
    translations: {
      "en": "Faroe Islands",
      "fr": "Îles Féroé",
      "si": "ෆාරෝ දිවයින්",
      "ta": "பரோயே தீவுகள்",
      "fi": "Färsaaret",
      "hi": "फ़रो द्वीपसमूह",
      "zh": "法罗群岛"
    },
    flag: '🇫🇴',
    flagU: 'U+1F1EB U+1F1F4',
  ),
  CountryModel(
    name: 'Fiji',
    iso3: 'FJI',
    iso2: 'FJ',
    phoneCode: '679',
    translations: {
      "en": "Fiji",
      "fr": "Fidji",
      "si": "ෆීජි",
      "ta": "பிஜி",
      "fi": "Fidži",
      "hi": "फ़िजी",
      "zh": "斐济"
    },
    flag: '🇫🇯',
    flagU: 'U+1F1EB U+1F1EF',
  ),
  CountryModel(
    name: 'Finland',
    iso3: 'FIN',
    iso2: 'FI',
    phoneCode: '358',
    translations: {
      "en": "Finland",
      "fr": "Finlande",
      "si": "ෆින්ලන්තය",
      "ta": "பின்லாந்து",
      "fi": "Suomi",
      "hi": "फिनलैंड",
      "zh": "芬兰"
    },
    flag: '🇫🇮',
    flagU: 'U+1F1EB U+1F1EE',
  ),
  CountryModel(
    name: 'France',
    iso3: 'FRA',
    iso2: 'FR',
    phoneCode: '33',
    translations: {
      "en": "France",
      "fr": "France",
      "si": "ප්‍රංශය",
      "ta": "பிரான்சு",
      "fi": "Ranska",
      "hi": "फ़्रान्स",
      "zh": "法国"
    },
    flag: '🇫🇷',
    flagU: 'U+1F1EB U+1F1F7',
  ),
  CountryModel(
    name: 'French Guiana',
    iso3: 'GUF',
    iso2: 'GF',
    phoneCode: '594',
    translations: {
      "en": "French Guiana",
      "fr": "Guyane française",
      "si": "ප්රංශ ගයනා",
      "ta": "பிரெஞ்சு கயானா",
      "fi": "Ranskan Guayana",
      "hi": "फ्रांसीसी गुयाना",
      "zh": "法属圭亚那"
    },
    flag: '🇬🇫',
    flagU: 'U+1F1EC U+1F1EB',
  ),
  CountryModel(
    name: 'French Polynesia',
    iso3: 'PYF',
    iso2: 'PF',
    phoneCode: '689',
    translations: {
      "en": "French Polynesia",
      "fr": "Polynésie française",
      "si": "ප්රංශ පොලිනීසියාව",
      "ta": "பிரெஞ்சு பொலினீசியா",
      "fi": "Ranskan Polynesia",
      "hi": "फ़्रान्सीसी पोलिनेशिया",
      "zh": "法属波利尼西亚"
    },
    flag: '🇵🇫',
    flagU: 'U+1F1F5 U+1F1EB',
  ),
  CountryModel(
    name: 'French Southern Territories',
    iso3: 'ATF',
    iso2: 'TF',
    phoneCode: '262',
    translations: {
      "en": "French Southern Territories",
      "fr": "Terres australes françaises",
      "si": "ප්රංශ දකුණු ප්රදේශ",
      "ta": "பிரெஞ்சு தெற்கு பிரதேசங்கள்",
      "fi": "Ranskan eteläiset alueet",
      "hi": "दक्षिणी फ्राँसिसी क्षेत्र",
      "zh": "法属南部领地"
    },
    flag: '🇹🇫',
    flagU: 'U+1F1F9 U+1F1EB',
  ),
  CountryModel(
    name: 'Gabon',
    iso3: 'GAB',
    iso2: 'GA',
    phoneCode: '241',
    translations: {
      "en": "Gabon",
      "fr": "Gabon",
      "si": "ගැබොන්",
      "ta": "காபோன்",
      "hi": "गाबोन",
      "zh": "加蓬"
    },
    flag: '🇬🇦',
    flagU: 'U+1F1EC U+1F1E6',
  ),
  CountryModel(
    name: 'Gambia',
    iso3: 'GMB',
    iso2: 'GM',
    phoneCode: '220',
    translations: {
      "en": "Gambia",
      "fr": "Gambie",
      "si": "ගැම්බියාව",
      "ta": "காம்பியா",
      "hi": "गाम्बिया",
      "zh": "冈比亚"
    },
    flag: '🇬🇲',
    flagU: 'U+1F1EC U+1F1F2',
  ),
  CountryModel(
    name: 'Georgia',
    iso3: 'GEO',
    iso2: 'GE',
    phoneCode: '995',
    translations: {
      "en": "Georgia",
      "fr": "Géorgie",
      "si": "ජෝර්ජියාව",
      "ta": "ஜார்ஜியா",
      "hi": "जॉर्जिया",
      "zh": "格鲁吉亚"
    },
    flag: '🇬🇪',
    flagU: 'U+1F1EC U+1F1EA',
  ),
  CountryModel(
    name: 'Germany',
    iso3: 'DEU',
    iso2: 'DE',
    phoneCode: '49',
    translations: {
      "en": "Germany",
      "fr": "Allemagne",
      "si": "ජර්මනිය",
      "ta": "ஜெர்மனி",
      "fi": "Saksa",
      "hi": "जर्मनी",
      "zh": "德国"
    },
    flag: '🇩🇪',
    flagU: 'U+1F1E9 U+1F1EA',
  ),
  CountryModel(
    name: 'Ghana',
    iso3: 'GHA',
    iso2: 'GH',
    phoneCode: '233',
    translations: {
      "en": "Ghana",
      "fr": "Ghana",
      "si": "ඝානාව",
      "ta": "கானா",
      "hi": "घाना",
      "zh": "加纳"
    },
    flag: '🇬🇭',
    flagU: 'U+1F1EC U+1F1ED',
  ),
  CountryModel(
    name: 'Gibraltar',
    iso3: 'GIB',
    iso2: 'GI',
    phoneCode: '350',
    translations: {
      "en": "Gibraltar",
      "fr": "Gibraltar",
      "si": "ජිබ්‍රෝල්ටාව",
      "ta": "ஜிப்ரால்ட்டர்",
      "hi": "जिब्राल्टर",
      "zh": "直布罗陀"
    },
    flag: '🇬🇮',
    flagU: 'U+1F1EC U+1F1EE',
  ),
  CountryModel(
    name: 'Greece',
    iso3: 'GRC',
    iso2: 'GR',
    phoneCode: '30',
    translations: {
      "en": "Greece",
      "fr": "Grèce",
      "si": "ග්‍රීසිය",
      "ta": "கிரீஸ்",
      "fi": "Kreikka",
      "hi": "यूनान",
      "zh": "希腊"
    },
    flag: '🇬🇷',
    flagU: 'U+1F1EC U+1F1F7',
  ),
  CountryModel(
    name: 'Greenland',
    iso3: 'GRL',
    iso2: 'GL',
    phoneCode: '299',
    translations: {
      "en": "Greenland",
      "fr": "Groenland",
      "si": "ග්‍රීන්ලන්තය",
      "ta": "கிரீன்லாந்து",
      "fi": "Grönlanti",
      "hi": "ग्रीनलैंड",
      "zh": "格陵兰岛"
    },
    flag: '🇬🇱',
    flagU: 'U+1F1EC U+1F1F1',
  ),
  CountryModel(
    name: 'Grenada',
    iso3: 'GRD',
    iso2: 'GD',
    phoneCode: '1',
    translations: {
      "en": "Grenada",
      "fr": "Grenade",
      "si": "ග්රෙනඩා",
      "ta": "கிரெனடா",
      "hi": "ग्रेनाडा",
      "zh": "格林纳达"
    },
    flag: '🇬🇩',
    flagU: 'U+1F1EC U+1F1E9',
  ),
  CountryModel(
    name: 'Guadeloupe',
    iso3: 'GLP',
    iso2: 'GP',
    phoneCode: '590',
    translations: {
      "en": "Guadeloupe",
      "fr": "Guadeloupe",
      "ta": "குவாதலூப்பு",
      "hi": "गुआदेलूप",
      "zh": "瓜德罗普岛"
    },
    flag: '🇬🇵',
    flagU: 'U+1F1EC U+1F1F5',
  ),
  CountryModel(
    name: 'Guam',
    iso3: 'GUM',
    iso2: 'GU',
    phoneCode: '1',
    translations: {
      "en": "Guam",
      "fr": "Guam",
      "si": "ගුආම්",
      "ta": "குவாம்",
      "hi": "गुआम",
      "zh": "关岛"
    },
    flag: '🇬🇺',
    flagU: 'U+1F1EC U+1F1FA',
  ),
  CountryModel(
    name: 'Guatemala',
    iso3: 'GTM',
    iso2: 'GT',
    phoneCode: '502',
    translations: {
      "en": "Guatemala",
      "fr": "Guatemala",
      "si": "ගුවාටමාලා",
      "ta": "குவாத்தமாலா",
      "hi": "ग्वाटेमाला",
      "zh": "危地马拉"
    },
    flag: '🇬🇹',
    flagU: 'U+1F1EC U+1F1F9',
  ),
  CountryModel(
    name: 'Guernsey',
    iso3: 'GGY',
    iso2: 'GG',
    phoneCode: '44',
    translations: {
      "en": "Guernsey",
      "fr": "Guernsey",
      "si": "ගුර්න්සි",
      "ta": "கர்ன்சி",
      "hi": "गर्नसी",
      "zh": "根西岛"
    },
    flag: '🇬🇬',
    flagU: 'U+1F1EC U+1F1EC',
  ),
  CountryModel(
    name: 'Guinea',
    iso3: 'GIN',
    iso2: 'GN',
    phoneCode: '224',
    translations: {
      "en": "Guinea",
      "fr": "Guinée",
      "si": "ගිනියාව",
      "ta": "கினியா",
      "hi": "गिनी",
      "zh": "几内亚"
    },
    flag: '🇬🇳',
    flagU: 'U+1F1EC U+1F1F3',
  ),
  CountryModel(
    name: 'Guinea-Bissau',
    iso3: 'GNB',
    iso2: 'GW',
    phoneCode: '245',
    translations: {
      "en": "Guinea-Bissau",
      "fr": "Guinée-Bissau",
      "si": "ගිනියා-බිසාවු",
      "ta": "கினி-பிசாவு",
      "hi": "गिनी-बिसाऊ",
      "zh": "几内亚比绍"
    },
    flag: '🇬🇼',
    flagU: 'U+1F1EC U+1F1FC',
  ),
  CountryModel(
    name: 'Guyana',
    iso3: 'GUY',
    iso2: 'GY',
    phoneCode: '592',
    translations: {
      "en": "Guyana",
      "fr": "Guyane",
      "si": "ගයනාව",
      "ta": "கயானா",
      "hi": "गयाना",
      "zh": "圭亚那"
    },
    flag: '🇬🇾',
    flagU: 'U+1F1EC U+1F1FE',
  ),
  CountryModel(
    name: 'Haiti',
    iso3: 'HTI',
    iso2: 'HT',
    phoneCode: '509',
    translations: {
      "en": "Haiti",
      "fr": "Haïti",
      "si": "හෙයිටි",
      "ta": "ஹைட்டி",
      "hi": "हाइती",
      "zh": "海地"
    },
    flag: '🇭🇹',
    flagU: 'U+1F1ED U+1F1F9',
  ),
  CountryModel(
    name: 'Honduras',
    iso3: 'HND',
    iso2: 'HN',
    phoneCode: '504',
    translations: {
      "en": "Honduras",
      "fr": "Honduras",
      "si": "හොන්දුරාස්",
      "ta": "ஹோண்டுராஸ்",
      "hi": "हौण्डुरस",
      "zh": "洪都拉斯"
    },
    flag: '🇭🇳',
    flagU: 'U+1F1ED U+1F1F3',
  ),
  CountryModel(
    name: 'Hong Kong',
    iso3: 'HKG',
    iso2: 'HK',
    phoneCode: '852',
    translations: {
      "fr": "Hong Kong",
      "en": "Hong Kong",
      "si": "හොංකොං",
      "ta": "ஹாங்காங்",
      "fi": "Hongkong",
      "hi": "हॉन्ग कॉन्ग",
      "zh": "香港"
    },
    flag: '🇭🇰',
    flagU: 'U+1F1ED U+1F1F0',
  ),
  CountryModel(
    name: 'Hungary',
    iso3: 'HUN',
    iso2: 'HU',
    phoneCode: '36',
    translations: {
      "en": "Hungary",
      "fr": "Hongrie",
      "si": "හංගේරියාව",
      "ta": "ஹங்கேரி",
      "fi": "Unkari",
      "hi": "हंगरी",
      "zh": "匈牙利"
    },
    flag: '🇭🇺',
    flagU: 'U+1F1ED U+1F1FA',
  ),
  CountryModel(
    name: 'Iceland',
    iso3: 'ISL',
    iso2: 'IS',
    phoneCode: '354',
    translations: {
      "en": "Iceland",
      "fr": "Islande",
      "si": "අයිස්ලන්තය",
      "ta": "ஐசுலாந்து",
      "fi": "Islanti",
      "hi": "आइसलैंड",
      "zh": "冰岛"
    },
    flag: '🇮🇸',
    flagU: 'U+1F1EE U+1F1F8',
  ),
  CountryModel(
    name: 'India',
    iso3: 'IND',
    iso2: 'IN',
    phoneCode: '91',
    translations: {
      "en": "India",
      "fr": "Inde",
      "si": "ඉන්දියාව",
      "ta": "இந்தியா",
      "fi": "Intia",
      "hi": "भारत",
      "zh": "印度"
    },
    flag: '🇮🇳',
    flagU: 'U+1F1EE U+1F1F3',
  ),
  CountryModel(
    name: 'Indonesia',
    iso3: 'IDN',
    iso2: 'ID',
    phoneCode: '62',
    translations: {
      "en": "Indonesia",
      "fr": "Indonésie",
      "si": "ඉන්දුනීසියාව",
      "ta": "இந்தோனேசியா",
      "hi": "इंडोनेशिया",
      "zh": "印度尼西亚"
    },
    flag: '🇮🇩',
    flagU: 'U+1F1EE U+1F1E9',
  ),
  CountryModel(
    name: 'Iran',
    iso3: 'IRN',
    iso2: 'IR',
    phoneCode: '98',
    translations: {
      "en": "Iran",
      "fr": "Iran",
      "si": "ඉරානය",
      "ta": "ஈரான்",
      "hi": "ईरान",
      "zh": "伊朗"
    },
    flag: '🇮🇷',
    flagU: 'U+1F1EE U+1F1F7',
  ),
  CountryModel(
    name: 'Iraq',
    iso3: 'IRQ',
    iso2: 'IQ',
    phoneCode: '964',
    translations: {
      "en": "Iraq",
      "fr": "Irak",
      "si": "ඉරාකය",
      "ta": "ஈராக்கு",
      "fi": "Irak",
      "hi": "इराक़",
      "zh": "伊拉克"
    },
    flag: '🇮🇶',
    flagU: 'U+1F1EE U+1F1F6',
  ),
  CountryModel(
    name: 'Ireland',
    iso3: 'IRL',
    iso2: 'IE',
    phoneCode: '353',
    translations: {
      "en": "Ireland",
      "fr": "Irlande",
      "si": "අයර්ලන්තය",
      "ta": "அயர்லாந்து",
      "fi": "Irlanti",
      "hi": "आयरलैण्ड",
      "zh": "爱尔兰"
    },
    flag: '🇮🇪',
    flagU: 'U+1F1EE U+1F1EA',
  ),
  CountryModel(
    name: 'Isle of Man',
    iso3: 'IMN',
    iso2: 'IM',
    phoneCode: '44',
    translations: {
      "en": "Isle of Man",
      "fr": "Île de Man",
      "si": "අයිල් ඔෆ් මෑන්",
      "ta": "ஐல் ஆஃப் மேன்",
      "fi": "Mansaari",
      "hi": "आइल ऑफ़ मैन",
      "zh": "曼岛"
    },
    flag: '🇮🇲',
    flagU: 'U+1F1EE U+1F1F2',
  ),
  CountryModel(
    name: 'Israel',
    iso3: 'ISR',
    iso2: 'IL',
    phoneCode: '972',
    translations: {
      "en": "Israel",
      "fr": "Israël",
      "si": "ඊශ්‍රායලය",
      "ta": "இஸ்ரேல்",
      "hi": "इज़राइल",
      "zh": "以色列"
    },
    flag: '🇮🇱',
    flagU: 'U+1F1EE U+1F1F1',
  ),
  CountryModel(
    name: 'Italy',
    iso3: 'ITA',
    iso2: 'IT',
    phoneCode: '39',
    translations: {
      "en": "Italy",
      "fr": "Italie",
      "si": "ඉතාලිය",
      "ta": "இத்தாலி",
      "fi": "Italia",
      "hi": "इटली",
      "zh": "意大利"
    },
    flag: '🇮🇹',
    flagU: 'U+1F1EE U+1F1F9',
  ),
  CountryModel(
    name: 'Jamaica',
    iso3: 'JAM',
    iso2: 'JM',
    phoneCode: '1',
    translations: {
      "en": "Jamaica",
      "fr": "Jamaïque",
      "si": "ජැමෙයිකාව",
      "ta": "ஜமைக்கா",
      "fi": "Jamaika",
      "hi": "जमैका",
      "zh": "牙买加"
    },
    flag: '🇯🇲',
    flagU: 'U+1F1EF U+1F1F2',
  ),
  CountryModel(
    name: 'Japan',
    iso3: 'JPN',
    iso2: 'JP',
    phoneCode: '81',
    translations: {
      "en": "Japan",
      "fr": "Japon",
      "si": "ජපානය",
      "ta": "ஜப்பான்",
      "fi": "Japani",
      "hi": "जापान",
      "zh": "日本"
    },
    flag: '🇯🇵',
    flagU: 'U+1F1EF U+1F1F5',
  ),
  CountryModel(
    name: 'Jersey',
    iso3: 'JEY',
    iso2: 'JE',
    phoneCode: '44',
    translations: {
      "en": "Jersey",
      "fr": "Jersey",
      "si": "ජර්සි",
      "ta": "ஜெர்சி",
      "hi": "जर्सी",
      "zh": "泽西岛"
    },
    flag: '🇯🇪',
    flagU: 'U+1F1EF U+1F1EA',
  ),
  CountryModel(
    name: 'Jordan',
    iso3: 'JOR',
    iso2: 'JO',
    phoneCode: '962',
    translations: {
      "en": "Jordan",
      "fr": "Jordanie",
      "si": "ජෝර්දානය",
      "ta": "ஜோர்தான்",
      "fi": "Jordania",
      "hi": "जॉर्डन",
      "zh": "约旦"
    },
    flag: '🇯🇴',
    flagU: 'U+1F1EF U+1F1F4',
  ),
  CountryModel(
    name: 'Kazakhstan',
    iso3: 'KAZ',
    iso2: 'KZ',
    phoneCode: '7',
    translations: {
      "en": "Kazakhstan",
      "fr": "Kazakhstan",
      "si": "කසක්ස්තානය",
      "ta": "கசக்கஸ்தான்",
      "fi": "Kazakstan",
      "hi": "कज़ाख़िस्तान",
      "zh": "哈萨克斯坦"
    },
    flag: '🇰🇿',
    flagU: 'U+1F1F0 U+1F1FF',
  ),
  CountryModel(
    name: 'Kenya',
    iso3: 'KEN',
    iso2: 'KE',
    phoneCode: '254',
    translations: {
      "en": "Kenya",
      "fr": "Kenya",
      "si": "කෙන්යාව",
      "ta": "கென்யா",
      "fi": "Kenia",
      "hi": "केन्या",
      "zh": "肯尼亚"
    },
    flag: '🇰🇪',
    flagU: 'U+1F1F0 U+1F1EA',
  ),
  CountryModel(
    name: 'Kiribati',
    iso3: 'KIR',
    iso2: 'KI',
    phoneCode: '686',
    translations: {
      "en": "Kiribati",
      "fr": "Kiribati",
      "si": "කිරිබටි",
      "ta": "கிரிபட்டி",
      "hi": "किरिबाती",
      "zh": "基里巴斯"
    },
    flag: '🇰🇮',
    flagU: 'U+1F1F0 U+1F1EE',
  ),
  CountryModel(
    name: 'Kosovo',
    iso3: 'XKX',
    iso2: 'XK',
    phoneCode: '383',
    translations: {
      "en": "Kosovo",
      "fr": "Kosovo",
      "si": "කොසෝවො",
      "ta": "கொசோவோ",
      "hi": "कोसोवो",
      "zh": "科索沃"
    },
    flag: '🇽🇰',
    flagU: 'U+1F1FD U+1F1F0',
  ),
  CountryModel(
    name: 'Kuwait',
    iso3: 'KWT',
    iso2: 'KW',
    phoneCode: '965',
    translations: {
      "en": "Kuwait",
      "fr": "Koweït",
      "si": "කුවේට්",
      "ta": "குவைத்து",
      "hi": "कुवैत",
      "zh": "科威特"
    },
    flag: '🇰🇼',
    flagU: 'U+1F1F0 U+1F1FC',
  ),
  CountryModel(
    name: 'Kyrgyzstan',
    iso3: 'KGZ',
    iso2: 'KG',
    phoneCode: '996',
    translations: {
      "en": "Kyrgyzstan",
      "fr": "Kirghizistan",
      "si": "කිර්ගිස්තානය",
      "ta": "கிர்கிசுத்தான்",
      "fi": "Kirgisia",
      "hi": "किर्गिज़स्तान",
      "zh": "吉尔吉斯斯坦"
    },
    flag: '🇰🇬',
    flagU: 'U+1F1F0 U+1F1EC',
  ),
  CountryModel(
    name: 'Laos',
    iso3: 'LAO',
    iso2: 'LA',
    phoneCode: '856',
    translations: {
      "en": "Laos",
      "fr": "Laos",
      "si": "ලාඕසය",
      "ta": "லாவோஸ்",
      "hi": "लाओस",
      "zh": "老挝"
    },
    flag: '🇱🇦',
    flagU: 'U+1F1F1 U+1F1E6',
  ),
  CountryModel(
    name: 'Latvia',
    iso3: 'LVA',
    iso2: 'LV',
    phoneCode: '371',
    translations: {
      "en": "Latvia",
      "fr": "Lettonie",
      "si": "ලැට්වියාව",
      "ta": "லாத்வியா",
      "hi": "लातविया",
      "zh": "拉脱维亚"
    },
    flag: '🇱🇻',
    flagU: 'U+1F1F1 U+1F1FB',
  ),
  CountryModel(
    name: 'Lebanon',
    iso3: 'LBN',
    iso2: 'LB',
    phoneCode: '961',
    translations: {
      "en": "Lebanon",
      "fr": "Liban",
      "si": "ලෙබනනය",
      "ta": "லெபனான்",
      "fi": "Libanon",
      "hi": "लेबनान",
      "zh": "黎巴嫩"
    },
    flag: '🇱🇧',
    flagU: 'U+1F1F1 U+1F1E7',
  ),
  CountryModel(
    name: 'Lesotho',
    iso3: 'LSO',
    iso2: 'LS',
    phoneCode: '266',
    translations: {
      "en": "Lesotho",
      "fr": "Lesotho",
      "si": "ලෙසෝතෝ",
      "ta": "லெசோத்தோ",
      "hi": "लिसूतू",
      "zh": "莱索托"
    },
    flag: '🇱🇸',
    flagU: 'U+1F1F1 U+1F1F8',
  ),
  CountryModel(
    name: 'Liberia',
    iso3: 'LBR',
    iso2: 'LR',
    phoneCode: '231',
    translations: {
      "en": "Liberia",
      "fr": "Liberia",
      "si": "ලයිබීරියාව",
      "ta": "லைபீரியா",
      "hi": "लाइबेरिया",
      "zh": "利比里亚"
    },
    flag: '🇱🇷',
    flagU: 'U+1F1F1 U+1F1F7',
  ),
  CountryModel(
    name: 'Libya',
    iso3: 'LBY',
    iso2: 'LY',
    phoneCode: '218',
    translations: {
      "en": "Libya",
      "fr": "Libye",
      "si": "ලිබියාව",
      "ta": "லிபியா",
      "hi": "लीबिया",
      "zh": "利比亚"
    },
    flag: '🇱🇾',
    flagU: 'U+1F1F1 U+1F1FE',
  ),
  CountryModel(
    name: 'Liechtenstein',
    iso3: 'LIE',
    iso2: 'LI',
    phoneCode: '423',
    translations: {
      "en": "Liechtenstein",
      "fr": "Liechtenstein",
      "si": "ලීච්ටන්ස්ටේන්",
      "ta": "லீக்கின்ஸ்டைன்",
      "hi": "लिख्टेंश्टाइन",
      "zh": "列支敦士登"
    },
    flag: '🇱🇮',
    flagU: 'U+1F1F1 U+1F1EE',
  ),
  CountryModel(
    name: 'Lithuania',
    iso3: 'LTU',
    iso2: 'LT',
    phoneCode: '370',
    translations: {
      "en": "Lithuania",
      "fr": "Lituanie",
      "si": "ලිතුවේනියාව",
      "ta": "லித்துவேனியா",
      "fi": "Liettua",
      "hi": "लिथुआनिया",
      "zh": "立陶宛"
    },
    flag: '🇱🇹',
    flagU: 'U+1F1F1 U+1F1F9',
  ),
  CountryModel(
    name: 'Luxembourg',
    iso3: 'LUX',
    iso2: 'LU',
    phoneCode: '352',
    translations: {
      "en": "Luxembourg",
      "fr": "Luxembourg",
      "si": "ලක්සම්බර්ග්",
      "ta": "லக்சம்பர்க்",
      "fi": "Luxemburg",
      "hi": "लक्ज़मबर्ग",
      "zh": "卢森堡"
    },
    flag: '🇱🇺',
    flagU: 'U+1F1F1 U+1F1FA',
  ),
  CountryModel(
    name: 'Macau',
    iso3: 'MAC',
    iso2: 'MO',
    phoneCode: '853',
    translations: {
      "en": "Macau",
      "fr": "Macao",
      "si": "මකාවෝ",
      "ta": "மக்காவு",
      "fi": "Macao",
      "hi": "मकाउ",
      "zh": "澳门特别行政区"
    },
    flag: '🇲🇴',
    flagU: 'U+1F1F2 U+1F1F4',
  ),
  CountryModel(
    name: 'Madagascar',
    iso3: 'MDG',
    iso2: 'MG',
    phoneCode: '261',
    translations: {
      "en": "Madagascar",
      "fr": "Madagascar",
      "si": "මැඩගස්කරය",
      "ta": "மடகாசுகர்",
      "fi": "Madagaskar",
      "hi": "मेडागास्कर",
      "zh": "马达加斯加"
    },
    flag: '🇲🇬',
    flagU: 'U+1F1F2 U+1F1EC',
  ),
  CountryModel(
    name: 'Malawi',
    iso3: 'MWI',
    iso2: 'MW',
    phoneCode: '265',
    translations: {
      "en": "Malawi",
      "fr": "Malawi",
      "si": "මලාවි",
      "ta": "மலாவி",
      "hi": "मलावी",
      "zh": "马拉维"
    },
    flag: '🇲🇼',
    flagU: 'U+1F1F2 U+1F1FC',
  ),
  CountryModel(
    name: 'Malaysia',
    iso3: 'MYS',
    iso2: 'MY',
    phoneCode: '60',
    translations: {
      "en": "Malaysia",
      "fr": "Malaisie",
      "si": "මලයාසියාව",
      "ta": "மலேசியா",
      "fi": "Malesia",
      "hi": "मलेशिया",
      "zh": "马来西亚"
    },
    flag: '🇲🇾',
    flagU: 'U+1F1F2 U+1F1FE',
  ),
  CountryModel(
    name: 'Maldives',
    iso3: 'MDV',
    iso2: 'MV',
    phoneCode: '960',
    translations: {
      "en": "Maldives",
      "fr": "Maldives",
      "si": "මාලදිවයින",
      "ta": "மாலைத்தீவுகள்",
      "fi": "Malediivit",
      "hi": "मालदीव",
      "zh": "马尔代夫"
    },
    flag: '🇲🇻',
    flagU: 'U+1F1F2 U+1F1FB',
  ),
  CountryModel(
    name: 'Mali',
    iso3: 'MLI',
    iso2: 'ML',
    phoneCode: '223',
    translations: {
      "en": "Mali",
      "fr": "Mali",
      "si": "මාලි",
      "ta": "மாலி",
      "hi": "माली",
      "zh": "马里"
    },
    flag: '🇲🇱',
    flagU: 'U+1F1F2 U+1F1F1',
  ),
  CountryModel(
    name: 'Malta',
    iso3: 'MLT',
    iso2: 'MT',
    phoneCode: '356',
    translations: {
      "en": "Malta",
      "fr": "Malte",
      "si": "මෝල්ටාව",
      "ta": "மால்ட்டா",
      "hi": "माल्टा",
      "zh": "马耳他"
    },
    flag: '🇲🇹',
    flagU: 'U+1F1F2 U+1F1F9',
  ),
  CountryModel(
    name: 'Marshall Islands',
    iso3: 'MHL',
    iso2: 'MH',
    phoneCode: '692',
    translations: {
      "en": "Marshall Islands",
      "fr": "Îles Marshall",
      "si": "මාෂල් දූපත්",
      "ta": "மார்சல் தீவுகள்",
      "fi": "Marshallinsaaret",
      "hi": "मार्शल द्वीपसमूह",
      "zh": "马绍尔群岛"
    },
    flag: '🇲🇭',
    flagU: 'U+1F1F2 U+1F1ED',
  ),
  CountryModel(
    name: 'Martinique',
    iso3: 'MTQ',
    iso2: 'MQ',
    phoneCode: '596',
    translations: {
      "en": "Martinique",
      "fr": "Martinique",
      "si": "මාර්ටිනික්",
      "ta": "மார்டினிக்",
      "hi": "मार्टीनिक",
      "zh": "马提尼克岛"
    },
    flag: '🇲🇶',
    flagU: 'U+1F1F2 U+1F1F6',
  ),
  CountryModel(
    name: 'Mauritania',
    iso3: 'MRT',
    iso2: 'MR',
    phoneCode: '222',
    translations: {
      "en": "Mauritania",
      "fr": "Mauritanie",
      "si": "මොරිටේනියාව",
      "ta": "மூரித்தானியா",
      "hi": "मॉरीतानिया",
      "zh": "毛里塔尼亚"
    },
    flag: '🇲🇷',
    flagU: 'U+1F1F2 U+1F1F7',
  ),
  CountryModel(
    name: 'Mauritius',
    iso3: 'MUS',
    iso2: 'MU',
    phoneCode: '230',
    translations: {
      "en": "Mauritius",
      "fr": "Maurice",
      "si": "මොරිෂස්",
      "ta": "மொரிசியசு",
      "hi": "मॉरिशस",
      "zh": "毛里求斯"
    },
    flag: '🇲🇺',
    flagU: 'U+1F1F2 U+1F1FA',
  ),
  CountryModel(
    name: 'Mayotte',
    iso3: 'MYT',
    iso2: 'YT',
    phoneCode: '262',
    translations: {
      "en": "Mayotte",
      "fr": "Mayotte",
      "si": "මයෝට්",
      "ta": "மயோட்டே",
      "hi": "मायोत",
      "zh": "马约特"
    },
    flag: '🇾🇹',
    flagU: 'U+1F1FE U+1F1F9',
  ),
  CountryModel(
    name: 'Mexico',
    iso3: 'MEX',
    iso2: 'MX',
    phoneCode: '52',
    translations: {
      "en": "Mexico",
      "fr": "Mexique",
      "si": "මෙක්සිකෝව",
      "ta": "மெக்சிக்கோ",
      "fi": "Meksiko",
      "hi": "मेक्सिको",
      "zh": "墨西哥"
    },
    flag: '🇲🇽',
    flagU: 'U+1F1F2 U+1F1FD',
  ),
  CountryModel(
    name: 'Micronesia',
    iso3: 'FSM',
    iso2: 'FM',
    phoneCode: '691',
    translations: {
      "en": "Micronesia",
      "fr": "Micronésie",
      "si": "මයික්රොනීසියාව",
      "ta": "மைக்குரோனீசியா",
      "fi": "Mikronesia",
      "hi": "माइक्रोनीशिया",
      "zh": "密克罗尼西亚"
    },
    flag: '🇫🇲',
    flagU: 'U+1F1EB U+1F1F2',
  ),
  CountryModel(
    name: 'Moldova',
    iso3: 'MDA',
    iso2: 'MD',
    phoneCode: '373',
    translations: {
      "en": "Moldova",
      "fr": "Moldavie",
      "si": "මෝල්ඩෝවා",
      "ta": "மால்டோவா",
      "hi": "मॉल्डोवा",
      "zh": "摩尔多瓦"
    },
    flag: '🇲🇩',
    flagU: 'U+1F1F2 U+1F1E9',
  ),
  CountryModel(
    name: 'Monaco',
    iso3: 'MCO',
    iso2: 'MC',
    phoneCode: '377',
    translations: {
      "en": "Monaco",
      "fr": "Monaco",
      "si": "මොනාකෝ",
      "ta": "மொனாக்கோ",
      "hi": "मोनाको",
      "zh": "摩纳哥"
    },
    flag: '🇲🇨',
    flagU: 'U+1F1F2 U+1F1E8',
  ),
  CountryModel(
    name: 'Mongolia',
    iso3: 'MNG',
    iso2: 'MN',
    phoneCode: '976',
    translations: {
      "en": "Mongolia",
      "fr": "Mongolie",
      "si": "මොංගෝලියාව",
      "ta": "மங்கோலியா",
      "hi": "मंगोलिया",
      "zh": "蒙古"
    },
    flag: '🇲🇳',
    flagU: 'U+1F1F2 U+1F1F3',
  ),
  CountryModel(
    name: 'Montenegro',
    iso3: 'MNE',
    iso2: 'ME',
    phoneCode: '382',
    translations: {
      "en": "Montenegro",
      "fr": "Monténégro",
      "si": "මොන්ටිනිග්‍රෝ",
      "ta": "மொண்டெனேகுரோ",
      "hi": "मॉन्टेनीग्रो",
      "zh": "黑山"
    },
    flag: '🇲🇪',
    flagU: 'U+1F1F2 U+1F1EA',
  ),
  CountryModel(
    name: 'Montserrat',
    iso3: 'MSR',
    iso2: 'MS',
    phoneCode: '1',
    translations: {
      "en": "Montserrat",
      "fr": "Montserrat",
      "si": "මොන්ට්සෙරාට්",
      "ta": "மொன்செராட்",
      "hi": "मोंटसेराट",
      "zh": "蒙特塞拉特"
    },
    flag: '🇲🇸',
    flagU: 'U+1F1F2 U+1F1F8',
  ),
  CountryModel(
    name: 'Morocco',
    iso3: 'MAR',
    iso2: 'MA',
    phoneCode: '212',
    translations: {
      "en": "Morocco",
      "fr": "Maroc",
      "si": "මොරොක්කෝව",
      "ta": "மொரோக்கோ",
      "fi": "Marokko",
      "hi": "मोरक्को",
      "zh": "摩洛哥"
    },
    flag: '🇲🇦',
    flagU: 'U+1F1F2 U+1F1E6',
  ),
  CountryModel(
    name: 'Mozambique',
    iso3: 'MOZ',
    iso2: 'MZ',
    phoneCode: '258',
    translations: {
      "en": "Mozambique",
      "fr": "Mozambique",
      "si": "මොසැම්බික්",
      "ta": "மொசாம்பிக்",
      "fi": "Mosambik",
      "hi": "मोज़ाम्बिक",
      "zh": "莫桑比克"
    },
    flag: '🇲🇿',
    flagU: 'U+1F1F2 U+1F1FF',
  ),
  CountryModel(
    name: 'Myanmar',
    iso3: 'MMR',
    iso2: 'MM',
    phoneCode: '95',
    translations: {
      "en": "Myanmar",
      "fr": "Myanmar",
      "si": "මියන්මාරය",
      "ta": "மியான்மர்",
      "hi": "म्यांमार",
      "zh": "缅甸"
    },
    flag: '🇲🇲',
    flagU: 'U+1F1F2 U+1F1F2',
  ),
  CountryModel(
    name: 'Namibia',
    iso3: 'NAM',
    iso2: 'NA',
    phoneCode: '264',
    translations: {
      "en": "Namibia",
      "fr": "Namibie",
      "si": "නැමීබියාව",
      "ta": "நமீபியா",
      "hi": "नामीबिया",
      "zh": "纳米比亚"
    },
    flag: '🇳🇦',
    flagU: 'U+1F1F3 U+1F1E6',
  ),
  CountryModel(
    name: 'Nauru',
    iso3: 'NRU',
    iso2: 'NR',
    phoneCode: '674',
    translations: {
      "en": "Nauru",
      "fr": "Nauru",
      "si": "නාඌරූ",
      "ta": "நவூரு",
      "hi": "नाउरू",
      "zh": "瑙鲁"
    },
    flag: '🇳🇷',
    flagU: 'U+1F1F3 U+1F1F7',
  ),
  CountryModel(
    name: 'Nepal',
    iso3: 'NPL',
    iso2: 'NP',
    phoneCode: '977',
    translations: {
      "en": "Nepal",
      "fr": "Népal",
      "si": "නේපාලය",
      "ta": "நேபாளம்",
      "hi": "नेपाल",
      "zh": "尼泊尔"
    },
    flag: '🇳🇵',
    flagU: 'U+1F1F3 U+1F1F5',
  ),
  CountryModel(
    name: 'Netherlands',
    iso3: 'NLD',
    iso2: 'NL',
    phoneCode: '31',
    translations: {
      "en": "Netherlands",
      "fr": "Pays-Bas",
      "si": "නෙදර්ලන්තය",
      "ta": "நெதர்லாந்து",
      "fi": "Alankomaat",
      "hi": "नीदरलैंड",
      "zh": "荷兰"
    },
    flag: '🇳🇱',
    flagU: 'U+1F1F3 U+1F1F1',
  ),
  CountryModel(
    name: 'New Caledonia',
    iso3: 'NCL',
    iso2: 'NC',
    phoneCode: '687',
    translations: {
      "en": "New Caledonia",
      "fr": "Nouvelle-Calédonie",
      "si": "නව කැලිඩෝනියාව",
      "ta": "நியூ கலிடோனியா",
      "fi": "Uusi-Kaledonia",
      "hi": "नया कैलेडोनिया",
      "zh": "新喀里多尼亚"
    },
    flag: '🇳🇨',
    flagU: 'U+1F1F3 U+1F1E8',
  ),
  CountryModel(
    name: 'New Zealand',
    iso3: 'NZL',
    iso2: 'NZ',
    phoneCode: '64',
    translations: {
      "en": "New Zealand",
      "fr": "Nouvelle-Zélande",
      "si": "නව සීලන්තය",
      "ta": "நியூசிலாந்து",
      "fi": "Uusi-Seelanti",
      "hi": "न्यूजीलैंड",
      "zh": "新西兰"
    },
    flag: '🇳🇿',
    flagU: 'U+1F1F3 U+1F1FF',
  ),
  CountryModel(
    name: 'Nicaragua',
    iso3: 'NIC',
    iso2: 'NI',
    phoneCode: '505',
    translations: {
      "en": "Nicaragua",
      "fr": "Nicaragua",
      "si": "නිකැරගුවා",
      "ta": "நிக்கராகுவா",
      "hi": "निकारागुआ",
      "zh": "尼加拉瓜"
    },
    flag: '🇳🇮',
    flagU: 'U+1F1F3 U+1F1EE',
  ),
  CountryModel(
    name: 'Niger',
    iso3: 'NER',
    iso2: 'NE',
    phoneCode: '227',
    translations: {
      "en": "Niger",
      "fr": "Niger",
      "si": "නයිජර්",
      "ta": "நைஜர்",
      "hi": "नाइजर",
      "zh": "尼日尔"
    },
    flag: '🇳🇪',
    flagU: 'U+1F1F3 U+1F1EA',
  ),
  CountryModel(
    name: 'Nigeria',
    iso3: 'NGA',
    iso2: 'NG',
    phoneCode: '234',
    translations: {
      "en": "Nigeria",
      "fr": "Nigéria",
      "si": "නයිජීරියාව",
      "ta": "நைஜீரியா",
      "hi": "नाइजीरिया",
      "zh": "尼日利亚"
    },
    flag: '🇳🇬',
    flagU: 'U+1F1F3 U+1F1EC',
  ),
  CountryModel(
    name: 'Niue',
    iso3: 'NIU',
    iso2: 'NU',
    phoneCode: '683',
    translations: {
      "en": "Niue",
      "fr": "Niue",
      "si": "නියු",
      "ta": "நியுவே",
      "hi": "निउए",
      "zh": "纽埃"
    },
    flag: '🇳🇺',
    flagU: 'U+1F1F3 U+1F1FA',
  ),
  CountryModel(
    name: 'Norfolk Island',
    iso3: 'NFK',
    iso2: 'NF',
    phoneCode: '672',
    translations: {
      "en": "Norfolk Island",
      "fr": "Île Norfolk",
      "si": "නෝෆ්ලොක් දිවයින",
      "ta": "நோர்போக் தீவு",
      "fi": "Norfolkinsaari",
      "hi": "नॉरफ़ॉक द्वीप",
      "zh": "诺福克岛"
    },
    flag: '🇳🇫',
    flagU: 'U+1F1F3 U+1F1EB',
  ),
  CountryModel(
    name: 'North Korea',
    iso3: 'PRK',
    iso2: 'KP',
    phoneCode: '850',
    translations: {
      "en": "North Korea",
      "fr": "Corée du Nord",
      "si": "උතුරු කොරියාව",
      "ta": "வட கொரியா",
      "fi": "Pohjois-Korea",
      "hi": "उत्तर कोरिया",
      "zh": "朝鲜"
    },
    flag: '🇰🇵',
    flagU: 'U+1F1F0 U+1F1F5',
  ),
  CountryModel(
    name: 'North Macedonia',
    iso3: 'MKD',
    iso2: 'MK',
    phoneCode: '389',
    translations: {
      "en": "North Macedonia",
      "fr": "Macédoine du Nord",
      "si": "උතුරු මැසිඩෝනියාව",
      "ta": "வடக்கு மக்கெதோனியா",
      "fi": "Pohjois-Makedonia",
      "hi": "उत्तर मैसेडोनिया",
      "zh": "北马其顿"
    },
    flag: '🇲🇰',
    flagU: 'U+1F1F2 U+1F1F0',
  ),
  CountryModel(
    name: 'Northern Mariana Islands',
    iso3: 'MNP',
    iso2: 'MP',
    phoneCode: '1',
    translations: {
      "en": "Northern Mariana Islands",
      "fr": "Îles Mariannes du Nord",
      "si": "උතුරු මරියානා දූපත්",
      "ta": "வடக்கு மரியானா தீவுகள்",
      "fi": "Pohjois-Mariaanit",
      "hi": "उत्तरी मारियाना द्वीप",
      "zh": "北马里亚纳群岛"
    },
    flag: '🇲🇵',
    flagU: 'U+1F1F2 U+1F1F5',
  ),
  CountryModel(
    name: 'Norway',
    iso3: 'NOR',
    iso2: 'NO',
    phoneCode: '47',
    translations: {
      "en": "Norway",
      "fr": "Norvège",
      "si": "නෝර්වේ",
      "ta": "நோர்வே",
      "fi": "Norja",
      "hi": "नॉर्वे",
      "zh": "挪威"
    },
    flag: '🇳🇴',
    flagU: 'U+1F1F3 U+1F1F4',
  ),
  CountryModel(
    name: 'Oman',
    iso3: 'OMN',
    iso2: 'OM',
    phoneCode: '968',
    translations: {
      "en": "Oman",
      "fr": "Oman",
      "si": "ඕමානය",
      "ta": "ஓமான்",
      "hi": "ओमान",
      "zh": "阿曼"
    },
    flag: '🇴🇲',
    flagU: 'U+1F1F4 U+1F1F2',
  ),
  CountryModel(
    name: 'Pakistan',
    iso3: 'PAK',
    iso2: 'PK',
    phoneCode: '92',
    translations: {
      "en": "Pakistan",
      "fr": "Pakistan",
      "si": "පාකිස්ථානය",
      "ta": "பாகிஸ்தான்",
      "hi": "पाकिस्तान",
      "zh": "巴基斯坦"
    },
    flag: '🇵🇰',
    flagU: 'U+1F1F5 U+1F1F0',
  ),
  CountryModel(
    name: 'Palau',
    iso3: 'PLW',
    iso2: 'PW',
    phoneCode: '680',
    translations: {
      "en": "Palau",
      "fr": "Palaos",
      "si": "පලාවු",
      "ta": "பலாவு",
      "hi": "पलाउ",
      "zh": "帕劳"
    },
    flag: '🇵🇼',
    flagU: 'U+1F1F5 U+1F1FC',
  ),
  CountryModel(
    name: 'Palestine',
    iso3: 'PSE',
    iso2: 'PS',
    phoneCode: '970',
    translations: {
      "en": "Palestine",
      "fr": "Palestine",
      "si": "පලස්තීනය",
      "ta": "பலத்தீன் நாடு",
      "fi": "Palestiina",
      "hi": "फिलिस्तीन",
      "zh": "巴勒斯坦"
    },
    flag: '🇵🇸',
    flagU: 'U+1F1F5 U+1F1F8',
  ),
  CountryModel(
    name: 'Panama',
    iso3: 'PAN',
    iso2: 'PA',
    phoneCode: '507',
    translations: {
      "en": "Panama",
      "fr": "Panama",
      "si": "පැනමාව",
      "ta": "பனாமா",
      "hi": "पनामा",
      "zh": "巴拿马"
    },
    flag: '🇵🇦',
    flagU: 'U+1F1F5 U+1F1E6',
  ),
  CountryModel(
    name: 'Papua New Guinea',
    iso3: 'PNG',
    iso2: 'PG',
    phoneCode: '675',
    translations: {
      "en": "Papua New Guinea",
      "fr": "Papouasie-Nouvelle-Guinée",
      "si": "පැපුවා නිව්ගීනියාව",
      "ta": "பப்புவா நியூ கினி",
      "fi": "Papua-Uusi-Guinea",
      "hi": "पापुआ न्यू गिनी",
      "zh": "巴布亚新几内亚"
    },
    flag: '🇵🇬',
    flagU: 'U+1F1F5 U+1F1EC',
  ),
  CountryModel(
    name: 'Paraguay',
    iso3: 'PRY',
    iso2: 'PY',
    phoneCode: '595',
    translations: {
      "en": "Paraguay",
      "fr": "Paraguay",
      "si": "පැරගුවේ",
      "ta": "பரகுவை",
      "hi": "पैराग्वे",
      "zh": "巴拉圭"
    },
    flag: '🇵🇾',
    flagU: 'U+1F1F5 U+1F1FE',
  ),
  CountryModel(
    name: 'Peru',
    iso3: 'PER',
    iso2: 'PE',
    phoneCode: '51',
    translations: {
      "en": "Peru",
      "fr": "Pérou",
      "si": "පේරු",
      "ta": "பெரு",
      "hi": "पेरू",
      "zh": "秘鲁"
    },
    flag: '🇵🇪',
    flagU: 'U+1F1F5 U+1F1EA',
  ),
  CountryModel(
    name: 'Philippines',
    iso3: 'PHL',
    iso2: 'PH',
    phoneCode: '63',
    translations: {
      "en": "Philippines",
      "fr": "Philippines",
      "si": "පිලිපීනය",
      "ta": "பிலிப்பீன்சு",
      "fi": "Filippiinit",
      "hi": "फ़िलीपीन्स",
      "zh": "菲律宾"
    },
    flag: '🇵🇭',
    flagU: 'U+1F1F5 U+1F1ED',
  ),
  CountryModel(
    name: 'Pitcairn Islands',
    iso3: 'PCN',
    iso2: 'PN',
    phoneCode: '64',
    translations: {
      "en": "Pitcairn Islands",
      "fr": "Îles Pitcairn",
      "si": "පිට්කේන් දූපත්",
      "ta": "பிட்காயின் தீவுகள்",
      "fi": "Pitcairnsaaret",
      "hi": "पिटकेर्न द्वीप",
      "zh": "皮特凯恩群岛"
    },
    flag: '🇵🇳',
    flagU: 'U+1F1F5 U+1F1F3',
  ),
  CountryModel(
    name: 'Poland',
    iso3: 'POL',
    iso2: 'PL',
    phoneCode: '48',
    translations: {
      "en": "Poland",
      "fr": "Pologne",
      "si": "පෝලන්තය",
      "ta": "போலந்து",
      "fi": "Puola",
      "hi": "पोलैंड",
      "zh": "波兰"
    },
    flag: '🇵🇱',
    flagU: 'U+1F1F5 U+1F1F1',
  ),
  CountryModel(
    name: 'Portugal',
    iso3: 'PRT',
    iso2: 'PT',
    phoneCode: '351',
    translations: {
      "fr": "Portugal",
      "en": "Portugal",
      "si": "පෘතුගාලය",
      "ta": "போர்த்துகல்",
      "fi": "Portugali",
      "hi": "पुर्तगाल",
      "zh": "葡萄牙"
    },
    flag: '🇵🇹',
    flagU: 'U+1F1F5 U+1F1F9',
  ),
  CountryModel(
    name: 'Puerto Rico',
    iso3: 'PRI',
    iso2: 'PR',
    phoneCode: '1',
    translations: {
      "en": "Puerto Rico",
      "fr": "Porto Rico",
      "si": "පුවටෝ රිකෝ",
      "ta": "புவேர்ட்டோ ரிக்கோ",
      "hi": "पोर्टो रीको",
      "zh": "波多黎各"
    },
    flag: '🇵🇷',
    flagU: 'U+1F1F5 U+1F1F7',
  ),
  CountryModel(
    name: 'Qatar',
    iso3: 'QAT',
    iso2: 'QA',
    phoneCode: '974',
    translations: {
      "en": "Qatar",
      "fr": "Qatar",
      "si": "කටාර්",
      "ta": "கத்தார்",
      "hi": "क़तर",
      "zh": "卡塔尔"
    },
    flag: '🇶🇦',
    flagU: 'U+1F1F6 U+1F1E6',
  ),
  CountryModel(
    name: 'Republic of the Congo',
    iso3: 'COG',
    iso2: 'CG',
    phoneCode: '242',
    translations: {
      "en": "Republic of the Congo",
      "fr": "République du Congo",
      "si": "කොංගෝ ජනරජය",
      "ta": "கொங்கோ குடியரசு",
      "fi": "Kongon tasavalta",
      "hi": "कांगो गणराज्य",
      "zh": "刚果共和国"
    },
    flag: '🇨🇬',
    flagU: 'U+1F1E8 U+1F1EC',
  ),
  CountryModel(
    name: 'Spain',
    iso3: 'ESP',
    iso2: 'ES',
    phoneCode: '34',
    translations: {
      "en": "Spain",
      "fr": "Espagne",
      "si": "ස්පාඤ්ඤය",
      "ta": "எசுப்பானியா",
      "fi": "Espanja",
      "hi": "स्पेन",
      "zh": "西班牙"
    },
    flag: '🇪🇸',
    flagU: 'U+1F1EA U+1F1F8',
  ),
  CountryModel(
    name: 'Sri Lanka',
    iso3: 'LKA',
    iso2: 'LK',
    phoneCode: '94',
    translations: {
      "en": "Sri Lanka",
      "fr": "Sri Lanka",
      "si": "ශ්‍රී ලංකාව",
      "ta": "இலங்கை",
      "hi": "श्रीलंका",
      "zh": "斯里兰卡"
    },
    flag: '🇱🇰',
    flagU: 'U+1F1F1 U+1F1F0',
  ),
  CountryModel(
    name: 'Sudan',
    iso3: 'SDN',
    iso2: 'SD',
    phoneCode: '249',
    translations: {
      "en": "Sudan",
      "fr": "Soudan",
      "si": "සුඩානය",
      "ta": "சூடான்",
      "hi": "सूडान",
      "zh": "苏丹"
    },
    flag: '🇸🇩',
    flagU: 'U+1F1F8 U+1F1E9',
  ),
  CountryModel(
    name: 'Suriname',
    iso3: 'SUR',
    iso2: 'SR',
    phoneCode: '597',
    translations: {
      "en": "Suriname",
      "fr": "Surinam",
      "si": "සුරිනාමය",
      "ta": "சூரினாம்",
      "hi": "सूरीनाम",
      "zh": "苏里南"
    },
    flag: '🇸🇷',
    flagU: 'U+1F1F8 U+1F1F7',
  ),
  CountryModel(
    name: 'Svalbard and Jan Mayen',
    iso3: 'SJM',
    iso2: 'SJ',
    phoneCode: '47',
    translations: {
      "en": "Svalbard and Jan Mayen",
      "fr": "Svalbard et Jan Mayen",
      "si": "ස්වල්බාර්ඩ් සහ ජෑන් මායන්",
      "ta": "ஸ்வால்பார்ட் மற்றும் ஜான் மாயன்",
      "fi": "Huippuvuoret ja Jan Mayen",
      "hi": "स्वालबार्ड और जान मायेन",
      "zh": "斯瓦尔巴和扬马延"
    },
    flag: '🇸🇯',
    flagU: 'U+1F1F8 U+1F1EF',
  ),
  CountryModel(
    name: 'Sweden',
    iso3: 'SWE',
    iso2: 'SE',
    phoneCode: '46',
    translations: {
      "en": "Sweden",
      "fr": "Suède",
      "si": "ස්වීඩනය",
      "ta": "சுவீடன்",
      "fi": "Ruotsi",
      "hi": "स्वीडन",
      "zh": "瑞典"
    },
    flag: '🇸🇪',
    flagU: 'U+1F1F8 U+1F1EA',
  ),
  CountryModel(
    name: 'Switzerland',
    iso3: 'CHE',
    iso2: 'CH',
    phoneCode: '41',
    translations: {
      "en": "Switzerland",
      "fr": "Suisse",
      "si": "ස්විට්සර්ලන්තය",
      "ta": "சுவிட்சர்லாந்து",
      "fi": "Sveitsi",
      "hi": "स्विट्ज़रलैण्ड",
      "zh": "瑞士"
    },
    flag: '🇨🇭',
    flagU: 'U+1F1E8 U+1F1ED',
  ),
  CountryModel(
    name: 'Syria',
    iso3: 'SYR',
    iso2: 'SY',
    phoneCode: '963',
    translations: {
      "en": "Syria",
      "fr": "Syrie",
      "si": "සිරියාව",
      "ta": "சிரியா",
      "fi": "Syyria",
      "hi": "सीरिया",
      "zh": "叙利亚"
    },
    flag: '🇸🇾',
    flagU: 'U+1F1F8 U+1F1FE',
  ),
  CountryModel(
    name: 'Taiwan',
    iso3: 'TWN',
    iso2: 'TW',
    phoneCode: '886',
    translations: {
      "en": "Taiwan",
      "fr": "Taïwan",
      "si": "තායිවානය",
      "ta": "தைவான்",
      "hi": "ताइवान",
      "zh": "台湾"
    },
    flag: '🇹🇼',
    flagU: 'U+1F1F9 U+1F1FC',
  ),
  CountryModel(
    name: 'Tajikistan',
    iso3: 'TJK',
    iso2: 'TJ',
    phoneCode: '992',
    translations: {
      "en": "Tajikistan",
      "fr": "Tadjikistan",
      "si": "ටජිකිස්ථානය",
      "ta": "தஜிகிஸ்தான்",
      "fi": "Tadžikistan",
      "hi": "ताजिकिस्तान",
      "zh": "塔吉克斯坦"
    },
    flag: '🇹🇯',
    flagU: 'U+1F1F9 U+1F1EF',
  ),
  CountryModel(
    name: 'Tanzania',
    iso3: 'TZA',
    iso2: 'TZ',
    phoneCode: '255',
    translations: {
      "en": "Tanzania",
      "fr": "Tanzanie",
      "si": "ටැන්සානියාව",
      "ta": "தன்சானியா",
      "fi": "Tansania",
      "hi": "तंज़ानिया",
      "zh": "坦桑尼亚"
    },
    flag: '🇹🇿',
    flagU: 'U+1F1F9 U+1F1FF',
  ),
  CountryModel(
    name: 'Thailand',
    iso3: 'THA',
    iso2: 'TH',
    phoneCode: '66',
    translations: {
      "en": "Thailand",
      "fr": "Thaïlande",
      "si": "තායිලන්තය",
      "ta": "தாய்லாந்து",
      "fi": "Thaimaa",
      "hi": "थाईलैण्ड",
      "zh": "泰国"
    },
    flag: '🇹🇭',
    flagU: 'U+1F1F9 U+1F1ED',
  ),
  CountryModel(
    name: 'Timor-Leste',
    iso3: 'TLS',
    iso2: 'TL',
    phoneCode: '670',
    translations: {
      "en": "Timor-Leste",
      "fr": "Timor-Leste",
      "si": "ටිමෝර්-ලෙස්ටේ",
      "ta": "திமோர்-லெஸ்டே",
      "fi": "Itä-Timor",
      "hi": "तिमोर-लेस्ते",
      "zh": "东帝汶"
    },
    flag: '🇹🇱',
    flagU: 'U+1F1F9 U+1F1F1',
  ),
  CountryModel(
    name: 'Togo',
    iso3: 'TGO',
    iso2: 'TG',
    phoneCode: '228',
    translations: {
      "en": "Togo",
      "fr": "Togo",
      "si": "ටෝගෝ",
      "ta": "டோகோ",
      "hi": "टोगो",
      "zh": "多哥"
    },
    flag: '🇹🇬',
    flagU: 'U+1F1F9 U+1F1EC',
  ),
  CountryModel(
    name: 'Tokelau',
    iso3: 'TKL',
    iso2: 'TK',
    phoneCode: '690',
    translations: {
      "en": "Tokelau",
      "fr": "Tokelau",
      "si": "ටොකෙලාව්",
      "ta": "டோக்கெலாவ்",
      "hi": "टोकेलाऊ",
      "zh": "托克劳"
    },
    flag: '🇹🇰',
    flagU: 'U+1F1F9 U+1F1F0',
  ),
  CountryModel(
    name: 'Tonga',
    iso3: 'TON',
    iso2: 'TO',
    phoneCode: '676',
    translations: {
      "en": "Tonga",
      "fr": "Tonga",
      "si": "ටොංගා",
      "ta": "டோங்கா",
      "hi": "टोंगा",
      "zh": "汤加"
    },
    flag: '🇹🇴',
    flagU: 'U+1F1F9 U+1F1F4',
  ),
  CountryModel(
    name: 'Trinidad and Tobago',
    iso3: 'TTO',
    iso2: 'TT',
    phoneCode: '1',
    translations: {
      "en": "Trinidad and Tobago",
      "fr": "Trinité et Tobago",
      "si": "ට්‍රිනිඩෑඩ් සහ ටොබැගෝ",
      "ta": "டிரினிடாட் மற்றும் டொபாகோ",
      "fi": "Trinidad ja Tobago",
      "hi": "त्रिनिदाद और टोबैगो",
      "zh": "特立尼达和多巴哥"
    },
    flag: '🇹🇹',
    flagU: 'U+1F1F9 U+1F1F9',
  ),
  CountryModel(
    name: 'Tristan da Cunha',
    iso3: 'TAA',
    iso2: 'TA',
    phoneCode: '290',
    translations: {
      "en": "Tristan da Cunha",
      "si": "ට්‍රිස්ටන් ද කුන්හා",
      "ta": "டிரிஸ்டன் டா குன்ஹா",
      "hi": "त्रिस्तान दा कून्हा",
      "zh": "特里斯坦-达库尼亚"
    },
    flag: '🇹🇦',
    flagU: 'U+1F1F9 U+1F1E6',
  ),
  CountryModel(
    name: 'Tunisia',
    iso3: 'TUN',
    iso2: 'TN',
    phoneCode: '216',
    translations: {
      "en": "Tunisia",
      "fr": "Tunisie",
      "si": "ටියුනීසියාව",
      "ta": "தூனிசியா",
      "hi": "तूनिसीया",
      "zh": "突尼斯"
    },
    flag: '🇹🇳',
    flagU: 'U+1F1F9 U+1F1F3',
  ),
  CountryModel(
    name: 'Turkey',
    iso3: 'TUR',
    iso2: 'TR',
    phoneCode: '90',
    translations: {
      "en": "Turkey",
      "fr": "Turquie",
      "si": "තුර්කිය",
      "ta": "துருக்கி",
      "fi": "Turkki",
      "hi": "तुर्की",
      "zh": "土耳其"
    },
    flag: '🇹🇷',
    flagU: 'U+1F1F9 U+1F1F7',
  ),
  CountryModel(
    name: 'Turkmenistan',
    iso3: 'TKM',
    iso2: 'TM',
    phoneCode: '993',
    translations: {
      "en": "Turkmenistan",
      "fr": "Turkménistan",
      "si": "ටර්ක්මෙනිස්තානය",
      "ta": "துருக்மெனிஸ்தான்",
      "hi": "तुर्कमेनिस्तान",
      "zh": "土库曼斯坦"
    },
    flag: '🇹🇲',
    flagU: 'U+1F1F9 U+1F1F2',
  ),
  CountryModel(
    name: 'Turks and Caicos Islands',
    iso3: 'TCA',
    iso2: 'TC',
    phoneCode: '1',
    translations: {
      "en": "Turks and Caicos Islands",
      "fr": "Îles Turques-et-Caïques",
      "si": "ටර්ක්ස් සහ කයිකෝස් දූපත්",
      "ta": "துர்கசு கைகோசு தீவுகள்",
      "fi": "Turks- ja Caicossaaret",
      "hi": "तुर्क और केकोस द्वीपसमूह",
      "zh": "特克斯和凯科斯群岛"
    },
    flag: '🇹🇨',
    flagU: 'U+1F1F9 U+1F1E8',
  ),
  CountryModel(
    name: 'Tuvalu',
    iso3: 'TUV',
    iso2: 'TV',
    phoneCode: '688',
    translations: {
      "en": "Tuvalu",
      "fr": "Tuvalu",
      "si": "ටුවාලු",
      "ta": "துவாலு",
      "hi": "तुवालू",
      "zh": "图瓦卢"
    },
    flag: '🇹🇻',
    flagU: 'U+1F1F9 U+1F1FB',
  ),
  CountryModel(
    name: 'Uganda',
    iso3: 'UGA',
    iso2: 'UG',
    phoneCode: '256',
    translations: {
      "en": "Uganda",
      "fr": "Ouganda",
      "si": "උගන්ඩාව",
      "ta": "உகாண்டா",
      "hi": "युगांडा",
      "zh": "乌干达"
    },
    flag: '🇺🇬',
    flagU: 'U+1F1FA U+1F1EC',
  ),
  CountryModel(
    name: 'Ukraine',
    iso3: 'UKR',
    iso2: 'UA',
    phoneCode: '380',
    translations: {
      "en": "Ukraine",
      "fr": "Ukraine",
      "si": "යුක්රේනය",
      "ta": "உக்ரைன்",
      "fi": "Ukraina",
      "hi": "युक्रेन",
      "zh": "乌克兰"
    },
    flag: '🇺🇦',
    flagU: 'U+1F1FA U+1F1E6',
  ),
  CountryModel(
    name: 'United Arab Emirates',
    iso3: 'ARE',
    iso2: 'AE',
    phoneCode: '971',
    translations: {
      "en": "United Arab Emirates",
      "fr": "Émirats arabes unis",
      "si": "එක්සත් අරාබි එමීර් රාජ්‍යය",
      "ta": "ஐக்கிய அரபு அமீரகம்",
      "fi": "Yhdistyneet arabiemiirikunnat",
      "hi": "संयुक्त अरब अमीरात",
      "zh": "阿拉伯联合酋长国"
    },
    flag: '🇦🇪',
    flagU: 'U+1F1E6 U+1F1EA',
  ),
  CountryModel(
    name: 'United Kingdom',
    iso3: 'GBR',
    iso2: 'GB',
    phoneCode: '44',
    translations: {
      "en": "United Kingdom",
      "fr": "Royaume-Uni",
      "si": "එක්සත් රාජධානිය",
      "ta": "ஐக்கிய இராச்சியம்",
      "fi": "Yhdistynyt kuningaskunta",
      "hi": "यूनाइटेड किंगडम",
      "zh": "英国"
    },
    flag: '🇬🇧',
    flagU: 'U+1F1EC U+1F1E7',
  ),
  CountryModel(
    name: 'United States',
    iso3: 'USA',
    iso2: 'US',
    phoneCode: '1',
    translations: {
      "en": "United States",
      "fr": "États-Unis",
      "si": "එක්සත් ජනපදය",
      "ta": "அமெரிக்க ஐக்கிய நாடுகள்",
      "fi": "Yhdysvallat",
      "hi": "संयुक्त राज्य अमेरिका",
      "zh": "美国"
    },
    flag: '🇺🇸',
    flagU: 'U+1F1FA U+1F1F8',
  ),
  CountryModel(
    name: 'United States Virgin Islands',
    iso3: 'VIR',
    iso2: 'VI',
    phoneCode: '1',
    translations: {
      "en": "United States Virgin Islands",
      "fr": "Îles Vierges des États-Unis",
      "si": "එක්සත් ජනපද වර්ජින් දූපත්",
      "ta": "அமெரிக்க கன்னித் தீவுகள்",
      "fi": "Yhdysvaltain Neitsytsaaret",
      "hi": "संयुक्त राज्य वर्जिन द्वीपसमूह",
      "zh": "美属维尔京群岛"
    },
    flag: '🇻🇮',
    flagU: 'U+1F1FB U+1F1EE',
  ),
  CountryModel(
    name: 'Uruguay',
    iso3: 'URY',
    iso2: 'UY',
    phoneCode: '598',
    translations: {
      "en": "Uruguay",
      "fr": "Uruguay",
      "si": "උරුගුවායි",
      "ta": "உருகுவே",
      "hi": "उरुग्वे",
      "zh": "乌拉圭"
    },
    flag: '🇺🇾',
    flagU: 'U+1F1FA U+1F1FE',
  ),
  CountryModel(
    name: 'Uzbekistan',
    iso3: 'UZB',
    iso2: 'UZ',
    phoneCode: '998',
    translations: {
      "en": "Uzbekistan",
      "fr": "Ouzbékistan",
      "si": "උස්බෙකිස්තානය",
      "ta": "உசுபெக்கிசுத்தான்",
      "hi": "उज़्बेकिस्तान",
      "zh": "乌兹别克斯坦"
    },
    flag: '🇺🇿',
    flagU: 'U+1F1FA U+1F1FF',
  ),
  CountryModel(
    name: 'Vanuatu',
    iso3: 'VUT',
    iso2: 'VU',
    phoneCode: '678',
    translations: {
      "en": "Vanuatu",
      "fr": "Vanuatu",
      "si": "වනුවාටු",
      "ta": "வனுவாட்டு",
      "hi": "वानूआतू",
      "zh": "瓦努阿图"
    },
    flag: '🇻🇺',
    flagU: 'U+1F1FB U+1F1FA',
  ),
  CountryModel(
    name: 'Vatican City',
    iso3: 'VAT',
    iso2: 'VA',
    phoneCode: '39',
    translations: {
      "en": "Vatican City",
      "fr": "Cité du Vatican",
      "si": "වතිකානුව",
      "ta": "வத்திக்கான் நகர்",
      "fi": "Vatikaani",
      "hi": "वैटिकन सिटी",
      "zh": "梵蒂冈"
    },
    flag: '🇻🇦',
    flagU: 'U+1F1FB U+1F1E6',
  ),
  CountryModel(
    name: 'Venezuela',
    iso3: 'VEN',
    iso2: 'VE',
    phoneCode: '58',
    translations: {
      "en": "Venezuela",
      "fr": "Venezuela",
      "si": "වෙනිසියුලාව",
      "ta": "வெனிசுவேலா",
      "hi": "वेनेज़ुएला",
      "zh": "委内瑞拉"
    },
    flag: '🇻🇪',
    flagU: 'U+1F1FB U+1F1EA',
  ),
  CountryModel(
    name: 'Vietnam',
    iso3: 'VNM',
    iso2: 'VN',
    phoneCode: '84',
    translations: {
      "en": "Vietnam",
      "fr": "Viêt Nam",
      "si": "වියට්නාමය",
      "ta": "வியட்நாம்",
      "hi": "वियतनाम",
      "zh": "越南"
    },
    flag: '🇻🇳',
    flagU: 'U+1F1FB U+1F1F3',
  ),
  CountryModel(
    name: 'Wallis and Futuna',
    iso3: 'WLF',
    iso2: 'WF',
    phoneCode: '681',
    translations: {
      "en": "Wallis and Futuna",
      "fr": "Wallis-et-Futuna",
      "si": "වොලිස් සහ ෆුඩුනා",
      "ta": "வாலிஸ் மற்றும் ஃபுடுனா",
      "fi": "Wallis ja Futuna",
      "hi": "वालिस और फ़्यूचूना",
      "zh": "瓦利斯群岛和富图纳群岛"
    },
    flag: '🇼🇫',
    flagU: 'U+1F1FC U+1F1EB',
  ),
  CountryModel(
    name: 'Western Sahara',
    iso3: 'ESH',
    iso2: 'EH',
    phoneCode: '212',
    translations: {
      "en": "Western Sahara",
      "fr": "Sahara Occidental",
      "si": "බටහිර සහරා",
      "ta": "மேற்கு சகாரா",
      "fi": "Länsi-Sahara",
      "hi": "पश्चिमी सहारा",
      "zh": "西撒哈拉"
    },
    flag: '🇪🇭',
    flagU: 'U+1F1EA U+1F1ED',
  ),
  CountryModel(
    name: 'Yemen',
    iso3: 'YEM',
    iso2: 'YE',
    phoneCode: '967',
    translations: {
      "en": "Yemen",
      "fr": "Yémen",
      "si": "යේමනය",
      "ta": "யெமன்",
      "fi": "Jemen",
      "hi": "यमन",
      "zh": "也门"
    },
    flag: '🇾🇪',
    flagU: 'U+1F1FE U+1F1EA',
  ),
  CountryModel(
    name: 'Zambia',
    iso3: 'ZMB',
    iso2: 'ZM',
    phoneCode: '260',
    translations: {
      "en": "Zambia",
      "fr": "Zambie",
      "si": "සැම්බියා",
      "ta": "சாம்பியா",
      "fi": "Sambia",
      "hi": "जाम्बिया",
      "zh": "赞比亚"
    },
    flag: '🇿🇲',
    flagU: 'U+1F1FF U+1F1F2',
  ),
  CountryModel(
    name: 'Zimbabwe',
    iso3: 'ZWE',
    iso2: 'ZW',
    phoneCode: '263',
    translations: {
      "en": "Zimbabwe",
      "fr": "Zimbabwe",
      "si": "සිම්බාබ්වේ",
      "ta": "சிம்பாப்வே",
      "hi": "ज़िम्बाब्वे",
      "zh": "津巴布韦"
    },
    flag: '🇿🇼',
    flagU: 'U+1F1FF U+1F1FC',
  ),
];
