import 'dart:math';

import 'package:flutter/material.dart';
import 'package:playkosmos_v3/assets_gen/fonts.gen.dart';
import 'package:playkosmos_v3/enums/enums.dart';
import 'package:playkosmos_v3/models/display_user_model.dart';
import 'package:playkosmos_v3/models/flyer_positioning_model.dart';
import 'package:playkosmos_v3/models/home_activity_model.dart';
import 'package:playkosmos_v3/models/positioned_model.dart';
import 'package:playkosmos_v3/models/status_model.dart';
import 'package:playkosmos_v3/models/text_position_model.dart';
import 'package:playkosmos_v3/utils/utils.dart';

final _random = Random(10);

///Images from the internet
const String dInternetPhoto1 =
    'https://fastly.picsum.photos/id/0/5000/3333.jpg?hmac=_j6ghY5fCfSD6tvtcV74zXivkJSPIfR9B8w34XeQmvU';
const String dInternetPhoto2 =
    'https://fastly.picsum.photos/id/221/200/200.jpg?hmac=zy33VSww4_QQk0Hf2MngBaudI_ahiadnRwuREDTbWnA';
const String dInternetPhoto3 =
    'https://fastly.picsum.photos/id/0/5000/3333.jpg?hmac=_j6ghY5fCfSD6tvtcV74zXivkJSPIfR9B8w34XeQmvU';
const String dInternetVideo =
    'https://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4';
final List<String?> _imageList = [
  null,
  dInternetPhoto1,
  null,
  dInternetPhoto2,
  null,
  dInternetPhoto3,
];
const List<ReactionIconTypeEnum> _reactionList = ReactionIconTypeEnum.values;

final List<ActivityListModel> fHomeActivityList = [
  ActivityListModel(
    distance: 5,
    isActivityShared: false,
    activityPostTime: DateTime(2023, 4, 5, 13, 30, 20),
    activityUserProfile: const ActivityUserProfile(
      profileImage: dInternetPhoto1,
      profileName: 'Gold Daniel',
      profilePlan: 'diamond',
    ),
    activityBookmarked: false,
    activityIsUser: true,
    activityPost:
        'Lorem ipsum dolor sit amet consectetur. Et pellentesque morbi sit amet. Quam integer massa odio duis pulvinar consectetur dictum. Lorem ipsum dolor sit amet consectetur. Et pellentesque morbi sit amet. Quam integer massa odio duis pulvinar consectetur dictum ',
    activityFlyerProperties: ActivityFlyerProperties(
      activityTitle: 'Lorem ipsum dolor sit amet consectetur suspendisse.',
      activityDetails:
          'Lorem ipsum dolor sit amet consectetur. Enim eu proin in blandit pretium condimentum aliquam volutpat mattis scelerisque.',
      activityType: 'Classes',
      activityCity: 'Helsinki',
      activityVenue: 'Lönnrotinkatu 16, Salo, Varsinais-Suomi',
      activityCountry: 'Finland',
      activityInterest: 'basketball',
      activityPrice: '\$50',
      activityDate: DateTime(2023, 04, 10),
      activityTime: const TimeOfDay(
        hour: 12,
        minute: 10,
      ),
      activityDuration: '3 hrs',
      activityTimeZone: 'UTC(+1:00)',
      activityRefundTime: null,
      activityImage: null,
      activityRefundDate: null,
    ),
    activityPropertiesPosition: FlyerPositioning(
      image: FlyerUtils.cycling,
      interestName: 'cycling',
      positionText: const TextPositionModel(
        activityTitle: PositionedModel(
          top: 43,
          right: 20,
          left: 20,
          lines: 2,
          rowAlignment: MainAxisAlignment.center,
          textAlignment: TextAlign.center,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFFFFFFFF),
            fontSize: 14,
          ),
        ),
        activityDetails: PositionedModel(
          top: 286,
          right: 94,
          left: 9,
          lines: 3,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFF010101),
            fontSize: 10,
          ),
        ),
        activityType: PositionedModel(
          top: 98,
          right: 181,
          left: 6,
          rowAlignment: MainAxisAlignment.center,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFF010101),
            fontSize: 9,
          ),
        ),
        activityInterest: PositionedModel(
          top: 123,
          right: 181,
          left: 6,
          rowAlignment: MainAxisAlignment.center,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFF010101),
            fontSize: 9,
          ),
        ),
        activityDuration: PositionedModel(
          top: 236,
          right: 80,
          left: 19,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFFFFFFFF),
            fontSize: 9,
          ),
        ),
        activityDate: PositionedModel(
          top: 285,
          right: 10,
          left: 262,
          lines: 3,
          rowAlignment: MainAxisAlignment.center,
          textAlignment: TextAlign.center,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFF010101),
            fontSize: 10,
          ),
        ),
        activityTime: PositionedModel(
          top: 216,
          right: 100,
          left: 19,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFFFFFFFF),
            fontSize: 9,
          ),
        ),
        activityCity: PositionedModel(
          top: 178,
          right: 60,
          left: 19,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFFFFFFFF),
            fontSize: 9,
          ),
        ),
        activityCountry: PositionedModel(
          top: 197,
          right: 60,
          left: 19,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFFFFFFFF),
            fontSize: 9,
          ),
        ),
        activityVenue: PositionedModel(
          top: 152,
          right: 35,
          left: 19,
          lines: 2,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFFFFFFFF),
            fontSize: 8,
          ),
        ),
        activityFee: PositionedModel(
          top: 115,
          right: 10,
          left: 205,
          style: TextStyle(
            fontFamily: FontFamily.roboto,
            color: Color(0xFFFFFFFF),
            fontSize: 12,
            fontWeight: FontWeight.w500,
          ),
        ),
      ),
    ),
    activityAddedImages: [
      'https://fastly.picsum.photos/id/0/5000/3333.jpg?hmac=_j6ghY5fCfSD6tvtcV74zXivkJSPIfR9B8w34XeQmvU',
      'https://fastly.picsum.photos/id/705/200/200.jpg?hmac=2HZlwayMAMOyCllDpM-Mx3u2Xyk40VRHAzlpNLKyTC8',
      'https://fastly.picsum.photos/id/221/200/200.jpg?hmac=zy33VSww4_QQk0Hf2MngBaudI_ahiadnRwuREDTbWnA',
      'https://fastly.picsum.photos/id/1027/200/200.jpg?hmac=fiXlkLLwYm7JmmU80uRIj9g21XD4q9v_lM_2Z57UhuA',
      'https://fastly.picsum.photos/id/421/200/200.jpg?hmac=Kix073-H73pkRedH4XJ8fenHLI9Sd9akWlOFjKog0EA',
    ],
    activityParticipantsCount: 80,
    activityMaxParticipant: 100,
    playmatesAttending: List.generate(
      4,
      (index) => DisplayUser(
        username: 'Index $index',
        displayImage: _imageList[_random.nextInt(_imageList.length)],
      ),
    ),
    activityTag: const [
      'Rayna Rosser',
      'Kianna Vaccaro',
      'Swim Team Six Centre',
      'Kenny Event Centre',
      'Team Six Swim Store',
      'Kenny Event Centre',
      'Swim Team Six',
      'Dream Team',
    ],
    activityCommentsCount: 30,
    activityQAndACount: 40,
    activityReviewsCount: 3000,
    userReaction: null,
    activityReactionList: List.generate(
      1000,
      (index) => _reactionList[_random.nextInt(_reactionList.length)],
    ),
    activityShareCount: 500,
  ),
  ActivityListModel(
    isActivityShared: true,
    sharedActivityPost: null,
    sharedActivityPostTime: DateTime(2023, 6, 1, 13, 2, 20),
    sharedActivityTag: [
      'Ice Queen',
      'Okorie Ndubuisi',
    ],
    distance: 5,
    activityUserProfile: const ActivityUserProfile(
      profileImage: dInternetPhoto3,
      profileName: 'Chike Ebenezer',
      profilePlan: 'gold',
    ),
    activityPostTime: DateTime(2022, 4, 5, 13, 30, 20),
    sharedActivityUserProfile: const ActivityUserProfile(
      profileImage: dInternetPhoto1,
      profileName: 'Karol G',
      profilePlan: 'silver',
    ),
    activityIsUser: false,
    activityBookmarked: true,
    activityPost:
        'Lorem ipsum dolor sit amet consectetur. Et pellentesque morbi sit amet. Quam integer massa odio duis pulvinar consectetur dictum. Lorem ipsum dolor sit amet consectetur. Et pellentesque morbi sit amet. Quam integer massa odio duis pulvinar consectetur dictum ',
    activityFlyerProperties: ActivityFlyerProperties(
      activityTitle: 'Lorem ipsum dolor sit amet consectetur suspendisse.',
      activityDetails:
          'Lorem ipsum dolor sit amet consectetur. Enim eu proin in blandit pretium condimentum aliquam volutpat mattis scelerisque.',
      activityType: 'Classes',
      activityTime: const TimeOfDay(
        hour: 12,
        minute: 10,
      ),
      activityTimeZone: 'UTC(+1:00)',
      activityDate: DateTime(2023, 04, 10),
      activityDuration: '3 hrs',
      activityCity: 'Helsinki',
      activityRefundTime: null,
      activityImage: null,
      activityRefundDate: null,
      activityPrice: '\$50',
      activityVenue: 'Lönnrotinkatu 16, Salo, Varsinais-Suomi',
      activityCountry: 'Finland',
      activityInterest: 'basketball',
    ),
    activityPropertiesPosition: FlyerPositioning(
      image: FlyerUtils.bubbleFootball,
      interestName: 'bubbleFootball',
      positionText: const TextPositionModel(
        activityTitle: PositionedModel(
          top: 46,
          right: 20,
          left: 20,
          lines: 2,
          rowAlignment: MainAxisAlignment.center,
          textAlignment: TextAlign.center,
          style: TextStyle(
            fontFamily: FontFamily.bevan,
            color: Color(0xFF272361),
            fontSize: 14,
          ),
        ),
        activityDetails: PositionedModel(
          top: 275,
          right: 50,
          left: 50,
          lines: 3,
          rowAlignment: MainAxisAlignment.center,
          textAlignment: TextAlign.center,
          style: TextStyle(
            fontFamily: FontFamily.bevan,
            color: Color(0xFF272361),
            fontSize: 8,
          ),
        ),
        activityType: PositionedModel(
          top: 101,
          right: 91,
          left: 97,
          rowAlignment: MainAxisAlignment.center,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFF272361),
            fontSize: 9,
          ),
        ),
        activityInterest: PositionedModel(
          top: 128,
          right: 91,
          left: 97,
          rowAlignment: MainAxisAlignment.center,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFF272361),
            fontSize: 9,
          ),
        ),
        activityDuration: PositionedModel(
          top: 251,
          right: 10,
          left: 192,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFFFFFFFF),
            fontSize: 9,
          ),
        ),
        activityDate: PositionedModel(
          top: 20,
          right: 3,
          left: 218,
          rowAlignment: MainAxisAlignment.center,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFFFFFFFF),
            fontSize: 9,
          ),
        ),
        activityTime: PositionedModel(
          top: 251,
          right: 159,
          left: 63,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFFFFFFFF),
            fontSize: 9,
          ),
        ),
        activityCity: PositionedModel(
          top: 215,
          right: 20,
          left: 20,
          rowAlignment: MainAxisAlignment.center,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFFFFF200),
            fontSize: 10,
          ),
        ),
        activityCountry: PositionedModel(
          top: 233,
          right: 25,
          left: 25,
          rowAlignment: MainAxisAlignment.center,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFFFFFFFF),
            fontSize: 10,
          ),
        ),
        activityVenue: PositionedModel(
          top: 190,
          right: 10,
          left: 10,
          lines: 2,
          rowAlignment: MainAxisAlignment.center,
          textAlignment: TextAlign.center,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFFFFFFFF),
            fontSize: 8,
          ),
        ),
        activityFee: PositionedModel(
          top: 153,
          right: 129,
          left: 127,
          rowAlignment: MainAxisAlignment.center,
          style: TextStyle(
            fontFamily: FontFamily.roboto,
            color: Color(0xFFFFFFFF),
            fontSize: 8,
            fontWeight: FontWeight.w700,
          ),
        ),
      ),
    ),
    activityAddedImages: [
      'https://fastly.picsum.photos/id/0/5000/3333.jpg?hmac=_j6ghY5fCfSD6tvtcV74zXivkJSPIfR9B8w34XeQmvU',
      'https://fastly.picsum.photos/id/705/200/200.jpg?hmac=2HZlwayMAMOyCllDpM-Mx3u2Xyk40VRHAzlpNLKyTC8',
    ],
    playmatesAttending: List.generate(
      8,
      (index) => DisplayUser(
        username: 'Index $index',
        displayImage: _imageList[_random.nextInt(_imageList.length)],
      ),
    ),
    activityTag: const [
      'Rayna Rosser',
      'Kianna Vaccaro',
      'Swim Team Six Centre',
      'Rayna Rosser',
      'Kianna Vaccaro',
      'Swim Team Six Centre',
      'Kenny Event Centre',
      'Team Six Swim Store',
      'Kenny Event Centre',
      'Swim Team Six',
      'Dream Team',
    ],
    activityReactionList: List.generate(
      500,
      (index) => _reactionList[_random.nextInt(_reactionList.length)],
    ),
    activityReviewsCount: 20000,
    activityQAndACount: 20,
    activityCommentsCount: 10,
    activityMaxParticipant: null,
    activityParticipantsCount: 500,
    activityShareCount: 100,
    userReaction: _reactionList[_random.nextInt(_reactionList.length)],
  ),
  ActivityListModel(
    distance: 5,
    isActivityShared: true,
    sharedActivityPost:
        'Lorem ipsum die at conensur er fallon. Et pellentesque morbi sit amet. Quam integer massa odio duis pulvinar.',
    sharedActivityPostTime: DateTime(2023, 6, 1, 12, 2, 20),
    sharedActivityTag: null,
    activityUserProfile: const ActivityUserProfile(
      profileImage: dInternetPhoto2,
      profileName: 'Blaqbonez',
      profilePlan: 'bronze',
    ),
    activityPostTime: DateTime(2022, 4, 5, 13, 30, 20),
    sharedActivityUserProfile: const ActivityUserProfile(
      profileImage: dInternetPhoto1,
      profileName: 'Daniel Nkrumah Thannos Antetokoumpoo Giannis Jordan Blake',
      profilePlan: 'gold',
    ),
    activityIsUser: false,
    activityBookmarked: false,
    activityPost:
        'Lorem ipsum dolor sit amet consectetur. Et pellentesque morbi sit amet. Quam integer massa odio duis pulvinar consectetur dictum. Lorem ipsum dolor sit amet consectetur. Et pellentesque morbi sit amet. Quam integer massa odio duis pulvinar consectetur dictum ',
    activityFlyerProperties: ActivityFlyerProperties(
      activityTitle: 'Lorem ipsum dolor sit amet consectetur suspendisse.',
      activityDetails:
          'Lorem ipsum dolor sit amet consectetur. Enim eu proin in blandit pretium condimentum aliquam volutpat mattis scelerisque.',
      activityType: 'Classes',
      activityTime: const TimeOfDay(
        hour: 12,
        minute: 10,
      ),
      activityTimeZone: 'UTC(+1:00)',
      activityDate: DateTime(2023, 04, 10),
      activityDuration: '3 hrs',
      activityCity: 'Helsinki',
      activityRefundTime: null,
      activityImage: null,
      activityRefundDate: null,
      activityPrice: '\$50',
      activityVenue: 'Lönnrotinkatu 16, Salo, Varsinais-Suomi',
      activityCountry: 'Finland',
      activityInterest: 'basketball',
    ),
    activityPropertiesPosition: FlyerPositioning(
      image: FlyerUtils.checkers,
      interestName: 'checkers',
      positionText: const TextPositionModel(
        activityTitle: PositionedModel(
          top: 51,
          right: 26,
          left: 23,
          lines: 2,
          style: TextStyle(
            fontFamily: FontFamily.roboto,
            color: Color(0xFFFFFFFF),
            fontSize: 14,
            fontWeight: FontWeight.w900,
          ),
        ),
        activityDetails: PositionedModel(
          top: 92,
          right: 62,
          left: 23,
          lines: 3,
          style: TextStyle(
            fontFamily: FontFamily.roboto,
            color: Color(0xFFFFFFFF),
            fontSize: 9,
            fontWeight: FontWeight.w900,
          ),
        ),
        activityType: PositionedModel(
          top: 132,
          right: 150,
          left: 28,
          style: TextStyle(
            fontFamily: FontFamily.roboto,
            color: Color(0xFFFFFFFF),
            fontSize: 10,
            fontWeight: FontWeight.w900,
          ),
        ),
        activityInterest: PositionedModel(
          top: 153,
          right: 150,
          left: 28,
          style: TextStyle(
            fontFamily: FontFamily.roboto,
            color: Color(0xFFFFFFFF),
            fontSize: 10,
            fontWeight: FontWeight.w900,
          ),
        ),
        activityDuration: PositionedModel(
          top: 226,
          right: 50,
          left: 42,
          style: TextStyle(
            fontFamily: FontFamily.roboto,
            color: Color(0xFF8B2829),
            fontSize: 10,
            fontWeight: FontWeight.w900,
          ),
        ),
        activityDate: PositionedModel(
          top: 184,
          right: 100,
          left: 42,
          style: TextStyle(
            fontFamily: FontFamily.roboto,
            color: Color(0xFF8B2829),
            fontSize: 10,
            fontWeight: FontWeight.w900,
          ),
        ),
        activityTime: PositionedModel(
          top: 204,
          right: 100,
          left: 42,
          style: TextStyle(
            fontFamily: FontFamily.roboto,
            color: Color(0xFF8B2829),
            fontSize: 10,
            fontWeight: FontWeight.w900,
          ),
        ),
        activityCity: PositionedModel(
          top: 282,
          right: 20,
          left: 29,
          style: TextStyle(
            fontFamily: FontFamily.roboto,
            color: Color(0xFF8B2829),
            fontSize: 10,
            fontWeight: FontWeight.w900,
          ),
        ),
        activityCountry: PositionedModel(
          top: 301,
          right: 20,
          left: 29,
          style: TextStyle(
            fontFamily: FontFamily.roboto,
            color: Color(0xFF8B2829),
            fontSize: 10,
            fontWeight: FontWeight.w900,
          ),
        ),
        activityVenue: PositionedModel(
          top: 251,
          right: 10,
          left: 42,
          lines: 2,
          style: TextStyle(
            fontFamily: FontFamily.roboto,
            color: Color(0xFF8B2829),
            fontSize: 9,
            fontWeight: FontWeight.w900,
          ),
        ),
        activityFee: PositionedModel(
          top: 17,
          right: 2,
          left: 258,
          rowAlignment: MainAxisAlignment.center,
          style: TextStyle(
            fontFamily: FontFamily.roboto,
            color: Color(0xFFFFFFFF),
            fontSize: 9,
            fontWeight: FontWeight.w900,
          ),
        ),
      ),
    ),
    activityAddedImages: [
      'https://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4',
      'https://fastly.picsum.photos/id/0/5000/3333.jpg?hmac=_j6ghY5fCfSD6tvtcV74zXivkJSPIfR9B8w34XeQmvU',
      'https://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4',
      'https://fastly.picsum.photos/id/705/200/200.jpg?hmac=2HZlwayMAMOyCllDpM-Mx3u2Xyk40VRHAzlpNLKyTC8',
      'https://fastly.picsum.photos/id/221/200/200.jpg?hmac=zy33VSww4_QQk0Hf2MngBaudI_ahiadnRwuREDTbWnA',
      'https://fastly.picsum.photos/id/1027/200/200.jpg?hmac=fiXlkLLwYm7JmmU80uRIj9g21XD4q9v_lM_2Z57UhuA',
      'https://fastly.picsum.photos/id/421/200/200.jpg?hmac=Kix073-H73pkRedH4XJ8fenHLI9Sd9akWlOFjKog0EA',
    ],
    playmatesAttending: [],
    activityTag: const [
      'Rayna Rosser',
      'Kianna Vaccaro',
      'Swim Team Six Centre',
      'Kenny Event Centre',
      'Team Six Swim Store',
      'Kenny Event Centre',
      'Swim Team Six',
      'Dream Team',
      'Swim Team Six Centre',
      'Kenny Event Centre',
      'Team Six Swim Store',
      'Kenny Event Centre',
      'Swim Team Six',
      'Dream Team',
      'Swim Team Six Centre',
      'Kenny Event Centre',
      'Team Six Swim Store',
      'Kenny Event Centre',
      'Swim Team Six',
      'Dream Team',
    ],
    activityReactionList: List.generate(
      10000,
      (index) => _reactionList[_random.nextInt(_reactionList.length)],
    ),
    activityParticipantsCount: 60,
    activityMaxParticipant: null,
    activityCommentsCount: 3000,
    activityQAndACount: 200,
    activityReviewsCount: 20,
    userReaction: _reactionList[_random.nextInt(_reactionList.length)],
    activityShareCount: 50000,
  ),
  ActivityListModel(
    distance: 5,
    activityUserProfile: const ActivityUserProfile(
      profileImage: dInternetPhoto2,
      profileName: 'Blaqbonez',
      profilePlan: 'bronze',
    ),
    isActivityShared: false,
    activityPostTime: DateTime(2023, 4, 5, 13, 42, 20),
    sharedActivityUserProfile: const ActivityUserProfile(
      profileImage: dInternetPhoto1,
      profileName: 'Gold Daniel',
      profilePlan: 'diamond',
    ),
    activityIsUser: true,
    activityBookmarked: false,
    activityPost: null,
    activityFlyerProperties: ActivityFlyerProperties(
      activityTitle: 'Lorem ipsum dolor sit amet consectetur suspendisse.',
      activityDetails:
          'Lorem ipsum dolor sit amet consectetur. Enim eu proin in blandit pretium condimentum aliquam volutpat mattis scelerisque.',
      activityType: 'Classes',
      activityTime: const TimeOfDay(
        hour: 12,
        minute: 10,
      ),
      activityTimeZone: 'UTC(+1:00)',
      activityDate: DateTime(2023, 04, 10),
      activityDuration: '3 hrs',
      activityCity: 'Helsinki',
      activityRefundTime: null,
      activityImage: null,
      activityRefundDate: null,
      activityPrice: '\$50',
      activityVenue: 'Lönnrotinkatu 16, Salo, Varsinais-Suomi',
      activityCountry: 'Finland',
      activityInterest: 'basketball',
    ),
    activityPropertiesPosition: FlyerPositioning(
      image: FlyerUtils.baseball,
      interestName: 'baseball',
      positionText: const TextPositionModel(
        activityTitle: PositionedModel(
          top: 36,
          right: 24,
          left: 15,
          lines: 2,
          rowAlignment: MainAxisAlignment.center,
          textAlignment: TextAlign.center,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFFFFFFFF),
            fontSize: 15,
          ),
        ),
        activityDetails: PositionedModel(
          top: 91,
          right: 35,
          left: 20,
          lines: 2,
          rowAlignment: MainAxisAlignment.center,
          textAlignment: TextAlign.center,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFFFFFFFF),
            fontSize: 10,
          ),
        ),
        activityType: PositionedModel(
          top: 135,
          right: 30,
          left: 95,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFFFFFFFF),
            fontSize: 9,
          ),
        ),
        activityInterest: PositionedModel(
          top: 155,
          right: 30,
          left: 95,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFFFFFFFF),
            fontSize: 9,
          ),
        ),
        activityDuration: PositionedModel(
          top: 178,
          right: 6,
          left: 240,
          lines: 2,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFFFFFFFF),
            fontSize: 8,
          ),
        ),
        activityDate: PositionedModel(
          top: 178,
          right: 110,
          left: 131,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFFFFFFFF),
            fontSize: 8,
          ),
        ),
        activityTime: PositionedModel(
          top: 202,
          right: 110,
          left: 144,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFF262262),
            fontSize: 9,
          ),
        ),
        activityCity: PositionedModel(
          top: 274,
          right: 70,
          left: 24,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFFFFFFFF),
            fontSize: 10,
          ),
        ),
        activityCountry: PositionedModel(
          top: 300,
          right: 113,
          left: 24,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFFFFFFFF),
            fontSize: 10,
          ),
        ),
        activityVenue: PositionedModel(
          top: 225,
          right: 30,
          left: 96,
          lines: 3,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFFFFFFFF),
            fontSize: 9,
          ),
        ),
        activityFee: PositionedModel(
          top: 301,
          right: 38,
          left: 230,
          rowAlignment: MainAxisAlignment.center,
          style: TextStyle(
            fontFamily: FontFamily.roboto,
            color: Color(0xFF262262),
            fontSize: 8,
            fontWeight: FontWeight.w700,
          ),
        ),
      ),
    ),
    activityAddedImages: [
      'https://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4',
      'https://fastly.picsum.photos/id/0/5000/3333.jpg?hmac=_j6ghY5fCfSD6tvtcV74zXivkJSPIfR9B8w34XeQmvU',
      'https://fastly.picsum.photos/id/705/200/200.jpg?hmac=2HZlwayMAMOyCllDpM-Mx3u2Xyk40VRHAzlpNLKyTC8',
      'https://fastly.picsum.photos/id/221/200/200.jpg?hmac=zy33VSww4_QQk0Hf2MngBaudI_ahiadnRwuREDTbWnA',
      'https://fastly.picsum.photos/id/1027/200/200.jpg?hmac=fiXlkLLwYm7JmmU80uRIj9g21XD4q9v_lM_2Z57UhuA',
    ],
    activityTag: const [
      'Swim Team Six Centre',
      'Kenny Event Centre',
      'Team Six Swim Store',
      'Kenny Event Centre',
      'Swim Team Six',
      'Dream Team',
      'Rayna Rosser',
      'Kianna Vaccaro',
    ],
    activityReactionList: List.generate(
      200,
      (index) => _reactionList[_random.nextInt(_reactionList.length)],
    ),
    activityShareCount: 20000,
    activityMaxParticipant: 200,
    activityCommentsCount: 300,
    activityParticipantsCount: 20,
    activityQAndACount: 5000,
    activityReviewsCount: 300,
    playmatesAttending: [],
    userReaction: null,
  ),
  ActivityListModel(
    distance: 20,
    isActivityShared: false,
    activityUserProfile: const ActivityUserProfile(
      profileImage: dInternetPhoto1,
      profileName: 'Gold Daniel Nkrumah',
      profilePlan: 'bronze',
    ),
    activityPostTime: DateTime(2023, 4, 5, 13, 40, 20),
    sharedActivityUserProfile: const ActivityUserProfile(
      profileImage: dInternetPhoto2,
      profileName: 'Gold Daniel Nkrumah',
      profilePlan: 'bronze',
    ),
    activityIsUser: false,
    activityBookmarked: true,
    activityPost:
        'Lorem ipsum dolor sit amet consectetur. Et pellentesque morbi sit amet. Quam integer massa odio duis pulvinar consectetur dictum. Lorem ipsum dolor sit amet consectetur. Et pellentesque morbi sit amet. Quam integer massa odio duis pulvinar consectetur dictum ',
    activityFlyerProperties: ActivityFlyerProperties(
      activityTitle: 'Lorem ipsum dolor sit amet consectetur suspendisse.',
      activityDetails:
          'Lorem ipsum dolor sit amet consectetur. Enim eu proin in blandit pretium condimentum aliquam volutpat mattis scelerisque.',
      activityType: 'Classes',
      activityTime: const TimeOfDay(
        hour: 12,
        minute: 10,
      ),
      activityTimeZone: 'UTC(+1:00)',
      activityCity: 'Helsinki',
      activityRefundTime: null,
      activityImage: null,
      activityRefundDate: null,
      activityPrice: '\$50',
      activityVenue: 'Lönnrotinkatu 16, Salo, Varsinais-Suomi',
      activityCountry: 'Finland',
      activityInterest: 'basketball',
      activityDate: DateTime(2023, 04, 10),
      activityDuration: '3 hrs',
    ),
    activityPropertiesPosition: FlyerPositioning(
      image: FlyerUtils.cycling,
      interestName: 'cycling',
      positionText: const TextPositionModel(
        activityTitle: PositionedModel(
          top: 43,
          right: 20,
          left: 20,
          lines: 2,
          rowAlignment: MainAxisAlignment.center,
          textAlignment: TextAlign.center,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFFFFFFFF),
            fontSize: 14,
          ),
        ),
        activityDetails: PositionedModel(
          top: 286,
          right: 94,
          left: 9,
          lines: 3,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFF010101),
            fontSize: 10,
          ),
        ),
        activityType: PositionedModel(
          top: 98,
          right: 181,
          left: 6,
          rowAlignment: MainAxisAlignment.center,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFF010101),
            fontSize: 9,
          ),
        ),
        activityInterest: PositionedModel(
          top: 123,
          right: 181,
          left: 6,
          rowAlignment: MainAxisAlignment.center,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFF010101),
            fontSize: 9,
          ),
        ),
        activityDuration: PositionedModel(
          top: 236,
          right: 80,
          left: 19,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFFFFFFFF),
            fontSize: 9,
          ),
        ),
        activityDate: PositionedModel(
          top: 285,
          right: 10,
          left: 262,
          lines: 3,
          rowAlignment: MainAxisAlignment.center,
          textAlignment: TextAlign.center,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFF010101),
            fontSize: 10,
          ),
        ),
        activityTime: PositionedModel(
          top: 216,
          right: 100,
          left: 19,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFFFFFFFF),
            fontSize: 9,
          ),
        ),
        activityCity: PositionedModel(
          top: 178,
          right: 60,
          left: 19,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFFFFFFFF),
            fontSize: 9,
          ),
        ),
        activityCountry: PositionedModel(
          top: 197,
          right: 60,
          left: 19,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFFFFFFFF),
            fontSize: 9,
          ),
        ),
        activityVenue: PositionedModel(
          top: 152,
          right: 35,
          left: 19,
          lines: 2,
          style: TextStyle(
            fontFamily: FontFamily.lalezar,
            color: Color(0xFFFFFFFF),
            fontSize: 8,
          ),
        ),
        activityFee: PositionedModel(
          top: 115,
          right: 10,
          left: 205,
          style: TextStyle(
            fontFamily: FontFamily.roboto,
            color: Color(0xFFFFFFFF),
            fontSize: 12,
            fontWeight: FontWeight.w500,
          ),
        ),
      ),
    ),
    activityAddedImages: [],
    activityTag: const [
      'Rayna Rosser',
      'Kianna Vaccaro',
      'Swim Team Six Centre',
      'Kenny Event Centre',
      'Team Six Swim Store',
      'Kenny Event Centre',
      'Swim Team Six',
      'Dream Team',
    ],
    activityReactionList: List.generate(
      200000,
      (index) => _reactionList[_random.nextInt(_reactionList.length)],
    ),
    activityReviewsCount: 40000,
    activityQAndACount: 300,
    activityCommentsCount: 500,
    activityMaxParticipant: null,
    activityParticipantsCount: 300,
    playmatesAttending: List.generate(
      2,
      (index) => DisplayUser(
        username: 'Index $index',
        displayImage: _imageList[_random.nextInt(_imageList.length)],
      ),
    ),
    userReaction: _reactionList[_random.nextInt(_reactionList.length)],
    activityShareCount: 10,
  ),
  ActivityListModel(
    distance: 50,
    isActivityShared: false,
    activityPostTime: DateTime(2023, 4, 5, 10, 42, 20),
    activityUserProfile: const ActivityUserProfile(
      profileImage: dInternetPhoto2,
      profileName: 'Gold Daniel Nkrumah',
      profilePlan: 'bronze',
    ),
    activityIsUser: false,
    activityBookmarked: true,
    activityPost:
        'Lorem ipsum dolor sit amet consectetur. Et pellentesque morbi sit amet. Quam integer massa odio duis pulvinar consectetur dictum. Lorem ipsum dolor sit amet consectetur. Et pellentesque morbi sit amet. Quam integer massa odio duis pulvinar consectetur dictum ',
    activityFlyerProperties: ActivityFlyerProperties(
      activityTitle: 'Lorem ipsum dolor sit amet consectetur suspendisse.',
      activityDetails:
          'Lorem ipsum dolor sit amet consectetur. Enim eu proin in blandit pretium condimentum aliquam volutpat mattis scelerisque.',
      activityType: 'Classes',
      activityTime: const TimeOfDay(
        hour: 12,
        minute: 10,
      ),
      activityTimeZone: 'UTC(+1:00)',
      activityCity: 'Helsinki',
      activityRefundTime: null,
      activityImage: null,
      activityRefundDate: null,
      activityPrice: '\$50',
      activityVenue: 'Lönnrotinkatu 16, Salo, Varsinais-Suomi',
      activityCountry: 'Finland',
      activityInterest: 'basketball',
      activityDate: DateTime(2023, 04, 10),
      activityDuration: '3 hrs',
    ),
    activityPropertiesPosition: FlyerPositioning(
      image: FlyerUtils.highJump,
      interestName: 'highJump',
      positionText: const TextPositionModel(
        activityTitle: PositionedModel(
          top: 48,
          right: 127,
          left: 21,
          lines: 3,
          style: TextStyle(
            fontFamily: FontFamily.sairaStencilOne,
            color: Color(0xFFFFFFFF),
            fontSize: 13,
          ),
        ),
        activityDetails: PositionedModel(
          top: 118,
          right: 73,
          left: 15,
          lines: 2,
          style: TextStyle(
            fontFamily: FontFamily.play,
            color: Color(0xFF231F20),
            fontSize: 8,
          ),
        ),
        activityType: PositionedModel(
          top: 186,
          right: 183,
          left: 18,
          rowAlignment: MainAxisAlignment.center,
          style: TextStyle(
            fontFamily: FontFamily.play,
            color: Color(0xFFF7941D),
            fontSize: 8,
          ),
        ),
        activityInterest: PositionedModel(
          top: 207,
          right: 172,
          left: 18,
          rowAlignment: MainAxisAlignment.center,
          style: TextStyle(
            fontFamily: FontFamily.play,
            color: Color(0xFF231F20),
            fontSize: 8,
          ),
        ),
        activityTime: PositionedModel(
          top: 227,
          right: 230,
          left: 18,
          rowAlignment: MainAxisAlignment.center,
          style: TextStyle(
            fontFamily: FontFamily.play,
            color: Color(0xFFF7941D),
            fontSize: 8,
          ),
        ),
        activityDate: PositionedModel(
          top: 51,
          right: 20,
          left: 252,
          lines: 3,
          rowAlignment: MainAxisAlignment.center,
          textAlignment: TextAlign.center,
          style: TextStyle(
            fontFamily: FontFamily.play,
            color: Color(0xFF231F20),
            fontSize: 9,
          ),
        ),
        activityDuration: PositionedModel(
          top: 226,
          right: 130,
          left: 119,
          lines: 2,
          style: TextStyle(
            fontFamily: FontFamily.play,
            color: Color(0xFF231F20),
            fontSize: 9,
          ),
        ),
        activityCity: PositionedModel(
          top: 303,
          right: 100,
          left: 34,
          style: TextStyle(
            fontFamily: FontFamily.play,
            color: Color(0xFF231F20),
            fontSize: 9,
          ),
        ),
        activityCountry: PositionedModel(
          top: 317,
          right: 130,
          left: 34,
          style: TextStyle(
            fontFamily: FontFamily.play,
            color: Color(0xFF231F20),
            fontSize: 9,
          ),
        ),
        activityVenue: PositionedModel(
          top: 270,
          right: 90,
          left: 37,
          lines: 3,
          style: TextStyle(
            fontFamily: FontFamily.play,
            color: Color(0xFF231F20),
            fontSize: 9,
          ),
        ),
        activityFee: PositionedModel(
          top: 165,
          right: 170,
          left: 24,
          style: TextStyle(
            fontFamily: FontFamily.roboto,
            color: Color(0xFF231F20),
            fontSize: 11,
            fontWeight: FontWeight.w700,
          ),
        ),
      ),
    ),
    activityAddedImages: [],
    activityTag: [],
    activityReactionList: List.generate(
      0,
      (index) => _reactionList[_random.nextInt(_reactionList.length)],
    ),
    activityParticipantsCount: 10,
    activityMaxParticipant: 40,
    activityCommentsCount: 3000,
    activityQAndACount: 300,
    activityReviewsCount: 48,
    activityShareCount: 0,
    playmatesAttending: List.generate(
      1,
      (index) => DisplayUser(
        username: 'Index $index',
        displayImage: _imageList[_random.nextInt(_imageList.length)],
      ),
    ),
    userReaction: null,
  ),
];

final List<String> _questionList = [
  'Lorem ipsum dolor sit amet, consectetur elit, ssed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur elit, ssed do eiusmod tempor incididunt ut labore.',
  'Lorem ipsum dolor sit amet consectetur. Aliquam erat mi gravida ultricies nam dui pharetra molestie leo pretium pharetra.',
  'Lorem ipsum dolor sit amet, consectetur elit, ssed do eiusmod tempor incididunt ut labore.',
  'Lorem ipsum dolor sit amet consectetur.',
  'How am i sure that i will be safe, and what are the security measures in place for this activity? Also, how secure is the venue of this activity, and what are the refreshment available',
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nibh aenean vulputate netus netus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nibh aenean vulputate netus netus.',
];

final List<StatusModel> fHomeStatusList = [
  StatusModel(
    isStatusShared: true,
    sharedStatusPost: null,
    sharedStatusPostTime: DateTime(2023, 6, 1, 14, 42, 20),
    sharedStatusTag: [
      'Ice Queen',
      'Okorie Ndubuisi',
    ],
    activityUserProfile: const ActivityUserProfile(
      profileImage: dInternetPhoto3,
      profileName: 'Chike Ebenezer',
      profilePlan: 'gold',
    ),
    statusPostTime: DateTime(2023, 4, 5, 13, 42, 20),
    statusPost: _questionList[_random.nextInt(_questionList.length)],
    sharedActivityUserProfile: const ActivityUserProfile(
      profileImage: dInternetPhoto1,
      profileName: 'Gold Daniel',
      profilePlan: 'diamond',
    ),
    statusBookmarked: false,
    statusIsUser: true,
    statusAddedImages: [
      'https://fastly.picsum.photos/id/0/5000/3333.jpg?hmac=_j6ghY5fCfSD6tvtcV74zXivkJSPIfR9B8w34XeQmvU',
      'https://fastly.picsum.photos/id/705/200/200.jpg?hmac=2HZlwayMAMOyCllDpM-Mx3u2Xyk40VRHAzlpNLKyTC8',
      'https://fastly.picsum.photos/id/221/200/200.jpg?hmac=zy33VSww4_QQk0Hf2MngBaudI_ahiadnRwuREDTbWnA',
      'https://fastly.picsum.photos/id/1027/200/200.jpg?hmac=fiXlkLLwYm7JmmU80uRIj9g21XD4q9v_lM_2Z57UhuA',
      'https://fastly.picsum.photos/id/421/200/200.jpg?hmac=Kix073-H73pkRedH4XJ8fenHLI9Sd9akWlOFjKog0EA',
    ],
    statusTag: const [
      'Rayna Rosser',
      'Kianna Vaccaro',
      'Swim Team Six Centre',
      'Kenny Event Centre',
      'Team Six Swim Store',
      'Kenny Event Centre',
      'Swim Team Six',
      'Dream Team',
    ],
    statusReactionList: List.generate(
      1000,
      (index) => _reactionList[_random.nextInt(_reactionList.length)],
    ),
    userReaction: _reactionList[_random.nextInt(_reactionList.length)],
    statusShareCount: 500000,
    statusCommentsCount: 400,
  ),
  StatusModel(
    activityUserProfile: const ActivityUserProfile(
      profileImage: dInternetPhoto3,
      profileName: 'James Brown',
      profilePlan: 'bronze',
    ),
    isStatusShared: false,
    statusPostTime: DateTime(2023, 4, 5, 13, 45, 20),
    statusPost: _questionList[_random.nextInt(_questionList.length)],
    sharedActivityUserProfile: const ActivityUserProfile(
      profileImage: dInternetPhoto1,
      profileName: 'Petrov Dimitrov',
      profilePlan: 'gold',
    ),
    statusBookmarked: true,
    statusIsUser: false,
    statusAddedImages: [
      'https://fastly.picsum.photos/id/0/5000/3333.jpg?hmac=_j6ghY5fCfSD6tvtcV74zXivkJSPIfR9B8w34XeQmvU',
      'https://fastly.picsum.photos/id/705/200/200.jpg?hmac=2HZlwayMAMOyCllDpM-Mx3u2Xyk40VRHAzlpNLKyTC8',
      'https://fastly.picsum.photos/id/221/200/200.jpg?hmac=zy33VSww4_QQk0Hf2MngBaudI_ahiadnRwuREDTbWnA',
      'https://fastly.picsum.photos/id/1027/200/200.jpg?hmac=fiXlkLLwYm7JmmU80uRIj9g21XD4q9v_lM_2Z57UhuA',
      'https://fastly.picsum.photos/id/421/200/200.jpg?hmac=Kix073-H73pkRedH4XJ8fenHLI9Sd9akWlOFjKog0EA',
    ],
    statusTag: const [
      'Rayna Rosser',
      'Kianna Vaccaro',
      'Swim Team Six Centre',
      'Kenny Event Centre',
      'Team Six Swim Store',
      'Rayna Rosser',
      'Kianna Vaccaro',
      'Swim Team Six Centre',
      'Kenny Event Centre',
      'Team Six Swim Store',
      'Rayna Rosser',
      'Kianna Vaccaro',
      'Swim Team Six Centre',
      'Kenny Event Centre',
      'Team Six Swim Store',
      'Kenny Event Centre',
      'Swim Team Six',
      'Dream Team',
    ],
    statusReactionList: List.generate(
      1000,
      (index) => _reactionList[_random.nextInt(_reactionList.length)],
    ),
    userReaction: _reactionList[_random.nextInt(_reactionList.length)],
    statusShareCount: 500000,
    statusCommentsCount: 400,
  ),
  StatusModel(
    isStatusShared: true,
    sharedStatusPost: null,
    sharedStatusPostTime: DateTime(2023, 5, 1, 13, 2, 20),
    sharedStatusTag: [
      'Ice Queen',
    ],
    activityUserProfile: const ActivityUserProfile(
      profileImage: dInternetPhoto3,
      profileName: 'James Brown',
      profilePlan: 'bronze',
    ),
    statusPostTime: DateTime(2023, 4, 5, 13, 50, 20),
    statusPost: _questionList[_random.nextInt(_questionList.length)],
    sharedActivityUserProfile: const ActivityUserProfile(
      profileImage: dInternetPhoto1,
      profileName: 'Gold Daniel',
      profilePlan: 'diamond',
    ),
    statusBookmarked: false,
    statusIsUser: true,
    statusAddedImages: [],
    statusTag: [],
    statusReactionList: [],
    userReaction: null,
    statusShareCount: 0,
    statusCommentsCount: 0,
  ),
  StatusModel(
    isStatusShared: false,
    activityUserProfile: const ActivityUserProfile(
      profileImage: dInternetPhoto3,
      profileName: 'James Brown',
      profilePlan: 'bronze',
    ),
    statusPostTime: DateTime(2022, 4, 5, 13, 50, 20),
    statusPost: _questionList[_random.nextInt(_questionList.length)],
    sharedActivityUserProfile: const ActivityUserProfile(
      profileImage: dInternetPhoto1,
      profileName: 'Gustav Torff',
      profilePlan: 'bronze',
    ),
    statusBookmarked: false,
    statusIsUser: false,
    statusAddedImages: [
      'https://fastly.picsum.photos/id/0/5000/3333.jpg?hmac=_j6ghY5fCfSD6tvtcV74zXivkJSPIfR9B8w34XeQmvU',
      'https://fastly.picsum.photos/id/705/200/200.jpg?hmac=2HZlwayMAMOyCllDpM-Mx3u2Xyk40VRHAzlpNLKyTC8',
      'https://fastly.picsum.photos/id/221/200/200.jpg?hmac=zy33VSww4_QQk0Hf2MngBaudI_ahiadnRwuREDTbWnA',
      'https://fastly.picsum.photos/id/1027/200/200.jpg?hmac=fiXlkLLwYm7JmmU80uRIj9g21XD4q9v_lM_2Z57UhuA',
      'https://fastly.picsum.photos/id/421/200/200.jpg?hmac=Kix073-H73pkRedH4XJ8fenHLI9Sd9akWlOFjKog0EA',
    ],
    statusTag: const [
      'Rayna Rosser',
      'Kianna Vaccaro',
      'Swim Team Six Centre',
      'Kenny Event Centre',
      'Team Six Swim Store',
      'Kenny Event Centre',
      'Swim Team Six',
      'Dream Team',
    ],
    statusReactionList: List.generate(
      1000000,
      (index) => _reactionList[_random.nextInt(_reactionList.length)],
    ),
    userReaction: _reactionList[_random.nextInt(_reactionList.length)],
    statusShareCount: 50,
    statusCommentsCount: 4,
  ),
  StatusModel(
    isStatusShared: false,
    activityUserProfile: const ActivityUserProfile(
      profileImage: dInternetPhoto3,
      profileName: 'James Brown',
      profilePlan: 'bronze',
    ),
    statusPostTime: DateTime(2022, 4, 2, 10, 50, 20),
    statusPost: _questionList[_random.nextInt(_questionList.length)],
    sharedActivityUserProfile: const ActivityUserProfile(
      profileImage: dInternetPhoto1,
      profileName: 'Connor Makhachev Oleivera Daniel',
      profilePlan: 'gold',
    ),
    statusBookmarked: true,
    statusIsUser: false,
    statusAddedImages: [
      'https://fastly.picsum.photos/id/0/5000/3333.jpg?hmac=_j6ghY5fCfSD6tvtcV74zXivkJSPIfR9B8w34XeQmvU',
      'https://fastly.picsum.photos/id/705/200/200.jpg?hmac=2HZlwayMAMOyCllDpM-Mx3u2Xyk40VRHAzlpNLKyTC8',
      'https://fastly.picsum.photos/id/221/200/200.jpg?hmac=zy33VSww4_QQk0Hf2MngBaudI_ahiadnRwuREDTbWnA',
      'https://fastly.picsum.photos/id/1027/200/200.jpg?hmac=fiXlkLLwYm7JmmU80uRIj9g21XD4q9v_lM_2Z57UhuA',
      'https://fastly.picsum.photos/id/421/200/200.jpg?hmac=Kix073-H73pkRedH4XJ8fenHLI9Sd9akWlOFjKog0EA',
      'https://fastly.picsum.photos/id/0/5000/3333.jpg?hmac=_j6ghY5fCfSD6tvtcV74zXivkJSPIfR9B8w34XeQmvU',
      'https://fastly.picsum.photos/id/705/200/200.jpg?hmac=2HZlwayMAMOyCllDpM-Mx3u2Xyk40VRHAzlpNLKyTC8',
      'https://fastly.picsum.photos/id/221/200/200.jpg?hmac=zy33VSww4_QQk0Hf2MngBaudI_ahiadnRwuREDTbWnA',
      'https://fastly.picsum.photos/id/1027/200/200.jpg?hmac=fiXlkLLwYm7JmmU80uRIj9g21XD4q9v_lM_2Z57UhuA',
      'https://fastly.picsum.photos/id/421/200/200.jpg?hmac=Kix073-H73pkRedH4XJ8fenHLI9Sd9akWlOFjKog0EA',
    ],
    statusTag: const [
      'Rayna Rosser',
      'Kianna Vaccaro',
      'Swim Team Six Centre',
      'Kenny Event Centre',
      'Team Six Swim Store',
      'Kenny Event Centre',
      'Swim Team Six',
      'Dream Team',
    ],
    statusReactionList: List.generate(
      10000,
      (index) => _reactionList[_random.nextInt(_reactionList.length)],
    ),
    userReaction: _reactionList[_random.nextInt(_reactionList.length)],
    statusShareCount: 500000000,
    statusCommentsCount: 400,
  ),
  StatusModel(
    activityUserProfile: const ActivityUserProfile(
      profileImage: dInternetPhoto3,
      profileName: 'James Brown',
      profilePlan: 'bronze',
    ),
    isStatusShared: false,
    statusPostTime: DateTime(2022, 4, 5, 12, 50, 20),
    statusPost: _questionList[_random.nextInt(_questionList.length)],
    sharedActivityUserProfile: const ActivityUserProfile(
      profileImage: dInternetPhoto1,
      profileName: 'Gold Daniel',
      profilePlan: 'diamond',
    ),
    statusBookmarked: true,
    statusIsUser: true,
    statusAddedImages: [
      'https://fastly.picsum.photos/id/0/5000/3333.jpg?hmac=_j6ghY5fCfSD6tvtcV74zXivkJSPIfR9B8w34XeQmvU',
      'https://fastly.picsum.photos/id/705/200/200.jpg?hmac=2HZlwayMAMOyCllDpM-Mx3u2Xyk40VRHAzlpNLKyTC8',
      'https://fastly.picsum.photos/id/221/200/200.jpg?hmac=zy33VSww4_QQk0Hf2MngBaudI_ahiadnRwuREDTbWnA',
      'https://fastly.picsum.photos/id/1027/200/200.jpg?hmac=fiXlkLLwYm7JmmU80uRIj9g21XD4q9v_lM_2Z57UhuA',
      'https://fastly.picsum.photos/id/421/200/200.jpg?hmac=Kix073-H73pkRedH4XJ8fenHLI9Sd9akWlOFjKog0EA',
    ],
    statusTag: const [
      'Rayna Rosser',
      'Kianna Vaccaro',
      'Swim Team Six Centre',
      'Kenny Event Centre',
      'Team Six Swim Store',
      'Kenny Event Centre',
      'Swim Team Six',
      'Dream Team',
    ],
    statusReactionList: List.generate(
      1000,
      (index) => _reactionList[_random.nextInt(_reactionList.length)],
    ),
    userReaction: _reactionList[_random.nextInt(_reactionList.length)],
    statusShareCount: 500000,
    statusCommentsCount: 400,
  ),
];
