import 'package:playkosmos_v3/models/activity_interest_groups.dart';

/// The activity interest groups
const List<ActivityInterestGroups> kActivityInterestGroups = [
  ActivityInterestGroups(
    categoryName: 'sports',
    interests: [
      'football',
      'basketball',
      'volleyball',
      'rugby',
      'cricket',
      'baseball',
      'hockey',
      'tennis',
      'badminton',
      'squash',
      'tableTennis',
      'swimming',
      'surfing',
      'kayaking',
      'waterPolo',
      'scubaDiving',
      'snorkeling',
      'sailing',
      'skiing',
      'snowboarding',
      'iceSkating',
      'curling',
      'rockClimbing',
      'hiking',
      'trailRunning',
      'mountainBiking',
      'karate',
      'judo',
      'taekwondo',
      'boxing',
      'mma',
      'fencing',
      'yoga',
      'pilates',
      'gymWorkouts',
      'zumba',
      'aerobics',
      'crossFit',
      'backpacking',
      'roadTrips',
      'trainJourneys',
      'culturalTourism',
      'skydiving',
      'paragliding',
      'bungeeJumping',
      'baseJumping',
      'birdwatching',
      'safariTours',
      'stargazing',
      'wildlifePhotography',
      'foodTours',
      'historicalTours',
      'artMuseumVisits',
      'festivalParticipation',
      'islandHopping',
      'riverRafting',
      'deepSeaFishing',
    ],
  ),
  ActivityInterestGroups(
    categoryName: 'arts',
    interests: [
      'painting',
      'drawing',
      'sculpting',
      'photography',
      'calligraphy',
      'graffitiArt',
      'dance',
      'acting',
      'singing',
      'comedy',
      'circusArts',
      'magic',
      'knitting',
      'crochet',
      'quilting',
      'woodworking',
      'pottery',
      'jewelryMaking',
      'graphicDesign',
      'videoEditing',
      'threeDModeling',
      'animation',
      'digitalPhotography',
      'poetry',
      'novelWriting',
      'blogging',
      'screenwriting',
      'journaling',
      'playingInstruments',
      'composing',
      'djing',
      'beatboxing',
      'folkDance',
      'weaving',
      'localFestivities',
      'visitingHistoricalMonuments',
      'religiousPilgrimages',
      'traditionalCuisineWorkshops',
      'nativeLanguages',
      'folkTales',
    ],
  ),
  ActivityInterestGroups(
    categoryName: 'technology',
    interests: [
      'appDevelopment',
      'webDevelopment',
      'gameProgramming',
      'consoleGaming',
      'pcGaming',
      'mobileGaming',
      'boardGaming',
      'virtualRealityGaming',
      'robotics',
      'threeDPrinting',
      'droneFlying',
      'aiMlProjects',
      'hackingChallenges',
      'competitiveOnlineGaming',
      'streamCommentary',
      'gameDesign',
      'stargazing',
      'telescopeObserving',
      'meteorShowers',
      'diyScienceKits',
      'robotics',
      'chemistry',
      'hackathons',
      'scienceFairs',
      'makerSpaces',
    ],
  ),
  ActivityInterestGroups(
    categoryName: 'food',
    interests: [
      'baking',
      'soupKitchens',
      'grilling',
      'internationalCuisine',
      'vegetarianCooking',
      'fermentation',
      'wineTasting',
      'coffeeCupping',
      'chocolatePairing',
      'streetFoodSampling',
      'cakeDecorating',
      'foodPhotography',
      'foodBlogging',
      'ketoCooking',
      'veganRecipes',
      'glutenFreeBaking',
      'bbq',
      'campingCooking',
      'openFlameBaking',
    ],
  ),
  ActivityInterestGroups(
    categoryName: 'education',
    interests: [
      'learningNewLanguages',
      'signLanguage',
      'translation',
      'diyCrafting',
      'photographyClasses',
      'danceLessons',
      'writingRetreats',
      'mathPuzzles',
      'scienceExperiments',
      'historyClubs',
      'literatureAnalysis',
      'publicSpeaking',
      'leadershipTraining',
      'timeManagement',
      'codingBootcamps',
      'aiSeminars',
      'cryptoTradingCourses',
      'pitchCompetitions',
      'ideationWorkshops',
      'networkingEvents',
      'stockTrading',
      'cryptocurrencyAnalysis',
      'realEstateInvestment',
      'marketingStrategies',
      'contentCreation',
      'productDesign',
      'storytime',
      'crafts',
      'sports',
      'boardGames',
      'treasureHunts',
      'puzzleChallenges',
      'codingForKids',
      'musicLessons',
      'artClasses',
    ],
  ),
  ActivityInterestGroups(
    categoryName: 'social',
    interests: [
      'charityWork',
      'animalShelters',
      'foodDrives',
      'tutoring',
      'communityCleanups',
      'businessMeetups',
      'professionalClubs',
      'alumniGatherings',
      'triviaNights',
      'karaoke',
      'bookClubs',
      'movieNights',
      'gardeningClubs',
      'carRestorationGroups',
      'astronomyClubs',
      'languageSwaps',
      'culturalFestivals',
      'storytellingSessions',
      'familyOutings',
      'socialGames',
    ],
  ),
  ActivityInterestGroups(
    categoryName: 'wellness',
    interests: [
      'meditation',
      'taiChi',
      'soundBaths',
      'massageTherapy',
      'aromatherapy',
      'skincareRoutines',
      'reading',
      'watchingMovies',
      'listeningToPodcasts',
      'journaling',
      'urbanGardening',
      'hydroponics',
      'bonsaiCultivation',
      'forestHikes',
      'desertTreks',
      'mountainExpeditions',
      'fishing',
      'paddleboarding',
      'jetSkiing',
      'treePlanting',
      'beachCleaning',
      'ecoVolunteering',
    ],
  ),
  ActivityInterestGroups(
    categoryName: 'animals',
    interests: [
      'horseRiding',
      'dogAgilityTraining',
      'petPhotography',
      'birdWatching',
      'wildlifeSafaris',
      'aquariumVisits',
      'volunteeringAtShelters',
      'animalConservation',
      'beekeeping',
    ],
  ),
  ActivityInterestGroups(
    categoryName: 'spirituality',
    interests: [
      'churchServices',
      'mosquePrayers',
      'templeVisits',
      'synagogueGatherings',
      'mindfulnessMeditation',
      'silentRetreats',
      'zenMeditation',
      'vipassana',
      'pilgrimages',
      'sacredSiteVisits',
      'barBatMitzvahs',
      'bibleStudies',
      'quranReading',
      'torahLearning',
      'dharmaTalks',
      'interfaithDialogues',
      'peacebuildingWorkshops',
      'religiousHarmonyConferences',
      'reiki',
      'chakraBalancing',
      'pranicHealing',
      'spiritualCounseling',
      'christmas',
      'ramadanIftarGatherings',
      'diwali',
      'hanukkah',
      'easter',
      'vesak',
      'religiousCommunityProjects',
      'volunteerMissions',
      'forestWalks',
      'ecoSpiritualRetreats',
      'sacredGrovesExploration',
      'hymnCompositions',
      'devotionalDance',
      'kundaliniYoga',
      'bhaktiYoga',
      'mantraChanting',
      'spiritualPhilosophy',
      'existentialism',
      'lifePurpose',
    ],
  ),
];



/// Maps a list of interests to their respective categories in `kActivityInterestGroups`.
List<ActivityInterestGroups> mapInterestsToCategories(List<String> receivedInterests) {
  // Create a map to hold categorized interests
  final Map<String, List<String>> categorizedInterests = {};

  // Iterate through each received interest
  for (final interest in receivedInterests) {
    for (final group in kActivityInterestGroups) {
      // Check if the interest belongs to this category
      if (group.interests.contains(interest)) {
        // If the category is not already in the map, initialize it
        if (!categorizedInterests.containsKey(group.categoryName)) {
          categorizedInterests[group.categoryName] = [];
        }
        // Add the interest to the category
        categorizedInterests[group.categoryName]!.add(interest);
        break;
      }
    }
  }

  // Convert the map into a list of ActivityInterestGroups
  return categorizedInterests.entries.map((entry) {
    return ActivityInterestGroups(
      categoryName: entry.key,
      interests: entry.value,
    );
  }).toList();
}

