import 'package:playkosmos_v3/models/activity_interest_groups.dart';

/// The activity interest groups
const List<ActivityInterestGroups> kActivityInterestGroup = [
  ActivityInterestGroups(
    categoryName: 'combat',
    interests: [
      'boxing',
      'fencing',
      'mixedMartialArts',
      'karate',
      'kickBoxing',
      'kungFu',
      'taekwondo',
      'wrestling',
    ],
  ),
  ActivityInterestGroups(
    categoryName: 'net',
    interests: [
      'basketball',
      'beachVolleyball',
      'fistball',
      'korfball',
      'netball',
      'volleyball',
    ],
  ),
  ActivityInterestGroups(
    categoryName: 'footHand',
    interests: [
      'americanFootball',
      'bubbleFootball',
      'football',
      'futsal',
      'rugby',
    ],
  ),
  ActivityInterestGroups(
    categoryName: 'sticksBat',
    interests: [
      'bandy',
      'baseball',
      'cricket',
      'finnishBaseball',
      'floorball',
      'golf',
      'polo',
    ],
  ),
  ActivityInterestGroups(
    categoryName: 'racket',
    interests: [
      'badminton',
      'padel',
      'racquetball',
      'squash',
      'tableTennis',
      'tennis',
    ],
  ),
  ActivityInterestGroups(
    categoryName: 'winterWater',
    interests: [
      'diving',
      'skating',
      'skiing',
      'swimming',
    ],
  ),
  ActivityInterestGroups(
    categoryName: 'racingAthletics',
    interests: [
      'cycling',
      'highJump',
      'javelin',
      'longJump',
      'motorSports',
      'poleVault',
      'running',
      'shotput',
      'tripleJump',
    ],
  ),
  ActivityInterestGroups(
    categoryName: 'games',
    interests: [
      'battleship',
      'backgammon',
      'carrom',
      'checkers',
      'jenga',
      'ludo',
      'snakeLadder',
      'videogames',
    ],
  ),
  ActivityInterestGroups(
    categoryName: 'mentalSpiritual',
    interests: [
      'bookReading',
      'chess',
      'scrabble',
      'spiritual',
      'yoga',
    ],
  ),
  ActivityInterestGroups(
    categoryName: 'fitness',
    interests: [
      'archery',
      'bowling',
      'dance',
      'darts',
      'gym',
      'pets',
      'rockClimbing',
      'shooting',
      'snookerPool',
    ],
  ),
];

const List<ActivityInterestGroups> kActivityInterestGroups = [
  ActivityInterestGroups(
    categoryName: 'sports',
    interests: [
      'football',
      'basketball',
      'volleyball',
      'rugby',
      'cricket',
      'baseball',
      'hockey',
      'tennis',
      'badminton',
      'squash',
      'tableTennis',
      'swimming',
      'surfing',
      'kayaking',
      'waterPolo',
      'scubaDiving',
      'snorkeling',
      'sailing',
      'skiing',
      'snowboarding',
      'iceSkating',
      'curling',
      'rockClimbing',
      'hiking',
      'trailRunning',
      'mountainBiking',
      'karate',
      'judo',
      'taekwondo',
      'boxing',
      'mma',
      'fencing',
      'yoga',
      'pilates',
      'gymWorkouts',
      'zumba',
      'aerobics',
      'crossFit',
      'backpacking',
      'roadTrips',
      'trainJourneys',
      'culturalTourism',
      'skydiving',
      'paragliding',
      'bungeeJumping',
      'baseJumping',
      'birdwatching',
      'safariTours',
      'stargazing',
      'wildlifePhotography',
      'foodTours',
      'historicalTours',
      'artMuseumVisits',
      'festivalParticipation',
      'islandHopping',
      'riverRafting',
      'deepSeaFishing',
    ],
  ),
  ActivityInterestGroups(
    categoryName: 'arts',
    interests: [
      'painting',
      'drawing',
      'sculpting',
      'photography',
      'calligraphy',
      'graffitiArt',
      'dance',
      'acting',
      'singing',
      'comedy',
      'circusArts',
      'magic',
      'knitting',
      'crochet',
      'quilting',
      'woodworking',
      'pottery',
      'jewelryMaking',
      'graphicDesign',
      'videoEditing',
      'threeDModeling',
      'animation',
      'digitalPhotography',
      'poetry',
      'novelWriting',
      'blogging',
      'screenwriting',
      'journaling',
      'playingInstruments',
      'composing',
      'djing',
      'beatboxing',
      'folkDance',
      'weaving',
      'localFestivities',
      'visitingHistoricalMonuments',
      'religiousPilgrimages',
      'traditionalCuisineWorkshops',
      'nativeLanguages',
      'folkTales',
    ],
  ),
  ActivityInterestGroups(
    categoryName: 'technology',
    interests: [
      'appDevelopment',
      'webDevelopment',
      'gameProgramming',
      'consoleGaming',
      'pcGaming',
      'mobileGaming',
      'boardGaming',
      'virtualRealityGaming',
      'robotics',
      'threeDPrinting',
      'droneFlying',
      'aiMlProjects',
      'hackingChallenges',
      'competitiveOnlineGaming',
      'streamCommentary',
      'gameDesign',
      'stargazing',
      'telescopeObserving',
      'meteorShowers',
      'diyScienceKits',
      'robotics',
      'chemistry',
      'hackathons',
      'scienceFairs',
      'makerSpaces',
    ],
  ),
  ActivityInterestGroups(
    categoryName: 'food',
    interests: [
      'baking',
      'grilling',
      'internationalCuisine',
      'vegetarianCooking',
      'fermentation',
      'wineTasting',
      'coffeeCupping',
      'chocolatePairing',
      'streetFoodSampling',
      'cakeDecorating',
      'foodPhotography',
      'foodBlogging',
      'ketoCooking',
      'veganRecipes',
      'glutenFreeBaking',
      'bbq',
      'campingCooking',
      'openFlameBaking',
    ],
  ),
  ActivityInterestGroups(
    categoryName: 'education',
    interests: [
      'learningNewLanguages',
      'signLanguage',
      'translation',
      'diyCrafting',
      'photographyClasses',
      'danceLessons',
      'writingRetreats',
      'mathPuzzles',
      'scienceExperiments',
      'historyClubs',
      'literatureAnalysis',
      'publicSpeaking',
      'leadershipTraining',
      'timeManagement',
      'codingBootcamps',
      'aiSeminars',
      'cryptoTradingCourses',
      'pitchCompetitions',
      'ideationWorkshops',
      'networkingEvents',
      'stockTrading',
      'cryptocurrencyAnalysis',
      'realEstateInvestment',
      'marketingStrategies',
      'contentCreation',
      'productDesign',
      'storytime',
      'crafts',
      'sports',
      'boardGames',
      'treasureHunts',
      'puzzleChallenges',
      'codingForKids',
      'musicLessons',
      'artClasses',
    ],
  ),
  ActivityInterestGroups(
    categoryName: 'social',
    interests: [
      'animalShelters',
      'foodDrives',
      'tutoring',
      'communityCleanups',
      'businessMeetups',
      'professionalClubs',
      'alumniGatherings',
      'triviaNights',
      'karaoke',
      'bookClubs',
      'movieNights',
      'gardeningClubs',
      'carRestorationGroups',
      'astronomyClubs',
      'languageSwaps',
      'culturalFestivals',
      'storytellingSessions',
      'familyOutings',
      'socialGames',
    ],
  ),
  ActivityInterestGroups(
    categoryName: 'wellness',
    interests: [
      'meditation',
      'taiChi',
      'soundBaths',
      'massageTherapy',
      'aromatherapy',
      'skincareRoutines',
      'reading',
      'watchingMovies',
      'listeningToPodcasts',
      'journaling',
      'urbanGardening',
      'hydroponics',
      'bonsaiCultivation',
      'forestHikes',
      'desertTreks',
      'mountainExpeditions',
      'fishing',
      'paddleboarding',
      'jetSkiing',
      'treePlanting',
      'beachCleaning',
      'ecoVolunteering',
    ],
  ),
  ActivityInterestGroups(
    categoryName: 'animals',
    interests: [
      'horseRiding',
      'dogAgilityTraining',
      'petPhotography',
      'birdWatching',
      'wildlifeSafaris',
      'aquariumVisits',
      'volunteeringAtShelters',
      'animalConservation',
      'beekeeping',
    ],
  ),
];
