import 'package:playkosmos_v3/models/countries_states_model.dart';

const List<CountriesStatesModel> kCsAfgAut = [
  CountriesStatesModel(
    name: "Afghanistan",
    iso3: "AFG",
    iso2: "AF",
    phoneCode: "93",
    translations: {
      "en": "Afghanistan",
      "fr": "Afghanistan",
      "si": "ඇෆ්ගනිස්ථානය",
      "ta": "ஆப்கானிஸ்தான்",
      "fi": "Afganistan",
      "hi": "अफ़ग़ानिस्तान",
      "zh": "阿富汗",
    },
    flag: "🇦🇫",
    flagU: "U+1F1E6 U+1F1EB",
    states: [
      States(
        name: "Badakhshan",
        translations: {
          "en": "Badakhshan",
          "fr": "Badakhshan",
          "si": "බදක්‍ෂාන්",
          "ta": "படாக்சான்",
          "fi": "Badakhshan",
          "hi": "बदख्शान",
          "zh": "巴达赫尚",
        },
      ),
      States(
        name: "Badghis",
        translations: {
          "en": "Badghis",
          "fr": "Badghis",
          "si": "බද්ගීස්",
          "ta": "பட்ஜீஸ்",
          "fi": "Badghis",
          "hi": "बद्घीस",
          "zh": "巴德吉斯",
        },
      ),
      States(
        name: "Baghlan",
        translations: {
          "en": "Baghlan",
          "fr": "Baghlan",
          "si": "බාඝ්ලාන්",
          "ta": "பகலான்",
          "fi": "Baghlan",
          "hi": "बग़लान",
          "zh": "巴格兰",
        },
      ),
      States(
        name: "Balkh",
        translations: {
          "en": "Balkh",
          "fr": "Balkh",
          "si": "බාල්ඛ්",
          "ta": "பால்க்",
          "fi": "Balkh",
          "hi": "बल्ख",
          "zh": "巴尔赫",
        },
      ),
      States(
        name: "Bamyan",
        translations: {
          "en": "Bamyan",
          "fr": "Bamyan",
          "si": "බාම්යාන්",
          "ta": "பாம்யான்",
          "fi": "Bamyan",
          "hi": "बामियान",
          "zh": "巴米扬",
        },
      ),
      States(
        name: "Daykundi",
        translations: {
          "en": "Daykundi",
          "fr": "Deykandi",
          "si": "ඩය්කුන්ඩි",
          "ta": "டேகுன்டி",
          "fi": "Daikondi",
          "hi": "दैकुंडी",
          "zh": "戴昆迪",
        },
      ),
      States(
        name: "Farah",
        translations: {
          "en": "Farah",
          "fr": "Farah",
          "si": "ෆාරා",
          "ta": "பரா",
          "fi": "Farah",
          "hi": "फ़राह",
          "zh": "法拉",
        },
      ),
      States(
        name: "Faryab",
        translations: {
          "en": "Faryab",
          "fr": "Faryab",
          "si": "ෆර්යාබ්",
          "ta": "பர்யாப்",
          "fi": "Faryab",
          "hi": "फ़ारयाब",
          "zh": "法雷阿卜",
        },
      ),
      States(
        name: "Ghazni",
        translations: {
          "en": "Ghazni",
          "fr": "Ghazni",
          "si": "ඝස්නි",
          "ta": "காஸ்னி",
          "fi": "Ghazni",
          "hi": "ग़ज़नी",
          "zh": "加兹尼",
        },
      ),
      States(
        name: "Ghōr",
        translations: {
          "en": "Ghōr",
          "fr": "Ghōr",
          "si": "ඝෝර්",
          "ta": "கோர்",
          "fi": "Ghōr",
          "hi": "घोर",
          "zh": "戈尔",
        },
      ),
      States(
        name: "Helmand",
        translations: {
          "en": "Helmand",
          "fr": "Helmand",
          "si": "හෙල්මන්ඩ්",
          "ta": "ஹெல்மாண்ட்",
          "fi": "Helmand",
          "hi": "हेल्मंड",
          "zh": "赫尔曼德",
        },
      ),
      States(
        name: "Herat",
        translations: {
          "en": "Herat",
          "fr": "Hérat",
          "si": "හේරාත්",
          "ta": "ஹெராத்",
          "fi": "Herat",
          "hi": "हेरात",
          "zh": "赫拉特",
        },
      ),
      States(
        name: "Jowzjan",
        translations: {
          "en": "Jowzjan",
          "fr": "Djozdjan",
          "si": "ජොව්ස්ජාන්",
          "ta": "ஜோவ்ஸ்ஜான்",
          "fi": "Džouzdžan",
          "hi": "जोज़जान",
          "zh": "朱兹詹",
        },
      ),
      States(
        name: "Kabul",
        translations: {
          "en": "Kabul",
          "fr": "Kaboul",
          "si": "කāබුල්",
          "ta": "காபூல்",
          "fi": "Kabul",
          "hi": "काबुल",
          "zh": "喀布尔",
        },
      ),
      States(
        name: "Kandahar",
        translations: {
          "en": "Kandahar",
          "fr": "Kandahar",
          "si": "කන්දාහාර",
          "ta": "கந்தகார்",
          "fi": "Kandahar",
          "hi": "कांधार",
          "zh": "坎大哈",
        },
      ),
      States(
        name: "Kapisa",
        translations: {
          "en": "Kapisa",
          "fr": "Kapissa",
          "si": "කපිසා",
          "ta": "கபிசா",
          "fi": "Kapisa",
          "hi": "कापीसा",
          "zh": "卡比萨",
        },
      ),
      States(
        name: "Khost",
        translations: {
          "en": "Khost",
          "fr": "Khost",
          "si": "කොස්ට්",
          "ta": "கோஸ்ட்",
          "fi": "Khust",
          "hi": "ख़ोस्त",
          "zh": "霍斯特",
        },
      ),
      States(
        name: "Kunar",
        translations: {
          "en": "Kunar",
          "fr": "Kounar",
          "si": "කූනාර්",
          "ta": "குனர்",
          "fi": "Kunar",
          "hi": "कुनर",
          "zh": "库纳尔",
        },
      ),
      States(
        name: "Kunduz",
        translations: {
          "en": "Kunduz",
          "fr": "Kondoz",
          "si": "කූන්ඩුස්",
          "ta": "குந்தூஸ்",
          "fi": "Kunduz",
          "hi": "कुंदुज़",
          "zh": "昆都士",
        },
      ),
      States(
        name: "Laghman",
        translations: {
          "en": "Laghman",
          "fr": "Laghman",
          "si": "ලාඝ්මන්",
          "ta": "லக்மான்",
          "fi": "Laghman",
          "hi": "लग़मान",
          "zh": "拉格曼",
        },
      ),
      States(
        name: "Logar",
        translations: {
          "en": "Logar",
          "fr": "Logar",
          "si": "ලාඝ්මන්",
          "ta": "லோகார்",
          "fi": "Logar",
          "hi": "लोगर",
          "zh": "洛加尔",
        },
      ),
      States(
        name: "Nangarhar",
        translations: {
          "en": "Nangarhar",
          "fr": "Nangarhar",
          "si": "නංගර්හාර්",
          "ta": "நங்கர்கார்",
          "fi": "Nangarhar",
          "hi": "नंगरहार",
          "zh": "楠格哈尔",
        },
      ),
      States(
        name: "Nimruz",
        translations: {
          "en": "Nimruz",
          "fr": "Nimroz",
          "si": "නිම්රුස්",
          "ta": "நிம்ரூஸ்",
          "fi": "Nimruz",
          "hi": "नीमरूज़",
          "zh": "尼姆鲁兹",
        },
      ),
      States(
        name: "Nuristan",
        translations: {
          "en": "Nuristan",
          "fr": "Nouristan",
          "si": "නූරිස්තාන්",
          "ta": "நூரிஸ்தான்",
          "fi": "Nuristan",
          "hi": "नूरिस्तान",
          "zh": "努里斯坦",
        },
      ),
      States(
        name: "Paktia",
        translations: {
          "en": "Paktia",
          "fr": "Paktiya",
          "si": "පක්ටියා",
          "ta": "பாக்டியா",
          "fi": "Paktia",
          "hi": "पकतिया",
          "zh": "帕克蒂亚",
        },
      ),
      States(
        name: "Paktika",
        translations: {
          "en": "Paktika",
          "fr": "Paktika",
          "si": "පක්ටිකා",
          "ta": "பாக்டிகா",
          "fi": "Paktika",
          "hi": "पकतीका",
          "zh": "帕克蒂卡",
        },
      ),
      States(
        name: "Panjshir",
        translations: {
          "en": "Panjshir",
          "fr": "Panchir",
          "si": "පන්ජ්ෂිර්",
          "ta": "பன்சீர்",
          "fi": "Panjshir",
          "hi": "पंजशीर",
          "zh": "潘傑希爾",
        },
      ),
      States(
        name: "Parwan",
        translations: {
          "en": "Parwan",
          "fr": "Parwan",
          "si": "පර්වාන්",
          "ta": "பர்வான்",
          "fi": "Parvan",
          "hi": "परवान",
          "zh": "帕尔旺",
        },
      ),
      States(
        name: "Samangan",
        translations: {
          "en": "Samangan",
          "fr": "Samangan",
          "si": "සමන්ගන්",
          "ta": "சமங்கன்",
          "fi": "Samangan",
          "hi": "समंगान",
          "zh": "萨曼甘",
        },
      ),
      States(
        name: "Sar-e Pol",
        translations: {
          "en": "Sar-e Pol",
          "fr": "Sar-é Pol",
          "si": "සර්-එ පොල්",
          "ta": "சர் இ போல்",
          "fi": "Sar-e Pol",
          "hi": "सर-ए पोल",
          "zh": "萨尔普勒",
        },
      ),
      States(
        name: "Takhar",
        translations: {
          "en": "Takhar",
          "fr": "Takhar",
          "si": "ටඛාර්",
          "ta": "தகார்",
          "fi": "Takhar",
          "hi": "तख़ार",
          "zh": "塔哈尔",
        },
      ),
      States(
        name: "Urozgan",
        translations: {
          "en": "Urozgan",
          "fr": "Orozgan",
          "si": "උරොස්ගාන්",
          "ta": "ஒரூஸ்கான்",
          "fi": "Urozgan",
          "hi": "ओरूज़्गान",
          "zh": "乌鲁兹甘",
        },
      ),
      States(
        name: "Wardak",
        translations: {
          "en": "Wardak",
          "fr": "Wardak",
          "si": "වර්ඩක්",
          "ta": "வர்தகு",
          "fi": "Vardak",
          "hi": "मैदान",
          "zh": "瓦尔达克",
        },
      ),
      States(
        name: "Zabul",
        translations: {
          "en": "Zabul",
          "fr": "Zabol",
          "si": "සාබුල්",
          "ta": "சாபுல்",
          "fi": "Zabul",
          "hi": "ज़ाबुल",
          "zh": "扎布尔",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Åland Islands",
    iso3: "ALA",
    iso2: "AX",
    phoneCode: "358",
    translations: {
      "en": "Åland Islands",
      "fr": "Åland",
      "si": "Åland දූපත්",
      "ta": "ஓலந்து தீவுகள்",
      "fi": "Ahvenanmaan maakunta",
      "hi": "ऑलैण्ड द्वीपसमूह",
      "zh": "奥兰群岛",
    },
    flag: "🇦🇽",
    flagU: "U+1F1E6 U+1F1FD",
    states: [],
  ),
  CountriesStatesModel(
    name: "Albania",
    iso3: "ALB",
    iso2: "AL",
    phoneCode: "355",
    translations: {
      "en": "Albania",
      "fr": "Albanie",
      "si": "ඇල්බේනියාව",
      "ta": "அல்பேனியா",
      "hi": "अल्बानिया",
      "zh": "阿尔巴尼亚",
    },
    flag: "🇦🇱",
    flagU: "U+1F1E6 U+1F1F1",
    states: [
      States(
        name: "Berat County",
        translations: {
          "en": "Berat County",
          "fr": "Comté de Berat",
          "si": "බෙරාට් දිස්ත්‍රික්කය",
          "ta": "பெராட் கவுண்டி",
          "fi": "Beratin maakunta",
          "hi": "बेराट काउंटी",
          "zh": "贝拉特县",
        },
      ),
      States(
        name: "Berat District",
        translations: {
          "en": "Berat District",
          "fr": "District de Berat",
          "si": "බෙරාට් දිස්ත්‍රික",
          "ta": "பெராட் மாவட்டம்",
          "fi": "Beratin piirikunta",
          "hi": "बेराट जिला",
          "zh": "贝拉特区",
        },
      ),
      States(
        name: "Bulqizë District",
        translations: {
          "en": "Bulqizë District",
          "fr": "District de Bulqizë",
          "si": "බල්කිස් දිස්ත්‍රිකය",
          "ta": "புல்கிஜே மாவட்டம்",
          "fi": "Beratin piirikunta",
          "hi": "बेराट जिला",
          "zh": "布爾基茨區",
        },
      ),
      States(
        name: "Delvinë District",
        translations: {
          "en": "Delvinë District",
          "fr": "District de Delvinë",
          "si": "ඩෙල්විනේ දිස්ත්‍රිකය",
          "ta": "டெல்வினே மாவட்டம்",
          "fi": "Delvinën piirikunta",
          "hi": "डेल्विने जिला",
          "zh": "德爾維內區",
        },
      ),
      States(
        name: "Devoll District",
        translations: {
          "en": "Devoll District",
          "fr": "District de Devoll",
          "si": "ඩෙවොල් දිස්ත්‍රිකය",
          "ta": "தேவோல் மாவட்டம்",
          "fi": "Devollin piirikunta",
          "hi": "देवोल जिलाा",
          "zh": "德沃爾區",
        },
      ),
      States(
        name: "Dibër County",
        translations: {
          "en": "Dibër County",
          "fr": "Comté de Dibër",
          "si": "ඩිබර් දිස්ත්‍රික්කය",
          "ta": "டிபெர் கவுண்டி",
          "fi": "Dibërin lääni",
          "hi": "िबेर काउंटी",
          "zh": "迪贝尔县",
        },
      ),
      States(
        name: "Dibër District",
        translations: {
          "en": "Dibër District",
          "fr": "District de Dibër",
          "si": "ඩිබර් දිස්ත්‍රිකය",
          "ta": "டிபெர் மாவட்டம்",
          "fi": "Dibërin piirikunta",
          "hi": "डिबेर जिला",
          "zh": "迪贝尔区",
        },
      ),
      States(
        name: "Durrës County",
        translations: {
          "en": "Durrës County",
          "fr": "Comté de Durrës",
          "si": "ඩර්රෙස් දිස්ත්‍රික්කය",
          "ta": "டுர்ரேஸ் கவுண்டி",
          "fi": "Durrësin lääni",
          "hi": "दुर्रेस काउंटी",
          "zh": "杜勒斯县",
        },
      ),
      States(
        name: "Durrës District",
        translations: {
          "en": "Durrës District",
          "fr": "District de Durrës",
          "si": "ඩර්රෙස් දිස්ත්‍රිකය",
          "ta": "டுர்ரேஸ் மாவட்டம்",
          "fi": "Durrësin piirikunta",
          "hi": "दुर्रेस जिला",
          "zh": "杜勒斯区",
        },
      ),
      States(
        name: "Elbasan County",
        translations: {
          "en": "Elbasan County",
          "fr": "Comté d'Elbasan",
          "si": "එල්බාසන් දිස්ත්‍රික්කය",
          "ta": "எல்பாசான் கவுண்டி",
          "fi": "Elbasanin lääni",
          "hi": "एल्बासन काउंटी",
          "zh": "埃尔巴桑县",
        },
      ),
      States(
        name: "Fier County",
        translations: {
          "en": "Fier County",
          "fr": "Comté d'Elbasan",
          "si": "එල්බාසන් දිස්ත්‍රික්කය",
          "ta": "எல்பாசான் கவுண்டி",
          "fi": "Elbasanin lääni",
          "hi": "एल्बासन काउंटी",
          "zh": "埃尔巴桑县",
        },
      ),
      States(
        name: "Fier District",
        translations: {
          "en": "Fier District",
          "fr": "District de Fier",
          "si": "ෆියර් දිස්ත්‍රිකය",
          "ta": "ஃபியர் மாவட்டம்",
          "fi": "Fierin piirikunta",
          "hi": "फिएर जिला",
          "zh": "费尔区",
        },
      ),
      States(
        name: "Gjirokastër County",
        translations: {
          "en": "Gjirokastër County",
          "fr": "Comté de Gjirokastër",
          "si": "ග්ජිරොකාස්ථාර දිස්ත්‍රික්කය",
          "ta": "கிஜிரோகாஸ்டர் கவுண்டி",
          "fi": "Gjirokastër lääni",
          "hi": "ग्जिरोकास्तेर काउंटी",
          "zh": "吉诺卡斯特尔县",
        },
      ),
      States(
        name: "Gjirokastër District",
        translations: {
          "en": "Gjirokastër District",
          "fr": "District de Gjirokastër",
          "si": "ග්ජිරොකාස්ථාර දිස්ත්‍රිකය",
          "ta": "கிஜிரோகாஸ்டர் மாவட்டம்",
          "fi": "Gjirokastërin piirikunta",
          "hi": "ग्जिरोकास्टर जिला",
          "zh": "吉诺卡斯特尔区",
        },
      ),
      States(
        name: "Gramsh District",
        translations: {
          "en": "Gramsh District",
          "fr": "District de Gramsh",
          "si": "ග්‍රැම්ෂ් දිස්ත්‍රික්කය",
          "ta": "கிராம்ஷ் மாவட்டம்",
          "fi": "Gramshin piirikunta",
          "hi": "ग्राम्श जिला",
          "zh": "格拉姆什区",
        },
      ),
      States(
        name: "Has District",
        translations: {
          "en": "Has District",
          "fr": "District de Has",
          "si": "හාස් දිස්ත්‍රිකය",
          "ta": "ஹாஸ் மாவட்டம்",
          "fi": "Hasin piirikunta",
          "hi": "हास जिला",
          "zh": "哈斯区",
        },
      ),
      States(
        name: "Kavajë District",
        translations: {
          "en": "Kavajë District",
          "fr": "District de Kavajë",
          "si": "කවජේ දිස්ත්‍රිකය",
          "ta": "கவாஜே மாவட்டம்",
          "fi": "Kavajën piirikunta",
          "hi": "कावजे जिला",
          "zh": "卡瓦耶区",
        },
      ),
      States(
        name: "Kolonjë District",
        translations: {
          "en": "Kolonjë District",
          "fr": "District de Kolonjë",
          "si": "කවජේ දිස්ත්‍රිකය",
          "ta": "கொலோஞ்சே மாவட்டம்",
          "fi": "Kolonjën piirikunta",
          "hi": "कोलोन्जे जिला",
          "zh": "科隆亚区",
        },
      ),
      States(
        name: "Korçë County",
        translations: {
          "en": "Korçë County",
          "fr": "Comté de Korçë",
          "si": "කොර්චේ දිස්ත්‍රික්කය",
          "ta": "கொர்ஸ் கவுண்டி",
          "fi": "Korçën lääni",
          "hi": "कोर्से काउंटी",
          "zh": "科尔察县",
        },
      ),
      States(
        name: "Korçë District",
        translations: {
          "en": "Korçë District",
          "fr": "District de Korçë",
          "si": "කොර්චේ දිස්ත්‍රිකය",
          "ta": "கொர்சி மாவட்டம்",
          "fi": "Korçën piirikunta",
          "hi": "कोर्से जिला",
          "zh": "科尔察区",
        },
      ),
      States(
        name: "Krujë District",
        translations: {
          "en": "Krujë District",
          "fr": "District de Krujë",
          "si": "කුරුජේ දිස්ත්‍රික්කය",
          "ta": "குருஜே மாவட்டம்",
          "fi": "Krujën piirikunta",
          "hi": "क्रुजे जिला",
          "zh": "克鲁亚区",
        },
      ),
      States(
        name: "Kuçovë District",
        translations: {
          "en": "Kuçovë District",
          "fr": "District de Korçë",
          "si": "කොර්චේ දිස්ත්‍රිකය",
          "ta": "கொர்சி மாவட்டம்",
          "fi": "Korçën piirikunta",
          "hi": "कोर्से जिला",
          "zh": "科尔察区",
        },
      ),
      States(
        name: "Kukës County",
        translations: {
          "en": "Kukës County",
          "fr": "Comté de Kukës",
          "si": "කුකෙස් දිස්ත්‍රික්කය",
          "ta": "குகேஸ் கவுண்டி",
          "fi": "Kukësin lääni",
          "hi": "कुकेस काउंटी",
          "zh": "库克斯县",
        },
      ),
      States(
        name: "Kukës District",
        translations: {
          "en": "Kukës District",
          "fr": "District de Kukës",
          "si": "කුකෙස් දිස්ත්‍රිකය",
          "ta": "குகேஸ் மாவட்டம்",
          "fi": "Kukësin piirikunta",
          "hi": "कुकेस जिला",
          "zh": "库克斯区",
        },
      ),
      States(
        name: "Kurbin District",
        translations: {
          "en": "Kurbin District",
          "fr": "District de Kukës",
          "si": "කුකෙස් දිස්ත්‍රිකය",
          "ta": "குகேஸ் மாவட்டம்",
          "fi": "Kukësin piirikunta",
          "hi": "कुकेस जिला",
          "zh": "库克斯区",
        },
      ),
      States(
        name: "Lezhë County",
        translations: {
          "en": "Lezhë County",
          "fr": "Comté de Lezhë",
          "si": "ලෙස්හේ දිස්ත්‍රික්කය",
          "ta": "லெஷே கவுண்டி",
          "fi": "Lezhën lääni",
          "hi": "लेझे काउंटी",
          "zh": "莱什县",
        },
      ),
      States(
        name: "Lezhë District",
        translations: {
          "en": "Lezhë District",
          "fr": "District de Lezhë",
          "si": "ලෙස්හේ දිස්ත්‍රිකය",
          "ta": "லெஷே மாவட்டம்",
          "fi": "Lezhën piirikunta",
          "hi": "लेझे जिला",
          "zh": "莱什区",
        },
      ),
      States(
        name: "Librazhd District",
        translations: {
          "en": "Librazhd District",
          "fr": "District de Librazhd",
          "si": "ලිබ්රාස්ද් දිස්ත්‍රික්කය",
          "ta": "லிப்ராஜ்ட் மாவட்டம்",
          "fi": "Librazhdin piirikunta",
          "hi": "लिब्राज़ड जिला",
          "zh": "利布拉兹德区",
        },
      ),
      States(
        name: "Lushnjë District",
        translations: {
          "en": "Lushnjë District",
          "fr": "District de Lushnjë",
          "si": "ලුෂ්න්ජේ දිස්ත්‍රිකය",
          "ta": "லுஷ்ஞே மாவட்டம்",
          "fi": "Lushnjën piirikunta",
          "hi": "लुश्न्जे जिला",
          "zh": "鲁什尼区",
        },
      ),
      States(
        name: "Malësi e Madhe District",
        translations: {
          "en": "Malësi e Madhe District",
          "fr": "District de Malësi e Madhe",
          "si": "මලේසි හා මහ්දේ දිස්ත්‍රික්කය",
          "ta": "மலேசி மற்றும் மாதே மாவட்டம்",
          "fi": "Malësi e Madhen piiri",
          "hi": "मालेसी इ माद्हे जिला",
          "zh": "马列西埃马德区",
        },
      ),
      States(
        name: "Mallakastër District",
        translations: {
          "en": "Mallakastër District",
          "fr": "District de Mallakastër",
          "si": "මල්ලකස්තර් දිස්ත්‍රිකය",
          "ta": "மல்லகஸ்டேர் மாவட்டம்",
          "fi": "Mallakastërin piirikunta",
          "hi": "मल्लाकास्टेर जिला",
          "zh": "马拉卡斯特尔区",
        },
      ),
      States(
        name: "Mat District",
        translations: {
          "en": "Mat District",
          "fr": "District de Mat",
          "si": "මැට් දිස්ත්‍රිකය",
          "ta": "மாட் மாவட்டம்",
          "fi": "Matin piirikunta",
          "hi": "मैट जिला",
          "zh": "马特区",
        },
      ),
      States(
        name: "Mirditë District",
        translations: {
          "en": "Mirditë District",
          "fr": "District de Mirditë",
          "si": "මිර්දිටේ දිස්ත්‍රිකය",
          "ta": "மிர்டிடே மாவட்டம்",
          "fi": "Mirditën piirikunta",
          "hi": "मिरदिते जिला",
          "zh": "米尔迪特区",
        },
      ),
      States(
        name: "Peqin District",
        translations: {
          "en": "Peqin District",
          "fr": "District de Peqin",
          "si": "පෙකින් දිස්ත්‍රිකය",
          "ta": "பெகின் மாவட்டம்",
          "fi": "Peqinin piirikunta",
          "hi": "पेकिन जिला",
          "zh": "佩钦区",
        },
      ),
      States(
        name: "Përmet District",
        translations: {
          "en": "Përmet District",
          "fr": "District de Përmet",
          "si": "පර්මෙට් දිස්ත්‍රිකය",
          "ta": "பெர்மெட் மாவட்டம்",
          "fi": "Përmetin piirikunta",
          "hi": "पेरमेट जिला",
          "zh": "佩尔梅特区",
        },
      ),
      States(
        name: "Pogradec District",
        translations: {
          "en": "Pogradec District",
          "fr": "District de Pogradec",
          "si": "පොග්රඩෙක් දිස්ත්‍රිකය",
          "ta": "பொக்ரடெக் மாவட்டம்",
          "fi": "Pogradecin piirikunta",
          "hi": "पोग्राडेक जिला",
          "zh": "波格拉德茨区",
        },
      ),
      States(
        name: "Pukë District",
        translations: {
          "en": "Pukë District",
          "fr": "District de Pukë",
          "si": "පුකේ දිස්ත්‍රිකය",
          "ta": "புக்கே மாவட்டம்",
          "fi": "Pukën piirikunta",
          "hi": "पुके जिला",
          "zh": "普克区",
        },
      ),
      States(
        name: "Sarandë District",
        translations: {
          "en": "Sarandë District",
          "fr": "District de Sarandë",
          "si": "සරන්දේ දිස්ත්‍රිකය",
          "ta": "சரண்டே மாவட்டம்",
          "fi": "Sarandën piirikunta",
          "hi": "सरन्दे जिला",
          "zh": "萨兰德区",
        },
      ),
      States(
        name: "Shkodër County",
        translations: {
          "en": "Shkodër County",
          "fr": "Comté de Shkodër",
          "si": "ශ්කොඩර් දිස්ත්‍රික්කය",
          "ta": "ஷ்கோடேர் கவுண்டி",
          "fi": "Shkodërin lääni",
          "hi": "श्कोडेर काउंटी",
          "zh": "什科德尔县",
        },
      ),
      States(
        name: "Shkodër District",
        translations: {
          "en": "Shkodër District",
          "fr": "District de Shkodër",
          "si": "ශ්කොඩර් දිස්ත්‍රික්කය",
          "ta": "ஷ்கோடர் மாவட்டம்",
          "fi": "Shkodërin piirikunta",
          "hi": "श्कोडेर जिला",
          "zh": "什科德尔区",
        },
      ),
      States(
        name: "Skrapar District",
        translations: {
          "en": "Skrapar District",
          "fr": "District de Skrapar",
          "si": "ස්ක්‍රපාර් දිස්ත්‍රිකය",
          "ta": "ஸ்க்ரபார் மாவட்டம்",
          "fi": "Skraparin piirikunta",
          "hi": "स्क्रपार जिला",
          "zh": "斯克拉帕尔区",
        },
      ),
      States(
        name: "Tepelenë District",
        translations: {
          "en": "Tepelenë District",
          "fr": "District de Tepelenë",
          "si": "ටෙපෙලෙන් දිස්ත්‍රිකය",
          "ta": "டெபெலெனே மாவட்டம்",
          "fi": "Tepelenën piirikunta",
          "hi": "टेपेलेने जिला",
          "zh": "泰佩莱尼区",
        },
      ),
      States(
        name: "Tirana County",
        translations: {
          "en": "Tirana County",
          "fr": "Comté de Tirana",
          "si": "ටිරානා දිස්ත්‍රික්කය",
          "ta": "திரானா கவுன்டி",
          "fi": "Tiranin lääni",
          "hi": "तिराना काउंटी",
          "zh": "地拉那县",
        },
      ),
      States(
        name: "Tirana District",
        translations: {
          "en": "Tirana District",
          "fr": "Comté de Tirana",
          "si": "ටිරානා දිස්ත්‍රික්කය",
          "ta": "திரானா கவுன்டி",
          "fi": "Tiranin lääni",
          "hi": "तिराना काउंटी",
          "zh": "地拉那县",
        },
      ),
      States(
        name: "Tropojë District",
        translations: {
          "en": "Tropojë District",
          "fr": "District de Tirana",
          "si": "ටිරානා දිස්ත්‍රික්කය",
          "ta": "திரானா மாவட்டம்",
          "fi": "Tiranin piirikunta",
          "hi": "तिराना जिला",
          "zh": "地拉那区",
        },
      ),
      States(
        name: "Vlorë County",
        translations: {
          "en": "Vlorë County",
          "fr": "Comté de Vlorë",
          "si": "ව්ලොර් දිස්ත්‍රික්කය",
          "ta": "விலோரே கவுண்டி",
          "fi": "Vlorën lääni",
          "hi": "व्लोर काउंटी",
          "zh": "沃洛尔县",
        },
      ),
      States(
        name: "Vlorë District",
        translations: {
          "en": "Vlorë District",
          "fr": "District de Vlorë",
          "si": "ව්ලොර් දිස්ත්‍රිකය",
          "ta": "விலோரே மாவட்டம்",
          "fi": "Vlorën piirikunta",
          "hi": "व्लोरे जिला",
          "zh": "沃洛尔区",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Algeria",
    iso3: "DZA",
    iso2: "DZ",
    phoneCode: "213",
    translations: {
      "en": "Algeria",
      "fr": "Algérie",
      "si": "ඇල්ජීරියාව",
      "ta": "அல்சீரியா",
      "hi": "अल्जीरिया",
      "zh": "阿尔及利亚",
    },
    flag: "🇩🇿",
    flagU: "U+1F1E9 U+1F1FF",
    states: [
      States(
        name: "Adrar",
        translations: {
          "en": "Adrar",
          "fr": "Adrar",
          "si": "අද්‍රාර්",
          "ta": "அத்ரார்",
          "fi": "Adrar",
          "hi": "अदरार",
          "zh": "阿德拉尔",
        },
      ),
      States(
        name: "Aïn Defla",
        translations: {
          "en": "Aïn Defla",
          "fr": "Aïn Defla",
          "si": "ඇයින් දේෆ්ලා",
          "ta": "ஐன் டெஃப்லா",
          "fi": "Aïn Defla",
          "hi": "आइन डेफला",
          "zh": "Ain Defla",
        },
      ),
      States(
        name: "Aïn Témouchent",
        translations: {
          "en": "Aïn Témouchent",
          "fr": "Aïn Témouchent",
          "si": "ඇයින් ටෙමූෂෙන්ට්",
          "ta": "ஐன் தேமூசெந்த்",
          "fi": "Aïn Témouchent",
          "hi": "ऐन टेमूशेंट",
          "zh": "Ain Temuchent",
        },
      ),
      States(
        name: "Algiers",
        translations: {
          "en": "Algiers",
          "fr": "Alger",
          "si": "ඇල්ජිය්ස්",
          "ta": "அல்ஜியர்ஸ்",
          "fi": "Alger",
          "hi": "अल्जीयर्सा",
          "zh": "阿尔及尔",
        },
      ),
      States(
        name: "Annaba",
        translations: {
          "en": "Annaba",
          "fr": "Annaba",
          "si": "අන්නාබා",
          "ta": "அன்னாபா",
          "fi": "Annaba",
          "hi": "अन्नाबा",
          "zh": "安纳巴",
        },
      ),
      States(
        name: "Batna",
        translations: {
          "en": "Batna",
          "fr": "Batna",
          "si": "බැට්නා",
          "ta": "பாட்னா",
          "fi": "Batna",
          "hi": "बातना",
          "zh": "巴特纳",
        },
      ),
      States(
        name: "Béchar",
        translations: {
          "en": "Béchar",
          "fr": "Béchar",
          "si": "බේචාර්",
          "ta": "பேஷார்",
          "fi": "Béchar",
          "hi": "बेशार",
          "zh": "贝沙尔",
        },
      ),
      States(
        name: "Béjaïa",
        translations: {
          "en": "Béjaïa",
          "fr": "Béjaïa",
          "si": "බේජායා",
          "ta": "பேஜாயா",
          "fi": "Béjaïa",
          "hi": "बेजाया",
          "zh": "贝贾亚",
        },
      ),
      States(
        name: "Béni Abbès",
        translations: {
          "en": "Béni Abbès",
          "fr": "Béni Abbès",
          "si": "බේනි ඇබ්බෙස්",
          "ta": "பேனி அப்பேஸ்",
          "fi": "Béni Abbès",
          "hi": "बेनी अब्बेस",
          "zh": "贝尼阿贝斯",
        },
      ),
      States(
        name: "Biskra",
        translations: {
          "en": "Biskra",
          "fr": "Biskra",
          "si": "බිස්ක්‍රා",
          "ta": "பிஸ்க்ரா",
          "fi": "Biskra",
          "hi": "बिस्करा",
          "zh": "比斯克拉",
        },
      ),
      States(
        name: "Blida",
        translations: {
          "en": "Blida",
          "fr": "Blida",
          "si": "බ්ලිඩා",
          "ta": "பிலிடா",
          "fi": "Blida",
          "hi": "ब	ब्लीडा",
          "zh": "布利达",
        },
      ),
      States(
        name: "Bordj Baji Mokhtar",
        translations: {
          "en": "Bordj Baji Mokhtar",
          "fr": "Bordj Baji Mokhtar",
          "si": "බෝර්ජ් බජි මොක්ටාර්",
          "ta": "போர்ஜ் பாஜி மோக்தார்",
          "fi": "Bordj Baji Mokhtar",
          "hi": "बोर्ज बाजी मोख्तार",
          "zh": "博尔基巴吉莫赫塔尔",
        },
      ),
      States(
        name: "Bordj Bou Arréridj",
        translations: {
          "en": "Bordj Bou Arréridj",
          "fr": "Bordj Bou Arréridj",
          "si": "බෝර්ජ් බූ අර්රිජ්",
          "ta": "போர்ஜ் பூ அர்ரீரிஜ்",
          "fi": "Bordj Bou Arréridj",
          "hi": "बोर्ज बू अररिज",
          "zh": "博爾吉布阿里里治",
        },
      ),
      States(
        name: "Bouïra",
        translations: {
          "en": "Bouïra",
          "fr": "Bouïra",
          "si": "බූඅයිරා",
          "ta": "பூஐரா",
          "fi": "Bouïra",
          "hi": "बूइरा",
          "zh": "布伊拉",
        },
      ),
      States(
        name: "Boumerdès",
        translations: {
          "en": "Boumerdès",
          "fr": "Boumerdès",
          "si": "බූමර්දේස්",
          "ta": "போமேர்தேஸ்",
          "fi": "Boumerdès",
          "hi": "बोमर्डेस",
          "zh": "布梅尔代斯",
        },
      ),
      States(
        name: "Chlef",
        translations: {
          "en": "Chlef",
          "fr": "Chlef",
          "si": "ච්ලෙෆ්",
          "ta": "ச்லெஃப்",
          "fi": "Chlef",
          "hi": "च्लेफ",
          "zh": "常瓦勒",
        },
      ),
      States(
        name: "Constantine",
        translations: {
          "en": "Constantine",
          "fr": "Constantine",
          "si": "කොන්ස්ටන්ටින්",
          "ta": "கான்ஸ்டந்டைன்",
          "fi": "Constantine",
          "hi": "कोंस्टेन्टाइन",
          "zh": "康斯坦丁",
        },
      ),
      States(
        name: "Djanet",
        translations: {
          "en": "Djanet",
          "fr": "Djanet",
          "si": "ජනෙට්",
          "ta": "ஜனெட்",
          "fi": "Djanet",
          "hi": "जानेट",
          "zh": "扎纳特",
        },
      ),
      States(
        name: "Djelfa",
        translations: {
          "en": "Djelfa",
          "fr": "Djelfa",
          "si": "ජෙල්ෆා",
          "ta": "ஜெல்ஃபா",
          "fi": "Djelfa",
          "hi": "जेल्फा",
          "zh": "傑爾法",
        },
      ),
      States(
        name: "El Bayadh",
        translations: {
          "en": "El Bayadh",
          "fr": "El Bayadh",
          "si": "එල් බයාඩ්",
          "ta": "எல் பயாத்",
          "fi": "El Bayadh",
          "hi": "एल बायाध",
          "zh": "艾尔巴亚德",
        },
      ),
      States(
        name: "El M'ghair",
        translations: {
          "en": "El M'ghair",
          "fr": "El M'ghair",
          "si": "එල් එම්'ගේර්",
          "ta": "எல் எம்கைர்",
          "fi": "El M'ghair",
          "hi": "एल एम'गैर",
          "zh": "艾尔姆盖尔",
        },
      ),
      States(
        name: "El Menia",
        translations: {
          "en": "El Menia",
          "fr": "El Menia",
          "si": "එල් මෙනියා",
          "ta": "எல் மீனியா",
          "fi": "El Menia",
          "hi": "एल मेनिया",
          "zh": "埃尔梅尼亚",
        },
      ),
      States(
        name: "El Oued",
        translations: {
          "en": "El Oued",
          "fr": "El Oued",
          "si": "එල් ඔව්ඩ්",
          "ta": "எல் ஒவேட்",
          "fi": "El Oued",
          "hi": "एल ऊएड",
          "zh": "艾尔瓦德",
        },
      ),
      States(
        name: "El Tarf",
        translations: {
          "en": "El Tarf",
          "fr": "El Tarf",
          "si": "එල් ටර්ෆ්",
          "ta": "எல் தார்ஃப்",
          "fi": "El Tarf",
          "hi": "एल तर्फ",
          "zh": "艾尔塔夫",
        },
      ),
      States(
        name: "Ghardaïa",
        translations: {
          "en": "Ghardaïa",
          "fr": "Ghardaïa",
          "si": "ගාර්දායා",
          "ta": "கார்தாயா",
          "fi": "Ghardaïa",
          "hi": "गर्दाया",
          "zh": "加尔达亚",
        },
      ),
      States(
        name: "Guelma",
        translations: {
          "en": "Guelma",
          "fr": "Guelma",
          "si": "ගුල්මා",
          "ta": "குவேல்மா",
          "fi": "Guelma",
          "hi": "ग्वेल्मा",
          "zh": "盖尔默",
        },
      ),
      States(
        name: "Illizi",
        translations: {
          "en": "Illizi",
          "fr": "Illizi",
          "si": "ඉල්ලිසි",
          "ta": "இல்லிசி",
          "fi": "Illizi",
          "hi": "इल्लिजी",
          "zh": "伊利齐",
        },
      ),
      States(
        name: "In Guezzam",
        translations: {
          "en": "In Guezzam",
          "fr": "In Guezzam",
          "si": "ඉන් ගුඇස්සාම්",
          "ta": "இன் குயெஸ்ஸாம்",
          "fi": "In Guezzam",
          "hi": "इन गुएज़्जाम",
          "zh": "因古薩姆",
        },
      ),
      States(
        name: "In Salah",
        translations: {
          "en": "In Salah",
          "fr": "In Salah",
          "si": "ඉන් සලා",
          "ta": "இன் சலா",
          "fi": "In Salah",
          "hi": "इन सलाह",
          "zh": "因萨拉",
        },
      ),
      States(
        name: "Jijel",
        translations: {
          "en": "Jijel",
          "fr": "Jijel",
          "si": "ජිජෙල්",
          "ta": "ஜிஜேல்",
          "fi": "Jijel",
          "hi": "जीजेल",
          "zh": "吉傑爾",
        },
      ),
      States(
        name: "Khenchela",
        translations: {
          "en": "Khenchela",
          "fr": "Khenchela",
          "si": "කෙන්චෙලා",
          "ta": "கென்செலா",
          "fi": "Khenchela",
          "hi": "खेंचेला",
          "zh": "肯舍拉",
        },
      ),
      States(
        name: "Laghouat",
        translations: {
          "en": "Laghouat",
          "fr": "Laghouat",
          "si": "ලැගොන්",
          "ta": "லகூவாத்",
          "fi": "Laghouat",
          "hi": "लागोवाट",
          "zh": "拉古阿特",
        },
      ),
      States(
        name: "M'Sila",
        translations: {
          "en": "M'Sila",
          "fr": "M'Sila",
          "si": "එම්'සිලා",
          "ta": "மு'சிலா",
          "fi": "M'Sila",
          "hi": "एम'सिला",
          "zh": "穆西拉",
        },
      ),
      States(
        name: "Mascara",
        translations: {
          "en": "Mascara",
          "fr": "Mascara",
          "si": "මස්කරා",
          "ta": "மாஸ்கரா",
          "fi": "Mascara",
          "hi": "मास्कारा",
          "zh": "马斯卡拉",
        },
      ),
      States(
        name: "Médéa",
        translations: {
          "en": "Médéa",
          "fr": "Médéa",
          "si": "මෙඩියා",
          "ta": "மேடியா",
          "fi": "Médéa",
          "hi": "मेदिया",
          "zh": "梅迪亚",
        },
      ),
      States(
        name: "Mila",
        translations: {
          "en": "Mila",
          "fr": "Mila",
          "si": "මිලා",
          "ta": "மிலா",
          "fi": "Mila",
          "hi": "मीला",
          "zh": "米拉",
        },
      ),
      States(
        name: "Mostaganem",
        translations: {
          "en": "Mostaganem",
          "fr": "Mostaganem",
          "si": "මොස්ටගානෙම්",
          "ta": "மோஸ்டகேனெம்",
          "fi": "Mostaganem",
          "hi": "मोस्तागानेम",
          "zh": "莫斯塔加纳姆",
        },
      ),
      States(
        name: "Naama",
        translations: {
          "en": "Naama",
          "fr": "Naama",
          "si": "නාමා",
          "ta": "நாமா",
          "fi": "Naama",
          "hi": "नामा",
          "zh": "纳玛",
        },
      ),
      States(
        name: "Oran",
        translations: {
          "en": "Oran",
          "fr": "Oran",
          "si": "ඔරාන්",
          "ta": "ஓரான்",
          "fi": "Oran",
          "hi": "ओरान",
          "zh": "奥兰",
        },
      ),
      States(
        name: "Ouargla",
        translations: {
          "en": "Ouargla",
          "fr": "Ouargla",
          "si": "ඔවර්ග්ලා",
          "ta": "ஒவார்க்லா",
          "fi": "Ouargla",
          "hi": "वार्ग्ला",
          "zh": "瓦尔格拉",
        },
      ),
      States(
        name: "Ouled Djellal",
        translations: {
          "en": "Ouled Djellal",
          "fr": "Ouled Djellal",
          "si": "ඔලෙඩ් ජෙල්ලාල්",
          "ta": "ஒலேட் ஜெல்லால்",
          "fi": "Ouled Djellal",
          "hi": "ऊलेड जेलाल",
          "zh": "乌勒杰拉勒",
        },
      ),
      States(
        name: "Oum El Bouaghi",
        translations: {
          "en": "Oum El Bouaghi",
          "fr": "Oum El Bouaghi",
          "si": "ඔම් ඇල් බුඅගි",
          "ta": "ஓம் எல் பொவாகி",
          "fi": "Oum El Bouaghi",
          "hi": "ऊम एल बुआगी",
          "zh": "乌姆布瓦基",
        },
      ),
      States(
        name: "Relizane",
        translations: {
          "en": "Relizane",
          "fr": "Relizane",
          "si": "රෙලිසාන්",
          "ta": "ரெலிசான்",
          "fi": "Relizane",
          "hi": "रेलिजान",
          "zh": "瑞利赞",
        },
      ),
      States(
        name: "Saïda",
        translations: {
          "en": "Saïda",
          "fr": "Saïda",
          "si": "සයිඩා",
          "ta": "சாய்டா",
          "fi": "Saïda",
          "hi": "साइदा",
          "zh": "赛达",
        },
      ),
      States(
        name: "Sétif",
        translations: {
          "en": "Sétif",
          "fr": "Sétif",
          "si": "සෙටීෆ්",
          "ta": "சேடிஃப்",
          "fi": "Sétif",
          "hi": "सेटीफ़",
          "zh": "赛蒂夫",
        },
      ),
      States(
        name: "Sidi Bel Abbès",
        translations: {
          "en": "Sidi Bel Abbès",
          "fr": "Sidi Bel Abbès",
          "si": "සිදී බෙල් ඇබ්ස්",
          "ta": "சிடி பெல் அப்பெஸ்",
          "fi": "Sidi Bel Abbès",
          "hi": "सीदी बेल अब्सा",
          "zh": "西迪贝勒阿贝斯",
        },
      ),
      States(
        name: "Skikda",
        translations: {
          "en": "Skikda",
          "fr": "Skikda",
          "si": "ස්කික්ඩා",
          "ta": "ஸ்கிக்டா",
          "fi": "Skikda",
          "hi": "स्किक्डा",
          "zh": "斯基克达",
        },
      ),
      States(
        name: "Souk Ahras",
        translations: {
          "en": "Souk Ahras",
          "fr": "Souk Ahras",
          "si": "සූක් අහ්රාස්",
          "ta": "சௌக் அஹ்ராஸ்",
          "fi": "Souk Ahras",
          "hi": "सूक अहरास",
          "zh": "索克艾哈拉斯",
        },
      ),
      States(
        name: "Tamanghasset",
        translations: {
          "en": "Tamanghasset",
          "fr": "Tamanrasset",
          "si": "ටමන්රස්ට්",
          "ta": "தமன்ரசெட்",
          "fi": "Tamanghasset",
          "hi": "तमन्रसेत",
          "zh": "塔曼拉赛特",
        },
      ),
      States(
        name: "Tébessa",
        translations: {
          "en": "Tébessa",
          "fr": "Tébessa",
          "si": "ටෙබෙසා",
          "ta": "தேபெஸ்ஸா",
          "fi": "Tébessa",
          "hi": "तेबेस्सा",
          "zh": "泰贝萨",
        },
      ),
      States(
        name: "Tiaret",
        translations: {
          "en": "Tiaret",
          "fr": "Tiaret",
          "si": "ටියරෙට්",
          "ta": "டியரெட்",
          "fi": "Tiaret",
          "hi": "तीअरेट",
          "zh": "提亚雷特",
        },
      ),
      States(
        name: "Timimoun",
        translations: {
          "en": "Timimoun",
          "fr": "Timimoun",
          "si": "ටිමිමුන්",
          "ta": "திமிமூன்",
          "fi": "Timimoun",
          "hi": "तिमिमौन",
          "zh": "提米穆恩",
        },
      ),
      States(
        name: "Tindouf",
        translations: {
          "en": "Tindouf",
          "fr": "Tindouf",
          "si": "ටින්ඩුෆ්",
          "ta": "திண்டூஃப்",
          "fi": "Tindouf",
          "hi": "तिंडूफ़",
          "zh": "丁杜夫",
        },
      ),
      States(
        name: "Tipasa",
        translations: {
          "en": "Tipasa",
          "fr": "Tipasa",
          "si": "ටිපාසා",
          "ta": "திபாசா",
          "fi": "Tipasa",
          "hi": "टिपासा",
          "zh": "蒂帕萨",
        },
      ),
      States(
        name: "Tissemsilt",
        translations: {
          "en": "Tissemsilt",
          "fr": "Tissemsilt",
          "si": "ටිස්සෙම්සිල්ට්",
          "ta": "திசெம்சில்ட்",
          "fi": "Tissemsilt",
          "hi": "टिसेमसिल्ट",
          "zh": "蒂瑟姆西尔特",
        },
      ),
      States(
        name: "Tizi Ouzou",
        translations: {
          "en": "Tizi Ouzou",
          "fr": "Tizi Ouzou",
          "si": "ටිසි ඔසු",
          "ta": "திசி ஊசு",
          "fi": "Tizi Ouzou",
          "hi": "तीज़ी ऊज़ू",
          "zh": "蒂茲苏",
        },
      ),
      States(
        name: "Tlemcen",
        translations: {
          "en": "Tlemcen",
          "fr": "Tlemcen",
          "si": "ට්ලෙම්සෙන්",
          "ta": "துலெம்சென்",
          "fi": "Tlemcen",
          "hi": "त्लेम्सेन",
          "zh": "特莱姆森",
        },
      ),
      States(
        name: "Touggourt",
        translations: {
          "en": "Touggourt",
          "fr": "Touggourt",
          "si": "ටුගෝර්ට්",
          "ta": "டௌக்கோர்ட்",
          "fi": "Touggourt",
          "hi": "तूगोर्ट",
          "zh": "圖古爾特",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "American Samoa",
    iso3: "ASM",
    iso2: "AS",
    phoneCode: "1",
    translations: {
      "en": "American Samoa",
      "fr": "Samoa américaines",
      "si": "ඇමරිකානු සැමෝවා",
      "ta": "அமெரிக்க சமோவா",
      "fi": "Amerikan Samoa",
      "hi": "अमेरिकी समोआ",
      "zh": "美属萨摩亚",
    },
    flag: "🇦🇸",
    flagU: "U+1F1E6 U+1F1F8",
    states: [],
  ),
  CountriesStatesModel(
    name: "Andorra",
    iso3: "AND",
    iso2: "AD",
    phoneCode: "376",
    translations: {
      "en": "Andorra",
      "fr": "Andorre",
      "si": "ඇන්ඩෝරා",
      "ta": "அந்தோரா",
      "hi": "अंडोरा",
      "zh": "安道尔",
    },
    flag: "🇦🇩",
    flagU: "U+1F1E6 U+1F1E9",
    states: [
      States(
        name: "Andorra la Vella",
        translations: {
          "en": "Andorra la Vella",
          "fr": "Andorre-la-Vieille",
          "si": "ඇන්ඩොරා ලා වෙල්ලා",
          "ta": "அன்டோரா லா வெல்லா",
          "fi": "Andorra la Vella",
          "hi": "अंडोरा ला वेला",
          "zh": "安道尔城",
        },
      ),
      States(
        name: "Canillo",
        translations: {
          "en": "Canillo",
          "fr": "Canillo",
          "si": "කැනිල්ලෝ",
          "ta": "கனில்லோ",
          "fi": "Canillo",
          "hi": "कानिल्लो",
          "zh": "卡尼略",
        },
      ),
      States(
        name: "Encamp",
        translations: {
          "en": "Encamp",
          "fr": "Camper",
          "si": "වැහිදුව",
          "ta": "இருக்கோள்",
          "fi": "Leiri",
          "hi": "शिविर",
          "zh": "宿营",
        },
      ),
      States(
        name: "Escaldes-Engordany",
        translations: {
          "en": "Escaldes-Engordany",
          "fr": "Escaldes-Engordany",
          "si": "එස්කල්ඩෙස්-එන්ගෝර්ඩෑනි",
          "ta": "எஸ்கால்டிஸ்-எங்கார்டனி",
          "fi": "Escaldes-Engordany",
          "hi": "एस्काल्डेस-एन्गोर्डनी",
          "zh": "埃斯卡尔德斯-恩戈尔达尼",
        },
      ),
      States(
        name: "La Massana",
        translations: {
          "en": "La Massana",
          "fr": "La Massana",
          "si": "ලා මසානා",
          "ta": "லா மஸ்ஸானா",
          "fi": "La Massana",
          "hi": "ला मासाना",
          "zh": "拉马萨纳",
        },
      ),
      States(
        name: "Ordino",
        translations: {
          "en": "Ordino",
          "fr": "Ordino",
          "si": "ඔර්ඩිනෝ",
          "ta": "ஓர்டினோ",
          "fi": "Ordino",
          "hi": "ओर्डीनो",
          "zh": "奥尔迪诺",
        },
      ),
      States(
        name: "Sant Julià de Lòria",
        translations: {
          "en": "Sant Julià de Lòria",
          "fr": "Sant Julià de Lòria",
          "si": "Sant Julià de Lòria",
          "ta": "சாண்ட் ஜூலியா டே லோரியா",
          "fi": "Sant Julià de Lòria",
          "hi": "सैंट जूलिया दे लोरिया",
          "zh": "圣胡利娅德洛里亚",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Angola",
    iso3: "AGO",
    iso2: "AO",
    phoneCode: "244",
    translations: {
      "en": "Angola",
      "fr": "Angola",
      "si": "ඇන්ගෝලාව",
      "ta": "அங்கோலா",
      "hi": "अंगोला",
      "zh": "安哥拉",
    },
    flag: "🇦🇴",
    flagU: "U+1F1E6 U+1F1F4",
    states: [
      States(
        name: "Bengo Province",
        translations: {
          "en": "Bengo Province",
          "fr": "Province de Bengo",
          "si": "බෙන්ගෝ පළාත",
          "ta": "பெங்கோ மாகாணம்",
          "fi": "Bengon maakunta",
          "hi": "बेंगो प्रांत",
          "zh": "本戈省",
        },
      ),
      States(
        name: "Benguela Province",
        translations: {
          "en": "Benguela Province",
          "fr": "Province de Benguela",
          "si": "බෙන්ගුලා පළාත",
          "ta": "பெங்குவேலா மாகாணம்",
          "fi": "Benguelan maakunta",
          "hi": "बेंग्वेला प्रांत",
          "zh": "本格拉省",
        },
      ),
      States(
        name: "Bié Province",
        translations: {
          "en": "Bié Province",
          "fr": "Province de Bié",
          "si": "බී පළාත",
          "ta": "பீ மாகாணம்",
          "fi": "Bién maakunta",
          "hi": "बीए प्रांत",
          "zh": "比耶省",
        },
      ),
      States(
        name: "Cabinda Province",
        translations: {
          "en": "Cabinda Province",
          "fr": "Province de Cabinda",
          "si": "කබින්ඩා පළාත",
          "ta": "கபின்டா மாகாணம்",
          "fi": "Cabindan maakunta",
          "hi": "काबिंदा प्रांत",
          "zh": "卡宾达省",
        },
      ),
      States(
        name: "Cuando Cubango Province",
        translations: {
          "en": "Cuando Cubango Province",
          "fr": "Province de Cuando Cubango",
          "si": "කුවාන්ඩෝ කුබැන්ගෝ පළාත",
          "ta": "குவாண்டோ குபாங்கோ மாகாணம்",
          "fi": "Cuando Cubangon maakunta",
          "hi": "क्वांडो कुबांगो प्रांत",
          "zh": "昆多·库邦戈省",
        },
      ),
      States(
        name: "Cuanza Norte Province",
        translations: {
          "en": "Cuanza Norte Province",
          "fr": "Province de Cuanza Norte",
          "si": "කුවන්සා නෝර්ට් පළාත",
          "ta": "குவான்சா நார்தே மாகாணம்",
          "fi": "Cuanza Norten maakunta",
          "hi": "क्वांज़ा नोर्ते प्रांत",
          "zh": "库安扎北省",
        },
      ),
      States(
        name: "Cuanza Sul",
        translations: {
          "en": "Cuanza Sul",
          "fr": "Cuanza Sul",
          "si": "කුවන්සා සල්",
          "ta": "குவான்சா சல்",
          "fi": "Cuanza Sul",
          "hi": "क्वान्ज़ा सुल",
          "zh": "宽扎南",
        },
      ),
      States(
        name: "Cunene Province",
        translations: {
          "en": "Cunene Province",
          "fr": "Province de Cunene",
          "si": "කුනේනේ පළාත",
          "ta": "குநேனே மாகாணம்",
          "fi": "Cunenen maakunta",
          "hi": "कुनेने प्रांत",
          "zh": "库内内省",
        },
      ),
      States(
        name: "Huambo Province",
        translations: {
          "en": "Huambo Province",
          "fr": "Province de Huambo",
          "si": "හුඅම්බෝ පළාත",
          "ta": "ஹுவாம்போ மாகாணம்ஹுவாம்போ மாகாணம்",
          "fi": "Huambon maakunta",
          "hi": "ह्वाम्बो प्रांत",
          "zh": "省",
        },
      ),
      States(
        name: "Huíla Province",
        translations: {
          "en": "Huíla Province",
          "fr": "Province de Huíla",
          "si": "හුඅයිලා පළාත",
          "ta": "ஹுவிலா மாகாணம்",
          "fi": "Huílan maakunta",
          "hi": "हुइला प्रांत",
          "zh": "伊拉省",
        },
      ),
      States(
        name: "Luanda Province",
        translations: {
          "en": "Luanda Province",
          "fr": "Province de Luanda",
          "si": "ලුඅන්ඩා පළාත",
          "ta": "லுவாண்டா மாகாணம்",
          "fi": "Luandan maakunta",
          "hi": "लुआंडा प्रांत",
          "zh": "省",
        },
      ),
      States(
        name: "Lunda Norte Province",
        translations: {
          "en": "Lunda Norte Province",
          "fr": "Province de Lunda Norte",
          "si": "ලුන්ඩා නෝර්ට් පළාත",
          "ta": "லுண்டா நோர்த்தே",
          "fi": "Lunda Norten maakunta",
          "hi": "लुंडा नॉर्ट प्रांत",
          "zh": "隆达北省",
        },
      ),
      States(
        name: "Lunda Sul Province",
        translations: {
          "en": "Lunda Sul Province",
          "fr": "Province de Lunda Sul",
          "si": "ලුන්ඩා සල් පළාත",
          "ta": "லுண்டா சல் மாகாணம்",
          "fi": "Lunda Sulen maakunta",
          "hi": "लुंडा सुल प्रांत",
          "zh": "隆达南省",
        },
      ),
      States(
        name: "Malanje Province",
        translations: {
          "en": "Malanje Province",
          "fr": "Province de Malanje",
          "si": "මලන්ජේ පළාත",
          "ta": "மலஞ்சே மாகாணம்",
          "fi": "Malanjen maakunta",
          "hi": "मलांजे प्रांत",
          "zh": "马兰热省",
        },
      ),
      States(
        name: "Moxico Province",
        translations: {
          "en": "Moxico Province",
          "fr": "Province de Moxico",
          "si": "මොක්සිකෝ පළාත",
          "ta": "மோசிக்கோ மாகாணம்",
          "fi": "Moxicon maakunta",
          "hi": "मोक्सिको प्रांत",
          "zh": "莫希科省",
        },
      ),
      States(
        name: "Uíge Province",
        translations: {
          "en": "Uíge Province",
          "fr": "Province de Uíge",
          "si": "උයිගෝ පළාත",
          "ta": "உயிக் மாகாணம்",
          "fi": "Uígen maakunta",
          "hi": "यूइज प्रांत",
          "zh": "乌热热省",
        },
      ),
      States(
        name: "Zaire Province",
        translations: {
          "en": "Zaire Province",
          "fr": "Province de Zaire",
          "si": "සායිර් පළාත",
          "ta": "சாயர் மாகாணம்",
          "fi": "Zairen maakunta",
          "hi": "जायर प्रांत",
          "zh": "扎伊尔省",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Anguilla",
    iso3: "AIA",
    iso2: "AI",
    phoneCode: "1",
    translations: {
      "en": "Anguilla",
      "fr": "Anguilla",
      "si": "ඇන්ගුයිලා",
      "ta": "அங்கியுலா",
      "hi": "अंगुइला",
      "zh": "安圭拉",
    },
    flag: "🇦🇮",
    flagU: "U+1F1E6 U+1F1EE",
    states: [],
  ),
  CountriesStatesModel(
    name: "Antigua & Barbuda",
    iso3: "ATG",
    iso2: "AG",
    phoneCode: "1",
    translations: {
      "en": "Antigua & Barbuda",
      "fr": "Antigua-et-Barbuda",
      "si": "ඇන්ටිගුවා සහ බාබුඩා",
      "ta": "அன்டிகுவாவும் பர்பியுடாவும்",
      "fi": "Antigua ja Barbuda",
      "hi": "अण्टीगुआ और बारबूडा",
      "zh": "安提瓜和巴布达",
    },
    flag: "🇦🇬",
    flagU: "U+1F1E6 U+1F1EC",
    states: [
      States(
        name: "Barbuda",
        translations: {
          "en": "Barbuda",
          "fr": "Barbuda",
          "si": "බාර්බූඩා",
          "ta": "பார்புடா",
          "fi": "Barbuda",
          "hi": "बार्बूडाा",
          "zh": "巴布达",
        },
      ),
      States(
        name: "Redonda",
        translations: {
          "en": "Redonda",
          "fr": "Redonda",
          "si": "රෙඩොන්ඩා",
          "ta": "ரெடோண்டா",
          "fi": "Redonda",
          "hi": "रेडोंडा",
          "zh": "雷东达",
        },
      ),
      States(
        name: "Saint George Parish",
        translations: {
          "en": "Saint George Parish",
          "fr": "Paroisse de Saint-George",
          "si": "ශාන්ත ජෝජ් පරිශ්වය",
          "ta": "செயிண்ட் ஜோர்ஜ் பாரிஷ்",
          "fi": "Pyhän Yrjön seurakunta",
          "hi": "सेंट जॉर्ज पैरिश",
          "zh": "圣乔治教区",
        },
      ),
      States(
        name: "Saint John Parish",
        translations: {
          "en": "Saint John Parish",
          "fr": "Paroisse de Saint-John",
          "si": "ශාන්ත ජොන් පරිශ්වය",
          "ta": "செயிண்ட் ஜான் பாரிஷ்",
          "fi": "Pyhän Johanneksen seurakunta",
          "hi": "सेंट जॉन पैरिश",
          "zh": "圣约翰教区",
        },
      ),
      States(
        name: "Saint Mary Parish",
        translations: {
          "en": "Saint Mary Parish",
          "fr": "Paroisse de Sainte-Marie",
          "si": "ශාන්ත මේරි පරිශ්වය",
          "ta": "செயிண்ட் மேரி பாரிஷ்",
          "fi": "Pyhän Marian seurakunta",
          "hi": "सेंट मेरी पैरिश",
          "zh": "圣玛丽教区",
        },
      ),
      States(
        name: "Saint Paul Parish",
        translations: {
          "en": "Saint Paul Parish",
          "fr": "Paroisse de Saint-Paul",
          "si": "ශාන්ත පෝල් පරිශ්වය",
          "ta": "செயிண்ட் பால் பாரிஷ்",
          "fi": "Pyhän Paavalin seurakunta",
          "hi": "सेंट पॉल पैरिश",
          "zh": "圣保罗教区",
        },
      ),
      States(
        name: "Saint Peter Parish",
        translations: {
          "en": "Saint Peter Parish",
          "fr": "Paroisse de Saint-Pierre",
          "si": "ශාන්ත පීටර් පරිශ්වය",
          "ta": "செயிண்ட் பீட்டர் பாரிஷ்",
          "fi": "Pyhän Pietarin seurakunta",
          "hi": "सेंट पीटर पैरिश",
          "zh": "圣彼得教区",
        },
      ),
      States(
        name: "Saint Philip Parish",
        translations: {
          "en": "Saint Philip Parish",
          "fr": "Paroisse de Saint-Philippe",
          "si": "ශාන්ත පිලිප් පරිශ්වය",
          "ta": "செயிண்ட் பிலிப் பாரிஷ்",
          "fi": "Pyhän Filipin seurakunta",
          "hi": "सेंट फिलिप पैरिश",
          "zh": "圣菲利普教区",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Argentina",
    iso3: "ARG",
    iso2: "AR",
    phoneCode: "54",
    translations: {
      "en": "Argentina",
      "fr": "Argentine",
      "si": "ආජන්ටිනාව",
      "ta": "அர்கெந்தீனா",
      "fi": "Argentiina",
      "hi": "अर्जेण्टीना",
      "zh": "阿根廷",
    },
    flag: "🇦🇷",
    flagU: "U+1F1E6 U+1F1F7",
    states: [
      States(
        name: "Buenos Aires",
        translations: {
          "en": "Buenos Aires",
          "fr": "Buenos Aires",
          "si": "බුනොස් එයර්ස්",
          "ta": "புவெனஸ் ஏர்ஸ்",
          "fi": "Buenos Aires",
          "hi": "ब्यूनस आयर्स",
          "zh": "布宜诺斯艾利斯",
        },
      ),
      States(
        name: "Catamarca",
        translations: {
          "en": "Catamarca",
          "fr": "Catamarca",
          "si": "කැටමර්කා",
          "ta": "கடாமார்கா",
          "fi": "Catamarca",
          "hi": "कैटामार्का",
          "zh": "卡塔马卡",
        },
      ),
      States(
        name: "Chaco",
        translations: {
          "en": "Chaco",
          "fr": "Chaco",
          "si": "චාකෝ",
          "ta": "சாக்கோ",
          "fi": "Chaco",
          "hi": "चाको",
          "zh": "查科",
        },
      ),
      States(
        name: "Chubut",
        translations: {
          "en": "Chubut",
          "fr": "Chubut",
          "si": "චුබුට්",
          "ta": "சுபுட்",
          "fi": "Chubut",
          "hi": "चुबूट",
          "zh": "丘布特",
        },
      ),
      States(
        name: "Ciudad Autónoma de Buenos Aires",
        translations: {
          "en": "Ciudad Autónoma de Buenos Aires",
          "fr": "Ville autonome de Buenos Aires",
          "si": "බුනොස් එයිර්ස්වේ ස්වයංගන්ත නගරය",
          "ta": "புவெனஸ் ஐரிஸின் சுதந்திர நகரம்",
          "fi": "Buenos Airesin autonomiasema",
          "hi": "स्वायत्त शहर ब्यूनस आयरेस",
          "zh": "布宜诺斯艾利斯自治市",
        },
      ),
      States(
        name: "Córdoba",
        translations: {
          "en": "Córdoba",
          "fr": "Córdoba",
          "si": "කොඩොබා",
          "ta": "கோர்டோபா",
          "fi": "Córdoba",
          "hi": "कोर्डोबा",
          "zh": "科尔多瓦",
        },
      ),
      States(
        name: "Corrientes",
        translations: {
          "en": "Corrientes",
          "fr": "Corrientes",
          "si": "කොරියෙන්ට්ස්",
          "ta": "கரியெண்டெஸ்",
          "fi": "Corrientes",
          "hi": "कोरिएंटेस",
          "zh": "科连特斯",
        },
      ),
      States(
        name: "Entre Ríos",
        translations: {
          "en": "Entre Ríos",
          "fr": "Entre Ríos",
          "si": "එන්ට්රි රියෝස්",
          "ta": "என்ட்ரே ரியோஸ்",
          "fi": "Entre Ríos",
          "hi": "एंत्रे रिओस",
          "zh": "恩特雷里奥斯",
        },
      ),
      States(
        name: "Formosa",
        translations: {
          "en": "Formosa",
          "fr": "Formosa",
          "si": "ෆෝමෝසා",
          "ta": "ஃபார்மோஸா",
          "fi": "Formosa",
          "hi": "फ़ोर्मोसा",
          "zh": "佛莫萨",
        },
      ),
      States(
        name: "Jujuy",
        translations: {
          "en": "Jujuy",
          "fr": "Jujuy",
          "si": "ජුජුයි",
          "ta": "ஜுஜுய்",
          "fi": "Jujuy",
          "hi": "जुजुई",
          "zh": "胡胡伊",
        },
      ),
      States(
        name: "La Pampa",
        translations: {
          "en": "La Pampa",
          "fr": "La Pampa",
          "si": "ලා පැම්පා",
          "ta": "லா பம்பா",
          "fi": "La Pampa",
          "hi": "ला पाम्पा",
          "zh": "拉潘帕",
        },
      ),
      States(
        name: "La Rioja",
        translations: {
          "en": "La Rioja",
          "fr": "La Rioja",
          "si": "ලා රියෝජා",
          "ta": "லா ரியோஜா",
          "fi": "La Rioja",
          "hi": "ला रिओजा",
          "zh": "拉里奥哈",
        },
      ),
      States(
        name: "Mendoza",
        translations: {
          "en": "Mendoza",
          "fr": "La Rioja",
          "si": "ලා රියෝජා",
          "ta": "லா ரியோஜா",
          "fi": "La Rioja",
          "hi": "ला रिओजा",
          "zh": "拉里奥哈",
        },
      ),
      States(
        name: "Misiones",
        translations: {
          "en": "Misiones",
          "fr": "Misiones",
          "si": "මිසියෝනේස්",
          "ta": "மிசியோன்ஸ்",
          "fi": "Misiones",
          "hi": "मिसिओनेस",
          "zh": "密西奥内斯",
        },
      ),
      States(
        name: "Neuquén",
        translations: {
          "en": "Neuquén",
          "fr": "Neuquén",
          "si": "නෙව්කුට්න්",
          "ta": "நியூகுவென்",
          "fi": "Neuquén",
          "hi": "नेउकेन",
          "zh": "内乌肯",
        },
      ),
      States(
        name: "Río Negro",
        translations: {
          "en": "Río Negro",
          "fr": "Río Negro",
          "si": "රීයෝ නිග්‍රෝ",
          "ta": "ரியோ நெக்ரோ",
          "fi": "Río Negro",
          "hi": "रियो नेग्रो",
          "zh": "里奥内格罗",
        },
      ),
      States(
        name: "Salta",
        translations: {
          "en": "Salta",
          "fr": "Salta",
          "si": "සාල්ටා",
          "ta": "சால்டா",
          "fi": "Salta",
          "hi": "साल्टा",
          "zh": "萨尔塔",
        },
      ),
      States(
        name: "San Juan",
        translations: {
          "en": "San Juan",
          "fr": "San Juan",
          "si": "සෑන් ජුවානය",
          "ta": "சான் ஜுவான்",
          "fi": "Salta",
          "hi": "San Juan",
          "zh": "圣胡安",
        },
      ),
      States(
        name: "San Luis",
        translations: {
          "en": "San Luis",
          "fr": "San Luis",
          "si": "සැන් ලුයිස්",
          "ta": "சான் லூயிஸ்",
          "fi": "San Luis",
          "hi": "सान लुइस",
          "zh": "圣路易斯",
        },
      ),
      States(
        name: "Santa Cruz",
        translations: {
          "en": "Santa Cruz",
          "fr": "Santa Cruz",
          "si": "සැන්ටා කුරුස්",
          "ta": "சாந்தா கிருஸ்",
          "fi": "Santa Cruz",
          "hi": "सांता क्रुज़",
          "zh": "圣克鲁斯",
        },
      ),
      States(
        name: "Santa Fe",
        translations: {
          "en": "Santa Fe",
          "fr": "Santa Fe",
          "si": "සැන්ටා ෆේ",
          "ta": "சாந்தா ஃபே",
          "fi": "Santa Fe",
          "hi": "सांता फे",
          "zh": "圣菲",
        },
      ),
      States(
        name: "Santiago del Estero",
        translations: {
          "en": "Santiago del Estero",
          "fr": "Santiago del Estero",
          "si": "සන්ටියාගො ඩෙල් එස්ටෙරො",
          "ta": "சாந்தியாகோ டெல் எஸ்டேரோ",
          "fi": "Santiago del Estero",
          "hi": "सांतियागो डेल एस्टेरो",
          "zh": "圣地亚哥-德尔埃斯特罗",
        },
      ),
      States(
        name: "Tierra del Fuego",
        translations: {
          "en": "Tierra del Fuego",
          "fr": "Terre de Feu",
          "si": "ටියරා ඩෙල් ෆුඑගෝ",
          "ta": "தியேரா டெல் ஃபுயூகோ",
          "fi": "Tuli- ja jäämaa",
          "hi": "तिएरा डेल फ्यूगो",
          "zh": "火地岛",
        },
      ),
      States(
        name: "Tucumán",
        translations: {
          "en": "Tucumán",
          "fr": "Tucumán",
          "si": "ටුකුමාන්",
          "ta": "டுகுமான்",
          "fi": "Tucumán",
          "hi": "टुकुमान",
          "zh": "图库曼",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Armenia",
    iso3: "ARM",
    iso2: "AM",
    phoneCode: "374",
    translations: {
      "en": "Armenia",
      "fr": "Arménie",
      "si": "ආර්මේනියාව",
      "ta": "ஆர்மீனியா",
      "hi": "आर्मीनिया",
      "zh": "亚美尼亚",
    },
    flag: "🇦🇲",
    flagU: "U+1F1E6 U+1F1F2",
    states: [
      States(
        name: "Aragatsotn Region",
        translations: {
          "en": "Aragatsotn Region",
          "fr": "Région d'Aragatsotn",
          "si": "අරගට්සොට්න් පළාත",
          "ta": "அரகத்சோட்ன் பகுதி",
          "fi": "Aragatsotnin alue",
          "hi": "अरगात्सोट्न क्षेत्र",
          "zh": "阿拉加特索特恩区",
        },
      ),
      States(
        name: "Ararat Province",
        translations: {
          "en": "Ararat Province",
          "fr": "Province d'Ararat",
          "si": "අරරාට් පළාත",
          "ta": "அராராட் மாகாணம்",
          "fi": "Araratin maakunta",
          "hi": "अराराट प्रांत",
          "zh": "阿勒拉特省",
        },
      ),
      States(
        name: "Armavir Region",
        translations: {
          "en": "Armavir Region",
          "fr": "Région d'Armavir",
          "si": "ආර්මාවිර් පළාත",
          "ta": "ஆர்மவீர் பகுதி",
          "fi": "Armavirin alue",
          "hi": "अर्मावीर क्षेत्र",
          "zh": "阿尔马维尔区",
        },
      ),
      States(
        name: "Gegharkunik Province",
        translations: {
          "en": "Gegharkunik Province",
          "fr": "Province de Gegharkunik",
          "si": "ගෙග්හර්කුනික් පළාත",
          "ta": "கேகர்குனிக் மாகாணம்",
          "fi": "Gegharkunikin maakunta",
          "hi": "गेघरकुनिक प्रांत",
          "zh": "格加尔库尼克省",
        },
      ),
      States(
        name: "Kotayk Region",
        translations: {
          "en": "Kotayk Region",
          "fr": "Région de Kotayk",
          "si": "කොටයික් පළාත",
          "ta": "கொடாய்க் பகுதி",
          "fi": "Kotaykin alue",
          "hi": "कोटायक क्षेत्र",
          "zh": "科泰克大区",
        },
      ),
      States(
        name: "Lori Region",
        translations: {
          "en": "Lori Region",
          "fr": "Région de Lori",
          "si": "ලෝරි පළාත",
          "ta": "லோரி பகுதி",
          "fi": "Lorin alue",
          "hi": "लोरी क्षेत्र",
          "zh": "洛里大区",
        },
      ),
      States(
        name: "Shirak Region",
        translations: {
          "en": "Shirak Region",
          "fr": "Région de Shirak",
          "si": "ශිරාක් පළාත",
          "ta": "ஷிராக் பகுதி",
          "fi": "Shirakin alue",
          "hi": "शिरक क्षेत्र",
          "zh": "希拉克大区",
        },
      ),
      States(
        name: "Syunik Province",
        translations: {
          "en": "Syunik Province",
          "fr": "Province de Syunik",
          "si": "සුනික් පළාත",
          "ta": "சியுனிக் மாகாணம்",
          "fi": "Syunikin maakunta",
          "hi": "स्युनिक प्रांत",
          "zh": "苏尼克省",
        },
      ),
      States(
        name: "Tavush Region",
        translations: {
          "en": "Tavush Region",
          "fr": "Région de Tavush",
          "si": "ටවුෂ් පළාත",
          "ta": "தாவுஷ் பகுதி",
          "fi": "Tavushin alue",
          "hi": "तावुष प्रांत",
          "zh": "塔武什大区",
        },
      ),
      States(
        name: "Vayots Dzor Region",
        translations: {
          "en": "Vayots Dzor Region",
          "fr": "Région de Vayots Dzor",
          "si": "වයොට්ස් ද්සොර් පළාත",
          "ta": "வாயோட்ஸ் த்ஜோர் பகுதி",
          "fi": "Vayots Dzorin alue",
          "hi": "वायोट्स डजोर प्रांत",
          "zh": "瓦约茨·佐尔大区",
        },
      ),
      States(
        name: "Yerevan",
        translations: {
          "en": "Yerevan",
          "fr": "Erevan",
          "si": "යෙරෙවානය",
          "ta": "ஏரிவான்",
          "fi": "Jerevan",
          "hi": "येरेवान",
          "zh": "埃里温",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Aruba",
    iso3: "ABW",
    iso2: "AW",
    phoneCode: "297",
    translations: {
      "en": "Aruba",
      "fr": "Aruba",
      "si": "අරුබා",
      "ta": "அரூபா",
      "hi": "अरूबा",
      "zh": "阿鲁巴",
    },
    flag: "🇦🇼",
    flagU: "U+1F1E6 U+1F1FC",
    states: [],
  ),
  CountriesStatesModel(
    name: "Ascension Island",
    iso3: "ASC",
    iso2: "AC",
    phoneCode: "247",
    translations: {
      "en": "Ascension Island",
      "fr": "Île de l'Ascension",
      "si": "ඇසෙන්ෂන් දූපත",
      "ta": "அசென்சன் தீவு",
      "hi": "असेंशियन द्वीप",
      "zh": "阿森松岛",
    },
    flag: "🇦🇨",
    flagU: "U+1F1E6 U+1F1E8",
    states: [],
  ),
  CountriesStatesModel(
    name: "Australia",
    iso3: "AUS",
    iso2: "AU",
    phoneCode: "61",
    translations: {
      "en": "Australia",
      "fr": "Australie",
      "si": "ඕස්ට්‍රේලියාව",
      "ta": "ஆத்திரேலியா",
      "hi": "ऑस्ट्रेलिया",
      "zh": "澳大利亚",
    },
    flag: "🇦🇺",
    flagU: "U+1F1E6 U+1F1FA",
    states: [
      States(
        name: "Australian Capital Territory",
        translations: {
          "en": "Australian Capital Territory",
          "fr": "Territoire de la capitale australienne",
          "si": "ඕස්ට්‍රේලියානු ප්‍රාන්තයේ කළමනාකාරිත්වය",
          "ta": "ஆஸ்திரேலிய கைபிடல் மாகாணம்",
          "fi": "Australian pääkaupunkiterritorio",
          "hi": "ऑस्ट्रेलियाई कैपिटल टेरिटरी",
          "zh": "澳大利亚首都领地",
        },
      ),
      States(
        name: "New South Wales",
        translations: {
          "en": "New South Wales",
          "fr": "Nouvelle-Galles du Sud",
          "si": "නිව් සමුද්‍රවේශය",
          "ta": "புதிய தென் வேல்ஸ்",
          "fi": "Uusi Etelä-Wales",
          "hi": "न्यू साउथ वेल्स",
          "zh": "新南威爾士州",
        },
      ),
      States(
        name: "Northern Territory",
        translations: {
          "en": "Northern Territory",
          "fr": "Territoire du Nord",
          "si": "උතුරු කලාපය",
          "ta": "வட மாகாணம்",
          "fi": "Pohjoisterritorio",
          "hi": "उत्तरी क्षेत्र",
          "zh": "北领地",
        },
      ),
      States(
        name: "Queensland",
        translations: {
          "en": "Queensland",
          "fr": "Queensland",
          "si": "ක්වීන්ස්ලන්තය",
          "ta": "குவீன்ஸ்லாந்து",
          "fi": "Queensland",
          "hi": "குவீன்ஸ்லாந்து",
          "zh": "昆士兰",
        },
      ),
      States(
        name: "South Australia",
        translations: {
          "en": "South Australia",
          "fr": "Australie-Méridionale",
          "si": "දකුණු ඔස්ට්‍රේලියාව",
          "ta": "தென் ஆஸ்திரேலியா",
          "fi": "Etelä-Australia",
          "hi": "दक्षिण आस्ट्रेलिया",
          "zh": "南澳大利亚州",
        },
      ),
      States(
        name: "Tasmania",
        translations: {
          "en": "Tasmania",
          "fr": "Tasmanie",
          "si": "ටැස්මේනියාව",
          "ta": "டாஸ்மேனியா",
          "fi": "Tasmania",
          "hi": "तस्मानिया",
          "zh": "南澳大利亚州",
        },
      ),
      States(
        name: "Victoria",
        translations: {
          "en": "Victoria",
          "fr": "Victoria",
          "si": "වික්ටෝරියාව",
          "ta": "விக்டோரியா",
          "fi": "Victoria",
          "hi": "विक्टोरिया",
          "zh": "维多利亚",
        },
      ),
      States(
        name: "Western Australia",
        translations: {
          "en": "Western Australia",
          "fr": "Tasmanie",
          "si": "ටැස්මේනියාව",
          "ta": "டாஸ்மேனியா",
          "fi": "Tasmania",
          "hi": "तस्मानिया",
          "zh": "南澳大利亚州",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Austria",
    iso3: "AUT",
    iso2: "AT",
    phoneCode: "43",
    flag: "🇦🇹",
    flagU: "U+1F1E6 U+1F1F9",
    translations: {
      "en": "Austria",
      "fr": "Autriche",
      "si": "ඔස්ට්‍රියාව",
      "ta": "ஆஸ்திரியா",
      "fi": "Itävalta",
      "hi": "ऑस्ट्रिया",
      "zh": "奥地利",
    },
    states: [
      States(
        name: "Burgenland",
        translations: {
          "en": "Burgenland",
          "fr": "Burgenland",
          "si": "බර්ගෙන්ලන්තය",
          "ta": "பர்கென்லாந்து",
          "fi": "Burgenland",
          "hi": "बुर्गेनलैंड",
          "zh": "布尔根兰州",
        },
      ),
      States(
        name: "Carinthia",
        translations: {
          "en": "Carinthia",
          "fr": "Carinthie",
          "si": "කැරින්තියාව",
          "ta": "கேரிந்தியா",
          "fi": "Kärnten",
          "hi": "कैरिंथिया",
          "zh": "克恩顿州",
        },
      ),
      States(
        name: "Lower Austria",
        translations: {
          "en": "Lower Austria",
          "fr": "Basse-Autriche",
          "si": "පහල ඔස්ට්‍රියාව",
          "ta": "குறைந்த ஆஸ்திரியா",
          "fi": "Ala-Itävalta",
          "hi": "निचला ऑस्ट्रिया ा",
          "zh": "下奥地利州",
        },
      ),
      States(
        name: "Salzburg",
        translations: {
          "en": "Salzburg",
          "fr": "Salzbourg",
          "si": "සැල්ස්බර්ග්",
          "ta": "சால்ஸ்பர்க்",
          "fi": "Salzburg",
          "hi": "சால்ஸ்பர்க்",
          "zh": "萨尔茨堡",
        },
      ),
      States(
        name: "Styria",
        translations: {
          "en": "Styria",
          "fr": "Styrie",
          "si": "ස්ටිය්රියාව",
          "ta": "ஸ்டீரியா",
          "fi": "Steiermark",
          "hi": "स्टायरिया",
          "zh": "施蒂利亚州",
        },
      ),
      States(
        name: "Tyrol",
        translations: {
          "en": "Tyrol",
          "fr": "Tyrol",
          "si": "ටයිරොල්",
          "ta": "தைரால்",
          "fi": "Tirol",
          "hi": "तिरोल",
          "zh": "蒂罗尔州",
        },
      ),
      States(
        name: "Upper Austria",
        translations: {
          "en": "Upper Austria",
          "fr": "Haute-AutricheHaute-Autriche",
          "si": "උඩ ඔස්ට්‍රියාව",
          "ta": "மேற்கு ஆஸ்திரியா",
          "fi": "Ylä-Itävalta",
          "hi": "अपर ऑस्ट्रिया",
          "zh": "上奥地利州",
        },
      ),
      States(
        name: "Vienna",
        translations: {
          "en": "Vienna",
          "fr": "Vienne",
          "si": "වියානා",
          "ta": "வியன்னா",
          "fi": "Wien",
          "hi": "वियना",
          "zh": "维也纳",
        },
      ),
      States(
        name: "Vorarlberg",
        translations: {
          "en": "Vorarlberg",
          "fr": "Vorarlberg",
          "si": "වොරල්බර්ග්",
          "ta": "வொரார்ல்பெர்க்",
          "fi": "Vorarlberg",
          "hi": "वोरार्लबर्ग",
          "zh": "福拉尔贝格州",
        },
      ),
    ],
  ),
];
