import 'package:playkosmos_v3/models/countries_states_model.dart';

const List<CountriesStatesModel> kCsCpvCuw = [
  CountriesStatesModel(
    name: "Cape Verde",
    iso3: "CPV",
    iso2: "CV",
    phoneCode: "238",
    translations: {
      "en": "Cape Verde",
      "fr": "Cap-Vert",
      "si": "කේප් වර්ඩ්",
      "ta": "கேப் வர்டி",
      "fi": "Kap Verde",
      "hi": "केप वर्दे",
      "zh": "佛得角",
    },
    flag: "🇨🇻",
    flagU: "U+1F1E8 U+1F1FB",
    states: [
      States(
        name: "Barlavento Islands",
        translations: {
          "en": "Barlavento Islands",
          "fr": "Îles Barlavento",
          "si": "බාර්ලාවෙන්ටෝ දුපත්",
          "ta": "பர்லவெண்டோ தீவுகள்",
          "fi": "Barlavento-saaret",
          "hi": "बारलावेंटो द्वीप समूह",
          "zh": "巴拉文托群岛",
        },
      ),
      States(
        name: "Boa Vista",
        translations: {
          "en": "Boa Vista",
          "fr": "Boa Vista",
          "si": "බෝඇ විස්ටා",
          "ta": "போவா விஸ்டா",
          "fi": "Boa Vista",
          "hi": "बोआ विस्ता",
          "zh": "博阿维斯塔",
        },
      ),
      States(
        name: "Brava",
        translations: {
          "en": "Brava",
          "fr": "Brava",
          "si": "බ්‍රාවා",
          "ta": "பிராவா",
          "fi": "Brava",
          "hi": "ब्रावा",
          "zh": "布拉瓦",
        },
      ),
      States(
        name: "Maio Municipality",
        translations: {
          "en": "Maio Municipality",
          "fr": "Municipalité de Maio",
          "si": "මායිඔ ප්‍රාන්තය",
          "ta": "மாயோ காவலர்",
          "fi": "Maion kunta",
          "hi": "माइओ नगरपालिका",
          "zh": "马约市",
        },
      ),
      States(
        name: "Mosteiros",
        translations: {
          "en": "Mosteiros",
          "fr": "Mosteiros",
          "si": "මොස්ටෙයිරෝස්",
          "ta": "மோஸ்டெய்ரோஸ்",
          "fi": "Mosteiro",
          "hi": "मोस्तेरोस",
          "zh": "莫斯泰罗什",
        },
      ),
      States(
        name: "Paul",
        translations: {
          "en": "Paul",
          "fr": "Paul",
          "si": "පෝල්",
          "ta": "பால்",
          "fi": "Paavali",
          "hi": "पॉल",
          "zh": "保罗",
        },
      ),
      States(
        name: "Porto Novo",
        translations: {
          "en": "Porto Novo",
          "fr": "Porto Novo",
          "si": "පොර්ටෝ නොවෝ",
          "ta": "போர்ட்டோ நோவோ",
          "fi": "Porto Novo",
          "hi": "पोर्टो नोवो",
          "zh": "诺沃港",
        },
      ),
      States(
        name: "Praia",
        translations: {
          "en": "Praia",
          "fr": "Praia",
          "si": "ප්‍රයා",
          "ta": "ப்ராயா",
          "fi": "Praia",
          "hi": "प्रायाो",
          "zh": "普拉亚",
        },
      ),
      States(
        name: "Ribeira Brava Municipality",
        translations: {
          "en": "Ribeira Brava Municipality",
          "fr": "Municipalité de Ribeira Brava",
          "si": "රිබෙයිරා බ්‍රව නගර ප්‍රාන්තය",
          "ta": "ரிபேரா பிராவா நகர பகுதி",
          "fi": "Ribeira Bravan kunta",
          "hi": "रिबेरा ब्रावा नगरपालिका",
          "zh": "里贝拉布拉瓦市",
        },
      ),
      States(
        name: "Ribeira Grande",
        translations: {
          "en": "Ribeira Grande",
          "fr": "Ribeira Grande",
          "si": "රිබෙයිරා ග්‍රැන්ඩ්",
          "ta": "ரிபேரா கிராண்டே",
          "fi": "Ribeira Grande",
          "hi": "रिबेरा ग्रांड",
          "zh": "里贝拉格兰德",
        },
      ),
      States(
        name: "Ribeira Grande de Santiago",
        translations: {
          "en": "Ribeira Grande de Santiago",
          "fr": "Ribeira Grande de Santiago",
          "si": "සැන්ටියාගෝ රිබෙයිරා ග්‍රැන්ඩ්",
          "ta": "ரிபேரா கிராண்டே டீ சான்டியாகோ",
          "fi": "Ribeira Grande de Santiago",
          "hi": "रिबेरा ग्रांड दे संतियागो",
          "zh": "圣地亚哥里贝拉格兰德",
        },
      ),
      States(
        name: "Sal",
        translations: {
          "en": "Sal",
          "fr": "Sal",
          "si": "සාල්",
          "ta": "சால்",
          "fi": "Sal",
          "hi": "साल",
          "zh": "萨尔",
        },
      ),
      States(
        name: "Santa Catarina",
        translations: {
          "en": "Santa Catarina",
          "fr": "Santa Catarina",
          "si": "සැන්ටා කැටරිනා",
          "ta": "சாந்தா கதரினா",
          "fi": "Santa Catarina",
          "hi": "सांता कैटरीना",
          "zh": "圣卡塔琳娜",
        },
      ),
      States(
        name: "Santa Catarina do Fogo",
        translations: {
          "en": "Santa Catarina do Fogo",
          "fr": "Santa Catarina do Fogo",
          "si": "සැන්ටා කැටරිනා ඩූ ෆොගො",
          "ta": "சாந்தா கதரினா டூ ஃபோகோ",
          "fi": "Santa Catarina do Fogo",
          "hi": "सांता कैटरीना दो फोगो",
          "zh": "火山圣卡塔琳娜",
        },
      ),
      States(
        name: "Santa Cruz",
        translations: {
          "en": "Santa Cruz",
          "fr": "Santa Cruz",
          "si": "සැන්ටා ක්‍රුස්",
          "ta": "சாந்தா குரூஸ்",
          "fi": "Santa Cruz",
          "hi": "सांता क्रूज़",
          "zh": "圣克鲁斯",
        },
      ),
      States(
        name: "São Domingos",
        translations: {
          "en": "São Domingos",
          "fr": "São Domingos",
          "si": "සාන් දොමින්ගොස්",
          "ta": "சாவ் டொமிங்கோஸ்",
          "fi": "São Domingos",
          "hi": "सां डोमिंगोस",
          "zh": "圣多明戈",
        },
      ),
      States(
        name: "São Filipe",
        translations: {
          "en": "São Filipe",
          "fr": "São Filipe",
          "si": "සාන් ෆිලිපේ",
          "ta": "சாவ் ஃபிலிபி",
          "fi": "São Filipe",
          "hi": "सां फिलिप",
          "zh": "圣菲利普",
        },
      ),
      States(
        name: "São Lourenço dos Órgãos",
        translations: {
          "en": "São Lourenço dos Órgãos",
          "fr": "São Lourenço dos Órgãos",
          "si": "සාන් ලුරෙන්සෝ ඩොස් ඔර්ගන්ස්",
          "ta": "சாவ் லொரென்சோ டோஸ் ஒர்கான்ஸ்",
          "fi": "São Lourenço dos Órgãos",
          "hi": "सां लोरेन्सो दोस ओर्गास",
          "zh": "圣洛伦索多斯奥尔贡斯",
        },
      ),
      States(
        name: "São Miguel",
        translations: {
          "en": "São Miguel",
          "fr": "São Miguel",
          "si": "සාන් මිගුල්",
          "ta": "சாவ் மிக்கேல்",
          "fi": "São Miguel",
          "hi": "साउ मिग्युएल",
          "zh": "圣米格尔",
        },
      ),
      States(
        name: "São Vicente",
        translations: {
          "en": "São Vicente",
          "fr": "São Vicente",
          "si": "සාන් විසෙන්ට්",
          "ta": "சாவ் விசெண்டே",
          "fi": "São Vicente",
          "hi": "सां विसेंट",
          "zh": "圣维森特",
        },
      ),
      States(
        name: "Sotavento Islands",
        translations: {
          "en": "Sotavento Islands",
          "fr": "Îles Sous-le-Vent",
          "si": "සොටාවෙන්ටෝ දුපත්",
          "ta": "சோடவென்டோ தீவுகள்",
          "fi": "Sotavento-saaret",
          "hi": "सोतावेंटो द्वीपसमूह",
          "zh": "风暴群岛",
        },
      ),
      States(
        name: "Tarrafal",
        translations: {
          "en": "Tarrafal",
          "fr": "Tarrafal",
          "si": "ටරරාෆල්",
          "ta": "தர்ராஃபல்",
          "fi": "Tarrafal",
          "hi": "ताराफाल",
          "zh": "塔拉法尔",
        },
      ),
      States(
        name: "Tarrafal de São Nicolau",
        translations: {
          "en": "Tarrafal de São Nicolau",
          "fr": "Tarrafal de São Nicolau",
          "si": "ටරාෆල් ඩේ සාඕ නිකොලාව",
          "ta": "தர்ராஃபல் டே சாவ் நிகொலௌ",
          "fi": "Tarrafal de São Nicolau",
          "hi": "ताराफाल डी साओ निकोलॉ",
          "zh": "圣尼古拉斯塔拉法尔",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Caribbean Netherlands",
    iso3: "BES",
    iso2: "BQ",
    phoneCode: "599",
    translations: {
      "en": "Caribbean Netherlands",
      "fr": "Pays-Bas caribéens",
      "si": "කැරිබියානු නෙදර්ලන්තය",
      "ta": "கரீபியன் நெதர்லாந்து",
      "fi": "Alankomaiden Karibia",
      "hi": "कैरेबियन नीदरलैंड",
      "zh": "加勒比荷兰",
    },
    flag: "🇧🇶",
    flagU: "U+1F1E7 U+1F1F6",
    states: [
      States(
        name: "Bonaire",
        translations: {
          "en": "Bonaire",
          "fr": "Bonaire",
          "si": "බොනෙයර්",
          "ta": "போனைர்",
          "fi": "Bonaire",
          "hi": "बोनेर",
          "zh": "博奈尔",
        },
      ),
      States(
        name: "Saba",
        translations: {
          "en": "Saba",
          "fr": "Saba",
          "si": "සාබා",
          "ta": "சாபா",
          "fi": "Saba",
          "hi": "साबा",
          "zh": "萨巴",
        },
      ),
      States(
        name: "Sint Eustatius",
        translations: {
          "en": "Sint Eustatius",
          "fr": "Sint Eustatius",
          "si": "සින්ට් යූස්ටේසියස්",
          "ta": "சிண்ட் யூஸ்டேஷியஸ்",
          "fi": "Sint Eustatius",
          "hi": "सिंट यूस्टेशियस",
          "zh": "圣尤斯特歇斯",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Cayman Islands",
    iso3: "CYM",
    iso2: "KY",
    phoneCode: "1",
    translations: {
      "en": "Cayman Islands",
      "fr": "Îles Caïmans",
      "si": "කේමන් දූපත්",
      "ta": "கேமன் தீவுகள்",
      "fi": "Caymansaaret",
      "hi": "केमन द्वीपसमूह",
      "zh": "开曼群岛",
    },
    flag: "🇰🇾",
    flagU: "U+1F1F0 U+1F1FE",
    states: [],
  ),
  CountriesStatesModel(
    name: "Central African Republic",
    iso3: "CAF",
    iso2: "CF",
    phoneCode: "236",
    translations: {
      "en": "Central African Republic",
      "fr": "République centrafricaine",
      "si": "මධ්‍යම අප්‍රිකානු ජනරජය",
      "ta": "மத்திய ஆப்பிரிக்கக் குடியரசு",
      "fi": "Keski-Afrikan tasavalta",
      "hi": "मध्य अफ़्रीकी गणराज्य",
      "zh": "中非共和國",
    },
    flag: "🇨🇫",
    flagU: "U+1F1E8 U+1F1EB",
    states: [
      States(
        name: "Bamingui-Bangoran Prefecture",
        translations: {
          "en": "Bamingui-Bangoran Prefecture",
          "fr": "Préfecture de Bamingui-Bangoran",
          "si": "බමින්ගුයි-බන්ගොරන් ප්‍රාන්තය",
          "ta": "பமிங்குயி-பங்கோரன் மாகாண ஆட்சிமன்றம்",
          "fi": "Bamingui-Bangoran prefektuuri",
          "hi": "बमिंगुई-बैंगोरान प्रिफेक्चर",
          "zh": "巴明吉-班戈兰专区",
        },
      ),
      States(
        name: "Bangui",
        translations: {
          "en": "Bangui",
          "fr": "Bangui",
          "si": "බන්ගුයි",
          "ta": "பாங்குயி",
          "fi": "Bangui",
          "hi": "बांगुई",
          "zh": "班基",
        },
      ),
      States(
        name: "Basse-Kotto Prefecture",
        translations: {
          "en": "Basse-Kotto Prefecture",
          "fr": "Préfecture de Basse-Kotto",
          "si": "බස්ස්-කොට්ටෝ ප්‍රාන්තය",
          "ta": "பாஸ்-கொட்டோ மாகாண ஆட்சிமன்றம்",
          "fi": "Basse-Kotton prefektuuri",
          "hi": "बास-कोट्टो प्रिफेक्चर",
          "zh": "巴塞科托专区",
        },
      ),
      States(
        name: "Haut-Mbomou Prefecture",
        translations: {
          "en": "Haut-Mbomou Prefecture",
          "fr": "Préfecture du Haut-Mbomou",
          "si": "හෝ ම්බොමු ප්‍රාන්තය",
          "ta": "ஹௌட்-ம்போமோ மாகாண ஆட்சிமன்றம்",
          "fi": "Haut-Mbomoun prefektuuri",
          "hi": "होट-एम्बोमू प्रिफेक्चर",
          "zh": "上姆博穆专区",
        },
      ),
      States(
        name: "Haute-Kotto Prefecture",
        translations: {
          "en": "Haute-Kotto Prefecture",
          "fr": "Préfecture de la Haute-Kotto",
          "si": "හෝට්-කොට්ටෝ ප්‍රාන්තය",
          "ta": "ஹௌட்-கொட்டோ மாகாண ஆட்சிமன்றம்",
          "fi": "Haute-Kotton prefektuuri",
          "hi": "होट-कोट्टो प्रिफेक्चर",
          "zh": "高科托专区",
        },
      ),
      States(
        name: "Kémo Prefecture",
        translations: {
          "en": "Kémo Prefecture",
          "fr": "Préfecture de Kémo",
          "si": "කෙමෝ ප්‍රාන්තය",
          "ta": "கேமோ மாகாண ஆட்சிமன்றம்",
          "fi": "Kémo-prefektuuri",
          "hi": "केमो प्रिफेक्चर",
          "zh": "凯莫专区",
        },
      ),
      States(
        name: "Lobaye Prefecture",
        translations: {
          "en": "Lobaye Prefecture",
          "fr": "Préfecture de la Lobaye",
          "si": "ලෝබයේ ප්‍රාන්තය",
          "ta": "லோபயே மாகாண ஆட்சிமன்றம்",
          "fi": "Lobaye-prefektuuri",
          "hi": "लोबाये प्रिफेक्चर",
          "zh": "洛拜专区",
        },
      ),
      States(
        name: "Mambéré-Kadéï",
        translations: {
          "en": "Mambéré-Kadéï",
          "fr": "Mambéré-Kadéï",
          "si": "මම්බරේ-කඩේ",
          "ta": "மம்பேரே-கடே",
          "fi": "Mambéré-Kadéï",
          "hi": "माम्बेरे-कादे",
          "zh": "曼贝雷-卡迪",
        },
      ),
      States(
        name: "Mbomou Prefecture",
        translations: {
          "en": "Mbomou Prefecture",
          "fr": "Préfecture de la Mbomou",
          "si": "ම්බෝමු ප්‍රාන්තය",
          "ta": "ம்போமோ மாகாண ஆட்சிமன்றம்",
          "fi": "Mbomoun prefektuuri",
          "hi": "म्बोमू प्रिफेक्चर",
          "zh": "恩博穆专区",
        },
      ),
      States(
        name: "Nana-Grébizi Economic Prefecture",
        translations: {
          "en": "Nana-Grébizi Economic Prefecture",
          "fr": "Préfecture économique de Nana-Grébizi",
          "si": "නානා-ග්‍රෙබිසි ආර්ථික ප්‍රාදේශීයය",
          "ta": "நானா-க்ரேபிசி பொது வளாகம்",
          "fi": "Nana-Grébizin talousprefektuuri",
          "hi": "नाना-ग्रेबिज़ी आर्थिक प्रांत",
          "zh": "纳纳-格雷比兹经济州",
        },
      ),
      States(
        name: "Nana-Mambéré Prefecture",
        translations: {
          "en": "Nana-Mambéré Prefecture",
          "fr": "Préfecture de la Nana-Mambéré",
          "si": "නානා-මම්බෙරේ ප්‍රාදේශීයය",
          "ta": "நானா-மாம்பேரே மாகாணம்",
          "fi": "Nana-Mambérén prefektuuri",
          "hi": "नाना-माम्बेर प्रांत",
          "zh": "纳纳-曼贝雷州",
        },
      ),
      States(
        name: "Ombella-M'Poko Prefecture",
        translations: {
          "en": "Ombella-M'Poko Prefecture",
          "fr": "Préfecture de l'Ombella-M'Poko",
          "si": "ඕම්බෙලා-එම්'පොකෝ ප්‍රාදේශීයය",
          "ta": "ஒம்பெல்லா-எம்'போக்கோ மாகாணம்",
          "fi": "Ombella-M'Pokon prefektuuri",
          "hi": "ओम्बेला-एम'पोको प्रांत",
          "zh": "翁贝拉-姆波科州",
        },
      ),
      States(
        name: "Ouaka Prefecture",
        translations: {
          "en": "Ouaka Prefecture",
          "fr": "Préfecture de l'Ouaka",
          "si": "ඔඋකා ප්‍රාදේශීයය",
          "ta": "ஒவாக்கா மாகாணம்",
          "fi": "Ouakan prefektuuri",
          "hi": "ओम्बेला-एमओउआका प्रांत",
          "zh": "瓦卡州",
        },
      ),
      States(
        name: "Ouham Prefecture",
        translations: {
          "en": "Ouham Prefecture",
          "fr": "Préfecture de l'Ouham",
          "si": "ඔවාම් ප්‍රාදේශීයය",
          "ta": "ஓஹாம் மாகாணம்",
          "fi": "Ouhamin prefektuuri",
          "hi": "ओहाम प्रांत",
          "zh": "瓦姆州",
        },
      ),
      States(
        name: "Ouham-Pendé Prefecture",
        translations: {
          "en": "Ouham-Pendé Prefecture",
          "fr": "Préfecture de l'Ouaka",
          "si": "ඔඋකා ප්‍රාදේශීයය",
          "ta": "ஒவாக்கா மாகாணம்",
          "fi": "Ouakan prefektuuri",
          "hi": "ओम्बेला-एमओउआका प्रांत",
          "zh": "瓦卡州",
        },
      ),
      States(
        name: "Sangha-Mbaéré",
        translations: {
          "en": "Sangha-Mbaéré",
          "fr": "Sangha-Mbaéré",
          "si": "සංඝා-ම්බායේරේ",
          "ta": "சங்கா-ம்பாயேரே",
          "fi": "Sangha-Mbaéré",
          "hi": "सांघा-म्बाएरे",
          "zh": "瓦卡州",
        },
      ),
      States(
        name: "Vakaga Prefecture",
        translations: {
          "en": "Vakaga Prefecture",
          "fr": "Préfecture de la Vakaga",
          "si": "වාකගා ප්‍රාදේශීයය",
          "ta": "வாகாகா மாகாண",
          "fi": "Vakagan prefektuuri",
          "hi": "वाकागा प्रांत",
          "zh": "瓦卡加州",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Chad",
    iso3: "TCD",
    iso2: "TD",
    phoneCode: "235",
    translations: {
      "en": "Chad",
      "fr": "Tchad",
      "si": "චෑඩ්",
      "ta": "சாட்",
      "fi": "Tšad",
      "hi": "चाड",
      "zh": "乍得",
    },
    flag: "🇹🇩",
    flagU: "U+1F1F9 U+1F1E9",
    states: [
      States(
        name: "Bahr el Gazel",
        translations: {
          "en": "Bahr el Gazel",
          "fr": "Bahr el Gazel",
          "si": "බාර් එල් ගාසෙල්",
          "ta": "பார் எல் கஸேல்",
          "fi": "Bahr el Gazel",
          "hi": "बाह्र एल गैज़ेल",
          "zh": "巴尔加赛尔",
        },
      ),
      States(
        name: "Batha",
        translations: {
          "en": "Batha",
          "fr": "Batha",
          "si": "බතා",
          "ta": "பாதா",
          "fi": "Batha",
          "hi": "बाथा",
          "zh": "巴塔",
        },
      ),
      States(
        name: "Borkou",
        translations: {
          "en": "Borkou",
          "fr": "Borkou",
          "si": "බෝර්කොව්",
          "ta": "போர்கூ",
          "fi": "Borkou",
          "hi": "बोरको",
          "zh": "博爾寇",
        },
      ),
      States(
        name: "Chari-Baguirmi",
        translations: {
          "en": "Chari-Baguirmi",
          "fr": "Préfecture de l'Ouaka",
          "si": "ඔඋකා ප්‍රාදේශීයය",
          "ta": "ஒவாக்கா மாகாணம்",
          "fi": "Ouakan prefektuuri",
          "hi": "ओम्बेला-एमओउआका प्रांत",
          "zh": "瓦卡州",
        },
      ),
      States(
        name: "Ennedi-Est",
        translations: {
          "en": "Ennedi-Est",
          "fr": "Ennedi-Est",
          "si": "එන්නෙඩි-එස්ට්",
          "ta": "என்னெடி-ஈஸ்ட்",
          "fi": "Ennedi-Est",
          "hi": "एनेडी-इस्ट",
          "zh": "恩内迪-东部",
        },
      ),
      States(
        name: "Ennedi-Ouest",
        translations: {
          "en": "Ennedi-Ouest",
          "fr": "Ennedi-Ouest",
          "si": "එන්නෙඩි-ඔස්ට්",
          "ta": "என்னெடி-ஒவேஸ்ட்",
          "fi": "Ennedi-Ouest",
          "hi": "एनेडी-ओस्ट",
          "zh": "恩内迪-西部",
        },
      ),
      States(
        name: "Guéra",
        translations: {
          "en": "Guéra",
          "fr": "Guéra",
          "si": "ගුරා",
          "ta": "குவேரா",
          "fi": "Guéra",
          "hi": "गेरा",
          "zh": "吉拉",
        },
      ),
      States(
        name: "Hadjer-Lamis",
        translations: {
          "en": "Hadjer-Lamis",
          "fr": "Hadjer-Lamis",
          "si": "හජර්-ලාමිස්",
          "ta": "ஹஜர்-லாமிஸ்",
          "fi": "Hadjer-Lamis",
          "hi": "हजर-लामिस",
          "zh": "哈杰尔-拉米斯",
        },
      ),
      States(
        name: "Kanem",
        translations: {
          "en": "Kanem",
          "fr": "Kanem",
          "si": "කානෙම්",
          "ta": "கானெம்",
          "fi": "Kanem",
          "hi": "कानेम",
          "zh": "卡内姆",
        },
      ),
      States(
        name: "Lac",
        translations: {
          "en": "Lac",
          "fr": "Lac",
          "si": "වැව",
          "ta": "ஏரி்",
          "fi": "Järvi",
          "hi": "झील",
          "zh": "湖",
        },
      ),
      States(
        name: "Logone Occidental",
        translations: {
          "en": "Logone Occidental",
          "fr": "Logone Occidental",
          "si": "ලොගෝන් ඔක්සිඩෙන්ටල්",
          "ta": "லோகோன் ஒக்சிடெண்டல்",
          "fi": "Logone Occidental",
          "hi": "लोगोने ओक्सीडेंटल",
          "zh": "洛贡欧西登特",
        },
      ),
      States(
        name: "Logone Oriental",
        translations: {
          "en": "Logone Oriental",
          "fr": "Logone Oriental",
          "si": "ලොගෝන් ඔරියන්ටල්",
          "ta": "லோகோன் ஓரியெண்டல்",
          "fi": "Logone Oriental",
          "hi": "लोगोने ओरियंटल",
          "zh": "洛贡东部",
        },
      ),
      States(
        name: "Mandoul",
        translations: {
          "en": "Mandoul",
          "fr": "Mandoul",
          "si": "මන්ඩුල්",
          "ta": "மண்டோல்",
          "fi": "Mandoul",
          "hi": "मंदौल",
          "zh": "曼都",
        },
      ),
      States(
        name: "Mayo-Kebbi Est",
        translations: {
          "en": "Mayo-Kebbi Est",
          "fr": "Mayo-Kebbi Est",
          "si": "මායෝ-කෙබ්බි නැගෙනහිර",
          "ta": "மாயோ-கெப்பி கிழக்கு்",
          "fi": "Mayo-Kebbi Est",
          "hi": "मायो-केबी पूर्व",
          "zh": "马约凯比东部",
        },
      ),
      States(
        name: "Mayo-Kebbi Ouest",
        translations: {
          "en": "Mayo-Kebbi Ouest",
          "fr": "Mayo-Kebbi Ouest",
          "si": "මායෝ-කෙබ්බි බටහිර",
          "ta": "மாயோ-கெப்பி மேற்கு்",
          "fi": "Mayo-Kebbi Ouest",
          "hi": "मायो-केबी पश्चिम",
          "zh": "马约凯比西部",
        },
      ),
      States(
        name: "Moyen-Chari",
        translations: {
          "en": "Moyen-Chari",
          "fr": "Moyen-Chari",
          "si": "මොයන්-චාරි",
          "ta": "மாயன்-சாரி்",
          "fi": "Moyen-Chari",
          "hi": "म्वां चारी",
          "zh": "莫亚恩夏里",
        },
      ),
      States(
        name: "N'Djamena",
        translations: {
          "en": "N'Djamena",
          "fr": "Moyen-Chari",
          "si": "මොයන්-චාරි",
          "ta": "மாயன்-சாரி",
          "fi": "Moyen-Chari",
          "hi": "म्वां चारी",
          "zh": "莫亚恩夏里",
        },
      ),
      States(
        name: "Ouaddaï",
        translations: {
          "en": "Ouaddaï",
          "fr": "Ouaddaï",
          "si": "ඔවාඩායි",
          "ta": "ஒவட்டாய்ி்",
          "fi": "Ouaddaï",
          "hi": "वाडडाई",
          "zh": "瓦代",
        },
      ),
      States(
        name: "Salamat",
        translations: {
          "en": "Salamat",
          "fr": "Salamat",
          "si": "සලාමට්",
          "ta": "சலாமத்",
          "fi": "Salamat",
          "hi": "सलामात",
          "zh": "萨拉马特",
        },
      ),
      States(
        name: "Sila",
        translations: {
          "en": "Sila",
          "fr": "Sila",
          "si": "සිලා",
          "ta": "சிலா",
          "fi": "Sila",
          "hi": "सीला",
          "zh": "西拉",
        },
      ),
      States(
        name: "Tandjilé",
        translations: {
          "en": "Tandjilé",
          "fr": "Tandjilé",
          "si": "ටන්ජිලේ",
          "ta": "டாண்ஜிலே",
          "fi": "Tandjilé",
          "hi": "तांजिले",
          "zh": "坦吉莱",
        },
      ),
      States(
        name: "Tibesti",
        translations: {
          "en": "Tibesti",
          "fr": "Tibesti",
          "si": "ටිබෙස්ටි",
          "ta": "திபெஸ்டி",
          "fi": "Tibesti",
          "hi": "तिबेस्ती",
          "zh": "提贝斯蒂",
        },
      ),
      States(
        name: "Wadi Fira",
        translations: {
          "en": "Wadi Fira",
          "fr": "Wadi Fira",
          "si": "වාදි ෆිරා",
          "ta": "வாடி பிரா்",
          "fi": "Wadi Fira",
          "hi": "वादी फिरा",
          "zh": "瓦迪菲拉",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Chile",
    iso3: "CHL",
    iso2: "CL",
    phoneCode: "56",
    translations: {
      "en": "Chile",
      "fr": "Chili",
      "si": "චිලි ජනරජය",
      "ta": "சிலி",
      "hi": "चिली",
      "zh": "智利",
    },
    flag: "🇨🇱",
    flagU: "U+1F1E8 U+1F1F1",
    states: [
      States(
        name: "Aisén del General Carlos Ibañez del Campo",
        translations: {
          "en": "Aisén del General Carlos Ibañez del Campo",
          "fr": "Aisén del General Carlos Ibañez del Campo",
          "si": "ජනරජ් කාල්ලොස් ඉබනේස් ඩෙල් කැම්පොවා අයිසෙන්",
          "ta": "ஜெனரல் கார்லோஸ் இபான்யேஸ் டெல் காம்போவின் ஐசேன்",
          "fi": "Aisén del General Carlos Ibañez del Campo",
          "hi": "जनरल कार्लोस इबानेज़ डेल कैंपो का आईसेन",
          "zh": "将军卡洛斯·伊瓦涅斯·德尔坎波的艾森",
        },
      ),
      States(
        name: "Antofagasta",
        translations: {
          "en": "Antofagasta",
          "fr": "Antofagasta",
          "si": "ඇන්ටෝෆාගස්ටා",
          "ta": "அந்தோஃபகஸ்டா",
          "fi": "Antofagasta",
          "hi": "अंतोफागास्ता",
          "zh": "安托法加斯塔",
        },
      ),
      States(
        name: "Arica y Parinacota",
        translations: {
          "en": "Arica y Parinacota",
          "fr": "Arica y Parinacota",
          "si": "අරිකා සහ පැරිනාකොටා",
          "ta": "அரிக்கா உடன் பரினாகோடா",
          "fi": "Arica y Parinacota",
          "hi": "अरिका व पारिनाकोटा",
          "zh": "अरिका व पारिनाकोटा",
        },
      ),
      States(
        name: "Atacama",
        translations: {
          "en": "Atacama",
          "fr": "Atacama",
          "si": "ඇටකාමා",
          "ta": "அடகாமா",
          "fi": "Atacama",
          "hi": "अटाकामा",
          "zh": "阿塔卡马",
        },
      ),
      States(
        name: "Biobío",
        translations: {
          "en": "Biobío",
          "fr": "Biobío",
          "si": "බිඔබියෝ",
          "ta": "பியோபியோ",
          "fi": "Biobío",
          "hi": "बिओबिओ",
          "zh": "比奥比奥",
        },
      ),
      States(
        name: "Coquimbo",
        translations: {
          "en": "Coquimbo",
          "fr": "Coquimbo",
          "si": "කොකිම්බෝ",
          "ta": "கோக்கிம்போ",
          "fi": "Coquimbo",
          "hi": "कोकिम्बो",
          "zh": "科金博",
        },
      ),
      States(
        name: "La Araucanía",
        translations: {
          "en": "La Araucanía",
          "fr": "La Araucanía",
          "si": "ලා අරවුකානියා",
          "ta": "லா அராகுவானியா",
          "fi": "La Araucanía",
          "hi": "ला अरौकानिया",
          "zh": "阿劳卡尼亚大区",
        },
      ),
      States(
        name: "Libertador General Bernardo O'Higgins",
        translations: {
          "en": "Libertador General Bernardo O'Higgins",
          "fr": "Libertador General Bernardo O'Higgins",
          "si": "ලිබර්ටදෙර් ජෙනරල් බර්නාඩෝ ඔහිගින්ස්",
          "ta": "லிபர்டேடர் ஜெனரல் பெர்னார்டோ ஓ'ஹிக்கின்ஸ்",
          "fi": "Libertador General Bernardo O'Higgins",
          "hi": "लिबर्टाडोर जनरल बर्नार्डो ओ'हिग्गिन्स",
          "zh": "伯納多·希金斯解放將軍",
        },
      ),
      States(
        name: "Los Lagos",
        translations: {
          "en": "Los Lagos",
          "fr": "Los Lagos",
          "si": "ලොස් ලාගෝස්",
          "ta": "லாஸ் லாகோஸ்",
          "fi": "Los Lagos",
          "hi": "लोस लागोस",
          "zh": "洛斯拉戈斯",
        },
      ),
      States(
        name: "Los Ríos",
        translations: {
          "en": "Los Ríos",
          "fr": "Los Ríos",
          "si": "ලොස් රීයෝස්",
          "ta": "லோஸ் ரியோஸ்",
          "fi": "Los Ríos",
          "hi": "लोस रिओस",
          "zh": "洛斯里奥斯",
        },
      ),
      States(
        name: "Magallanes y de la Antártica Chilena",
        translations: {
          "en": "Magallanes y de la Antártica Chilena",
          "fr": "Magallanes et de l'Antarctique chilien",
          "si": "මගල්ලානේස් සහ චිලියාන් ඇන්ටාක්ටිකා",
          "ta": "மகல்லானேஸ் மற்றும் சிலி அண்டார்க்டிக்கா",
          "fi": "Magallanes ja Chilen antarktinen alue",
          "hi": "मैगालेनेस और चिली एंटार्कटिका",
          "zh": "马加良尼斯和智利南极地区",
        },
      ),
      States(
        name: "Maule",
        translations: {
          "en": "Maule",
          "fr": "Maule",
          "si": "මායුල්",
          "ta": "மாவுலே",
          "fi": "Maule",
          "hi": "मॉयल",
          "zh": "莫莱",
        },
      ),
      States(
        name: "Ñuble",
        translations: {
          "en": "Ñuble",
          "fr": "Ñuble",
          "si": "ඤුබ්ලේ",
          "ta": "ஞூபிளே",
          "fi": "Ñuble",
          "hi": "ञुब्ले",
          "zh": "尼烏布萊",
        },
      ),
      States(
        name: "Región Metropolitana de Santiago",
        translations: {
          "en": "Región Metropolitana de Santiago",
          "fr": "Région métropolitaine de Santiago",
          "si": "සැන්ටියාගෝ ප්‍රාන්ත කලාපය",
          "ta": "சாண்டியாகோ புரட்சியக் காலமான்",
          "fi": "Santiagon metropolialue",
          "hi": "सैंटियागो क्षेत्रीय नगर",
          "zh": "圣地亚哥大都会区",
        },
      ),
      States(
        name: "Tarapacá",
        translations: {
          "en": "Tarapacá",
          "fr": "Tarapacá",
          "si": "ටරපකා",
          "ta": "தரபாகாி்",
          "fi": "Tarapacá",
          "hi": "तारापाका",
          "zh": "塔拉帕卡",
        },
      ),
      States(
        name: "Valparaíso",
        translations: {
          "en": "Valparaíso",
          "fr": "Valparaíso",
          "si": "වැල්පරායිසෝ",
          "ta": "வால்பரைசோ",
          "fi": "Valparaíso",
          "hi": "वालपराइसो",
          "zh": "瓦尔帕莱索",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "China",
    iso3: "CHN",
    iso2: "CN",
    phoneCode: "86",
    translations: {
      "en": "China",
      "fr": "Chine",
      "si": "චීනය",
      "ta": "சீனா",
      "fi": "Kiina",
      "hi": "चीन",
      "zh": "中国",
    },
    flag: "🇨🇳",
    flagU: "U+1F1E8 U+1F1F3",
    states: [
      States(
        name: "Anhui",
        translations: {
          "en": "Anhui",
          "fr": "Anhui",
          "si": "ඇන්හුඉ",
          "ta": "அன்ஹுய்",
          "fi": "Anhui",
          "hi": "आन्हुई",
          "zh": "安徽",
        },
      ),
      States(
        name: "Beijing",
        translations: {
          "en": "Beijing",
          "fr": "Beijingi",
          "si": "බෙජිංගි",
          "ta": "பீஜிங்கி",
          "fi": "Beijingi",
          "hi": "बीजिंगी",
          "zh": "北京",
        },
      ),
      States(
        name: "Chongqing",
        translations: {
          "en": "Chongqing",
          "fr": "Chongqing",
          "si": "චොන්ග්කින්",
          "ta": "சோங்க்கிங்",
          "fi": "Chongqing",
          "hi": "चोंग्किंग",
          "zh": "重庆",
        },
      ),
      States(
        name: "Fujian",
        translations: {
          "en": "Fujian",
          "fr": "Fujian",
          "si": "වැව",
          "ta": "புஜியான்",
          "fi": "Fujian",
          "hi": "फुजियान",
          "zh": "福建",
        },
      ),
      States(
        name: "Gansu",
        translations: {
          "en": "Gansu",
          "fr": "Gansu",
          "si": "ගන්සු",
          "ta": "கான்சு",
          "fi": "Gansu",
          "hi": "गांसू",
          "zh": "甘肃",
        },
      ),
      States(
        name: "Guangdong",
        translations: {
          "en": "Guangdong",
          "fr": "Guangdong",
          "si": "ග්වාන්ග්ඩොන්ග්",
          "ta": "குவாங்டாங்",
          "fi": "Guangdong",
          "hi": "ग्वांगडोंग",
          "zh": "广东",
        },
      ),
      States(
        name: "Guangxi Zhuang",
        translations: {
          "en": "Guangxi Zhuang",
          "fr": "Guangxi Zhuang",
          "si": "ග්වාන්ග්සි ස්වාංශ",
          "ta": "குவாங்சி ஜுவாங்்",
          "fi": "Guangxi Zhuang",
          "hi": "ग्वांग्सी ज़ुआंग",
          "zh": "广西壮族",
        },
      ),
      States(
        name: "Guizhou",
        translations: {
          "en": "Guizhou",
          "fr": "Guizhou",
          "si": "ගුයිසෝ",
          "ta": "கிவிழோ்",
          "fi": "Guizhou",
          "hi": "गुइझोउ",
          "zh": "贵州",
        },
      ),
      States(
        name: "Hainan",
        translations: {
          "en": "Hainan",
          "fr": "Hainan",
          "si": "හයිනාන්",
          "ta": "ஹைநான்",
          "fi": "Hainan",
          "hi": "हैनान",
          "zh": "海南",
        },
      ),
      States(
        name: "Hebei",
        translations: {
          "en": "Hebei",
          "fr": "Hebei",
          "si": "හෙබෙයි",
          "ta": "ஹெபேய்",
          "fi": "Hebei",
          "hi": "हेबेई",
          "zh": "河北",
        },
      ),
      States(
        name: "Heilongjiang",
        translations: {
          "en": "Heilongjiang",
          "fr": "Heilongjiang",
          "si": "හෙයිලොන්ග්ජියාන්",
          "ta": "ஹைலாங்ஜியாங்",
          "fi": "Heilongjiang",
          "hi": "हेइलोंगजियां",
          "zh": "黑龙江",
        },
      ),
      States(
        name: "Henan",
        translations: {
          "en": "Henan",
          "fr": "Henan",
          "si": "හෙනාන්",
          "ta": "ஹெனான்ி்",
          "fi": "Henan",
          "hi": "हेनान",
          "zh": "河南",
        },
      ),
      States(
        name: "Hubei",
        translations: {
          "en": "Hubei",
          "fr": "Hubei",
          "si": "හුබෙයි",
          "ta": "ஹுபே",
          "fi": "Hubei",
          "hi": "हुबेई",
          "zh": "湖北",
        },
      ),
      States(
        name: "Hunan",
        translations: {
          "en": "Hunan",
          "fr": "Hunan",
          "si": "හුනාන්",
          "ta": "ஹுனான்",
          "fi": "Hunan",
          "hi": "हुनान",
          "zh": "湖南",
        },
      ),
      States(
        name: "Inner Mongolia",
        translations: {
          "en": "Inner Mongolia",
          "fr": "Mongolie Intérieure",
          "si": "අභියාවේ මොංගෝලියාව",
          "ta": "உள் மங்கோலியா்",
          "fi": "Sisä-Mongolia",
          "hi": "आंतरिक मंगोलिया",
          "zh": "内蒙古",
        },
      ),
      States(
        name: "Jiangsu",
        translations: {
          "en": "Jiangsu",
          "fr": "Jiangsu",
          "si": "ජියාංග්සු",
          "ta": "ஜியாங்சு",
          "fi": "Jiangsu",
          "hi": "जियांगसू",
          "zh": "江苏",
        },
      ),
      States(
        name: "Jiangxi",
        translations: {
          "en": "Jiangxi",
          "fr": "Jiangxi",
          "si": "ජියාංග්සි",
          "ta": "ஜியாங்சிி்",
          "fi": "Jiangxi",
          "hi": "जियांगशी",
          "zh": "江西",
        },
      ),
      States(
        name: "Jilin",
        translations: {
          "en": "Jilin",
          "fr": "Jilin",
          "si": "ජිලින්",
          "ta": "ஜிலின்",
          "fi": "Jilin",
          "hi": "जिलिन",
          "zh": "吉林",
        },
      ),
      States(
        name: "Liaoning",
        translations: {
          "en": "Liaoning",
          "fr": "Liaoning",
          "si": "ලියානිං",
          "ta": "லியானிங்",
          "fi": "Liaoning",
          "hi": "लियानिंग",
          "zh": "辽宁",
        },
      ),
      States(
        name: "Ningxia Huizu",
        translations: {
          "en": "Ningxia Huizu",
          "fr": "Ningxia Huizu",
          "si": "නිංග්සියා හ්වීසු",
          "ta": "நிங்சியா ஹுய்சு்",
          "fi": "Ningxia Huizu",
          "hi": "निंग्शिया हुइज़ू",
          "zh": "宁夏回族",
        },
      ),
      States(
        name: "Qinghai",
        translations: {
          "en": "Qinghai",
          "fr": "Qinghai",
          "si": "ක්විංහායි",
          "ta": "கிங்ஹை",
          "fi": "Qinghai",
          "hi": "क्विंगहाई",
          "zh": "青海",
        },
      ),
      States(
        name: "Shaanxi",
        translations: {
          "en": "Shaanxi",
          "fr": "Shaanxi",
          "si": "ශාන්ශි",
          "ta": "ஷான்ஷி",
          "fi": "Shaanxi",
          "hi": "शांसी",
          "zh": "陕西",
        },
      ),
      States(
        name: "Shandong",
        translations: {
          "en": "Shandong",
          "fr": "Shandong",
          "si": "ශැන්ඩොං",
          "ta": "ஷாண்டாங்்",
          "fi": "Shandong",
          "hi": "शानदोंग",
          "zh": "山东",
        },
      ),
      States(
        name: "Shanghai",
        translations: {
          "en": "Shanghai",
          "fr": "Shanghai",
          "si": "ශාන්ග්හායි",
          "ta": "சாங்காய்",
          "fi": "Shanghai",
          "hi": "शंघाई",
          "zh": "上海",
        },
      ),
      States(
        name: "Shanxi",
        translations: {
          "en": "Shanxi",
          "fr": "Shanxi",
          "si": "ශාන්ශි",
          "ta": "ஷான்சி",
          "fi": "Shanxi",
          "hi": "शान्सी",
          "zh": "山西",
        },
      ),
      States(
        name: "Sichuan",
        translations: {
          "en": "Sichuan",
          "fr": "Sichuan",
          "si": "සීචුවාන්",
          "ta": "சிசுவான்",
          "fi": "Sichuan",
          "hi": "सीचुआन",
          "zh": "四川",
        },
      ),
      States(
        name: "Tianjin",
        translations: {
          "en": "Tianjin",
          "fr": "Tianjin",
          "si": "ටියාන්ජින්",
          "ta": "தியாஞ்சின்",
          "fi": "Tianjin",
          "hi": "तियांजिन",
          "zh": "天津",
        },
      ),
      States(
        name: "Xinjiang",
        translations: {
          "en": "Xinjiang",
          "fr": "Xinjiang",
          "si": "චින්ජියාන්ග්",
          "ta": "சின்ஜியாங்ி்",
          "fi": "Xinjiang",
          "hi": "शिंजियांग",
          "zh": "新疆",
        },
      ),
      States(
        name: "Xizang",
        translations: {
          "en": "Xizang",
          "fr": "Xizang",
          "si": "ශීසාංග්",
          "ta": "சிசாங்",
          "fi": "Xizang",
          "hi": "शिजांग",
          "zh": "西藏",
        },
      ),
      States(
        name: "Yunnan",
        translations: {
          "en": "Yunnan",
          "fr": "Yunnan",
          "si": "යුන්නාන්",
          "ta": "யுன்னான்",
          "fi": "Yunnan",
          "hi": "युन्नान",
          "zh": "云南",
        },
      ),
      States(
        name: "Zhejiang",
        translations: {
          "en": "Zhejiang",
          "fr": "Zhejiang",
          "si": "සෙජියාන්ග්",
          "ta": "செசியாங்",
          "fi": "Zhejiang",
          "hi": "झेजियांग",
          "zh": "浙江",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Christmas Island",
    iso3: "CXR",
    iso2: "CX",
    phoneCode: "61",
    translations: {
      "en": "Christmas Island",
      "fr": "Île Christmas",
      "si": "ක්‍රිස්මස් දූපත",
      "ta": "கிறிஸ்துமசு தீவு",
      "fi": "Joulusaari",
      "hi": "क्रिसमस द्वीप",
      "zh": "圣诞岛",
    },
    flag: "🇨🇽",
    flagU: "U+1F1E8 U+1F1FD",
    states: [],
  ),
  CountriesStatesModel(
    name: "Cocos (Keeling) Islands",
    iso3: "CCK",
    iso2: "CC",
    phoneCode: "61",
    translations: {
      "en": "Cocos (Keeling) Islands",
      "fr": "Îles Cocos",
      "si": "කොකෝස් (කීලිං) දූපත්",
      "ta": "கொக்கோசு (கீலிங்) தீவுகள்",
      "fi": "Kookossaaret",
      "hi": "कोकोस (कीलिंग) द्वीपसमूह",
      "zh": "科科斯（基林）群岛",
    },
    flag: "🇨🇨",
    flagU: "U+1F1E8 U+1F1E8",
    states: [],
  ),
  CountriesStatesModel(
    name: "Colombia",
    iso3: "COL",
    iso2: "CO",
    phoneCode: "57",
    translations: {
      "en": "Colombia",
      "fr": "Colombie",
      "si": "කොලොම්බියාව",
      "ta": "கொலம்பியா",
      "fi": "Kolumbia",
      "hi": "कोलम्बिया",
      "zh": "哥伦比亚",
    },
    flag: "🇨🇴",
    flagU: "U+1F1E8 U+1F1F4",
    states: [
      States(
        name: "Amazonas",
        translations: {
          "en": "Amazonas",
          "fr": "Amazonas",
          "si": "ඇමසෝනාස්",
          "ta": "அமேசோனாஸ்",
          "fi": "Amazonas",
          "hi": "अमेज़ोनस",
          "zh": "亚马孙",
        },
      ),
      States(
        name: "Antioquia",
        translations: {
          "en": "Antioquia",
          "fr": "Antioquia",
          "si": "ඇන්ටියෝකියා",
          "ta": "அந்தியோகியா",
          "fi": "Antioquia",
          "hi": "अंतिओकिया",
          "zh": "安提奥基亚",
        },
      ),
      States(
        name: "Arauca",
        translations: {
          "en": "Arauca",
          "fr": "Arauca",
          "si": "අරවුකා",
          "ta": "அரவுகா",
          "fi": "Arauca",
          "hi": "आराउका",
          "zh": "阿劳卡",
        },
      ),
      States(
        name: "Archipiélago de San Andrés, Providencia y Santa Catalina",
        translations: {
          "en": "Archipelago of San Andrés, Providencia and Santa Catalina",
          "fr": "Archipel de San Andrés, Providencia et Santa Catalina",
          "si":
              "සාන් ඇන්ඩ්‍රෙස්, ප්‍රොවිඩෙන්සියා සහ සැන්ටා කැටලිනා වාද්‍ය සමූහය",
          "ta":
              "சான் அன்டிரஸ், ப்ரொவிடென்சியா மற்றும் சாந்தா கேடலினா தீவுகள் தீவுக்குழு",
          "fi": "San Andrésin, Providencian ja Santa Catalan saaristo",
          "hi": "सैन एंड्रेस, प्रोवीडेंसिया और सांता कैटलीना का द्वीप समूह",
          "zh": "圣安德列斯、普罗维登西亚和圣卡塔琳娜群岛",
        },
      ),
      States(
        name: "Atlántico",
        translations: {
          "en": "Atlántico",
          "fr": "Atlántico",
          "si": "අත්ලාන්ටිකෝ",
          "ta": "அட்லாண்டிக்கோ",
          "fi": "Atlántico",
          "hi": "अट्लांटिको",
          "zh": "大西洋",
        },
      ),
      States(
        name: "Bogotá D.C.",
        translations: {
          "en": "Bogotá D.C.",
          "fr": "Bogotá D.C.",
          "si": "බොගොටා ඩී.සී.",
          "ta": "பொகோடா டி.சி.",
          "fi": "Bogotá D.C.",
          "hi": "बोगोटा डी.सी.",
          "zh": "波哥大D.C.",
        },
      ),
      States(
        name: "Bolívar",
        translations: {
          "en": "Bolívar",
          "fr": "Bolívar",
          "si": "බොලිවාර්",
          "ta": "பொலிவார்",
          "fi": "Bolívar",
          "hi": "बोलीवार",
          "zh": "波利瓦尔",
        },
      ),
      States(
        name: "Boyacá",
        translations: {
          "en": "Boyacá",
          "fr": "Boyacá",
          "si": "බොයාකා",
          "ta": "பொயாகா",
          "fi": "Boyacá",
          "hi": "बोयाका",
          "zh": "博亚卡",
        },
      ),
      States(
        name: "Caldas",
        translations: {
          "en": "Caldas",
          "fr": "Caldas",
          "si": "කොල්ඩාස්",
          "ta": "கால்டாஸ்",
          "fi": "Caldas",
          "hi": "काल्डास",
          "zh": "卡尔达斯",
        },
      ),
      States(
        name: "Caquetá",
        translations: {
          "en": "Caquetá",
          "fr": "Caquetá",
          "si": "කාකෙටා",
          "ta": "காகேடா",
          "fi": "Caquetá",
          "hi": "काकेटा",
          "zh": "卡克塔",
        },
      ),
      States(
        name: "Casanare",
        translations: {
          "en": "Casanare",
          "fr": "Casanare",
          "si": "කසානාරේ",
          "ta": "காசானாரே",
          "fi": "Casanare",
          "hi": "कासानारे",
          "zh": "卡萨纳雷",
        },
      ),
      States(
        name: "Cauca",
        translations: {
          "en": "Cauca",
          "fr": "Cauca",
          "si": "කව්කා",
          "ta": "காஉகா",
          "fi": "Cauca",
          "hi": "कॉका",
          "zh": "卡瓦卡",
        },
      ),
      States(
        name: "Cesar",
        translations: {
          "en": "Cesar",
          "fr": "César",
          "si": "සීසාර්",
          "ta": "சேசார்",
          "fi": "Cesar",
          "hi": "सीज़र",
          "zh": "塞萨尔",
        },
      ),
      States(
        name: "Chocó",
        translations: {
          "en": "Chocó",
          "fr": "Chocó",
          "si": "චොකෝ",
          "ta": "சோகோ",
          "fi": "Chocó",
          "hi": "चोको",
          "zh": "乔科",
        },
      ),
      States(
        name: "Córdoba",
        translations: {
          "en": "Córdoba",
          "fr": "Córdoba",
          "si": "කෝඩෝබා",
          "ta": "கோர்டோபா",
          "fi": "Córdoba",
          "hi": "कोर्डोबा",
          "zh": "科尔多瓦",
        },
      ),
      States(
        name: "Cundinamarca",
        translations: {
          "en": "Cundinamarca",
          "fr": "Cundinamarca",
          "si": "කුන්ඩිනාමාර්කා",
          "ta": "குண்டினாமார்கா",
          "fi": "Cundinamarca",
          "hi": "कुन्डिनामार्का",
          "zh": "孔迪那马卡",
        },
      ),
      States(
        name: "Guainía",
        translations: {
          "en": "Guainía",
          "fr": "Guainía",
          "si": "ගුයිනියා",
          "ta": "குவாய்னியா",
          "fi": "Guainía",
          "hi": "गुआइनिया",
          "zh": "瓜因尼亚",
        },
      ),
      States(
        name: "Guaviare",
        translations: {
          "en": "Guaviare",
          "fr": "Guaviare",
          "si": "ගුවාසියා",
          "ta": "குவாயாரே",
          "fi": "Guaviare",
          "hi": "ग्वावियार",
          "zh": "瓜维亚雷",
        },
      ),
      States(
        name: "Huila",
        translations: {
          "en": "Huila",
          "fr": "Huila",
          "si": "හුයිලා",
          "ta": "ஹுயிலா",
          "fi": "Huila",
          "hi": "Huila",
          "zh": "乌伊拉",
        },
      ),
      States(
        name: "La Guajira",
        translations: {
          "en": "La Guajira",
          "fr": "La Guajira",
          "si": "ලා ගුවාහිරා",
          "ta": "லா குவாஜீரா",
          "fi": "La Guajira",
          "hi": "ला गुआहीरा",
          "zh": "拉瓜希拉",
        },
      ),
      States(
        name: "Magdalena",
        translations: {
          "en": "Magdalena",
          "fr": "Magdalena",
          "si": "මැග්ඩලෙනා",
          "ta": "மக்டலேனா",
          "fi": "Magdalena",
          "hi": "मैग्डालेना",
          "zh": "马格达莱纳",
        },
      ),
      States(
        name: "Meta",
        translations: {
          "en": "Meta",
          "fr": "Meta",
          "si": "මෙටා",
          "ta": "மெடா",
          "fi": "Meta",
          "hi": "मेटा",
          "zh": "梅塔",
        },
      ),
      States(
        name: "Nariño",
        translations: {
          "en": "Nariño",
          "fr": "Nariño",
          "si": "නාරීන්යෝ",
          "ta": "நாரினியோ",
          "fi": "Nariño",
          "hi": "नारिन्यो",
          "zh": "纳里尼奥",
        },
      ),
      States(
        name: "Norte de Santander",
        translations: {
          "en": "Norte de Santander",
          "fr": "Norte de Santander",
          "si": "නෝර්ටේ ඩේ සැන්ටන්ඩර්",
          "ta": "நோர்தே டே சான்டாண்டர்	北桑坦",
          "fi": "Norte de Santander",
          "hi": "नोर्ते डे सैंटांडर",
          "zh": "北桑坦德省",
        },
      ),
      States(
        name: "Putumayo",
        translations: {
          "en": "Putumayo",
          "fr": "Putumayo",
          "si": "පුටුමයෝ",
          "ta": "புதுமாயோ",
          "fi": "Putumayo",
          "hi": "पुतुमायो",
          "zh": "普图马约",
        },
      ),
      States(
        name: "Quindío",
        translations: {
          "en": "Quindío",
          "fr": "Quindío",
          "si": "ක්වින්ඩියෝ",
          "ta": "குவின்டியோ",
          "fi": "Quindío",
          "hi": "क्विन्डियो",
          "zh": "金迪奥",
        },
      ),
      States(
        name: "Risaralda",
        translations: {
          "en": "Risaralda",
          "fr": "Risaralda",
          "si": "රිසාරාල්ඩා",
          "ta": "ரிஸாரால்டா",
          "fi": "Risaralda",
          "hi": "रिसाराल्डा",
          "zh": "里萨拉尔达",
        },
      ),
      States(
        name: "Santander",
        translations: {
          "en": "Santander",
          "fr": "Santander",
          "si": "සැන්ටන්ඩර්",
          "ta": "சாந்தாண்டர்",
          "fi": "Santander",
          "hi": "सांतांडेर",
          "zh": "桑坦德",
        },
      ),
      States(
        name: "Sucre",
        translations: {
          "en": "Sucre",
          "fr": "Sucre",
          "si": "සුක්රේ",
          "ta": "சுக்ரே",
          "fi": "Sucre",
          "hi": "सुक्रे",
          "zh": "苏克雷",
        },
      ),
      States(
        name: "Tolima",
        translations: {
          "en": "Tolima",
          "fr": "Tolima",
          "si": "ටොලිමා",
          "ta": "டொலிமா",
          "fi": "Tolima",
          "hi": "टोलिमा",
          "zh": "托利马",
        },
      ),
      States(
        name: "Valle del Cauca",
        translations: {
          "en": "Valle del Cauca",
          "fr": "Vallée du Cauca",
          "si": "වායි ඩෙල් කව්කා",
          "ta": "வாலியே டெல் காஉகா",
          "fi": "Valle del Cauca",
          "hi": "वाये डेल कौका",
          "zh": "卡瓜省",
        },
      ),
      States(
        name: "Vaupés",
        translations: {
          "en": "Vaupés",
          "fr": "Vaupés",
          "si": "වාපෙස්",
          "ta": "வாபேஸ்",
          "fi": "Vaupés",
          "hi": "वॉपेस",
          "zh": "瓦佩斯",
        },
      ),
      States(
        name: "Vichada",
        translations: {
          "en": "Vichada",
          "fr": "Vichada",
          "si": "විචාඩා",
          "ta": "விசாடா",
          "fi": "Vichada",
          "hi": "विचाडा",
          "zh": "维查达",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Comoros",
    iso3: "COM",
    iso2: "KM",
    phoneCode: "269",
    translations: {
      "en": "Comoros",
      "fr": "Comores",
      "si": "කොමරොස්",
      "ta": "கொமொரோசு",
      "fi": "Komorit",
      "hi": "कोमोरोस",
      "zh": "科摩罗",
    },
    flag: "🇰🇲",
    flagU: "U+1F1F0 U+1F1F2",
    states: [
      States(
        name: "Anjouan",
        translations: {
          "en": "Anjouan",
          "fr": "Anjouan",
          "si": "ඇන්ජුවාන්",
          "ta": "அஞ்சோவான்",
          "fi": "Anjouan",
          "hi": "आञ्जवान",
          "zh": "安茹安",
        },
      ),
      States(
        name: "Grande Comore",
        translations: {
          "en": "Grande Comore",
          "fr": "Grande Comore",
          "si": "ග්‍රැන්ඩ් කොමොර්",
          "ta": "கிராண்டே கொமோர்",
          "fi": "Grande Comore",
          "hi": "ग्रांड कोमोर",
          "zh": "大科莫罗",
        },
      ),
      States(
        name: "Mohéli",
        translations: {
          "en": "Mohéli",
          "fr": "Mohéli",
          "si": "මොහේලී",
          "ta": "மோஹேலி",
          "fi": "Mohéli",
          "hi": "मोहेली",
          "zh": "莫埃利",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Cook Islands",
    iso3: "COK",
    iso2: "CK",
    phoneCode: "682",
    translations: {
      "en": "Cook Islands",
      "fr": "Îles Cook",
      "si": "කුක් දිවයින්",
      "ta": "குக் தீவுகள்",
      "fi": "Cookinsaaret",
      "hi": "कुक द्वीपसमूह",
      "zh": "库克群岛",
    },
    flag: "🇨🇰",
    flagU: "U+1F1E8 U+1F1F0",
    states: [],
  ),
  CountriesStatesModel(
    name: "Costa Rica",
    iso3: "CRI",
    iso2: "CR",
    phoneCode: "506",
    translations: {
      "en": "Costa Rica",
      "fr": "Costa Rica",
      "si": "කෝස්ට රිකා",
      "ta": "கோஸ்ட்டா ரிக்கா",
      "hi": "कोस्टा रिका",
      "zh": "哥斯达黎加",
    },
    flag: "🇨🇷",
    flagU: "U+1F1E8 U+1F1F7",
    states: [
      States(
        name: "Alajuela Province",
        translations: {
          "en": "Alajuela Province",
          "fr": "Province d'Alajuela",
          "si": "අලාහුවේලා පළාත",
          "ta": "அலாகுவேலா மாகாணம்",
          "fi": "Alajuela Province",
          "hi": "आलाहुएला प्रांत",
          "zh": "阿拉惠拉省",
        },
      ),
      States(
        name: "Guanacaste Province",
        translations: {
          "en": "Guanacaste Province",
          "fr": "Province de Guanacaste",
          "si": "ග්වානකස්ට් පළාත",
          "ta": "குவானகாஸ்டி மாகாணம்",
          "fi": "Guanacaste Province",
          "hi": "गुआनाकास्टे प्रांत",
          "zh": "瓜纳卡斯特省",
        },
      ),
      States(
        name: "Heredia Province",
        translations: {
          "en": "Heredia Province",
          "fr": "Province d'Heredia",
          "si": "හෙරෙඩියා පළාත",
          "ta": "ஹெரெடியா மாகாணம்",
          "fi": "Heredia Province",
          "hi": "हेरेडिया प्रांत",
          "zh": "हेरेडिया प्रांत",
        },
      ),
      States(
        name: "Limón Province",
        translations: {
          "en": "Limón Province",
          "fr": "Province de Limón",
          "si": "ලිමන් පළාත",
          "ta": "லிமோன் மாகாணம்",
          "fi": "Limónin maakunta",
          "hi": "लिमोन प्रांत",
          "zh": "利蒙省",
        },
      ),
      States(
        name: "Provincia de Cartago",
        translations: {
          "en": "Provincia de Cartago",
          "fr": "Province de Cartago",
          "si": "කාටගො පළාත",
          "ta": "கார்டாகோ மாகாணம்",
          "fi": "Cartagon maakunta",
          "hi": "कार्तागो प्रांत",
          "zh": "卡塔戈省",
        },
      ),
      States(
        name: "Puntarenas Province",
        translations: {
          "en": "Puntarenas Province",
          "fr": "Province de Puntarenas",
          "si": "පුන්ටරෙනාස් පළාත",
          "ta": "புன்டரேனாஸ் மாகாணம்",
          "fi": "Puntarenasin maakunta",
          "hi": "पुन्तारेनास प्रांत",
          "zh": "朋塔雷納斯省",
        },
      ),
      States(
        name: "San José Province",
        translations: {
          "en": "San José Province",
          "fr": "Province de San José",
          "si": "සෑන් හොසේ පළාත",
          "ta": "சான் ஹோசே மாகாணம்",
          "fi": "San Josén maakunta",
          "hi": "सैन होसे प्रांत",
          "zh": "圣何塞省",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Cote d'Ivoire (Ivory Coast)",
    iso3: "CIV",
    iso2: "CI",
    phoneCode: "225",
    translations: {
      "en": "Ivory Coast",
      "fr": "Côte d'Ivoire",
      "si": "අයිවරි කෝස්ට්",
      "ta": "ஐவரி கோஸ்ட்",
      "fi": "Norsunluurannikko",
      "hi": "कोत दिव्वार",
      "zh": "科特迪瓦",
    },
    flag: "🇨🇮",
    flagU: "U+1F1E8 U+1F1EE",
    states: [
      States(
        name: "Abidjan",
        translations: {
          "en": "Abidjan",
          "fr": "Abidjan",
          "si": "අබිජාන්",
          "ta": "Abidjan",
          "fi": "Abidjan",
          "hi": "आबिजान",
          "zh": "阿比让",
        },
      ),
      States(
        name: "Agnéby",
        translations: {
          "en": "Agnéby",
          "fr": "Agnéby",
          "si": "ඇග්නෙබි",
          "ta": "அக்னேபி",
          "fi": "Agnéby",
          "hi": "एग्नेबी",
          "zh": "阿涅比",
        },
      ),
      States(
        name: "Bafing Region",
        translations: {
          "en": "Bafing Region",
          "fr": "Région du Bafing",
          "si": "බාෆිං කලාපය",
          "ta": "பாஃபிங் பகுதி",
          "fi": "Bafingin alue",
          "hi": "बाफिंग क्षेत्र",
          "zh": "巴芬区",
        },
      ),
      States(
        name: "Bas-Sassandra District",
        translations: {
          "en": "Bas-Sassandra District",
          "fr": "District de Bas-Sassandra",
          "si": "බාස්-සැන්ඩ්රාස් දිස්ත්‍රික්කය",
          "ta": "பாஸ்-சான்திரா மாகாணம்",
          "fi": "Bas-Sassandrain piirikunta",
          "hi": "बास-सांड्रास जिला",
          "zh": "巴薩薩德拉區",
        },
      ),
      States(
        name: "Bas-Sassandra Region",
        translations: {
          "en": "Bas-Sassandra Region",
          "fr": "Région du Bas-Sassandra",
          "si": "බාස් සන්ද්‍රාස්ස කලාපය",
          "ta": "பாஸ்-சான்திரா பிராந்தித்",
          "fi": "Bas-Sassandra-alue",
          "hi": "बास-सांड्रा क्षेत्र",
          "zh": "巴萨桑德拉大区",
        },
      ),
      States(
        name: "Comoé District",
        translations: {
          "en": "Comoé District",
          "fr": "District de Comoé",
          "si": "District de Comoé",
          "ta": "கோமோ மாகாணம்",
          "fi": "Comoéin piirikunta",
          "hi": "कोमोए जिला",
          "zh": "科莫埃区",
        },
      ),
      States(
        name: "Denguélé District",
        translations: {
          "en": "Denguélé District",
          "fr": "District de la Denguélé",
          "si": "ඩෙන්ගුලෙ දිස්ත්‍රික්කය",
          "ta": "டெங்குலே மாகாணம்",
          "fi": "Denguéléin piirikunta",
          "hi": "डेंग्गुले जिला",
          "zh": "登盖勒区",
        },
      ),
      States(
        name: "Denguélé Region",
        translations: {
          "en": "Denguélé Region",
          "fr": "Région du Denguélé",
          "si": "ඩෙන්ගුවෙල් කලාපය",
          "ta": "டெங்குவேலே பிராந்தித்",
          "fi": "Denguélé-alue",
          "hi": "देंगुएले क्षेत्र",
          "zh": "登盖勒大区",
        },
      ),
      States(
        name: "Dix-Huit Montagnes",
        translations: {
          "en": "Dix-Huit Montagnes",
          "fr": "Dix-Huit Montagnes",
          "si": "දහස් කඳු රාජවංශය",
          "ta": "பதினெட்டு மலைகள்",
          "fi": "Kahdeksantoista Vuoret",
          "hi": "अठारह पहाड़ियाँ",
          "zh": "v",
        },
      ),
      States(
        name: "Fromager",
        translations: {
          "en": "Fromager",
          "fr": "Fromager",
          "si": "ක්‍රීමාවර්",
          "ta": "பாலத்தை உருவாக்குவதானே",
          "fi": "Juustonvalmistaja",
          "hi": "पनीर बनाने वाला",
          "zh": "芝士制造商",
        },
      ),
      States(
        name: "Gôh-Djiboua District",
        translations: {
          "en": "Gôh-Djiboua District",
          "fr": "District du Gôh-Djiboua",
          "si": "ගෝ-ජිබේවා දිස්ත්‍රික්කය",
          "ta": "கோ-ஜிபோயா மாவட்டம்",
          "fi": "Gôh-Djibouan piirikunta",
          "hi": "गो-जिबोआ जनपद",
          "zh": "豪吉布阿区",
        },
      ),
      States(
        name: "Haut-Sassandra",
        translations: {
          "en": "Haut-Sassandra",
          "fr": "Haut-Sassandra",
          "si": "හෝ-සන්ඩ්‍රාසා",
          "ta": "ஹோ-சான்டிரா",
          "fi": "Ylä-Sassandra",
          "hi": "हो-सांड्रा",
          "zh": "高桑松德拉区",
        },
      ),
      States(
        name: "Lacs District",
        translations: {
          "en": "Lacs District",
          "fr": "District des Lacs",
          "si": "ලැක්ස් දිස්ත්‍රික්කය",
          "ta": "லாக்ஸ் மாவட்டம்",
          "fi": "Järvien piirikunta",
          "hi": "लैक्स जनपद",
          "zh": "拉克区",
        },
      ),
      States(
        name: "Lacs Region",
        translations: {
          "en": "Lacs Region",
          "fr": "Région des Lacs",
          "si": "ලැක්ස් කලාපය",
          "ta": "பூகங்கள் பிராந்தித்",
          "fi": "Järvien alue",
          "hi": "झील स्थान",
          "zh": "拉克斯地区",
        },
      ),
      States(
        name: "Lagunes District",
        translations: {
          "en": "Lagunes District",
          "fr": "District des Lagunes",
          "si": "ලැගුන්ස් දිස්ත්‍රික්කය",
          "ta": "லகூன்கள் மாவட்டம்",
          "fi": "Laguunien piirikunta",
          "hi": "लागुन जनपद",
          "zh": "拉古纳区",
        },
      ),
      States(
        name: "Lagunes region",
        translations: {
          "en": "Lagunes region",
          "fr": "Région des Lagunes",
          "si": "ලැගුන්ස් කලාපය",
          "ta": "லகூன்கள் பிராந்தித்",
          "fi": "Laguunien alue",
          "hi": "लागुन जनपद",
          "zh": "拉古纳区",
        },
      ),
      States(
        name: "Marahoué Region",
        translations: {
          "en": "Marahoué Region",
          "fr": "Région de la Marahoué",
          "si": "මරහවු කලාපය",
          "ta": "மரகூ மாவட்டம்",
          "fi": "Marahoué-alue",
          "hi": "माराहू जनपद",
          "zh": "马拉乌埃区",
        },
      ),
      States(
        name: "Montagnes District",
        translations: {
          "en": "Montagnes District",
          "fr": "District des Montagnes",
          "si": "ගල් බුල්ගන් දිස්ත්‍රික්කය",
          "ta": "மவுண்டேன்ஸ் மாவட்டம்",
          "fi": "Vuorten piirikunta",
          "hi": "पहाड़ जनपद",
          "zh": "山区",
        },
      ),
      States(
        name: "Moyen-Cavally",
        translations: {
          "en": "Moyen-Cavally",
          "fr": "Moyen-Cavally",
          "si": "මොයෙන්-කැවැලී",
          "ta": "மாயன்-காவாலி",
          "fi": "Moyen-Cavally",
          "hi": "मॉयेन-कैवेली",
          "zh": "中坦卡瓦利",
        },
      ),
      States(
        name: "Moyen-Comoé",
        translations: {
          "en": "Moyen-Comoé",
          "fr": "Moyen-Comoé",
          "si": "මොයෙන්-කොම්මෝ",
          "ta": "மாயன்-காவாலி",
          "fi": "Moyen-Comoé",
          "hi": "मॉयेन-कोमोए",
          "zh": "中科莫埃",
        },
      ),
      States(
        name: "N'zi-Comoé",
        translations: {
          "en": "N'zi-Comoé",
          "fr": "N'zi-Comoé",
          "si": "නි-සි-කොමෝඇ",
          "ta": "நி'சி-கொமோஇ",
          "fi": "N'zi-Comoé",
          "hi": "एनजी-कोमोए",
          "zh": "恩济科莫埃",
        },
      ),
      States(
        name: "Sassandra-Marahoué District",
        translations: {
          "en": "Sassandra-Marahoué District",
          "fr": "District de Sassandra-Marahoué",
          "si": "සැන්සන්ඩ්රා-මරහවු දිස්ත්‍රික්කය",
          "ta": "சாஸாந்திரா-மாரஹோ மாவட்டம்",
          "fi": "Sassandra-Marahoué-alue",
          "hi": "सासांद्रा-माराहू जनपद",
          "zh": "桑松德拉-马拉乌埃区",
        },
      ),
      States(
        name: "Savanes Region",
        translations: {
          "en": "Savanes Region",
          "fr": "Région des Savanes",
          "si": "සාවන්ස් කලාපය",
          "ta": "சவன்ஸ் பகுதி",
          "fi": "Savannien alue",
          "hi": "सवन्न जनपद",
          "zh": "萨瓦纳大区",
        },
      ),
      States(
        name: "Sud-Bandama",
        translations: {
          "en": "Sud-Bandama",
          "fr": "Sud-Bandama",
          "si": "සමග-බන්ඩාමා",
          "ta": "தெற்கு-பாண்டாமா",
          "fi": "Etelä-Bandama",
          "hi": "सुद-बंडामा",
          "zh": "苏德班达马",
        },
      ),
      States(
        name: "Sud-Comoé",
        translations: {
          "en": "Sud-Comoé",
          "fr": "Sud-Comoé",
          "si": "සමග-කොමොවේ",
          "ta": "தெற்கு-கோமோஇ",
          "fi": "Etelä-Comoé",
          "hi": "सुद-कोमोएा",
          "zh": "苏德科莫埃",
        },
      ),
      States(
        name: "Vallée du Bandama District",
        translations: {
          "en": "Vallée du Bandama District",
          "fr": "District de la Vallée du Bandama",
          "si": "බන්ඩාම සංචාරයේ දිස්ත්‍රික්කය",
          "ta": "வல்லே டு பாண்டாமா மாவட்டம்",
          "fi": "Bandama-laakson piirikunta",
          "hi": "बैंडामा घाटी जनपद",
          "zh": "班达马谷区",
        },
      ),
      States(
        name: "Vallée du Bandama Region",
        translations: {
          "en": "Vallée du Bandama Region",
          "fr": "Région de la Vallée du Bandama",
          "si": "වැල්ලේ ඩු බන්ඩාම පළාත්",
          "ta": "வல்லே டு பாண்டாமா பகுதி",
          "fi": "Bandama-laakson alue",
          "hi": "बैंडामा घाटी क्षेत्र",
          "zh": "班达马谷地区",
        },
      ),
      States(
        name: "Woroba District",
        translations: {
          "en": "Woroba District",
          "fr": "District du Woroba",
          "si": "වොරෝබා දිස්ත්‍රික්කය",
          "ta": "வொரோபா மாவட்டம்",
          "fi": "வொரோபா மாவட்டம்",
          "hi": "वोरोबा जनपद",
          "zh": "乌罗巴区",
        },
      ),
      States(
        name: "Worodougou",
        translations: {
          "en": "Worodougou",
          "fr": "Worodougou",
          "si": "වොරොඩූගො",
          "ta": "வொரொதோகோ",
          "fi": "වොරොඩූගො",
          "hi": "वोरोदूगु",
          "zh": "伍罗杜古",
        },
      ),
      States(
        name: "Yamoussoukro",
        translations: {
          "en": "Yamoussoukro",
          "fr": "Yamoussoukro",
          "si": "යාමුසුක්‍රෝ",
          "ta": "யாமூசுக்ரோ",
          "fi": "Yamoussoukro",
          "hi": "यामौसुक्रो",
          "zh": "雅穆苏克罗",
        },
      ),
      States(
        name: "Zanzan Region",
        translations: {
          "en": "Zanzan Region",
          "fr": "Région du Zanzan",
          "si": "සන්සාන් පළාත",
          "ta": "சாஞ்சான் பகுதி",
          "fi": "சாஞ்சான் பகுதி",
          "hi": "जांजान क्षेत्र",
          "zh": "赞赞区",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Croatia",
    iso3: "HRV",
    iso2: "HR",
    phoneCode: "385",
    translations: {
      "en": "Croatia",
      "fr": "Croatie",
      "si": "ක්‍රොඒෂියා",
      "ta": "குரோவாசியா",
      "fi": "Kroatia",
      "hi": "क्रोएशिया",
      "zh": "克罗地亚",
    },
    flag: "🇭🇷",
    flagU: "U+1F1ED U+1F1F7",
    states: [
      States(
        name: "Bjelovar-Bilogora",
        translations: {"en": "Bjelovar-Bilogora"},
      ),
      States(
        name: "Brod-Posavina",
        translations: {"en": "Brod-Posavina"},
      ),
      States(
        name: "Dubrovnik-Neretva",
        translations: {"en": "Dubrovnik-Neretva"},
      ),
      States(
        name: "Istria",
        translations: {"en": "Istria"},
      ),
      States(
        name: "Karlovac",
        translations: {"en": "Karlovac"},
      ),
      States(
        name: "Koprivnica-Križevci",
        translations: {"en": "Koprivnica-Križevci"},
      ),
      States(
        name: "Krapina-Zagorje",
        translations: {"en": "Krapina-Zagorje"},
      ),
      States(
        name: "Lika-Senj",
        translations: {"en": "Lika-Senj"},
      ),
      States(
        name: "Međimurje",
        translations: {"en": "Međimurje"},
      ),
      States(
        name: "Osijek-Baranja",
        translations: {"en": "Osijek-Baranja"},
      ),
      States(
        name: "Požega-Slavonia",
        translations: {"en": "Požega-Slavonia"},
      ),
      States(
        name: "Primorje-Gorski Kotar",
        translations: {"en": "Primorje-Gorski Kotar"},
      ),
      States(
        name: "Šibenik-Knin",
        translations: {"en": "Šibenik-Knin"},
      ),
      States(
        name: "Sisak-Moslavina",
        translations: {"en": "Sisak-Moslavina"},
      ),
      States(
        name: "Split-Dalmatia",
        translations: {"en": "Split-Dalmatia"},
      ),
      States(
        name: "Varaždin",
        translations: {
          "en": "Varaždin",
        },
      ),
      States(
        name: "Virovitica-Podravina",
        translations: {
          "en": "Virovitica-Podravina",
        },
      ),
      States(
        name: "Vukovar-Syrmia",
        translations: {
          "en": "Vukovar-Syrmia",
        },
      ),
      States(
        name: "Zadar",
        translations: {
          "en": "Zadar",
        },
      ),
      States(
        name: "Zagreb",
        translations: {
          "en": "Zagreb",
        },
      ),
      States(
        name: "Zagreb",
        translations: {
          "en": "Zagreb",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Cuba",
    iso3: "CUB",
    iso2: "CU",
    phoneCode: "53",
    translations: {
      "en": "Cuba",
      "fr": "Cuba",
      "si": "කියුබාව",
      "ta": "கியூபா",
      "fi": "Kuuba",
      "hi": "क्यूबा",
      "zh": "古巴",
    },
    flag: "🇨🇺",
    flagU: "U+1F1E8 U+1F1FA",
    states: [
      States(
        name: "Artemisa Province",
        translations: {
          "en": "Artemisa Province",
        },
      ),
      States(
        name: "Camagüey Province",
        translations: {
          "en": "Camagüey Province",
        },
      ),
      States(
        name: "Ciego de Ávila Province",
        translations: {
          "en": "Ciego de Ávila Province",
        },
      ),
      States(
        name: "Cienfuegos Province",
        translations: {
          "en": "Cienfuegos Province",
        },
      ),
      States(
        name: "Granma Province",
        translations: {
          "en": "Granma Province",
        },
      ),
      States(
        name: "Guantánamo Province",
        translations: {
          "en": "Guantánamo Province",
        },
      ),
      States(
        name: "Havana Province",
        translations: {
          "en": "Havana Province",
        },
      ),
      States(
        name: "Holguín Province",
        translations: {
          "en": "Holguín Province",
        },
      ),
      States(
        name: "Isla de la Juventud",
        translations: {
          "en": "Isla de la Juventud",
        },
      ),
      States(
        name: "Las Tunas Province",
        translations: {
          "en": "Las Tunas Province",
        },
      ),
      States(
        name: "Matanzas Province",
        translations: {
          "en": "Matanzas Province",
        },
      ),
      States(
        name: "Mayabeque Province",
        translations: {
          "en": "Mayabeque Province",
        },
      ),
      States(
        name: "Pinar del Río Province",
        translations: {
          "en": "Pinar del Río Province",
        },
      ),
      States(
        name: "Sancti Spíritus Province",
        translations: {
          "en": "Sancti Spíritus Province",
        },
      ),
      States(
        name: "Santiago de Cuba Province",
        translations: {
          "en": "Santiago de Cuba Province",
        },
      ),
      States(
        name: "Villa Clara Province",
        translations: {
          "en": "Villa Clara Province",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Curaçao",
    iso3: "CUW",
    iso2: "CW",
    phoneCode: "599",
    translations: {
      "en": "Curaçao",
      "fr": "Curaçao",
      "si": "කුරකාවෝ",
      "ta": "குராசோ",
      "hi": "कुराकाओ",
      "zh": "库拉索",
    },
    flag: "🇨🇼",
    flagU: "U+1F1E8 U+1F1FC",
    states: [],
  ),
];
