import 'package:playkosmos_v3/models/countries_states_model.dart';

const List<CountriesStatesModel> kCsTlsTuv = [
  CountriesStatesModel(
    name: "Timor-Leste",
    iso3: "TLS",
    iso2: "TL",
    phoneCode: "670",
    translations: {
      "en": "Timor-Leste",
      "fr": "Timor-Leste",
      "si": "ටිමෝර්-ලෙස්ටේ",
      "ta": "திமோர்-லெஸ்டே",
      "fi": "Itä-Timor",
      "hi": "तिमोर-लेस्ते",
      "zh": "东帝汶",
    },
    flag: "🇹🇱",
    flagU: "U+1F1F9 U+1F1F1",
    states: [
      States(
        name: "Aileu municipality",
        translations: {
          "en": "Aileu municipality",
        },
      ),
      States(
        name: "Ainaro Municipality",
        translations: {
          "en": "Ainaro Municipality",
        },
      ),
      States(
        name: "Baucau Municipality",
        translations: {
          "en": "Baucau Municipality",
        },
      ),
      States(
        name: "Bobonaro Municipality",
        translations: {
          "en": "Bobonaro Municipality",
        },
      ),
      States(
        name: "Cova Lima Municipality",
        translations: {
          "en": "Cova Lima Municipality",
        },
      ),
      States(
        name: "Dili municipality",
        translations: {
          "en": "Dili municipality",
        },
      ),
      States(
        name: "Ermera District",
        translations: {
          "en": "Ermera District",
        },
      ),
      States(
        name: "Lautém Municipality",
        translations: {
          "en": "Lautém Municipality",
        },
      ),
      States(
        name: "Liquiçá Municipality",
        translations: {
          "en": "Liquiçá Municipality",
        },
      ),
      States(
        name: "Manatuto District",
        translations: {
          "en": "Manatuto District",
        },
      ),
      States(
        name: "Manufahi Municipality",
        translations: {
          "en": "Manufahi Municipality",
        },
      ),
      States(
        name: "Viqueque Municipality",
        translations: {
          "en": "Viqueque Municipality",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Togo",
    iso3: "TGO",
    iso2: "TG",
    phoneCode: "228",
    translations: {
      "en": "Togo",
      "fr": "Togo",
      "si": "ටෝගෝ",
      "ta": "டோகோ",
      "hi": "टोगो",
      "zh": "多哥",
    },
    flag: "🇹🇬",
    flagU: "U+1F1F9 U+1F1EC",
    states: [
      States(
        name: "Centrale Region",
        translations: {
          "en": "Centrale Region",
        },
      ),
      States(name: "Kara Region", translations: {"en": "Kara Region"}),
      States(
        name: "Maritime",
        translations: {
          "en": "Maritime",
        },
      ),
      States(
        name: "Plateaux Region",
        translations: {
          "en": "Plateaux Region",
        },
      ),
      States(
        name: "Savanes Region",
        translations: {
          "en": "Savanes Region",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Tokelau",
    iso3: "TKL",
    iso2: "TK",
    phoneCode: "690",
    translations: {
      "en": "Tokelau",
      "fr": "Tokelau",
      "si": "ටොකෙලාව්",
      "ta": "டோக்கெலாவ்",
      "hi": "टोकेलाऊ",
      "zh": "托克劳",
    },
    flag: "🇹🇰",
    flagU: "U+1F1F9 U+1F1F0",
    states: [],
  ),
  CountriesStatesModel(
    name: "Tonga",
    iso3: "TON",
    iso2: "TO",
    phoneCode: "676",
    translations: {
      "en": "Tonga",
      "fr": "Tonga",
      "si": "ටොංගා",
      "ta": "டோங்கா",
      "hi": "टोंगा",
      "zh": "汤加",
    },
    flag: "🇹🇴",
    flagU: "U+1F1F9 U+1F1F4",
    states: [
      States(
        name: "Haʻapai",
        translations: {
          "en": "Haʻapai",
        },
      ),
      States(
        name: "ʻEua",
        translations: {
          "en": "ʻEua",
        },
      ),
      States(
        name: "Niuas",
        translations: {
          "en": "Niuas",
        },
      ),
      States(
        name: "Tongatapu",
        translations: {
          "en": "Tongatapu",
        },
      ),
      States(
        name: "Vavaʻu",
        translations: {
          "en": "Vavaʻu",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Trinidad and Tobago",
    iso3: "TTO",
    iso2: "TT",
    phoneCode: "1",
    translations: {
      "en": "Trinidad and Tobago",
      "fr": "Trinité et Tobago",
      "si": "ට්‍රිනිඩෑඩ් සහ ටොබැගෝ",
      "ta": "டிரினிடாட் மற்றும் டொபாகோ",
      "fi": "Trinidad ja Tobago",
      "hi": "त्रिनिदाद और टोबैगो",
      "zh": "特立尼达和多巴哥",
    },
    flag: "🇹🇹",
    flagU: "U+1F1F9 U+1F1F9",
    states: [
      States(
        name: "Arima",
        translations: {
          "en": "Arima",
          "si": "අරිමා",
          "ta": "அரிமா",
          "hi": "अरिमा",
          "zh": "阿里马",
        },
      ),
      States(
        name: "Chaguanas",
        translations: {
          "en": "Chaguanas",
          "si": "චගුආනස්",
          "ta": "சகுவானாஸ்",
          "hi": "चगवानस",
          "zh": "查瓜纳斯",
        },
      ),
      States(
        name: "Couva-Tabaquite-Talparo",
        translations: {
          "en": "Couva-Tabaquite-Talparo",
          "si": "කූවා-තබාකිටේ-තල්පාරෝ",
          "ta": "கூவா-தபாக்கிதே-தலபாறோ",
          "hi": "कूवा-तबाकिते-तलपारो",
          "zh": "库瓦-塔巴基特-塔尔帕罗",
        },
      ),
      States(
        name: "Diego Martin",
        translations: {
          "en": "Diego Martin",
          "si": "ඩියාගෝ මාටින්",
          "ta": "டியேகோ மார்டின்",
          "hi": "डिएगो मार्टिन",
          "zh": "迭戈·马丁",
        },
      ),
      States(
        name: "Mayaro–Rio Claro",
        translations: {
          "en": "Mayaro–Rio Claro",
          "si": "මායාරෝ-රියෝ ක්ලැරෝ",
          "ta": "மாயாரோ-ரியோ கிளாரோ",
          "hi": "मायारो-रियो क्लारो",
          "zh": "马亚罗-里奥克拉罗",
        },
      ),
      States(
        name: "Penal-Debe",
        translations: {
          "en": "Penal-Debe",
          "si": "පෙනල්-දෙබෙ",
          "ta": "பெனால்-டெபே",
          "hi": "पेनल-डेबे",
          "zh": "佩纳尔-德贝",
        },
      ),
      States(
        name: "Point Fortin",
        translations: {
          "en": "Point Fortin",
          "si": "පොයින්ට් ෆෝටින්",
          "ta": "பாயிண்ட் ஃபோர்டின்",
          "hi": "पॉइंट फॉर्टिन",
          "zh": "波因特福廷",
        },
      ),
      States(
        name: "Port of Spain",
        translations: {
          "en": "Port of Spain",
          "fr": "Port d'Espagne",
          "si": "ස්පාඤ්ඤ වරාය",
          "ta": "போர்ட் ஆஃப் ஸ்பெய்ன்",
          "fi": "Espanjan satama",
          "hi": "पोर्ट ऑफ स्पेन",
          "zh": "西班牙港",
        },
      ),
      States(
        name: "Princes Town",
        translations: {
          "en": "Princes Town",
          "si": "ප්‍රින්සස් ටවුන්",
          "ta": "பிரின்ஸிஸ் டவுன்",
          "hi": "प्रिंसिस टाउन",
          "zh": "王子镇",
        },
      ),
      States(
        name: "San Fernando",
        translations: {
          "en": "San Fernando",
          "si": "සැන් ෆර්නැන්ඩෝ",
          "ta": "சான் ஃபர்னாண்டோ",
          "hi": "सैन फर्नांडो",
          "zh": "圣费尔南多",
        },
      ),
      States(
        name: "San Juan-Laventille",
        translations: {
          "en": "San Juan-Laventille",
          "si": "සෑන් ජුආන්-ලැවෙන්ටිල්",
          "ta": "சான் ஜுவான்-லாவென்டில்",
          "hi": "सैन जुआन-लैवेंटिले",
          "zh": "圣胡安-拉文蒂尔",
        },
      ),
      States(
        name: "Sangre Grande",
        translations: {
          "en": "Sangre Grande",
          "si": "සංග්රේ ග්රෑන්ඩ්",
          "ta": "சங்ரே கிராண்டே",
          "hi": "संग्रे ग्रांडे",
          "zh": "大桑格雷",
        },
      ),
      States(
        name: "Siparia",
        translations: {
          "en": "Siparia",
          "si": "සිපාරියා",
          "ta": "சிபாரியா",
          "hi": "सिपारिया",
          "zh": "西帕里亚",
        },
      ),
      States(
        name: "Tobago",
        translations: {
          "en": "Tobago",
          "si": "ටොබාගෝ",
          "ta": "டொபாகோ",
          "hi": "टोबेगो",
          "zh": "多巴哥",
        },
      ),
      States(
        name: "Tunapuna-Piarco",
        translations: {
          "en": "Tunapuna-Piarco",
          "si": "ටුනාපුනා-පියර්කෝ",
          "ta": "துனபுனா-பியர்கோ",
          "hi": "तुनापुना-पिआर्को",
          "zh": "图纳普纳-皮亚尔科",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Tristan da Cunha",
    iso3: "TAA",
    iso2: "TA",
    phoneCode: "290",
    translations: {
      "en": "Tristan da Cunha",
      "si": "ට්‍රිස්ටන් ද කුන්හා",
      "ta": "டிரிஸ்டன் டா குன்ஹா",
      "hi": "त्रिस्तान दा कून्हा",
      "zh": "特里斯坦-达库尼亚",
    },
    flag: "🇹🇦",
    flagU: "U+1F1F9 U+1F1E6",
    states: [],
  ),
  CountriesStatesModel(
    name: "Tunisia",
    iso3: "TUN",
    iso2: "TN",
    phoneCode: "216",
    translations: {
      "en": "Tunisia",
      "fr": "Tunisie",
      "si": "ටියුනීසියාව",
      "ta": "தூனிசியா",
      "hi": "तूनिसीया",
      "zh": "突尼斯",
    },
    flag: "🇹🇳",
    flagU: "U+1F1F9 U+1F1F3",
    states: [
      States(
        name: "Ariana Governorate",
        translations: {
          "en": "Ariana Governorate",
          "fr": "Gouvernorat d'Ariana",
          "si": "අරියානා ගවර්නරේට්",
          "ta": "அரியானா கவர்னரேட்",
          "fi": "Arianan kuvernementti",
          "hi": "आरिआना गवर्नरेट",
          "zh": "阿里亚纳省",
        },
      ),
      States(
        name: "Béja Governorate",
        translations: {
          "en": "Béja Governorate",
          "fr": "Gouvernorat de Béja",
          "si": "බෙජා ගවර්නරේට්",
          "ta": "பெஜா கவர்னரேட்",
          "fi": "Béjan kuvernementti",
          "hi": "बेजा गवर्नरेट",
          "zh": "贝雅省",
        },
      ),
      States(
        name: "Ben Arous Governorate",
        translations: {
          "en": "Ben Arous Governorate",
          "fr": "Gouvernorat de Ben Arous",
          "si": "බෙන් අරූස් ගවර්නරේට්",
          "ta": "பென் அரூஸ் கவர்னரேட்",
          "fi": "Ben Arousin kuvernementti",
          "hi": "बेन आरूस गवर्नरेट",
          "zh": "本阿鲁斯省",
        },
      ),
      States(
        name: "Bizerte Governorate",
        translations: {
          "en": "Bizerte Governorate",
          "fr": "Gouvernorat de Bizerte",
          "si": "බිසර්ටේ ගවර්නරේට්",
          "ta": "பிசெர்டே கவர்னரேட்",
          "fi": "Bizerten kuvernementti",
          "hi": "बिज़ेर्टे गवर्नरेट",
          "zh": "比塞大省",
        },
      ),
      States(
        name: "Gabès Governorate",
        translations: {
          "en": "Gabès Governorate",
          "fr": "Gouvernorat de Gabès",
          "si": "ගබෙස් ගවර්නරේට්",
          "ta": "காபேஸ் கவர்னரேட்",
          "fi": "Gabèsin kuvernementti",
          "hi": "गाबेस गवर्नरेट",
          "zh": "加贝斯省",
        },
      ),
      States(
        name: "Gafsa Governorate",
        translations: {
          "en": "Gafsa Governorate",
          "fr": "Gouvernorat de Gafsa",
          "si": "ගාෆ්සා ගවර්නරේට්",
          "ta": "கஃப்சா கவர்னரேட்",
          "fi": "Gafsan kuvernementti",
          "hi": "गफ्सा गवर्नरेट",
          "zh": "加夫萨省",
        },
      ),
      States(
        name: "Jendouba Governorate",
        translations: {
          "en": "Jendouba Governorate",
          "fr": "Gouvernorat de Jendouba",
          "si": "ජෙන්ඩුබා ගවර්නරේට්",
          "ta": "ஜென்டூபா கவர்னரேட்",
          "fi": "Jendouban kuvernementti",
          "hi": "जेन्डौबा गवर्नरेट",
          "zh": "坚杜巴省",
        },
      ),
      States(
        name: "Kairouan Governorate",
        translations: {
          "en": "Kairouan Governorate",
          "fr": "Gouvernorat de Kairouan",
          "si": "කයිරෝවාන් ගවර්නරේට්",
          "ta": "கைரோவான் கவர்னரேட்",
          "fi": "Kairouanin kuvernementti",
          "hi": "कैरोआन गवर्नरेट",
          "zh": "凯鲁万省",
        },
      ),
      States(
        name: "Kasserine Governorate",
        translations: {
          "en": "Kasserine Governorate",
          "fr": "Gouvernorat de Kasserine",
          "si": "කසෙරීන් ගවර්නරේට්",
          "ta": "கஸ்ஸரீன் மாகாணம்",
          "fi": "Kasserinen kuvernementti",
          "hi": "कासेरीन गवर्नरेट",
          "zh": "卡塞林省",
        },
      ),
      States(
        name: "Kebili Governorate",
        translations: {
          "en": "Kebili Governorate",
          "fr": "Gouvernorat de Kébili",
          "si": "කේබිලි ගවර්නරේට්",
          "ta": "கெபிலி கவர்னரேட்",
          "fi": "Kebilin kuvernementti",
          "hi": "केबिली गवर्नरेट",
          "zh": "凯比里省",
        },
      ),
      States(
        name: "Kef Governorate",
        translations: {
          "en": "Kef Governorate",
          "fr": "Gouvernorat de Kef",
          "si": "කෙෆ් ගවර්නරේට්",
          "ta": "கெஃப் கவர்னரேட்",
          "fi": "Kefin kuvernementti",
          "hi": "केफ़ गवर्नरेट",
          "zh": "卡夫省",
        },
      ),
      States(
        name: "Mahdia Governorate",
        translations: {
          "en": "Mahdia Governorate",
          "fr": "Gouvernorat de Mahdia",
          "si": "මහ්දියා ගවර්නරේට්",
          "ta": "மஹ்தியா கவர்னரேட்",
          "fi": "Mahdian kuvernementti",
          "hi": "महदिया गवर्नरेट",
          "zh": "马赫迪耶省",
        },
      ),
      States(
        name: "Manouba Governorate",
        translations: {
          "en": "Manouba Governorate",
          "fr": "Gouvernorat de Manouba",
          "si": "මනූබා ගවර්නරේට්",
          "ta": "மனுபா கவர்னரேட்",
          "fi": "Manouban kuvernementti",
          "hi": "मनूबा गवर्नरेट",
          "zh": "马努巴省",
        },
      ),
      States(
        name: "Medenine Governorate",
        translations: {
          "en": "Medenine Governorate",
          "fr": "Gouvernorat de Médenine",
          "si": "මෙඩෙනින් ගවර්නරේට්",
          "ta": "மெடனைன் கவர்னரேட்",
          "fi": "Medeninen kuvernementti",
          "hi": "मेडेनीन गवर्नरेट",
          "zh": "梅德宁省",
        },
      ),
      States(
        name: "Monastir Governorate",
        translations: {
          "en": "Monastir Governorate",
          "fr": "Gouvernorat de Monastir",
          "si": "මොනාස්ටීර් ගවර්නරේට්",
          "ta": "மொனாஸ்டிர் கவர்னரேட்",
          "fi": "Monastirin kuvernementti",
          "hi": "मोनास्टिर गवर्नरेट",
          "zh": "莫纳斯提尔省",
        },
      ),
      States(
        name: "Nabeul Governorate",
        translations: {
          "en": "Nabeul Governorate",
          "fr": "Gouvernorat de Nabeul",
          "si": "නාබ්යුල් ගවර්නරේට්",
          "ta": "நாபியூல் கவர்னரேட்",
          "fi": "Nabeulin kuvernementti",
          "hi": "नेबुल गवर्नरेट",
          "zh": "纳布勒省",
        },
      ),
      States(
        name: "Sfax Province",
        translations: {
          "en": "Sfax Province",
          "fr": "Gouvernorat de Sfax",
          "si": "ස්ෆාක්ස් ගවර්නරේට්",
          "ta": "ஸ்ஃபாக்ஸ் கவர்னரேட்",
          "fi": "Sfaxin kuvernementti",
          "hi": "स्फ़ैक्स गवर्नरेट",
          "zh": "斯法克斯省",
        },
      ),
      States(
        name: "Sidi Bouzid Governorate",
        translations: {
          "en": "Sidi Bouzid Governorate",
          "fr": "Gouvernorat de Sidi Bouzid",
          "si": "සිඩි බුසිඩ් ගවර්නරේට්",
          "ta": "சிடி பௌசிட் கவர்னரேட்",
          "fi": "Sidi Bouzidin kuvernementti",
          "hi": "सिदी बौज़िद गवर्नरेट",
          "zh": "西迪布济德省",
        },
      ),
      States(
        name: "Siliana Governorate",
        translations: {
          "en": "Siliana Governorate",
          "fr": "Gouvernorat de Siliana",
          "si": "සිලියානා ගවර්නරේට්",
          "ta": "சிலியானா கவர்னரேட்",
          "fi": "Silianan kuvernementti",
          "hi": "सिलियाना गवर्नरेट",
          "zh": "锡利亚纳省",
        },
      ),
      States(
        name: "Sousse Governorate",
        translations: {
          "en": "Sousse Governorate",
          "fr": "Gouvernorat de Sousse",
          "si": "සූස් ගවර්නරේට්",
          "ta": "சூஸ் கவர்னரேட்",
          "fi": "Soussen kuvernementti",
          "hi": "सॉसे गवर्नरेट",
          "zh": "苏塞省",
        },
      ),
      States(
        name: "Tataouine Governorate",
        translations: {
          "en": "Tataouine Governorate",
          "fr": "Gouvernorat de Tataouine",
          "si": "ටැටාවින් ගවර්නරේට්",
          "ta": "டாடாவின் கவர்னரேட்",
          "fi": "Tataouinen kuvernementti",
          "hi": "टाटाओइन गवर्नरेट",
          "zh": "塔塔温省",
        },
      ),
      States(
        name: "Tozeur Governorate",
        translations: {
          "en": "Tozeur Governorate",
          "fr": "Gouvernorat de Tozeur",
          "si": "ටොසුර් ගවර්නරේට්",
          "ta": "தொசுர் கவர்னரேட்",
          "fi": "Tozeurin kuvernementti",
          "hi": "तोज़ूर गवर्नरेट",
          "zh": "托泽尔省",
        },
      ),
      States(
        name: "Tunis Governorate",
        translations: {
          "en": "Tunis Governorate",
          "fr": "Gouvernorat de Tunis",
          "si": "ටියුනීස් ගවර්නරේට්",
          "ta": "துனிஸ் கவர்னரேட்",
          "fi": "Tunisin kuvernementti",
          "hi": "ट्यूनिस गवर्नरेट",
          "zh": "突尼斯省",
        },
      ),
      States(
        name: "Zaghouan Governorate",
        translations: {
          "en": "Zaghouan Governorate",
          "fr": "Gouvernorat de Zaghouan",
          "si": "සංග්හොවාන් ගවර්නරේට්",
          "ta": "சகூவான் கவர்னரேட்",
          "fi": "Zaghouanin kuvernementti",
          "hi": "ज़घौआन गवर्नरेट",
          "zh": "扎古万省",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Turkey",
    iso3: "TUR",
    iso2: "TR",
    phoneCode: "90",
    translations: {
      "en": "Turkey",
      "fr": "Turquie",
      "si": "තුර්කිය",
      "ta": "துருக்கி",
      "fi": "Turkki",
      "hi": "तुर्की",
      "zh": "土耳其",
    },
    flag: "🇹🇷",
    flagU: "U+1F1F9 U+1F1F7",
    states: [
      States(
        name: "Adana Province",
        translations: {
          "en": "Adana Province",
          "fr": "Province d'Adana",
          "si": "අඩානා පළාත",
          "ta": "அடானா மாகாணம்",
          "fi": "Adanan maakunta",
          "hi": "अदाना प्रांत",
          "zh": "阿达纳省",
        },
      ),
      States(
        name: "Adıyaman Province",
        translations: {
          "en": "Adıyaman Province",
          "fr": "Province d'Adıyaman",
          "si": "අඩියමන් පළාත",
          "ta": "அதியமான் மாகாணம்",
          "fi": "Adıyamanin maakunta",
          "hi": "अदियामन प्रांत",
          "zh": "阿德亚曼省",
        },
      ),
      States(
        name: "Afyonkarahisar Province",
        translations: {
          "en": "Afyonkarahisar Province",
          "fr": "Province d'Afyonkarahisar",
          "si": "අෆ්යොංකාරහිසාර් පළාත",
          "ta": "அஃப்யோங்கராஹிசார் மாகாணம்",
          "fi": "Afyonkarahisarin maakunta",
          "hi": "अफ्योनकारहिसर प्रांत",
          "zh": "阿菲永卡拉希萨尔省",
        },
      ),
      States(
        name: "Ağrı Province",
        translations: {
          "en": "Ağrı Province",
          "fr": "Province d'Ağrı",
          "si": "ආරි පළාත",
          "ta": "ஆரி மாகாணம்",
          "fi": "Ağrın maakunta",
          "hi": "आग्री प्रांत",
          "zh": "阿勒省",
        },
      ),
      States(
        name: "Aksaray Province",
        translations: {
          "en": "Aksaray Province",
          "fr": "Province d'Aksaray",
          "si": "අක්සරයි පළාත",
          "ta": "அக்சராய் மாகாணம்",
          "fi": "Aksarayn maakunta",
          "hi": "अक्सराय प्रांत",
          "zh": "阿克萨赖省",
        },
      ),
      States(
        name: "Amasya Province",
        translations: {
          "en": "Amasya Province",
          "fr": "Province d'Amasya",
          "si": "අමස්යා පළාත",
          "ta": "அமஸ்யா மாகாணம்",
          "fi": "Amasyan maakunta",
          "hi": "अमास्या प्रांत",
          "zh": "阿马西亚省",
        },
      ),
      States(
        name: "Ankara Province",
        translations: {
          "en": "Ankara Province",
          "fr": "Province d'Ankara",
          "si": "අන්කාරා පළාත",
          "ta": "அங்காரா மாகாணம்",
          "fi": "Ankaran maakunta",
          "hi": "अंकारा प्रांत",
          "zh": "安卡拉省",
        },
      ),
      States(
        name: "Antalya Province",
        translations: {
          "en": "Antalya Province",
          "fr": "Province d'Antalya",
          "si": "ඇන්ටලියා පළාත",
          "ta": "அன்டல்யா மாகாணம்",
          "fi": "Antalyan maakunta",
          "hi": "अंताल्या प्रांत",
          "zh": "安塔利亚省",
        },
      ),
      States(
        name: "Ardahan Province",
        translations: {
          "en": "Ardahan Province",
          "fr": "Province d'Ardahan",
          "si": "අර්දහන් පළාත",
          "ta": "அர்தஹான் மாகாணம்",
          "fi": "Ardahanin maakunta",
          "hi": "अर्दहान प्रांत",
          "zh": "阿尔达汉省",
        },
      ),
      States(
        name: "Artvin Province",
        translations: {
          "en": "Artvin Province",
          "fr": "Province d'Artvin",
          "si": "ආර්ට්වින් පළාත",
          "ta": "ஆர்ட்வின் மாகாணம்",
          "fi": "Artvinin maakunta",
          "hi": "आर्टविन प्रांत",
          "zh": "阿尔特温省",
        },
      ),
      States(
        name: "Aydın Province",
        translations: {
          "en": "Aydın Province",
          "fr": "Province d'Aydın",
          "si": "අයිඩින් පළාත",
          "ta": "அய்டின் மாகாணம்",
          "fi": "Aydınin maakunta",
          "hi": "आयडिन प्रांत",
          "zh": "艾登省",
        },
      ),
      States(
        name: "Balıkesir Province",
        translations: {
          "en": "Balıkesir Province",
          "fr": "Province de Balıkesir",
          "si": "බාලකේසීර් පළාත",
          "ta": "பாலிகேசிர் மாகாணம்",
          "fi": "Balıkesirin maakunta",
          "hi": "बालिकेसिर प्रांत",
          "zh": "巴勒克西尔省",
        },
      ),
      States(
        name: "Bartın Province",
        translations: {
          "en": "Bartın Province",
          "fr": "Province de Bartın",
          "si": "බාර්ටින් පළාත",
          "ta": "பார்டின் மாகாணம்",
          "fi": "Bartınin maakunta",
          "hi": "बार्तिन प्रांत",
          "zh": "巴尔廷省",
        },
      ),
      States(
        name: "Batman Province",
        translations: {
          "en": "Batman Province",
          "fr": "Province de Batman",
          "si": "බට්මෑන් පළාත",
          "ta": "பாட்மான் மாகாணம்",
          "fi": "Batmanin maakunta",
          "hi": "बैटमैन प्रांत",
          "zh": "巴特曼省",
        },
      ),
      States(
        name: "Bayburt Province",
        translations: {
          "en": "Bayburt Province",
          "fr": "Province de Bayburt",
          "si": "බේබර්ට් පළාත",
          "ta": "பேபர்ட் மாகாணம்",
          "fi": "Bayburtin maakunta",
          "hi": "बेबर्ट प्रांत",
          "zh": "巴伊布尔特省",
        },
      ),
      States(
        name: "Bilecik Province",
        translations: {
          "en": "Bilecik Province",
          "fr": "Province de Bilecik",
          "si": "බිලෙසික් පළාත",
          "ta": "பிலேசிக் மாகாணம்",
          "fi": "Bilecikin maakunta",
          "hi": "बिलेसिक प्रांत",
          "zh": "比莱吉克省",
        },
      ),
      States(
        name: "Bingöl Province",
        translations: {
          "en": "Bingöl Province",
          "fr": "Province de Bingöl",
          "si": "බිංගෝල් පළාත",
          "ta": "பிங்கோல் மாகாணம்",
          "fi": "Bingölin maakunta",
          "hi": "बिंगोल प्रांत",
          "zh": "宾格尔省",
        },
      ),
      States(
        name: "Bitlis Province",
        translations: {
          "en": "Bitlis Province",
          "fr": "Province de Bitlis",
          "si": "බිට්ලිස් පළාත",
          "ta": "பிட்லிஸ் மாகாணம்",
          "fi": "Bitlisin maakunta",
          "hi": "बिट्लिस प्रांत",
          "zh": "比特利斯省",
        },
      ),
      States(
        name: "Bolu Province",
        translations: {
          "en": "Bolu Province",
          "fr": "Province de Bolu",
          "si": "බොලු පළාත",
          "ta": "போலு மாகாணம்",
          "fi": "Bolun maakunta",
          "hi": "बोलू प्रांत",
          "zh": "博卢省",
        },
      ),
      States(
        name: "Burdur Province",
        translations: {
          "en": "Burdur Province",
          "fr": "Province de Burdur",
          "si": "බුර්දුර් පළාත",
          "ta": "புர்தூர் மாகாணம்",
          "fi": "Burdurin maakunta",
          "hi": "बुरदुर प्रांत",
          "zh": "布尔杜尔省",
        },
      ),
      States(
        name: "Bursa Province",
        translations: {
          "en": "Bursa Province",
          "fr": "Province de Bursa",
          "si": "බුර්සා පළාත",
          "ta": "பர்சா மாகாணம்",
          "fi": "Bursan maakunta",
          "hi": "बुर्सा प्रांत",
          "zh": "布尔萨省",
        },
      ),
      States(
        name: "Çanakkale Province",
        translations: {
          "en": "Çanakkale Province",
          "fr": "Province de Çanakkale",
          "si": "චානකලේ පළාත",
          "ta": "கனக்கலே மாகாணம்",
          "fi": "Çanakkalen maakunta",
          "hi": "चानककाले प्रांत",
          "zh": "恰纳卡莱省",
        },
      ),
      States(
        name: "Çankırı Province",
        translations: {
          "en": "Çankırı Province",
          "fr": "Province de Çankırı",
          "si": "චන්කිරි පළාත",
          "ta": "கான்கிரி மாகாணம்",
          "fi": "Çankırın maakunta",
          "hi": "चांकिरी प्रांत",
          "zh": "昌克勒省",
        },
      ),
      States(
        name: "Çorum Province",
        translations: {
          "en": "Çorum Province",
          "fr": "Province de Çorum",
          "si": "චොරම් පළාත",
          "ta": "கோரம் மாகாணம்",
          "fi": "Çorumin maakunta",
          "hi": "चोरम प्रांत",
          "zh": "乔鲁姆省",
        },
      ),
      States(
        name: "Denizli Province",
        translations: {
          "en": "Denizli Province",
          "fr": "Province de Denizli",
          "si": "ඩෙනිස්ලි පළාත",
          "ta": "டெனிஸ்லி மாகாணம்",
          "fi": "Denizlin maakunta",
          "hi": "डेनिज़्ली प्रांत",
          "zh": "代尼兹利省",
        },
      ),
      States(
        name: "Diyarbakır",
        translations: {
          "en": "Diyarbakır Province",
          "fr": "Province de Diyarbakır",
          "si": "දියර්බකීර් පළාත",
          "ta": "தியர்பாகிர் மாகாணம்",
          "fi": "Diyarbakırin maakunta",
          "hi": "दियारबाकिर प्रांत",
          "zh": "迪亚巴克尔省",
        },
      ),
      States(
        name: "Düzce Province",
        translations: {
          "en": "Düzce Province",
          "fr": "Province de Düzce",
          "si": "ඩුස්චේ පළාත",
          "ta": "டுஸ்ஜ மாகாணம்",
          "fi": "Düzcen maakunta",
          "hi": "डुज़से प्रांत",
          "zh": "迪兹杰省",
        },
      ),
      States(
        name: "Edirne Province",
        translations: {
          "en": "Edirne Province",
          "fr": "Province de Edirne",
          "si": "එඩිර්න් පළාත",
          "ta": "எடிர்னே மாகாணம்",
          "fi": "Edirnen maakunta",
          "hi": "एडरने प्रांत",
          "zh": "埃迪尔内省",
        },
      ),
      States(
        name: "Elazığ Province",
        translations: {
          "en": "Elazığ Province",
          "fr": "Province de Elazığ",
          "si": "එලාසීග් පළාත",
          "ta": "எலாசிக் மாகாணம்",
          "fi": "Elazığin maakunta",
          "hi": "एलाजिग प्रांत",
          "zh": "埃拉泽省",
        },
      ),
      States(
        name: "Erzincan Province",
        translations: {
          "en": "Erzincan Province",
          "fr": "Province de Erzincan",
          "si": "එර්සින්ජාන් පළාත",
          "ta": "எர்சின்ஜான் மாகாணம்",
          "fi": "Erzincanin maakunta",
          "hi": "एर्ज़िनकन प्रांत",
          "zh": "埃尔津詹省",
        },
      ),
      States(
        name: "Erzurum Province",
        translations: {
          "en": "Erzurum Province",
          "fr": "Province de Erzurum",
          "si": "එර්සුරුම් පළාත",
          "ta": "எர்சுரம் மாகாணம்",
          "fi": "Erzurumin maakunta",
          "hi": "एरजुरम प्रांत",
          "zh": "埃尔祖鲁姆省",
        },
      ),
      States(
        name: "Eskişehir Province",
        translations: {
          "en": "Eskişehir Province",
          "fr": "Province de Eskişehir",
          "si": "එස්කිෂේහිර් පළාත",
          "ta": "எஸ்கிசெஹிர் மாகாணம்",
          "fi": "Eskişehirin maakunta",
          "hi": "एस्किशेहिर प्रांत",
          "zh": "埃斯基谢希尔省",
        },
      ),
      States(
        name: "Gaziantep Province",
        translations: {
          "en": "Gaziantep Province",
          "fr": "Province de Gaziantep",
          "si": "ගැසියන්ටෙප් පළාත",
          "ta": "காசியான்டெப் மாகாணம்",
          "fi": "Gaziantepin maakunta",
          "hi": "गाज़ियांटेप प्रांत",
          "zh": "加济安泰普省",
        },
      ),
      States(
        name: "Giresun Province",
        translations: {
          "en": "Giresun Province",
          "fr": "Province de Giresun",
          "si": "ගිරේසුන් පළාත",
          "ta": "கிரேசுன் மாகாணம்",
          "fi": "Giresunin maakunta",
          "hi": "गिरेसुन प्रांत",
          "zh": "吉雷松省",
        },
      ),
      States(
        name: "Gümüşhane Province",
        translations: {
          "en": "Gümüşhane Province",
          "fr": "Province de Gümüşhane",
          "si": "ගුමුෂානේ පළාත",
          "ta": "குமுஷானே மாகாணம்",
          "fi": "Gümüşhanen maakunta",
          "hi": "गुमुशाने प्रांत",
          "zh": "古穆沙内省",
        },
      ),
      States(
        name: "Hakkâri Province",
        translations: {
          "en": "Hakkâri Province",
          "fr": "Province de Hakkâri",
          "si": "හක්කාරි පළාත",
          "ta": "ஹக்காரி மாகாணம்",
          "fi": "Hakkârin maakunta",
          "hi": "हक्कारी प्रांत",
          "zh": "哈卡里省",
        },
      ),
      States(
        name: "Hatay Province",
        translations: {
          "en": "Hatay Province",
          "fr": "Province de Hatay",
          "si": "හටෙයි පළාත",
          "ta": "ஹடாய் மாகாணம்",
          "fi": "Hatayn maakunta",
          "hi": "हटे प्रांत",
          "zh": "哈塔伊省",
        },
      ),
      States(
        name: "Iğdır Province",
        translations: {
          "en": "Iğdır Province",
          "fr": "Province d'Iğdır",
          "si": "ඉග්ඩිර් පළාත",
          "ta": "இக்திர் மாகாணம்",
          "fi": "Iğdırin maakunta",
          "hi": "इग्दिर प्रांत",
          "zh": "伊格迪尔省",
        },
      ),
      States(
        name: "Isparta Province",
        translations: {
          "en": "Isparta Province",
          "fr": "Province d'Isparta",
          "si": "ඉස්පාර්ටා පළාත",
          "ta": "இஸ்பார்டா மாகாணம்",
          "fi": "Ispartan maakunta",
          "hi": "इस्पार्टा प्रांत",
          "zh": "伊斯帕尔塔省",
        },
      ),
      States(
        name: "İstanbul",
        translations: {
          "en": "İstanbul",
          "si": "ඉස්තාන්බුල්",
          "ta": "இஸ்தான்புல்",
          "hi": "इस्तांबुल",
          "zh": "伊斯坦布尔",
        },
      ),
      States(
        name: "İzmir Province",
        translations: {
          "en": "İzmir Province",
          "fr": "Province d'İzmir",
          "si": "ඉස්මිර් පළාත",
          "ta": "இஸ்மிர் மாகாணம்",
          "fi": "İzmirin maakunta",
          "hi": "इजमीर प्रांत",
          "zh": "伊兹密尔省",
        },
      ),
      States(
        name: "Kahramanmaraş Province",
        translations: {
          "en": "Kahramanmaraş Province",
          "fr": "Province de Kahramanmaraş",
          "si": "කහ්රාමන්මරාශ් පළාත",
          "ta": "கஹ்ராமான்மராஷ் மாகாணம்",
          "fi": "Kahramanmaraşin maakunta",
          "hi": "काह्रामानमरास प्रांत",
          "zh": "卡赫拉曼马拉什省",
        },
      ),
      States(
        name: "Karabük Province",
        translations: {
          "en": "Karabük Province",
          "fr": "Province de Karabük",
          "si": "කරබුක් පළාත",
          "ta": "கராபுக் மாகாணம்",
          "fi": "Karabükin maakunta",
          "hi": "काराबुक प्रांत",
          "zh": "卡拉布克省",
        },
      ),
      States(
        name: "Karaman Province",
        translations: {
          "en": "Karaman Province",
          "fr": "Province de Karaman",
          "si": "කරමන් පළාත",
          "ta": "கரமன் மாகாணம்",
          "fi": "Karamanin maakunta",
          "hi": "कारमान प्रांत",
          "zh": "卡拉曼省",
        },
      ),
      States(
        name: "Kars Province",
        translations: {
          "en": "Kars Province",
          "fr": "Province de Kars",
          "si": "කාර්ස් පළාත",
          "ta": "கார்ஸ் மாகாணம்",
          "fi": "Karsin maakunta",
          "hi": "कार्स प्रांत",
          "zh": "卡尔斯省",
        },
      ),
      States(
        name: "Kastamonu Province",
        translations: {
          "en": "Kastamonu Province",
          "fr": "Province de Kastamonu",
          "si": "කස්ටමෝනු පළාත",
          "ta": "கஸ்டமோனு மாகாணம்",
          "fi": "Kastamonun maakunta",
          "hi": "कस्तमोनू प्रांत",
          "zh": "卡斯塔莫努省",
        },
      ),
      States(
        name: "Kayseri Province",
        translations: {
          "en": "Kayseri Province",
          "fr": "Province de Kayseri",
          "si": "කයිසේරි පළාත",
          "ta": "கைசேரி மாகாணம்",
          "fi": "Kayserin maakunta",
          "hi": "काइसेरी प्रांत",
          "zh": "开塞利省",
        },
      ),
      States(
        name: "Kilis Province",
        translations: {
          "en": "Kilis Province",
          "fr": "Province de Kilis",
          "si": "කිලිස් පළාත",
          "ta": "கிலிஸ் மாகாணம்",
          "fi": "Kilisin maakunta",
          "hi": "किलिस प्रांत",
          "zh": "基利斯省",
        },
      ),
      States(
        name: "Kırıkkale Province",
        translations: {
          "en": "Kırıkkale Province",
          "fr": "Province de Kırıkkale",
          "si": "කිරික්කලේ පළාත",
          "ta": "கிரிக்கலே மாகாணம்",
          "fi": "Kırıkkalen maakunta",
          "hi": "किरिक्काले प्रांत",
          "zh": "克勒克卡莱省",
        },
      ),
      States(
        name: "Kırklareli Province",
        translations: {
          "en": "Kırklareli Province",
          "fr": "Province de Kırklareli",
          "si": "කර්ක්ලරෙලි පළාත",
          "ta": "கிர்க்லரேலி மாகாணம்",
          "fi": "Kırklarelin maakunta",
          "hi": "किर्कलारेली प्रांत",
          "zh": "柯克拉雷利省",
        },
      ),
      States(
        name: "Kırşehir Province",
        translations: {
          "en": "Kırşehir Province",
          "fr": "Province de Kırşehir",
          "si": "කිර්ෂෙහිර් පළාත",
          "ta": "கிர்செஹிர் மாகாணம்",
          "fi": "Kırşehirin maakunta",
          "hi": "किरशेहीर प्रांत",
          "zh": "克尔谢希尔省",
        },
      ),
      States(
        name: "Kocaeli Province",
        translations: {
          "en": "Kocaeli Province",
          "fr": "Province de Kocaeli",
          "si": "කොකේලි පළාත",
          "ta": "கோகேலி மாகாணம்",
          "fi": "Kocaelin maakunta",
          "hi": "कोचेली प्रांत",
          "zh": "科贾埃利省",
        },
      ),
      States(
        name: "Konya Province",
        translations: {
          "en": "Konya Province",
          "fr": "Province de Konya",
          "si": "කෝන්යා පළාත",
          "ta": "கொன்யா மாகாணம்",
          "fi": "Konyan maakunta",
          "hi": "कोन्या प्रांत",
          "zh": "科尼亚省",
        },
      ),
      States(
        name: "Kütahya Province",
        translations: {
          "en": "Kütahya Province",
          "fr": "Province de Kütahya",
          "si": "කුටාහ්යා පළාත",
          "ta": "குதாஹ்யா மாகாணம்",
          "fi": "Kütahyan maakunta",
          "hi": "कुटाह्या प्रांत",
          "zh": "屈塔希亚省",
        },
      ),
      States(
        name: "Malatya Province",
        translations: {
          "en": "Malatya Province",
          "fr": "Province de Malatya",
          "si": "මලත්යා පළාත",
          "ta": "மாலத்யா மாகாணம்",
          "fi": "Malatyan maakunta",
          "hi": "मालट्या प्रांत",
          "zh": "马拉蒂亚省",
        },
      ),
      States(
        name: "Manisa Province",
        translations: {
          "en": "Manisa Province",
          "fr": "Province de Manisa",
          "si": "මනිසා පළාත",
          "ta": "மனிசா மாகாணம்",
          "fi": "Manisan maakunta",
          "hi": "मनीसा प्रांत",
          "zh": "马尼萨省",
        },
      ),
      States(
        name: "Mardin Province",
        translations: {
          "en": "Mardin Province",
          "fr": "Province de Mardin",
          "si": "මාර්දින් පළාත",
          "ta": "மார்தின் மாகாணம்",
          "fi": "Mardinin maakunta",
          "hi": "मर्दिन प्रांत",
          "zh": "马尔丁省",
        },
      ),
      States(
        name: "Mersin Province",
        translations: {
          "en": "Mersin Province",
          "fr": "Province de Mersin",
          "si": "මර්සින් පළාත",
          "ta": "மெர்சின் மாகாணம்",
          "fi": "Mersinin maakunta",
          "hi": "मेर्सिन प्रांत",
          "zh": "梅尔辛省",
        },
      ),
      States(
        name: "Muğla Province",
        translations: {
          "en": "Muğla Province",
          "fr": "Province de Muğla",
          "si": "මුග්ලා පළාත",
          "ta": "முக்லா மாகாணம்",
          "fi": "Muğlan maakunta",
          "hi": "मुग्ला प्रांत",
          "zh": "穆拉省",
        },
      ),
      States(
        name: "Muş Province",
        translations: {
          "en": "Muş Province",
          "fr": "Province de Muş",
          "si": "මුස් පළාත",
          "ta": "முஷ் மாகாணம்",
          "fi": "Muşin maakunta",
          "hi": "मुस प्रान्त",
          "zh": "穆什省",
        },
      ),
      States(
        name: "Nevşehir Province",
        translations: {
          "en": "Nevşehir Province",
          "fr": "Province de Nevşehir",
          "si": "නෙව්ෂෙහිර් පළාත",
          "ta": "நெவ்ஷெஹிர் மாகாணம்",
          "fi": "Nevşehirin maakunta",
          "hi": "नेवशेहिर प्रांत",
          "zh": "内夫谢希尔省",
        },
      ),
      States(
        name: "Niğde Province",
        translations: {
          "en": "Niğde Province",
          "fr": "Province de Niğde",
          "si": "නිග්දේ පළාත",
          "ta": "நிக்தே மாகாணம்",
          "fi": "Niğden maakunta",
          "hi": "निग्दे प्रांत",
          "zh": "尼代省",
        },
      ),
      States(
        name: "Ordu Province",
        translations: {
          "en": "Ordu Province",
          "fr": "Province d'Ordu",
          "si": "ඔර්දු පළාත",
          "ta": "ஒர்டு மாகாணம்",
          "fi": "Orduin maakunta",
          "hi": "ओर्डु प्रांत",
          "zh": "奥尔杜省",
        },
      ),
      States(
        name: "Osmaniye Province",
        translations: {
          "en": "Osmaniye Province",
          "fr": "Province d'Osmaniye",
          "si": "ඕස්මානියේ පළාත",
          "ta": "ஒஸ்மானியே மாகாணம்",
          "fi": "Osmaniyen maakunta",
          "hi": "ओस्मानिये प्रांत",
          "zh": "奥斯曼尼耶省",
        },
      ),
      States(
        name: "Rize Province",
        translations: {
          "en": "Rize Province",
          "fr": "Province de Rize",
          "si": "රිසේ පළාත",
          "ta": "ரிசே மாகாணம்",
          "fi": "Rizen maakunta",
          "hi": "रिज़े प्रांत",
          "zh": "里泽省",
        },
      ),
      States(
        name: "Sakarya Province",
        translations: {
          "en": "Sakarya Province",
          "fr": "Province de Sakarya",
          "si": "සකරියා පළාත",
          "ta": "சகார்யா மாகாணம்",
          "fi": "Sakaryan maakunta",
          "hi": "साकार्या प्रांत",
          "zh": "萨卡里亚省",
        },
      ),
      States(
        name: "Samsun Province",
        translations: {
          "en": "Samsun Province",
          "fr": "Province de Samsun",
          "si": "සම්සුන් පළාත",
          "ta": "சம்சுன் மாகாணம்",
          "fi": "Samsunin maakunta",
          "hi": "सम्सुन प्रांत",
          "zh": "萨姆松省",
        },
      ),
      States(
        name: "Şanlıurfa Province",
        translations: {
          "en": "Şanlıurfa Province",
          "fr": "Province de Şanlıurfa",
          "si": "ශන්ලීඔව්ර්ෆා පළාත",
          "ta": "சான்லியுர்ஃபா மாகாணம்",
          "fi": "Şanlıurfan maakunta",
          "hi": "शान्लीउर्फा प्रांत",
          "zh": "尚勒乌尔法省",
        },
      ),
      States(
        name: "Siirt Province",
        translations: {
          "en": "Siirt Province",
          "fr": "Province de Siirt",
          "si": "සියර්ට් පළාත",
          "ta": "சிர்ட் மாகாணம்",
          "fi": "Siirtin maakunta",
          "hi": "सिइर्ट प्रांत",
          "zh": "西尔特省",
        },
      ),
      States(
        name: "Sinop Province",
        translations: {
          "en": "Sinop Province",
          "fr": "Province de Sinop",
          "si": "සිනොප් පළාත",
          "ta": "சினோப் மாகாணம்",
          "fi": "Sinopin maakunta",
          "hi": "सिनोप प्रांत",
          "zh": "锡诺普省",
        },
      ),
      States(
        name: "Sivas Province",
        translations: {
          "en": "Sivas Province",
          "fr": "Province de Sivas",
          "si": "සිවස් පළාත",
          "ta": "சிவாஸ் மாகாணம்",
          "fi": "Sivasin maakunta",
          "hi": "सिवास प्रांत",
          "zh": "锡瓦斯省",
        },
      ),
      States(
        name: "Şırnak Province",
        translations: {
          "en": "Şırnak Province",
          "fr": "Province de Şırnak",
          "si": "ෂිර්නක් පළාත",
          "ta": "சிற்னக் மாகாணம்",
          "fi": "Şırnakin maakunta",
          "hi": "शिरनाक प्रांत",
          "zh": "舍尔纳克省",
        },
      ),
      States(
        name: "Tekirdağ Province",
        translations: {
          "en": "Tekirdağ Province",
          "fr": "Province de Tekirdağ",
          "si": "ටෙකීර්දාග් පළාත",
          "ta": "டெகிர்டாக் மாகாணம்",
          "fi": "Tekirdağin maakunta",
          "hi": "तेकिरदाग प्रांत",
          "zh": "泰基尔达省",
        },
      ),
      States(
        name: "Tokat Province",
        translations: {
          "en": "Tokat Province",
          "fr": "Province de Tokat",
          "si": "ටෝකට් පළාත",
          "ta": "தோகத் மாகாணம்",
          "fi": "Tokatin maakunta",
          "hi": "टोकाट प्रान्त",
          "zh": "托卡特省",
        },
      ),
      States(
        name: "Trabzon Province",
        translations: {
          "en": "Trabzon Province",
          "fr": "Province de Trabzon",
          "si": "ට්‍රාබ්සොන් පළාත",
          "ta": "டிராப்சோன் மாகாணம்",
          "fi": "Trabzonin maakunta",
          "hi": "त्राबजोन प्रांत",
          "zh": "特拉布宗省",
        },
      ),
      States(
        name: "Tunceli Province",
        translations: {
          "en": "Tunceli Province",
          "fr": "Province de Tunceli",
          "si": "ටුන්සෙලි පළාත",
          "ta": "துன்செலி மாகாணம்",
          "fi": "Tuncelin maakunta",
          "hi": "टुंसेली प्रांत",
          "zh": "通杰利省",
        },
      ),
      States(
        name: "Uşak Province",
        translations: {
          "en": "Uşak Province",
          "fr": "Province d'Uşak",
          "si": "උෂක් පළාත",
          "ta": "உஷக் மாகாணம்",
          "fi": "Uşakin maakunta",
          "hi": "उशाक प्रांत",
          "zh": "乌沙克省",
        },
      ),
      States(
        name: "Van Province",
        translations: {
          "en": "Van Province",
          "fr": "Province de Van",
          "si": "වාන් පළාත",
          "ta": "வான் மாகாணம்",
          "fi": "Vanin maakunta",
          "hi": "वैन प्रांत",
          "zh": "凡省",
        },
      ),
      States(
        name: "Yalova Province",
        translations: {
          "en": "Yalova Province",
          "fr": "Province de Yalova",
          "si": "යලෝවා පළාත",
          "ta": "யலோவா மாகாணம்",
          "fi": "Yalovan maakunta",
          "hi": "यालोवा प्रांत",
          "zh": "亚洛瓦省",
        },
      ),
      States(
        name: "Yozgat Province",
        translations: {
          "en": "Yozgat Province",
          "fr": "Province de Yozgat",
          "si": "යොස්ගාට් පළාත",
          "ta": "யோஸ்காட் மாகாணம்",
          "fi": "Yozgatin maakunta",
          "hi": "योज़गाट प्रांत",
          "zh": "约兹加特省",
        },
      ),
      States(
        name: "Zonguldak Province",
        translations: {
          "en": "Zonguldak Province",
          "fr": "Province de Zonguldak",
          "si": "සොන්ගුල්ඩක් පළාත",
          "ta": "சோங்குல்டாக் மாகாணம்",
          "fi": "Zonguldakin maakunta",
          "hi": "ज़ोंगुलडक प्रांत",
          "zh": "宗古尔达克省",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Turkmenistan",
    iso3: "TKM",
    iso2: "TM",
    phoneCode: "993",
    translations: {
      "en": "Turkmenistan",
      "fr": "Turkménistan",
      "si": "ටර්ක්මෙනිස්තානය",
      "ta": "துருக்மெனிஸ்தான்",
      "hi": "तुर्कमेनिस्तान",
      "zh": "土库曼斯坦",
    },
    flag: "🇹🇲",
    flagU: "U+1F1F9 U+1F1F2",
    states: [
      States(
        name: "Ahal Province",
        translations: {
          "en": "Ahal Province",
          "fr": "Province d'Ahal",
          "si": "ඇහාල් පළාත",
          "ta": "அஹல் மாகாணம்",
          "fi": "Ahalin maakunta",
          "hi": "अहल प्रांत",
          "zh": "阿哈尔省",
        },
      ),
      States(
        name: "Ashgabat",
        translations: {
          "en": "Ashgabat",
          "fr": "Achgabat",
          "si": "අෂ්ගාබාත්",
          "ta": "அஷ்கபத்",
          "fi": "Ašgabat",
          "hi": "अश्गाबात",
          "zh": "阿什哈巴德",
        },
      ),
      States(
        name: "Balkan Province",
        translations: {
          "en": "Balkan Province",
          "fr": "Province de Balkan",
          "si": "බෝල්කන් පළාත",
          "ta": "பால்கன் மாகாணம்",
          "fi": "Balkanin maakunta",
          "hi": "बाल्कन प्रांत",
          "zh": "巴尔干省",
        },
      ),
      States(
        name: "Daşoguz Province",
        translations: {
          "en": "Daşoguz Province",
          "fr": "Province de Daşoguz",
          "si": "ඩෂෝගුස් පළාත",
          "ta": "தாஷோகுஸ் மாகாணம்",
          "fi": "Daşoguzin maakunta",
          "hi": "दाषोगुज़ प्रांत",
          "zh": "达沙古兹省",
        },
      ),
      States(
        name: "Lebap Province",
        translations: {
          "en": "Lebap Province",
          "fr": "Province de Lebap",
          "si": "ලෙබප් පළාත",
          "ta": "லெபாப் மாகாணம்",
          "fi": "Lebapin maakunta",
          "hi": "लेबाप प्रांत",
          "zh": "列巴普省",
        },
      ),
      States(
        name: "Mary Province",
        translations: {
          "en": "Mary Province",
          "fr": "Province de Mary",
          "si": "මෙරි පළාත",
          "ta": "மேரி மாகாணம்",
          "fi": "Maryn maakunta",
          "hi": "मैरी प्रांत",
          "zh": "玛丽省",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Turks and Caicos Islands",
    iso3: "TCA",
    iso2: "TC",
    phoneCode: "1",
    translations: {
      "en": "Turks and Caicos Islands",
      "fr": "Îles Turques-et-Caïques",
      "si": "ටර්ක්ස් සහ කයිකෝස් දූපත්",
      "ta": "துர்கசு கைகோசு தீவுகள்",
      "fi": "Turks- ja Caicossaaret",
      "hi": "तुर्क और केकोस द्वीपसमूह",
      "zh": "特克斯和凯科斯群岛",
    },
    flag: "🇹🇨",
    flagU: "U+1F1F9 U+1F1E8",
    states: [],
  ),
  CountriesStatesModel(
    name: "Tuvalu",
    iso3: "TUV",
    iso2: "TV",
    phoneCode: "688",
    translations: {
      "en": "Tuvalu",
      "fr": "Tuvalu",
      "si": "ටුවාලු",
      "ta": "துவாலு",
      "hi": "तुवालू",
      "zh": "图瓦卢",
    },
    flag: "🇹🇻",
    flagU: "U+1F1F9 U+1F1FB",
    states: [
      States(
        name: "Funafuti",
        translations: {
          "en": "Funafuti",
          "si": "ෆුනාෆුටි",
          "ta": "ஃபுனாஃபுட்டி",
          "hi": "फुनाफुटी",
          "zh": "富纳富提",
        },
      ),
      States(
        name: "Nanumanga",
        translations: {
          "en": "Nanumanga",
          "si": "නානුමංග",
          "ta": "நானுமங்கா",
          "hi": "ननुमंगा",
          "zh": "纳努曼加",
        },
      ),
      States(
        name: "Nanumea",
        translations: {
          "en": "Nanumea",
          "si": "නානුමෙයා",
          "ta": "நானுமேயா",
          "hi": "ननुमेअ",
          "zh": "纳努梅阿",
        },
      ),
      States(
        name: "Niulakita",
        translations: {
          "en": "Niulakita",
          "si": "නියුලකිටා",
          "ta": "நியூலகிடா",
          "hi": "नीउलाकिटा",
          "zh": "纽拉基塔",
        },
      ),
      States(
        name: "Niutao",
        translations: {
          "en": "Niutao",
          "si": "නියුටාඕ",
          "ta": "நியூடாவோ",
          "hi": "निउताओ",
          "zh": "牛涛",
        },
      ),
      States(
        name: "Nui",
        translations: {
          "en": "Nui",
          "si": "නුයි",
          "ta": "நுய்",
          "hi": "नुई",
          "zh": "努伊",
        },
      ),
      States(
        name: "Nukufetau",
        translations: {
          "en": "Nukufetau",
          "si": "නුකුෆෙටවු",
          "ta": "நுகுஃபெடௌ",
          "hi": "नुकुफेतौ",
          "zh": "努库费陶",
        },
      ),
      States(
        name: "Nukulaelae",
        translations: {
          "en": "Nukulaelae",
          "si": "නුකුලඒලේ",
          "ta": "நுகுலேலே",
          "hi": "नुकुलेले",
          "zh": "努库莱莱",
        },
      ),
      States(
        name: "Vaitupu",
        translations: {
          "en": "Vaitupu",
          "si": "වෛටුපු",
          "ta": "வைடுபு",
          "hi": "वैतुपु",
          "zh": "瓦伊图普",
        },
      ),
    ],
  ),
];
