import 'package:playkosmos_v3/models/countries_states_model.dart';

const List<CountriesStatesModel> kCsUzbZwe = [
  CountriesStatesModel(
    name: "Uzbekistan",
    iso3: "UZB",
    iso2: "UZ",
    phoneCode: "998",
    translations: {
      "en": "Uzbekistan",
      "fr": "Ouzbékistan",
      "si": "උස්බෙකිස්තානය",
      "ta": "உசுபெக்கிசுத்தான்",
      "hi": "उज़्बेकिस्तान",
      "zh": "乌兹别克斯坦",
    },
    flag: "🇺🇿",
    flagU: "U+1F1FA U+1F1FF",
    states: [
      States(
        name: "Tashkent",
        translations: {
          "en": "Tashkent",
          "fr": "Tachkent",
          "si": "ටෂ්කන්ට්",
          "ta": "தாஷ்கந்து",
          "fi": "Taškent",
          "hi": "ताशकेंट",
          "zh": "塔什干",
        },
      ),
      States(
        name: "Andijan Region",
        translations: {
          "en": "Andijan Region",
          "fr": "Province d'Andijan",
          "si": "ඇන්ඩිජන් කලාපය",
          "ta": "அந்திச்சான் பிராந்தியம்",
          "fi": "Andižanin alue",
          "hi": "अन्दीझ़ान प्रान्त",
          "zh": "安集延州",
        },
      ),
      States(
        name: "Bukhara Region",
        translations: {
          "en": "Bukhara Region",
          "fr": "Province de Boukhara",
          "si": "බුහාරා කලාපය",
          "ta": "புகாரா பிராந்தியம்",
          "fi": "Buharan alue",
          "hi": "बुख़ारा प्रान्त",
          "zh": "布哈拉州",
        },
      ),
      States(
        name: "Fergana Region",
        translations: {
          "en": "Fergana Region",
          "fr": "Province de Ferghana",
          "si": "ෆර්ගානා කලාපය",
          "ta": "ஃபெர்கானா பிராந்தியம்",
          "fi": "Ferganan alue",
          "hi": "फ़रग़ना प्रान्त",
          "zh": "费尔干纳州",
        },
      ),
      States(
        name: "Jizzakh Region",
        translations: {
          "en": "Jizzakh Region",
          "fr": "Province de Djizak",
          "si": "ජිසාක් කලාපය",
          "ta": "ஜிசாக் பிராந்தியம்",
          "fi": "Jizzaxin alue",
          "hi": "जिज़ाख़ प्रान्त",
          "zh": "吉扎克州",
        },
      ),
      States(
        name: "Namangan Region",
        translations: {
          "en": "Namangan Region",
          "fr": "Province de Namangan",
          "si": "නාමන්ගන් කලාපය",
          "ta": "நமங்கன் பிராந்தியம்",
          "fi": "Namanganin alue",
          "hi": "नमन्गान प्रान्त",
          "zh": "纳曼干州",
        },
      ),
      States(
        name: "Navoiy Region",
        translations: {
          "en": "Navoiy Region",
          "fr": "Province de Navoï",
          "si": "නවෝයි කලාපය",
          "ta": "நவோய் பிராந்தியம்",
          "fi": "Navoiyn alue",
          "hi": "नवोई प्रान्त",
          "zh": "纳沃伊州",
        },
      ),
      States(
        name: "Qashqadaryo Region",
        translations: {
          "en": "Qashqadaryo Region",
          "fr": "Province de Kachkadaria",
          "si": "කෂ්කදාරියා කලාපය",
          "ta": "கசுக்கடரியோ பிராந்தியம்",
          "fi": "Qashqadaryon alue",
          "hi": "क़श्क़ादरिया प्रान्त",
          "zh": "卡什卡達里亞州",
        },
      ),
      States(
        name: "Samarqand Region",
        translations: {
          "en": "Samarqand Region",
          "fr": "Province de Samarcande",
          "si": "සමර්කන්ඩ් කලාපය",
          "ta": "சமர்கந்து பிராந்தியம்",
          "fi": "Samarkandin alue",
          "hi": "समरक़न्द प्रान्त",
          "zh": "撒马尔罕州",
        },
      ),
      States(
        name: "Sirdaryo Region",
        translations: {
          "en": "Sirdaryo Region",
          "fr": "Province de Syr-Daria",
          "si": "සිරිදාරියා කලාපය",
          "ta": "சிர்தார்யா பிராந்தியம்",
          "fi": "Sirdaryon alue",
          "hi": "सिरदरिया प्रान्त",
          "zh": "锡尔河州",
        },
      ),
      States(
        name: "Surxondaryo Region",
        translations: {
          "en": "Surxondaryo Region",
          "fr": "Province de Sourkhan-Daria",
          "si": "සුර්ඛන්දාරියා කලාපය",
          "ta": "சுர்க்ஷோன்டர்யோ பிராந்தியம்",
          "fi": "Surxondaryon alue",
          "hi": "सुरख़ानदरिया प्रान्त",
          "zh": "苏尔坎达里亚地州",
        },
      ),
      States(
        name: "Tashkent Region",
        translations: {
          "en": "Tashkent Region",
          "fr": "Province de Tachkent",
          "si": "ටෂ්කන්ට් කලාපය",
          "ta": "தாஷ்கண்ட் பிராந்தியம்",
          "fi": "Taškentin alue",
          "hi": "ताशकेंत प्रान्त",
          "zh": "塔什干州",
        },
      ),
      States(
        name: "Xorazm Region",
        translations: {
          "en": "Xorazm Region",
          "fr": "Province de Khorezm",
          "si": "කොරෙස්ම් කලාපය",
          "ta": "கோரெஸ்ம் பிராந்தியம்",
          "fi": "Xorazmin alue",
          "hi": "ख़ोरज़्म प्रान्त",
          "zh": "花拉子模州",
        },
      ),
      States(
        name: "Republic of Karakalpakstan",
        translations: {
          "en": "Republic of Karakalpakstan",
          "fr": "République du Karakalpakstan",
          "si": "කරකල්පක්ස්තාන් ජනරජය",
          "ta": "கரகல்பாக்ஸ்தான் குடியரசு",
          "fi": "Karakalpakstanin tasavalta",
          "hi": "क़ाराक़ालपाक़स्तान गणतंत्र",
          "zh": "花拉子模州",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Vanuatu",
    iso3: "VUT",
    iso2: "VU",
    phoneCode: "678",
    translations: {
      "en": "Vanuatu",
      "fr": "Vanuatu",
      "si": "වනුවාටු",
      "ta": "வனுவாட்டு",
      "hi": "वानूआतू",
      "zh": "瓦努阿图",
    },
    flag: "🇻🇺",
    flagU: "U+1F1FB U+1F1FA",
    states: [
      States(
        name: "Malampa",
        translations: {
          "en": "Malampa",
          "si": "මාලම්පා",
          "ta": "மலம்பா",
          "hi": "मालम्पा",
          "zh": "马朗巴",
        },
      ),
      States(
        name: "Penama",
        translations: {
          "en": "Penama",
          "fr": "Pénama",
          "si": "පෙනම",
          "ta": "பெனாமா",
          "hi": "पेनामा",
          "zh": "彭纳马",
        },
      ),
      States(
        name: "Sanma",
        translations: {
          "en": "Sanma",
          "si": "සන්මා",
          "ta": "சன்மா",
          "hi": "सनमा",
          "zh": "桑马",
        },
      ),
      States(
        name: "Shefa",
        translations: {
          "en": "Shefa",
          "fr": "Shéfa",
          "si": "ෂෙෆා",
          "ta": "ஷெஃபா",
          "hi": "शेफा",
          "zh": "谢法",
        },
      ),
      States(
        name: "Tafea",
        translations: {
          "en": "Tafea",
          "fr": "Taféa",
          "si": "ටැෆියා",
          "ta": "தாஃபியா",
          "hi": "तफ़िया",
          "zh": "塔菲亚",
        },
      ),
      States(
        name: "Torba",
        translations: {
          "en": "Torba",
          "si": "ටෝර්බා",
          "ta": "டோர்பா",
          "hi": "तोरबा",
          "zh": "托尔巴",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Vatican City",
    iso3: "VAT",
    iso2: "VA",
    phoneCode: "39",
    flag: "🇻🇦",
    flagU: "U+1F1FB U+1F1E6",
    translations: {
      "en": "Vatican City",
      "fr": "Cité du Vatican",
      "si": "වතිකානුව",
      "ta": "வத்திக்கான் நகர்",
      "fi": "Vatikaani",
      "hi": "वैटिकन सिटी",
      "zh": "梵蒂冈",
    },
    states: [],
  ),
  CountriesStatesModel(
    name: "Venezuela",
    iso3: "VEN",
    iso2: "VE",
    phoneCode: "58",
    translations: {
      "en": "Venezuela",
      "fr": "Venezuela",
      "si": "වෙනිසියුලාව",
      "ta": "வெனிசுவேலா",
      "hi": "वेनेज़ुएला",
      "zh": "委内瑞拉",
    },
    flag: "🇻🇪",
    flagU: "U+1F1FB U+1F1EA",
    states: [
      States(
        name: "Amazonas",
        translations: {
          "en": "Amazonas",
          "si": "ඇමසෝනාස්",
          "ta": "அமேசானாஸ்",
          "hi": "एमेज़ोनस",
          "zh": "亚马逊",
        },
      ),
      States(
        name: "Anzoátegui",
        translations: {
          "en": "Anzoátegui",
          "ta": "அன்சோடெகுய்",
          "hi": "एंज़ोअतेगुई",
          "zh": "安索阿特吉",
        },
      ),
      States(
        name: "Apure",
        translations: {
          "en": "Apure",
          "si": "අපූර්",
          "ta": "அபிரே",
          "hi": "अपुर",
          "zh": "阿普雷",
        },
      ),
      States(
        name: "Aragua",
        translations: {
          "en": "Aragua",
          "si": "අරගුවා",
          "ta": "அரகுவா",
          "hi": "अरागुआ",
          "zh": "阿拉瓜",
        },
      ),
      States(
        name: "Barinas",
        translations: {
          "en": "Barinas",
          "si": "බැරිනාස්",
          "ta": "பாரினாஸ்",
          "hi": "बरिनास",
          "zh": "巴里纳斯",
        },
      ),
      States(
        name: "Bolívar",
        translations: {
          "en": "Bolívar",
          "si": "බොලිවර්",
          "ta": "பொலிவர்",
          "hi": "बोलिवर",
          "zh": "玻利瓦",
        },
      ),
      States(
        name: "Carabobo",
        translations: {
          "en": "Carabobo",
          "si": "කරබෝබෝ",
          "ta": "காரபோபோ",
          "hi": "कारबोबो",
          "zh": "卡拉沃沃",
        },
      ),
      States(
        name: "Cojedes",
        translations: {
          "en": "Cojedes",
          "si": "කොජෙඩිස්",
          "ta": "கோஜெட்ஸ்",
          "hi": "कोजेदेस",
          "zh": "科赫德斯",
        },
      ),
      States(
        name: "Delta Amacuro",
        translations: {
          "en": "Delta Amacuro",
          "si": "ඩෙල්ටා අමාකුරෝ",
          "ta": "டெல்டா அமகுரோ",
          "hi": "डेल्टा अमाकुरो",
          "zh": "阿马库罗三角洲",
        },
      ),
      States(
        name: "Distrito Capital",
        translations: {
          "en": "Capital district",
          "fr": "District Capitale",
          "si": "අගනුවර දිස්ත්රික්කය",
          "ta": "தலைநகர் மாவட்டம்",
          "fi": "Pääkaupunkialue",
          "hi": "राजधानी जिला",
          "zh": "首都區",
        },
      ),
      States(
        name: "Falcón",
        translations: {
          "en": "Falcón",
          "si": "ෆැල්කන්",
          "ta": "பால்கான்",
          "hi": "फाल्कन",
          "zh": "法尔孔",
        },
      ),
      States(
        name: "Federal Dependencies",
        translations: {
          "en": "Federal Dependencies",
          "fr": "Dépendances fédérales",
          "si": "ෆෙඩරල් යැපීම්",
          "ta": "ஃபெடரல் சார்புநிலைகள்",
          "fi": "Liittovaltion riippuvuudet",
          "hi": "संघीय निर्भरताएँ",
          "zh": "联邦属地",
        },
      ),
      States(
        name: "Guárico",
        translations: {
          "en": "Guárico",
          "ta": "குவாரிகோ",
          "hi": "ग्वारिको",
          "zh": "瓜里科",
        },
      ),
      States(
        name: "La Guaira",
        translations: {
          "en": "La Guaira",
          "ta": "லா குவைரா",
          "hi": "ला गुएरा",
          "zh": "拉瓜伊拉",
        },
      ),
      States(
        name: "Lara",
        translations: {
          "en": "Lara",
          "si": "ලාරා",
          "ta": "லாரா",
          "hi": "लारा",
          "zh": "拉腊",
        },
      ),
      States(
        name: "Mérida",
        translations: {
          "en": "Mérida",
          "si": "මෙරිඩා",
          "ta": "மெரிடா",
          "hi": "मेरिडा",
          "zh": "梅里达",
        },
      ),
      States(
        name: "Miranda",
        translations: {
          "en": "Miranda",
          "si": "මිරැන්ඩා",
          "ta": "மிராண்டா",
          "hi": "मिरांडा",
          "zh": "米兰达",
        },
      ),
      States(
        name: "Monagas",
        translations: {
          "en": "Monagas",
          "si": "මොනාගස්",
          "ta": "மொனகாஸ்",
          "hi": "मोनागास",
          "zh": "莫纳加斯",
        },
      ),
      States(
        name: "Nueva Esparta",
        translations: {
          "en": "Nueva Esparta",
          "si": "නව ස්පාටා",
          "ta": "புதிய ஸ்பார்டா",
          "hi": "नया स्पार्टा",
          "zh": "新埃斯帕塔",
        },
      ),
      States(
        name: "Portuguesa",
        translations: {
          "en": "Portuguesa",
          "si": "පෘතුගීසි",
          "ta": "போர்த்துகீசிய",
          "hi": "पुर्तगाली",
          "zh": "波图格萨",
        },
      ),
      States(
        name: "Sucre",
        translations: {
          "en": "Sucre",
          "si": "සුක්රේ",
          "ta": "சுக்ரே",
          "hi": "सुक्रे",
          "zh": "苏克雷",
        },
      ),
      States(
        name: "Táchira",
        translations: {
          "en": "Táchira",
          "si": "ටචිරා",
          "ta": "தச்சிரா",
          "hi": "तचिरा",
          "zh": "塔奇拉",
        },
      ),
      States(
        name: "Trujillo",
        translations: {
          "en": "Trujillo",
          "si": "ටෘජිලෝ",
          "ta": "ட்ருஜிலோ",
          "hi": "ट्रूजिलो",
          "zh": "特鲁希略",
        },
      ),
      States(
        name: "Yaracuy",
        translations: {
          "en": "Yaracuy",
          "ta": "யாராசுய்",
          "hi": "याराकुय",
          "zh": "亚拉奎",
        },
      ),
      States(
        name: "Zulia",
        translations: {
          "en": "Zulia",
          "si": "සුලියා",
          "ta": "ஜூலியா",
          "hi": "ज़ुलिया",
          "zh": "苏利亚",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Vietnam",
    iso3: "VNM",
    iso2: "VN",
    phoneCode: "84",
    translations: {
      "en": "Vietnam",
      "fr": "Viêt Nam",
      "si": "වියට්නාමය",
      "ta": "வியட்நாம்",
      "hi": "वियतनाम",
      "zh": "越南",
    },
    flag: "🇻🇳",
    flagU: "U+1F1FB U+1F1F3",
    states: [
      States(
        name: "An Giang",
        translations: {
          "en": "An Giang",
          "ta": "ஒரு ஜியாங்",
          "hi": "ऐन गिआंग",
          "zh": "安江",
        },
      ),
      States(
        name: "Bà Rịa-Vũng Tàu",
        translations: {
          "en": "Bà Rịa-Vũng Tàu",
          "ta": "பா ரியா வுங் தாவ்",
          "hi": "बा रिया वुंग ताऊ",
          "zh": "巴地头顿",
        },
      ),
      States(
        name: "Bắc Giang",
        translations: {
          "en": "Bắc Giang",
          "ta": "பாக் ஜியாங்",
          "hi": "बाक गियांग",
          "zh": "北江",
        },
      ),
      States(
        name: "Bắc Kạn",
        translations: {
          "en": "Bắc Kạn",
          "si": "බැක් කාන්",
          "ta": "பாக் கான்",
          "hi": "बाक कान",
          "zh": "北干",
        },
      ),
      States(
        name: "Bạc Liêu",
        translations: {
          "en": "Bạc Liêu",
          "ta": "பாக் லியூ",
          "hi": "बाक लियू",
          "zh": "薄辽",
        },
      ),
      States(
        name: "Bắc Ninh",
        translations: {
          "en": "Bắc Ninh",
          "ta": "பாக் நின்",
          "hi": "बाक निन्ह",
          "zh": "北宁",
        },
      ),
      States(
        name: "Bến Tre",
        translations: {
          "en": "Bến Tre",
          "si": "බෙන් ට්රේ",
          "ta": "பென் ட்ரே",
          "hi": "बेन ट्रे",
          "zh": "槟知",
        },
      ),
      States(
        name: "Bình Định",
        translations: {
          "en": "Bình Định",
          "hi": "बन दन्ह",
          "zh": "班定",
        },
      ),
      States(
        name: "Bình Dương",
        translations: {
          "en": "Bình Dương",
          "ta": "பின் டுவாங்",
          "hi": "बिन्ह डुओंग",
          "zh": "平阳",
        },
      ),
      States(
        name: "Bình Phước",
        translations: {
          "en": "Bình Phước",
          "ta": "பின் ஃபூக்",
          "hi": "बिन्ह फुओक",
          "zh": "平福",
        },
      ),
      States(
        name: "Bình Thuận",
        translations: {
          "en": "Bình Thuận",
          "si": "බින් තුආන්",
          "ta": "பின் துவான்",
          "hi": "बिन्ह थुआन",
          "zh": "平顺",
        },
      ),
      States(
        name: "Cà Mau",
        translations: {
          "en": "Cà Mau",
          "hi": "कै माऊ",
          "zh": "金瓯",
        },
      ),
      States(
        name: "Cần Thơ",
        translations: {
          "en": "Cần Thơ",
          "ta": "கேன் தோ",
          "hi": "कैन थो",
          "zh": "芹苴",
        },
      ),
      States(
        name: "Cao Bằng",
        translations: {
          "en": "Cao Bằng",
          "ta": "காவ் பாங்",
          "hi": "कैओ बांग",
          "zh": "高平",
        },
      ),
      States(
        name: "Đà Nẵng",
        translations: {
          "en": "Đà Nẵng",
          "si": "ඩා නන්ග්",
          "ta": "டானாங்",
          "hi": "डै नैंग",
          "zh": "岘港",
        },
      ),
      States(
        name: "Đắk Lắk",
        translations: {
          "en": "Đắk Lắk",
          "si": "දක් ලක්",
          "ta": "தாக்லாக்",
          "hi": "डाक लाक",
          "zh": "多乐",
        },
      ),
      States(
        name: "Đắk Nông",
        translations: {
          "en": "Đắk Nông",
          "si": "ඩැක් නොං",
          "ta": "டக் நோங்",
          "hi": "डाक नोंग",
          "zh": "得农",
        },
      ),
      States(
        name: "Điện Biên",
        translations: {
          "en": "Điện Biên",
          "hi": "डिएन बिएन",
          "zh": "奠边",
        },
      ),
      States(
        name: "Đồng Nai",
        translations: {
          "en": "Đồng Nai",
          "si": "ඩොං නයි",
          "ta": "டோங் நாய்",
          "hi": "डोंग नाइ",
          "zh": "同奈",
        },
      ),
      States(
        name: "Đồng Tháp",
        translations: {
          "en": "Đồng Tháp",
          "si": "ඩොං තාප්",
          "ta": "டோங் தாப்",
          "hi": "डोंग थाप",
          "zh": "同塔",
        },
      ),
      States(
        name: "Gia Lai",
        translations: {
          "en": "Gia Lai",
          "ta": "கியா லாய்",
          "hi": "जिया लाई",
          "zh": "嘉莱",
        },
      ),
      States(
        name: "Hà Giang",
        translations: {
          "en": "Hà Giang",
          "ta": "ஹா ஜியாங்",
          "hi": "हा गियांग",
          "zh": "河江",
        },
      ),
      States(
        name: "Hà Nam",
        translations: {
          "en": "Hà Nam",
          "si": "හා නාම්",
          "ta": "ஹா நாம்",
          "hi": "हा नाम",
          "zh": "河南",
        },
      ),
      States(
        name: "Hà Nội",
        translations: {
          "en": "Hà Nội",
          "si": "හැනෝයි",
          "ta": "ஹனோய்",
          "hi": "हा नोइ",
          "zh": "河内",
        },
      ),
      States(
        name: "Hà Tĩnh",
        translations: {
          "en": "Hà Tĩnh",
          "ta": "ஹா டின்",
          "hi": "हा तिन्ह",
          "zh": "河静",
        },
      ),
      States(
        name: "Hải Dương",
        translations: {
          "en": "Hải Dương",
          "hi": "हाई डुओंग",
          "zh": "海阳",
        },
      ),
      States(
        name: "Hải Phòng",
        translations: {
          "en": "Hải Phòng",
          "si": "හායි ෆොන්ග්",
          "ta": "ஹாய் ஃபோங்",
          "hi": "हाई फोंग",
          "zh": "海防",
        },
      ),
      States(
        name: "Hậu Giang",
        translations: {
          "en": "Hậu Giang",
          "ta": "ஹவ் ஜியாங்",
          "hi": "हाऊ गियांग",
          "zh": "后江",
        },
      ),
      States(
        name: "Hồ Chí Minh",
        translations: {
          "en": "Hồ Chí Minh",
          "si": "හෝ චි මිං",
          "ta": "ஹோ சி மின்",
          "hi": "हो चि मिन्ह",
          "zh": "胡志明",
        },
      ),
      States(
        name: "Hòa Bình",
        translations: {
          "en": "Hòa Bình",
          "ta": "ஹோவா பின்",
          "hi": "होआ बिन्ह",
          "zh": "和平",
        },
      ),
      States(
        name: "Hưng Yên",
        translations: {
          "en": "Hưng Yên",
          "ta": "ஹங் யென்",
          "hi": "हंग येन",
          "zh": "兴安",
        },
      ),
      States(
        name: "Khánh Hòa",
        translations: {
          "en": "Khánh Hòa",
          "si": "ඛාන් හෝවා",
          "ta": "கான் ஹோவா",
          "hi": "खान होआ",
          "zh": "庆和",
        },
      ),
      States(
        name: "Kiên Giang",
        translations: {
          "en": "Kiên Giang",
          "ta": "கியென் ஜியாங்",
          "hi": "कियान गियांग",
          "zh": "坚江",
        },
      ),
      States(
        name: "Kon Tum",
        translations: {
          "en": "Kon Tum",
          "si": "කොන් ටුම්",
          "ta": "கோன் தும்",
          "hi": "कोन तुम",
          "zh": "昆嵩",
        },
      ),
      States(
        name: "Lai Châu",
        translations: {
          "en": "Lai Châu",
          "ta": "லாய் சாவ்",
          "hi": "लाई चाऊ",
          "zh": "莱州",
        },
      ),
      States(
        name: "Lâm Đồng",
        translations: {
          "en": "Lâm Đồng",
          "si": "ලැම් ඩොං",
          "ta": "லாம் டோங்",
          "hi": "लैम डोंग",
          "zh": "林同",
        },
      ),
      States(
        name: "Lạng Sơn",
        translations: {
          "en": "Lạng Sơn",
          "ta": "லாங் சோன்",
          "hi": "लैंग सोन",
          "zh": "谅山",
        },
      ),
      States(
        name: "Lào Cai",
        translations: {
          "en": "Lào Cai",
          "si": "ලාඕ කායි",
          "ta": "லாவோ காய்",
          "hi": "लाओ कै",
          "zh": "老街",
        },
      ),
      States(
        name: "Long An",
        translations: {
          "en": "Long An",
          "ta": "லாங் ஆன்",
          "hi": "लैंग सोन",
          "zh": "隆安",
        },
      ),
      States(
        name: "Nam Định",
        translations: {
          "en": "Nam Định",
          "ta": "நாம் டின்",
          "hi": "नाम दिन्ह",
          "zh": "南定",
        },
      ),
      States(
        name: "Nghệ An",
        translations: {
          "en": "Nghệ An",
          "hi": "न्घे एक",
          "zh": "义安",
        },
      ),
      States(
        name: "Ninh Bình",
        translations: {
          "en": "Ninh Bình",
          "hi": "निन्ह बिन्ह",
          "zh": "宁平",
        },
      ),
      States(
        name: "Ninh Thuận",
        translations: {
          "en": "Ninh Thuận",
          "ta": "நின் துவான்",
          "hi": "निन्ह थुआन",
          "zh": "宁顺",
        },
      ),
      States(
        name: "Phú Thọ",
        translations: {
          "en": "Phú Thọ",
          "si": "ෆු තෝ",
          "ta": "ஃபூ தோ",
          "hi": "फू थो",
          "zh": "富寿",
        },
      ),
      States(
        name: "Phú Yên",
        translations: {
          "en": "Phú Yên",
          "si": "ෆු යෙන්",
          "ta": "ஃபு யென்",
          "hi": "फू येन",
          "zh": "富安",
        },
      ),
      States(
        name: "Quảng Bình",
        translations: {
          "en": "Quảng Bình",
          "ta": "குவாங் பின்",
          "hi": "क्वांग बिन्ह",
          "zh": "广平",
        },
      ),
      States(
        name: "Quảng Nam",
        translations: {
          "en": "Quảng Nam",
          "ta": "குவாங் நாம்",
          "hi": "क्वांग नाम",
          "zh": "广南",
        },
      ),
      States(
        name: "Quảng Ngãi",
        translations: {
          "en": "Quảng Ngãi",
          "ta": "குவாங் நகாய்",
          "hi": "क्वांग नगाई",
          "zh": "广义",
        },
      ),
      States(
        name: "Quảng Ninh",
        translations: {
          "en": "Quảng Ninh",
          "ta": "குவாங் நின்",
          "hi": "क्वांग निन्ह",
          "zh": "广宁",
        },
      ),
      States(
        name: "Quảng Trị",
        translations: {
          "en": "Quảng Trị",
          "ta": "குவாங் திரி",
          "hi": "क्वांग ट्राई",
          "zh": "广治",
        },
      ),
      States(
        name: "Sóc Trăng",
        translations: {
          "en": "Sóc Trăng",
          "hi": "सोक ट्रांग",
          "zh": "朔庄",
        },
      ),
      States(
        name: "Sơn La",
        translations: {
          "en": "Sơn La",
          "si": "පුතා ලා",
          "ta": "சோன் லா",
          "hi": "सोन ला",
          "zh": "山罗",
        },
      ),
      States(
        name: "Tây Ninh",
        translations: {
          "en": "Tây Ninh",
          "hi": "ताई निन्ह",
          "zh": "西宁",
        },
      ),
      States(
        name: "Thái Bình",
        translations: {
          "en": "Thái Bình",
          "si": "තායි බිං",
          "ta": "தாய் பின்",
          "hi": "थाई बिन्ह",
          "zh": "太平",
        },
      ),
      States(
        name: "Thái Nguyên",
        translations: {
          "en": "Thái Nguyên",
          "hi": "थाई गुयेन",
          "zh": "太原",
        },
      ),
      States(
        name: "Thanh Hóa",
        translations: {
          "en": "Thanh Hóa",
          "si": "තන් හෝවා",
          "ta": "தான் ஹோவா",
          "hi": "थान्ह होआ",
          "zh": "清化",
        },
      ),
      States(
        name: "Thừa Thiên-Huế",
        translations: {
          "en": "Thừa Thiên-Huế",
          "hi": "थुआ थिएन-ह्यू",
          "zh": "承天顺化",
        },
      ),
      States(
        name: "Tiền Giang",
        translations: {
          "en": "Tiền Giang",
          "hi": "टीएन गियांग",
          "zh": "前江",
        },
      ),
      States(
        name: "Trà Vinh",
        translations: {
          "en": "Trà Vinh",
          "ta": "டிரா வின்",
          "hi": "त्रा विन्ह",
          "zh": "茶荣",
        },
      ),
      States(
        name: "Tuyên Quang",
        translations: {
          "en": "Tuyên Quang",
          "hi": "तुयेन क्वांग",
          "zh": "宣光",
        },
      ),
      States(
        name: "Vĩnh Long",
        translations: {
          "en": "Vĩnh Long",
          "ta": "வின் லாங்",
          "hi": "विंह लांग",
          "zh": "永隆",
        },
      ),
      States(
        name: "Vĩnh Phúc",
        translations: {
          "en": "Vĩnh Phúc",
          "hi": "विंह फुक",
          "zh": "永福",
        },
      ),
      States(
        name: "Yên Bái",
        translations: {
          "en": "Yên Bái",
          "si": "යෙන් බායි",
          "ta": "யென் பாய்",
          "hi": "येन बाई",
          "zh": "安沛",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Wallis and Futuna",
    iso3: "WLF",
    iso2: "WF",
    phoneCode: "681",
    translations: {
      "en": "Wallis and Futuna",
      "fr": "Wallis-et-Futuna",
      "si": "වොලිස් සහ ෆුඩුනා",
      "ta": "வாலிஸ் மற்றும் ஃபுடுனா",
      "fi": "Wallis ja Futuna",
      "hi": "वालिस और फ़्यूचूना",
      "zh": "瓦利斯群岛和富图纳群岛",
    },
    flag: "🇼🇫",
    flagU: "U+1F1FC U+1F1EB",
    states: [],
  ),
  CountriesStatesModel(
    name: "Western Sahara",
    iso3: "ESH",
    iso2: "EH",
    phoneCode: "212",
    translations: {
      "en": "Western Sahara",
      "fr": "Sahara Occidental",
      "si": "බටහිර සහරා",
      "ta": "மேற்கு சகாரா",
      "fi": "Länsi-Sahara",
      "hi": "पश्चिमी सहारा",
      "zh": "西撒哈拉",
    },
    flag: "🇪🇭",
    flagU: "U+1F1EA U+1F1ED",
    states: [],
  ),
  CountriesStatesModel(
    name: "Yemen",
    iso3: "YEM",
    iso2: "YE",
    phoneCode: "967",
    translations: {
      "en": "Yemen",
      "fr": "Yémen",
      "si": "යේමනය",
      "ta": "யெமன்",
      "fi": "Jemen",
      "hi": "यमन",
      "zh": "也门",
    },
    flag: "🇾🇪",
    flagU: "U+1F1FE U+1F1EA",
    states: [
      States(
        name: "Abyan",
        translations: {
          "en": "Abyan",
          "si": "අබියන්",
          "ta": "அப்யன்",
          "hi": "अबयन",
          "zh": "阿比扬",
        },
      ),
      States(
        name: "Aden",
        translations: {
          "en": "Aden",
          "si": "ඒඩන්",
          "ta": "ஏடன்",
          "hi": "अदन",
          "zh": "亚丁",
        },
      ),
      States(
        name: "Al Bayda",
        translations: {
          "en": "Al Bayda",
          "si": "අල් බයිඩා",
          "ta": "அல் பெய்தா",
          "hi": "अल-बैदा",
          "zh": "阿尔贝达",
        },
      ),
      States(
        name: "Al Hudaydah",
        translations: {
          "en": "Al Hudaydah",
          "fr": "Al Hodeïda",
          "si": "අල් හොඩෙයිඩා",
          "ta": "அல் ஹொடைடா",
          "fi": "Al Hudaydah",
          "hi": "अल-हुदैदाह",
          "zh": "荷台达",
        },
      ),
      States(
        name: "Al Jawf",
        translations: {
          "en": "Al Jawf",
          "si": "අල් ජවුෆ්",
          "ta": "அல் ஜவ்ஃப்",
          "hi": "अल-जौफ़",
          "zh": "焦夫省",
        },
      ),
      States(
        name: "Al Mahrah",
        translations: {
          "en": "Al Mahrah",
          "fr": "Al-Mahra",
          "si": "අල් මහ්රා",
          "ta": "அல்-மஹ்ரா",
          "fi": "Al-Mahra",
          "hi": "अल-महराह",
          "zh": "阿尔马赫拉",
        },
      ),
      States(
        name: "Al Mahwit",
        translations: {
          "en": "Al Mahwit",
          "si": "අල් මහවිට්",
          "ta": "அல் மஹ்விட்",
          "hi": "अल-महवीत",
          "zh": "阿尔·马维特",
        },
      ),
      States(
        name: "Amanat Al Asimah",
        translations: {
          "en": "Amanat Al Asimah",
          "si": "අමනත් අල් අසිමහ්",
          "ta": "அமானத் அல் அசிமா",
          "hi": "अमानत अल-आसिमाह",
          "zh": "阿马纳特·阿西玛",
        },
      ),
      States(
        name: "'Amran",
        translations: {
          "en": "'Amran",
          "fr": "Amran",
          "si": "අම්රාන්",
          "ta": "அம்ரன்",
          "fi": "Amran",
          "hi": "अमरान",
          "zh": "阿姆兰",
        },
      ),
      States(
        name: "Dhale",
        translations: {
          "en": "Dhale",
          "fr": "Al-Dhali",
          "si": "අල් ධාලි",
          "ta": "அல் தாலி",
          "fi": "Al Dali",
          "hi": "अद-दाली",
          "zh": "阿尔达利",
        },
      ),
      States(
        name: "Dhamar",
        translations: {
          "en": "Dhamar",
          "si": "ධමර්",
          "ta": "தாமர்",
          "hi": "धामर",
          "zh": "达玛尔",
        },
      ),
      States(
        name: "Hadhramaut",
        translations: {
          "en": "Hadhramaut",
          "fr": "Hadramaout",
          "si": "හද්‍රමවුට්",
          "ta": "ஹத்ரமாட்",
          "hi": "हदरामौत",
          "zh": "哈德拉毛",
        },
      ),
      States(
        name: "Hajjah",
        translations: {
          "en": "Hajjah",
          "si": "හජ්ජා",
          "ta": "ஹஜ்ஜா",
          "hi": "हज्जाह",
          "zh": "哈杰省",
        },
      ),
      States(
        name: "Ibb",
        translations: {
          "en": "Ibb",
          "si": "Ibb ආණ්ඩුකාරවරයා",
          "ta": "Ibb கவர்னரேட்",
          "hi": "इब्ब",
          "zh": "伊卜省",
        },
      ),
      States(
        name: "Lahij",
        translations: {
          "en": "Lahij",
          "si": "ලහිජ්",
          "ta": "லாஹிஜ்",
          "hi": "लहिज",
          "zh": "拉赫季",
        },
      ),
      States(
        name: "Ma'rib",
        translations: {
          "en": "Ma'rib",
          "si": "මාරිබ්",
          "ta": "மாரிப்",
          "hi": "मारिब",
          "zh": "马里卜",
        },
      ),
      States(
        name: "Raymah",
        translations: {
          "en": "Raymah",
          "fr": "Raima",
          "si": "රේමාහ්",
          "ta": "ரேமா",
          "fi": "Raima",
          "hi": "रेमाह",
          "zh": "赖马",
        },
      ),
      States(
        name: "Sa'dah",
        translations: {
          "en": "Sa'dah",
          "si": "සදාහ්",
          "ta": "சாதா",
          "fi": "Saada",
          "hi": "सआदाह",
          "zh": "萨达",
        },
      ),
      States(
        name: "Sana'a",
        translations: {
          "en": "Sana'a",
          "fr": "Sanaa",
          "si": "සනා",
          "ta": "சனா",
          "fi": "Sanaa",
          "hi": "सनआ",
          "zh": "萨那",
        },
      ),
      States(
        name: "Shabwah",
        translations: {
          "en": "Shabwah",
          "fr": "Sanaa",
          "si": "ෂබ්වා",
          "ta": "ஷப்வா",
          "fi": "Sanaa",
          "hi": "शब्वाह",
          "zh": "舍卜沃",
        },
      ),
      States(
        name: "Socotra",
        translations: {
          "en": "Socotra",
          "si": "සොකොත්රා",
          "ta": "சோகோட்ரா",
          "fi": "Sokotra",
          "hi": "सोकोत्रा",
          "zh": "索科特拉",
        },
      ),
      States(
        name: "Taiz",
        translations: {
          "en": "Taiz",
          "fr": "Ta'izz",
          "si": "ටයිස්",
          "ta": "டைஸ்",
          "fi": "Taizz",
          "hi": "ताइज़",
          "zh": "塔伊兹",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Zambia",
    iso3: "ZMB",
    iso2: "ZM",
    phoneCode: "260",
    translations: {
      "en": "Zambia",
      "fr": "Zambie",
      "si": "සැම්බියා",
      "ta": "சாம்பியா",
      "fi": "Sambia",
      "hi": "जाम्बिया",
      "zh": "赞比亚",
    },
    flag: "🇿🇲",
    flagU: "U+1F1FF U+1F1F2",
    states: [
      States(
        name: "Central",
        translations: {
          "en": "Central",
          "fr": "Centrale",
          "si": "මධ්යම",
          "ta": "மத்திய",
          "fi": "Keski",
          "hi": "केंद्रीय",
          "zh": "中央",
        },
      ),
      States(
        name: "Copperbelt",
        translations: {
          "en": "Copperbelt",
          "si": "තඹ පටිය",
          "ta": "காப்பர்பெல்ட்",
          "fi": "Kuparivyö",
          "hi": "कॉपरबेल्ट",
          "zh": "铜带",
        },
      ),
      States(
        name: "Eastern",
        translations: {
          "en": "Eastern",
          "fr": "Orientale",
          "si": "නැගෙනහිර",
          "ta": "கிழக்கு",
          "fi": "Itäinen",
          "hi": "पूर्व का",
          "zh": "东方",
        },
      ),
      States(
        name: "Luapula",
        translations: {
          "en": "Luapula",
          "si": "ලුආපුලා",
          "ta": "லுபுலா",
          "hi": "ल्वपुला",
          "zh": "卢阿普拉",
        },
      ),
      States(
        name: "Lusaka",
        translations: {
          "en": "Lusaka",
          "si": "ලුසාකා",
          "ta": "லுசாகா",
          "hi": "लुसाका",
          "zh": "卢萨卡",
        },
      ),
      States(
        name: "Muchinga",
        translations: {
          "en": "Muchinga",
          "si": "මුචිංගා",
          "ta": "முச்சிங்கா",
          "hi": "मुचिंगा",
          "zh": "穆钦加",
        },
      ),
      States(
        name: "North-Western",
        translations: {
          "en": "North-Western",
          "fr": "Nord-Occidentale",
          "si": "වයඹ",
          "ta": "வடமேற்கு",
          "fi": "Luoteis",
          "hi": "उत्तर-पश्चिम",
          "zh": "西北",
        },
      ),
      States(
        name: "Northern",
        translations: {
          "en": "Northern",
          "fr": "Septentrionale",
          "si": "උතුරු",
          "ta": "வடக்கு",
          "fi": "Pohjoinen",
          "hi": "उत्तरी",
          "zh": "北方",
        },
      ),
      States(
        name: "Southern",
        translations: {
          "en": "Southern",
          "fr": "Méridionale",
          "si": "දක්ෂිණ",
          "ta": "தெற்கு",
          "fi": "Eteläinen",
          "hi": "दक्षिण",
          "zh": "南方",
        },
      ),
      States(
        name: "Western",
        translations: {
          "en": "Western",
          "fr": "Occidentale",
          "si": "බටහිර",
          "ta": "மேற்கு",
          "fi": "Läntinen",
          "hi": "वेस्टर्न",
          "zh": "西",
        },
      ),
    ],
  ),
  CountriesStatesModel(
    name: "Zimbabwe",
    iso3: "ZWE",
    iso2: "ZW",
    phoneCode: "263",
    translations: {
      "en": "Zimbabwe",
      "fr": "Zimbabwe",
      "si": "සිම්බාබ්වේ",
      "ta": "சிம்பாப்வே",
      "hi": "ज़िम्बाब्वे",
      "zh": "津巴布韦",
    },
    flag: "🇿🇼",
    flagU: "U+1F1FF U+1F1FC",
    states: [
      States(
        name: "Bulawayo",
        translations: {
          "en": "Bulawayo",
          "si": "බුලවායෝ",
          "ta": "புலவாயோ",
          "hi": "बुलावायो",
          "zh": "布拉瓦约",
        },
      ),
      States(
        name: "Harare",
        translations: {
          "en": "Harare",
          "si": "හරාරේ",
          "ta": "ஹராரே",
          "hi": "हरारे",
          "zh": "哈拉雷",
        },
      ),
      States(
        name: "Manicaland",
        translations: {
          "en": "Manicaland",
          "si": "මැනිකලන්ඩ්",
          "ta": "மணிக்கலாண்ட்",
          "hi": "मानिकालैण्ड",
          "zh": "马尼卡兰",
        },
      ),
      States(
        name: "Mashonaland Central",
        translations: {
          "en": "Mashonaland Central",
          "si": "මෂෝනලන්ඩ් මධ්‍යම",
          "ta": "மஷோனாலண்ட் சென்ட்ரல்",
          "hi": "माशोनालैण्ड मध्य",
          "zh": "中马绍纳兰",
        },
      ),
      States(
        name: "Mashonaland East",
        translations: {
          "en": "Mashonaland East",
          "fr": "Mashonaland Oriental",
          "si": "මාෂෝනාලන්ඩ් නැගෙනහිර",
          "ta": "மசோனாலண்ட் கிழக்கு",
          "hi": "माशोनालैण्ड पूर्व",
          "zh": "东马绍纳兰",
        },
      ),
      States(
        name: "Mashonaland West",
        translations: {
          "en": "Mashonaland West",
          "fr": "Mashonaland Occidental",
          "si": "බටහිර මාෂෝනාලන්ඩ්",
          "ta": "மசோனாலண்ட் மேற்கு",
          "hi": "माशोनालैण्ड पश्चिम",
          "zh": "西马绍纳兰",
        },
      ),
      States(
        name: "Masvingo",
        translations: {
          "en": "Masvingo",
          "si": "මස්විංගෝ",
          "ta": "மாஸ்விங்கோ",
          "hi": "मासविंगो",
          "zh": "马斯温戈",
        },
      ),
      States(
        name: "Matabeleland North",
        translations: {
          "en": "Matabeleland North",
          "fr": "Matabeleland Septentrional",
          "si": "මාටබෙල්ලන්ඩ් උතුර",
          "ta": "மாடபெலேலேண்ட் வடக்கு",
          "hi": "माताबेलेलैण्ड उत्तर",
          "zh": "北马塔贝莱兰",
        },
      ),
      States(
        name: "Matabeleland South",
        translations: {
          "en": "Matabeleland South",
          "fr": "Matabeleland Méridional",
          "si": "මාටබෙල්ලන්ඩ් දකුණ",
          "ta": "மாடபெலேலேண்ட் தெற்கு",
          "hi": "माताबेलेलैण्ड दक्षिण",
          "zh": "南马塔贝莱兰",
        },
      ),
      States(
        name: "Midlands",
        translations: {
          "en": "Midlands",
          "si": "මිඩ්ලන්ඩ්ස්",
          "ta": "மிட்லாண்ட்ஸ்",
          "hi": "मिडलैण्ड्स",
          "zh": "中部",
        },
      ),
    ],
  ),
];
